ci: Add help comment for Markdown lint check failure
magma/magma pull request #10057
Opened 2021-11-03 07:56 UTC by hcgatewood

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-11-03 18:05 UTC, themarwhal commented on .github/workflows/comment-pr-on-check-failure.yml
> +        if: ${{ github.event.workflow.name == 'Markdown lint check'
```suggestion
        if: ${{ github.event.workflow.name == 'Markdown lint check' }}
```
i think?

2021-11-03 18:06 UTC, quentinDERORY commented on .github/workflows/comment-pr-on-check-failure.yml
> +        if: ${{ github.event.workflow.name == 'Markdown lint check'
You need to add the workflow name to the list at the top of the file too.

2021-11-03 18:06 UTC, quentinDERORY requested changes
LGTM but see comment

2021-11-03 21:37 UTC, quentinDERORY approved these changes

2021-11-04 11:16 UTC, themarwhal approved these changes

2021-11-04 23:04 UTC, merged