fix(sessiond): fix race condition on handle_activate_ue_flows_callback
magma/magma pull request #10213
Opened 2021-11-09 23:39 UTC by uri200

## Summary
backport of https://github.com/magma/magma/pull/10211

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-11-09 23:43 UTC, themarwhal approved these changes

2021-11-10 00:13 UTC, ulaskozat requested changes
needs verification on spirent

2021-11-10 03:54 UTC, uri200 commented on lte/gateway/c/session_manager/LocalEnforcer.cpp
> -          pending_deactivation, false);
it looks like i was passing a sting directly not a reference. Not sure why it was not crashing

2021-11-10 04:26 UTC, uri200 commented
> needs verification on spirent

verified around 10 times.  I saw same numbers on mme, a1ap, table 0 and sessiond. |

```
magma@u-160-161-nonnat:~$ sudo ./state_check.sh
MME_state = 206
S1AP_state = 206
SPGW_state = 206
Sessiond_state = 206
table0 DL bearers = 206
table12 DL flows = 206 ; table12 UL flows = 206
table13 DL flows = 412 ; table13 UL flows = 412
Mobilityd state = 210
```

2021-11-10 04:34 UTC, ulaskozat approved these changes
Thanks for the runs. I will merge after sanity confirmations.

2021-11-10 07:01 UTC, merged