feat(orc8r): Include a configuration to deploy an additional namespce for staging orc8r
magma/magma pull request #10215
Opened 2021-11-10 01:21 UTC by joary

## Summary

1. Include a new variable to define the orc8r staging namespace (default empty)
2. Include a new resource creating the namespace when the variable is not empty

## Test Plan

If main.tf includes:

```
module "orc8r-app" {
  ...
  orc8r_staging_namespace = "orc8r-staging"
  ...
}
```

Terraform plan shows:

```
  # module.orc8r-app.kubernetes_namespace.staging-orc8r[0] will be created
  + resource "kubernetes_namespace" "staging-orc8r" {
      + id = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = "orc8r-staging"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }
    }
```

After terraform apply the namespace can be seen:

```
# kubectl get namespace
NAME              STATUS   AGE
default           Active   6d
kube-node-lease   Active   6d
kube-public       Active   6d
kube-system       Active   6d
monitoring        Active   44m
orc8r             Active   44m
orc8r-staging     Active   6s
```

**Attention**

OBS1: In case the namespace variable is removed after apply. Terraform will delete the existing namespace and all the content deploied on it will be lost (Need to be very carefull with this.)

OBS1: In case the namespace variable is changed after apply. Terraform will delete the existing namespace and create a new one with the updated name. All the content in the previous namespace will be lost.

## Additional Information

- [ ] This change is backwards-breaking

2021-11-12 08:03 UTC, hcgatewood reviewed
Is this forcing us to set the `orc8r_staging_namespace` now? If yes, let's instead set some intelligent default (relative to the `orc8r` namespace)

2021-11-12 09:28 UTC, arunuke commented
> Is this forcing us to set the `orc8r_staging_namespace` now? If yes, let's instead set some intelligent default (relative to the `orc8r` namespace)

I think the current PR sets the default to an empty string and creates a secondary namespace only when a namespace is specified. Although this would work, my request for @joary would be to consider a global blue-green variable to be used as well. Creating an extra namespace doesn't cost anything, but it would be good to create it only if the customer is using blue-green upgrades (defaults to false until we GA and will then default to true).

2021-11-12 09:30 UTC, arunuke requested changes

2021-11-12 09:30 UTC, arunuke commented on orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
> +variable "orc8r_staging_namespace" {
Should we consider adding a enable_blue_green variable and use that as a condition to create the namespace with the default value set to a non-empty string of our preference? This way, the secondary namespace will be created if customer using blue-green and will have a default value already. 

Might be a better alternative to consider over the check for empty vs valid string.

2021-11-12 09:32 UTC, arunuke commented
I see the global variable for blue-green enabled in [another PR](https://github.com/magma/magma/pull/10212/files). Perhaps we should merge that first and use that variable here as a check for the namespace with a default value specified. Perhaps orc8r-staging?

2021-11-24 20:44 UTC, joary commented
I'm closing this PR since the namespace will be configured in a different way when deploying blue-green

2021-11-24 20:44 UTC, closed without merging