feat(amf): Change the amf_parameter_name.
magma/magma pull request #10222
Opened 2021-11-10 09:00 UTC by RahulKalsangra

Signed-off-by: RahulKalsangra <rahul.kalsangra@wavelabs.ai>

## Summary
Change the amf specific parameter name 

## Test Plan

UERANSIM

2021-11-11 01:43 UTC, ulaskozat approved these changes
LGTM

2021-11-11 01:47 UTC, ulaskozat commented
This can break 5G  until staging orc8r is updated with #9756. You should note the issue on backward compatibility.

2021-11-11 17:07 UTC, ulaskozat requested changes
where are the pb files for proto? (cc @panyogesh @hcgatewood)

2021-11-11 17:12 UTC, ulaskozat commented
@quentinDERORY why is insync checks are not done on this PR? there are updated protos in the PR but pb files are missing, so the check would have failed.

2021-11-11 17:19 UTC, hcgatewood commented
> @quentinDERORY why is insync checks are not done on this PR? there are updated protos in the PR but pb files are missing, so the check would have failed.

Hm yeah @quentinDERORY any thoughts on this?

2021-11-11 17:26 UTC, quentinDERORY commented
Thanks to @themarwhal, typo in the path filter of the job! Just merged the fix, you should rebase to trigger the workflow

2021-11-12 07:48 UTC, RahulKalsangra commented
> where are the pb files for proto? (cc @panyogesh @hcgatewood)

comment addressed and pb files are added

2021-11-15 14:07 UTC, electronjoe commented on lte/gateway/python/scripts/generate_oai_config.py
> +            return enable_default_service_slice_type
Please review PEP finding `WPS503 Found useless returning `else` statement`

2021-11-17 18:35 UTC, panyogesh commented
Some extra commit went in which was not required.  Will be closing the same. This will be replaced by #10392

2021-11-24 05:45 UTC, closed without merging