feat: Add mme app latency  metric
magma/magma pull request #10243
Opened 2021-11-11 07:00 UTC by wallyrb

Signed-off-by: Wally Rodriguez B <wallyrb@fb.com>

## Summary

Add mme app latency  metric. Re-using the already calculated latency mme_app_last_msg_latency

## Test Plan

- Tested in local environment

```
(python) vagrant@magma-dev-focal:~/magma/lte/gateway$ service303_cli.py metrics mme

....
name: "s1u_bearers"
help: ""
type: GAUGE
metric {
  gauge {
    value: 0.0
  }
}

name: "mme_app_last_msg_latency"
help: ""
type: GAUGE
metric {
  gauge {
    value: 606.0
  }
}

...

![image](https://user-images.githubusercontent.com/37117037/141252589-20d1cb8b-3594-40c3-8c87-6bac99d3dc2c.png)

2021-11-15 18:15 UTC, ardzoht requested changes
we need to add `pre_mme_task_msg_latency` as well

2021-11-29 18:06 UTC, ardzoht approved these changes
lgtm

2021-12-01 19:25 UTC, wallyrb commented on lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
> +  if (pre_mme_task_msg_latency < 0) {
@ardzoht I notice majority of times `pre_mme_task_msg_latency` is populated with large negative value `-4702111234474983746'. It was always the same negative value.   I think this is populated when there is not a value on pre_mme_task_msg_latency which is obtained from `[ittiMsgHeader.last_hop_latency](https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/lib/itti/intertask_interface.h#L64)` 

For this cases, I am setting the latency to zero for negative values

2021-12-01 19:27 UTC, wallyrb commented on lte/gateway/c/core/oai/tasks/service303/service303_mme_stats.c
> +      "s1ap_last_msg_latency", stats_msg_p->nb_s1ap_last_msg_latency, label);
Adding the metric 's1ap_last_msg_latency` since I think will be useful to measure latency of s1ap task

2021-12-03 07:53 UTC, merged