feat(orc8r): FEG_RELAY update to redirect session request to N7_Proxy
magma/magma pull request #10254
Opened 2021-11-11 16:47 UTC by Abhishek-R15

## Summary

FEG_RELAY code changes to redirect sessiond request to N7_PROXY based on the RAT-TYPE 

## Additional Information

 Signed-off-by: Abhishek-R15 <abhishek.r@wavelabs.ai>

2021-12-14 19:35 UTC, uri200 requested changes
you may need to add an entry [here](
https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Amagma%2Fmagma.git&branch=master&file=feg%2Fcloud%2Fconfigs%2Fservice_registry.yml&editor=JetBrains&version=v1.2.1&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2.2&start_row=27&start_col=9&end_row=27&end_col=9) so feg can forward this properly


Check [here](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Amagma%2Fmagma.git&branch=master&file=feg%2Fgateway%2Fregistry%2Flocal_registry.go&editor=JetBrains&version=v1.2.1&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2.2&start_row=34&start_col=37&end_row=34&end_col=37) too to see how other services piping is done

2021-12-14 19:53 UTC, uri200 requested changes

2021-12-14 19:53 UTC, uri200 commented on feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/relay_router.go
> +	FegN7Proxy      gateway_registry.GwServiceType = "n7_proxy"
shoudn;t this be `N7_N40_PROXY`

2021-12-14 19:53 UTC, uri200 commented on feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/session_proxy_relay.go
> +			client, ctx, cancel, err := s.getProxyClient(ctx, req.Updates[0].CommonContext.RatType, plmnid)
can't updates come for different types of  rats on the same report?

2021-12-14 19:53 UTC, uri200 commented on feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/session_proxy_relay.go
> +
place this functions at the end

2021-12-14 19:53 UTC, uri200 commented on feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/session_proxy_relay.go
> +func (s *RelayRouter) getProxyClient(
move this function before the other two. This way the reader can read incrementally

2021-12-14 19:53 UTC, uri200 commented on feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/session_proxy_relay.go
> +	}
use a switch, this way you can have a default to `getSessionProxyClient` and it is clearer

2021-12-14 19:53 UTC, uri200 commented on feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/session_proxy_relay.go
> +func (s *RelayRouter) getN7ProxyClient(
`getN7N40ProxyClient`

Maybe we can rename the whole service to N740... .but that may be confusing. We can think about it

2021-12-14 19:53 UTC, uri200 commented on feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/session_proxy_relay.go
> +//N7_proxy service for 5G
i think you do not need different functions for each client. They are in fact only check if they are error, for you to check again on the main function

```
func (s *RelayRouter) getProxyClientctx context.Context, r protos.RATType, imsi string) (protos.CentralSessionControllerClient, context.Context, context.CancelFunc, error) {
	conn, ctx, cancel, err := s.GetFegServiceConnection(c, imsi, getProxyType(r))
	if err != nil {
		return nil, nil, nil, err
	}
	return protos.NewCentralSessionControllerClient(conn), ctx, cancel, nil

func getProxyType(r protos.RATType){
	switch(r):{
	case protos.RATType_TGPP_NR:
		return FegN7Proxy
	default:
		return FegSessionProxy
		
	}
}



```

2022-01-06 03:19 UTC, anusha-konda commented
@uri200 , all the comments provided here will be addressed in PR #11046 (in Draft, will open for review). Hence closing this PR.

2022-01-06 03:19 UTC, closed without merging