Add auto-healing tool for gateways in k8s cluster
magma/magma pull request #1029
Opened 2019-12-17 11:20 UTC by vladiskuz

This is standalone tool that aims to re-register
Magma's gateways in kubernetes cluster. It listens
kubernetes events and re-register gateways in orc8r.

2019-12-18 01:29 UTC, mpgermano requested changes
Thanks for this! I just had a few comments to combine the registration and configuration steps.

2019-12-18 01:29 UTC, mpgermano commented on orc8r/tools/magma-manipulator/README.md
> +git clone git@github.com:vladiskuz/magma-manipulator.git
Can you update this link to the magma repo and change the command to `cd magma/or8cr/tools/magma-manipulator`

2019-12-18 01:29 UTC, mpgermano commented on orc8r/tools/magma-manipulator/magma_manipulator/config.yml
> +    kubeconfig_path: /root/vkuzmin/test/magma-manipulator/magma_manipulator/kconfig
Can you remove/change `vkuzmin` to something more generic in this config

2019-12-18 01:29 UTC, mpgermano commented on orc8r/tools/magma-manipulator/magma_manipulator/magma_api.py
> +def _get_register_gateway_data(gw_net_type, gw_id, gw_uuid, gw_key, gw_name):
We should be able to get rid of this entire function by just registering the gateway with an existing config. See my comment below.

2019-12-18 01:29 UTC, mpgermano commented on orc8r/tools/magma-manipulator/magma_manipulator/main.py
> +                                               CONF.magma_certs_path)
We should just combine the `magma_api.register_gateway` and `magma_api.apply_gateway_config` calls. Any data that can be specified as configuration can instead be provided when we register the gateway. This helps ensure that we don't get into a bad state where registration succeeds, but the config update fails.

2019-12-18 01:29 UTC, mpgermano commented on orc8r/tools/magma-manipulator/magma_manipulator/magma_api.py
> +    data = _get_register_gateway_data(gw_net_type,
Replace this call with a call to fetch previous configuration.

2019-12-18 07:31 UTC, xjtian commented
Thanks for this @vladiskuz! This is a good tool for our CWF deployments which run the cwag on k8s, but it's not the right time to pull something like this into trunk magma since we're focused on the fixed wireless story for now (i.e. AGW on baremetal). 

I think it'd be great to keep this tool opensourced under its own repository, which I see you've already done at https://github.com/vladiskuz/magma-manipulator. We can revisit the possibility of pulling this into trunk if our recommended deployment form factor for AGW shifts to k8s.

2019-12-18 07:31 UTC, closed without merging

2019-12-23 20:23 UTC, zer0tweets commented
Jacky, hey! Can you share more with us re: what you mean about "focus on fixed wireless story" ? Related, is there some place where we can find roadmap / list of near term feature priorities for Magma to make sure our upstream work is aligned with mainline direction?