feat(nms):  Add support to configure PDN type of a APN
magma/magma pull request #10322
Opened 2021-11-15 15:34 UTC by HannaFar

Signed-off-by: HannaFar <hannafarag159@gmail.com>

## Summary

Add support to configure PDN type of a APN

<img width="1281" alt="Capture d’écran 2021-11-15 à 16 32 11" src="https://user-images.githubusercontent.com/26038920/141809285-e9b9e45c-6d76-4f51-9228-22308699cf6d.png">

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-11-17 21:58 UTC, andreilee requested changes
Add a test plan to the pull request. As a reviewer, I should have good confidence that this works end to end.

2021-11-17 21:58 UTC, andreilee commented on nms/packages/magmalte/app/views/traffic/ApnEdit.js
> +type pdn = 0 | 1 | 2 | 3;
This isn't a meaningful definition - in part I think encouraged by how we defined the type in the swagger files in the first place. Nonetheless, you should add clarity to this definition. First, use `Object.freeze` as typical for our enums. Have keys like `IPv4`, `IPv6`, etc, and map those keys to the values 0 - 3. I had to look up the swagger definition to understand what this meant, and ideally the definition should be self explanatory.

2021-12-01 04:35 UTC, andreilee approved these changes
lgtm!

2022-01-20 18:43 UTC, pshelar approved these changes

2022-01-26 10:12 UTC, merged