Lockless changes for CSFB related changes for combined attach, TAU and detach procedure
magma/magma pull request #1035
Opened 2019-12-18 02:32 UTC by rsarwad

Summary: Lock less changes for CSFB related changes for combined attach, TAU and detach procedure
Type: Refactor
Test Plan: Executed s1ap tester test suite

2019-12-19 12:46 UTC, rsarwad commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +  /*Initialize SGS context to default values*/
Change //

2019-12-19 12:46 UTC, rsarwad commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +  ue_context_p->sgs_context->ts9_timer.id = MME_APP_TIMER_INACTIVE_ID;
ts9_timer, ts10_timer, ts13_timer and ts8_timer remove 
Remove duplicates

2019-12-19 12:46 UTC, rsarwad commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +  emm_ctx_p->csfbparams.presencemask |= LAI_CSFB;
Keep in order for LAI copy

2019-12-19 12:46 UTC, rsarwad commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +  //Store Mobile Identity to be sent in Attach Accept/TAU Accept
Space

2019-12-19 12:46 UTC, rsarwad commented on lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c
>    if (EMM_REGISTERED == fsm_state) {
Use variable on left and constant on right

2019-12-19 12:46 UTC, rsarwad commented on lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c
>  {
Rename fun is_csfb_enabled() to emm_proc_combined_attach_req( )

2019-12-19 12:46 UTC, rsarwad commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +  rc = handle_cs_domain_loc_updt_acc(ue_context_p);
send_cs_domain_attach_tau_accept()()

Change the current fun name to handle_cs_domain_loc_updt_acc()

2019-12-19 12:46 UTC, rsarwad commented on lte/gateway/c/oai/tasks/nas/nas_proc.c
> +
Remove line

2019-12-19 12:46 UTC, rsarwad commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> -/**********************************************************************************
Move the map_sgs_emm_cause() to mme_app_sgsap_location_update.c file

2019-12-20 05:07 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
> +      if (NULL == ue_context_p->sgs_context->message_p) {
if (!ue_context_p->sgs_context->message_p)

2019-12-20 05:14 UTC, ssanadhya commented on lte/gateway/c/oai/include/nas_messages_def.h
> +
Remove space here to be consistent with rest of the file

2019-12-20 05:19 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +static uint8_t _get_eps_attach_type(uint8_t emm_attach_type);
Move definition of _get_eps_attach_type, _mme_app_update_granted_service_for_ue  and _mme_app_compare_tmsi here

2019-12-20 05:30 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +  emm_ctx_p->csfbparams.lai.mncdigit3 =
Swap line 230 and 236 so all MCC and MNC digits are in order

2019-12-20 05:41 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +      tmsi_mobile_identity_t received_tmsi = {0}, *received_tmsi_p = NULL;
We don't need two variables here, just "received_tmsi" is enough. Replace calls to "received_tmsi_p" below with "&received_tmsi"

2019-12-20 05:41 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +  /* Store the status of Location Update procedure(success/failure) to send appropriate cause
Line too long

2019-12-20 06:26 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +    ue_context_p->e_utran_cgi.plmn.mcc_digit2;
Re-order the statements so that all MCC and MNC digits are together

2019-12-20 06:41 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +      RETURNerror == (_handle_cs_domain_loc_updt_acc(
Move Macro to right side of check

2020-01-13 05:38 UTC, ssanadhya requested changes

2020-01-13 05:38 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
> +         * Handle Ue initiated EPS detach towards SGS
Convert to single line comment

2020-01-13 05:38 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
> +         * Handle Ue initiated IMSI detach towards SGS
Convert to single line comment

2020-01-13 05:38 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
> +         * Handle Ue initiated Combined EPS/IMSI detach towards SGS
Convert to single line comment

2020-01-13 05:38 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
> +       * process the respective message in different state
Comment can be wrapped in fewer lines

2020-01-13 05:38 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
> +#include "emm_proc.h"
Do we need this header here?

2020-01-13 05:38 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +  additional_update_type =
Can be merged with line 73

2020-01-13 05:38 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
> +int _mme_app_compare_tmsi(
Can this be converted into a macro?

2020-01-13 06:42 UTC, rsarwad commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
> +#include "emm_proc.h"
Yes removed

2020-01-14 20:17 UTC, closed without merging