feat(feg): N7 Proxy service metrics and health check implementation
magma/magma pull request #10362
Opened 2021-11-16 20:31 UTC by GANESH-WAVELABS

Signed-off-by: GANESH IRRINKI <ganesh.irrinki@wavelabs.ai>
## Summary
Implements metrics and health check for N7 Proxy service.

## Additional Information
Depends on #10360. Can be merged only after 10360 is merged.
This is a split from #10223

2021-11-16 20:42 UTC, uri200 commented
this PR comes from https://github.com/magma/magma/pull/10223

2021-11-18 08:14 UTC, GANESH-WAVELABS commented
@uri200 and @themarwhal Could you please start review this PR

2021-11-18 08:19 UTC, uri200 commented
Hey @GANESH-WAVELABS , note i just reviewed the PR that is under this one .

Please, go through all the coments I mentioned. All those changes will trigger changes on this current PR. 

Otherwise @themarwhal may be  eviewing something is being reviewed on n another PR.

2021-11-19 07:51 UTC, uri200 requested changes
rebase please

2021-11-19 07:51 UTC, uri200 commented on feg/gateway/services/n7_proxy/metrics/metrics.go
> +		return nil, fmt.Errorf("nil current health metrics provided")
What about 
```
GetDelta has nil SessionHealthMetrics
```
This way it gives more information about the call and  it is easy to find the error doing a quick search

2021-11-19 07:51 UTC, uri200 commented on feg/gateway/services/n7_proxy/servicers/session_controller.go
> +		RequestTimeout: 3 * time.Second,
Try not to hardcode values in the middle of the code 

Use constants 

https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Amagma%2Fmagma.git&branch=master&file=feg%2Fgateway%2Fgtp%2Fgtp_client.go&editor=JetBrains&version=v1.2.1&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2.2&start_row=31&start_col=12&end_row=31&end_col=12

2021-11-19 07:51 UTC, uri200 commented on feg/gateway/services/n7_proxy/servicers/session_controller.go
> +) (*protos.CreateSessionResponse, error) {
i think you need to rebase now to get the changes here

2021-11-19 07:51 UTC, uri200 commented on feg/gateway/services/n7_proxy/servicers/session_controller.go
> +func (srv *CentralSessionController) Disable(
If I recall correctly health service is related with High Availability (HA) feature. When health is bad, orc8r will switch to another FEG and then send disable message (the other feg will receive enable)

However, that enable/disable was needed for diameter (its connection is stateful, so you need to disconnect from the server and release the client). But  per what I understand 5g is connectionless which means there client doesn't really need to be enabled.

If this is the case you can just implement thos functions to do nothing

2021-11-19 07:51 UTC, uri200 commented on feg/gateway/services/n7_proxy/servicers/session_controller.go
> +	DisableN7      bool
If you check session_proxy, this  field comes from mconfig field with the same name, 
This field it is noot related with Enabled/Disabled status on health service

2021-11-19 07:51 UTC, uri200 commented on feg/gateway/services/n7_proxy/servicers/session_controller.go
> +	srv.cfg.DisableN7 = false
I think session_porxy was a little bit confusing [here](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Amagma%2Fmagma.git&branch=master&file=feg%2Fgateway%2Fservices%2Fsession_proxy%2Fservicers%2Fsession_controller.go&editor=JetBrains&version=v1.2.1&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2.2&start_row=405&start_col=20&end_row=405&end_col=20)

This field in session proxy only indicates if gx or gy are enabled by configuration. We don't save the transient state of the feg. 

But in any case, i think Enable/Disable can be void functions

2021-11-19 07:51 UTC, uri200 commented on feg/gateway/services/n7_proxy/servicers/session_controller.go
> +
what about creating `health.go` and putting all those functions there

Then session_controller.go will be small and clean

Look how in [here](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Amagma%2Fmagma.git&branch=master&file=feg%2Fgateway%2Fservices%2Fs8_proxy%2Fservicers%2Fs8_proxy.go&editor=JetBrains&version=v1.2.1&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2.2&start_row=73&start_col=1&end_row=73&end_col=1) how each functions is just a set of functios which describe clearly what they do (parse message, send message, return messge)

2021-11-19 07:51 UTC, uri200 commented on feg/gateway/services/n7_proxy/servicers/session_controller.go
> +) (*fegprotos.HealthStatus, error) {
btw, golang has a longer limit per line (i think it is 185). Lets use it if possible, 

you can do this
```
func (srv *CentralSessionController) GetHealthStatus(ctx context.Context, void *orcprotos.Void) (*fegprotos.HealthStatus, error) {
```

2021-11-19 07:51 UTC, uri200 commented on feg/gateway/services/n7_proxy/servicers/session_controller.go
> +			HealthMessage: fmt.Sprintf("Error occurred while retrieving health metrics: %s", err),
since this will be returned to the caller, it is better to return the service name 
```
Error occurred while retrieving health metrics on N7:
```

2021-11-19 15:19 UTC, GANESH-WAVELABS commented
> rebase please

Done.

2021-11-19 20:32 UTC, uri200 commented on feg/gateway/services/n7_n40_proxy/servicers/health.go
> +}
Normally we set the grpc end points in the same file so we can see them all in one look. The rest of the functions are in other files (like health)

But it is true that this also make sense this way. 

Let's leave if as it is right now. We can change it in the future if needed. This is another good thing of go, you can move functions around without caring about headers.

2021-11-19 20:33 UTC, uri200 commented on feg/gateway/services/n7_n40_proxy/metrics/metrics.go
> +}
i know we do not have any test file for any of our health files. Someday we will have to fix that. But lets leave it as it is for now

2021-11-19 20:35 UTC, uri200 approved these changes
nice. See how easy review becomes when we have ~300 to 500 lines PRs

Thanks for dividing them into separate PRs!

2021-11-19 20:35 UTC, merged