fix(ci): Fix for issue 10193 Exit gracefully on skips
magma/magma pull request #10414
Opened 2021-11-18 14:52 UTC by ranj8work

Signed-off-by: Ranjini Iyer <ranj8work@gmail.com>

## Summary
Fix for issue [10193](https://github.com/magma/magma/issues/10193) Exit gracefully comment on PR job when job was skipped.

## Test Plan
Testing is done in forked repo with changes in master branch to reflect the workflow and its execution.

## Additional Information

- [NO] This change is backwards-breaking

2021-11-18 15:55 UTC, quentinDERORY requested changes
You need to skip the comment workflow when the triggering workflows are skipped

2021-11-23 17:28 UTC, ranj8work commented
> You need to skip the comment workflow when the triggering workflows are skipped

Hi @quentinDERORY I took care of the changes needed. Please review.

2021-11-23 17:29 UTC, quentinDERORY commented on .github/workflows/docs-workflow.yml
> +          echo -n ${{ github.event.number }} > ./pr/NR
You don't need to upload the artifacts a second time.

2021-11-23 17:31 UTC, quentinDERORY commented on .github/workflows/comment-pr-on-check-failure.yml
> +    runs-on: ubuntu-latest
add this here` if: github.event.workflow_run.event == 'pull_request' ||  github.event.workflow_run.event == 'pull_request_target'`

2021-11-23 17:31 UTC, quentinDERORY commented on .github/workflows/comment-pr-on-check-failure.yml
> +    if: >
only specify the skip_check_output condition

2021-11-23 17:32 UTC, quentinDERORY requested changes
See comments

2021-11-24 02:24 UTC, ranj8work commented
> See comments

Took care of all the review comments of @quentinDERORY. Ready for review.

2021-11-29 18:39 UTC, quentinDERORY commented on .github/workflows/comment-pr-on-check-failure.yml
> +            if( skipFlag == 'true' ) {
Can you do a or instead of an else if

2021-11-29 18:39 UTC, quentinDERORY commented on .github/workflows/comment-pr-on-check-failure.yml
> +
Address linter issues

2021-11-29 18:40 UTC, quentinDERORY commented on .github/workflows/docs-workflow.yml
> +
here too

2021-11-29 23:51 UTC, ranj8work commented on .github/workflows/comment-pr-on-check-failure.yml
> +
Updated and pushed code changes

2021-11-29 23:51 UTC, ranj8work commented on .github/workflows/docs-workflow.yml
> +
Updated and pushed code changes

2021-11-29 23:52 UTC, ranj8work commented on .github/workflows/comment-pr-on-check-failure.yml
> +            if( skipFlag == 'true' ) {
Updated and pushed code changes

2021-11-29 23:52 UTC, ranj8work commented
@quentinDERORY - Took care of the review comments and pushed the changes.

2021-11-30 16:49 UTC, quentinDERORY approved these changes

2021-11-30 16:49 UTC, merged