[WIP]: Magma Domain Proxy -  Github workflows
magma/magma pull request #10531
Opened 2021-11-24 12:54 UTC by m-trojanowski

Signed-off-by: Marcin Trojanowski <marcin.trojanowski@freedomfi.com>

[WIP]: Magma Domain Proxy

## Summary
As concluded in https://github.com/magma/magma/pull/10230
This set of PRs is a proposal of a merge of Domain Proxy development into Magma codebase.

As discussed in a community meeting with @talkhasib , @hcgatewood, @jpad-freedomfi, @aswin-alexander, @bbarritt and others, this PR is a first step of discussion on how to include the ongoing development of vendor neutral Domain Proxy code into Magma's codebase.

The PR consists of a few commit's, each commit intended to target a specific section of magma code and its ownership.
Please review and comment if this division makes logical sense. We could either proceed with having one PR with such commits, or we can issue individual PRs per each section/domain.

Currently we have 5 PRs in this set which breaks code in somewhat more reviewable chunks:
1) Helm charts integration - this development has already been reviewed by @hcgatewood 
2) Orchestrator deployment integration
3) Domain Proxy: AGW side - integration with AGW/enodebd (LTE module) based on Baicells 436Q eNB
4) Domain Proxy: ORC8R side - domain proxy microservices that interact with AGW/enodebd and SAS server
5) Github workflows

The Domain Proxy part presented here, with minor alternations done due to rebase onto magmas master, has been fully tested in a local lab - helm, deployment, DProxy in orc8r interface with AGW, Baicells 436Q eNB able to be fully configured.

The code is now capable of acquiring and maintaining a SAS grant on behalf of a Baicells 436Q and fully configure it for transmission via TR069.

2021-12-27 17:12 UTC, quentinDERORY requested changes
LGTM but the new workflows are failing

2022-01-05 18:40 UTC, ardzoht commented
@xbend Looks like the workflow is failing, is this because we need the dependent PRs merged first?

2022-01-05 18:55 UTC, xbend commented
@ardzoht 
Correct. #10527 must be merged first for this one to start passing the workflow CI tests.

2022-01-10 20:46 UTC, quentinDERORY approved these changes

2022-01-10 23:11 UTC, merged