chore(agw) Reduce loglevel of error-treating functions
magma/magma pull request #10628
Opened 2021-12-02 08:18 UTC by jheidbrink

Fixes 10408

## Summary

This reduces some loglevels from error to Info or Debug. All log statements touched here are executed while treating a RpcError ("Checkin Error") which is already logged with loglevel Error.

## Test Plan

None

## Additional Information

- [ ] This change is backwards-breaking

2021-12-02 09:01 UTC, Neudrino reviewed
For consistency we should have always sentences or nowhere.

2021-12-02 09:01 UTC, Neudrino commented on orc8r/gateway/python/magma/common/cert_validity.py
> +            'Tcp connection succeeded but SSL connection did not: %s, %s. Assuming invalid SSL certificate.',
```suggestion
            'TCP connection succeeded but SSL connection did not: %s, %s. Assuming invalid SSL certificate.',
```
For consistency. :wink:

2021-12-02 09:01 UTC, Neudrino commented on orc8r/gateway/python/magma/common/cert_validity.py
> +            'Error making TCP connection: %s, %s - thus no indication for invalid SSL certificate',
```suggestion
            'Error making TCP connection: %s, %s. Thus, no indication of an invalid SSL certificate.',
```
For consistency with below.

2021-12-02 09:01 UTC, Neudrino commented on orc8r/gateway/python/magma/common/cert_validity.py
> +    logging.debug('SSL connection succeeded - thus no indication for invalid SSL certificate')
```suggestion
    logging.debug('SSL connection succeeded. Thus, no indication of an invalid SSL certificate.')
```

2021-12-02 09:01 UTC, Neudrino commented on orc8r/gateway/python/magma/magmad/state_reporter.py
> +            logging.info('Bootstrapping due to invalid cert')
```suggestion
            logging.info('Bootstrapping due to invalid certificate')
```
For consistency.

2021-12-02 09:33 UTC, jheidbrink commented
> For consistency we should have always sentences or nowhere.

Agreed. I would then tend to not use sentences as that aligns with the overall style in Magma.

2021-12-02 10:45 UTC, Neudrino approved these changes

2021-12-07 20:26 UTC, andreilee approved these changes

2021-12-07 21:46 UTC, hcgatewood requested changes
Hm I'm not sure this is how we want to handle this -- correct me if I'm wrong!

Basically, failure to check-in is like *things are broken*, and treating it as debug-only will increase operator confusion

If this is part of a larger plan to be more concise about err logging, e.g. only logging check-in errs once, then can you add that info to the PR summary and re-request review 🙂

2021-12-08 08:29 UTC, sebathomas commented
@hcgatewood The idea is that the initial check-in error will still be logged as an error, while all the log statements changed here are an expected part of the reaction to the error, and not really errors themselves. It's better explained in the [linked issue](https://github.com/magma/magma/issues/10408#issuecomment-983784335).

So yes, it's part of a plan to be more concise about error logging.

2021-12-11 00:14 UTC, hcgatewood approved these changes
Okay awesome, that's what I wanted to hear, sounds good / carry on! 🙂

2021-12-13 15:08 UTC, merged