WIP migrate sentry to GHA
magma/magma pull request #10693
Opened 2021-12-06 18:59 UTC by quentinDERORY

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-12-13 17:12 UTC, jheidbrink commented on .github/workflows/build_all.yml
> +          MAGMA_VERSION=ls lte/gateway/magma-packages/ | grep "^magma_[0-9].*"xargs -I "%" dpkg -I ~/magma-packages/% | grep "Version" | awk \'{print $2}\'
pull/10832 changes this for CircleCI.

2021-12-15 16:18 UTC, themarwhal commented on .github/workflows/composite/sentry-create-and-upload-artifacts/action.yml
> +        projects: ["lab-agws-native", "radtonics_lab_native", "magma-staging-native", "si-agw-native"]
As a note for maybe future improvements, sentry does support just uploading to a custom repository (https://docs.sentry.io/platforms/native/data-management/debug-files/symbol-servers/) . Then maybe we don't have to upload to every new project we add, we can just add it to one place. Maybe I'll add an issue to file this :D

2021-12-17 20:49 UTC, themarwhal approved these changes

2021-12-20 16:07 UTC, jheidbrink requested changes

2021-12-20 16:07 UTC, jheidbrink commented on .github/workflows/build_all.yml
> +           COMMIT_HASH_WITH_VERSION="magma@1.7.0.$(git rev-list --count HEAD)-${GITHUB_SHA:0:9}"
I think we should use `${GITHUB_SHA:0:8}` here to align with the `get_commit_hash` [function](https://github.com/magma/magma/blob/master/orc8r/tools/fab/pkg.py#L65-L66) that is used to [determine the version](https://github.com/magma/magma/blob/9e9cb764e57d038fa9d8a08d81b49a3ddc526aa8/lte/gateway/release/build-magma.sh#L268) in `build-magma-sh`.

2021-12-20 16:10 UTC, jheidbrink commented on .github/workflows/build_all.yml
> +           COMMIT_HASH_WITH_VERSION="magma@1.7.0.$(git rev-list --count HEAD)-${GITHUB_SHA:0:9}"
Now that we don't read `magma_version` anymore, we can remove the comment above.

2021-12-20 20:16 UTC, jheidbrink approved these changes

2021-12-20 20:18 UTC, merged