chore(ci): update devcontainer image in CI
magma/magma pull request #10736
Opened 2021-12-08 14:57 UTC by alexzurbonsen

Signed-off-by: Alexander zur Bonsen <alexander.zur.bonsen@tngtech.com>

## Summary

Update the devcontainer image in CI and devcontainer.json

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-12-08 15:40 UTC, Neudrino approved these changes

2021-12-08 15:44 UTC, Neudrino commented
Btw, the image stream change is due to parametrisation and the use of Github variables within the Github composite actions. It should not be any issue though.

2021-12-08 16:07 UTC, quentinDERORY approved these changes

2021-12-08 16:09 UTC, electronjoe commented
> Btw, the image stream change is due to parametrisation and the use of Github variables within the Github composite actions. It should not be any issue though.

Thanks for the explanation!

2021-12-08 16:10 UTC, electronjoe approved these changes
Looks like all workflows pass! CodeCov is in progress but I expect that to be GTG (plus it's required so LGTM here is safe).

2021-12-09 10:30 UTC, Neudrino requested changes
This PR depends on https://github.com/magma/magma/pull/10755. We will update the hash again, when changes from https://github.com/magma/magma/pull/10755 are available in GHCR.

To not change image twice, I will mark this as "Request changes" to avoid accidental merging.

2021-12-10 16:44 UTC, Neudrino approved these changes

2021-12-10 17:07 UTC, Neudrino commented
Docker image hash was updated after https://github.com/magma/magma/pull/10755 was merged.

2021-12-13 10:40 UTC, Neudrino commented
This PR is required for https://github.com/magma/magma/pull/10341.

2021-12-13 15:08 UTC, merged

2021-12-13 15:10 UTC, themarwhal commented
Hey @Neudrino, does this mean we should update other usages like this one? https://github.com/magma/magma/blob/master/lte/gateway/python/precommit.py#L27

2021-12-13 15:42 UTC, Neudrino commented
> Hey @Neudrino, does this mean we should update other usages like this one? https://github.com/magma/magma/blob/master/lte/gateway/python/precommit.py#L27

Hi @themarwhal , that depends.
Of course the old image is still available, and if there are no changes to the Dockerfile it will be the same as the new one. So there is no immediate necessity to do so. However, in long term, an update of the image stream tag is sensible also for all other images used. I created an issue for it https://github.com/magma/magma/issues/10828 and assigned it to myself.