feat(CI) : Check if PR is rebased on top of Master
magma/magma pull request #10766
Opened 2021-12-09 21:04 UTC by JeanPec

Signed-off-by: JeanPec <andremarie67450@gmail.com>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-12-14 17:44 UTC, quentinDERORY commented on .github/workflows/check-rebase.yml
> +      PR_NUMBER: "${{ github.workspace }}"
remove this

2021-12-14 17:44 UTC, quentinDERORY commented on .github/workflows/check-rebase.yml
> +      - run: |
define the head and base SHA as environment variable to make the code more readable

2021-12-14 17:45 UTC, quentinDERORY commented on .github/workflows/check-rebase.yml
> +          BASE_HEAD_HASH=$(git merge-base ${{github.event.pull_request.base.sha}} ${{github.event.pull_request.head.sha}})
ReName BASE_HEAD_HASH to COMMON_SHA

2021-12-14 17:45 UTC, quentinDERORY commented on .github/workflows/check-rebase.yml
> +      - run: |
Name the step check commits hash

2021-12-14 17:46 UTC, quentinDERORY requested changes
See comments

2021-12-14 23:56 UTC, quentinDERORY approved these changes

2021-12-15 17:13 UTC, quentinDERORY commented
/rebase

2021-12-15 17:56 UTC, tmdzk approved these changes

2021-12-15 18:32 UTC, merged