restart all services when shared config changes
magma/magma pull request #10809
Opened 2021-12-10 19:44 UTC by ankitbhadoria21

## Summary

while processing updates to gateway.mconfig, we check if shared_mconfig changes, if yes, add all the services to restart list.

## Test Plan

ran various scenarios on local vm.

![Screen Shot 2021-12-10 at 1 47 56 PM](https://user-images.githubusercontent.com/12483853/145632477-52b72062-4e0b-4bd8-8510-dddbe9c8f9ca.png)
<img width="990" alt="Screen Shot 2021-12-10 at 1 49 09 PM" src="https://user-images.githubusercontent.com/12483853/145632479-a9cc24c7-1dd7-40b8-80bb-6ba38082594d.png">
<img width="1145" alt="Screen Shot 2021-12-10 at 1 47 46 PM" src="https://user-images.githubusercontent.com/12483853/145632482-ac7c94f8-aa51-45f4-8b7b-852ce7e84de7.png">

2021-12-10 20:47 UTC, themarwhal commented on orc8r/gateway/python/magma/magmad/config_manager.py
> -        # TODO adapt service restart logic to include changes in shared_mconfig
Let's also restart magmad if we modify the shared config as well ^ see line 113

2021-12-10 20:48 UTC, themarwhal commented
Rename PR title to "feat(agw): restart services on shared config changes" to make the semantic PR check happy :)

2021-12-10 20:55 UTC, themarwhal commented on orc8r/gateway/python/magma/magmad/config_manager.py
> +        if 'shared_mconfig' in mconfig.configs_by_key and did_mconfig_change('shared_mconfig'):
let's define a const value for this so we avoid typos :D

2021-12-10 20:56 UTC, themarwhal commented on orc8r/gateway/python/magma/magmad/config_manager.py
> +            logging.info("shared config changed. Restarting all services.")
```suggestion
            logging.info("Shared config changed. Restarting all services.")
```

2021-12-13 14:01 UTC, themarwhal approved these changes
LGTM :)

2021-12-13 14:03 UTC, themarwhal commented on orc8r/gateway/python/magma/magmad/config_manager.py
> +        def restart_magmad():
Does this function restart magmad or only the dynamic servicecs loaded from the magmad config?

2021-12-13 14:05 UTC, themarwhal commented on orc8r/gateway/python/magma/magmad/config_manager.py
> +        if did_mconfig_change('magmad'):
might be cleaner to keep these two logics separate. So something like 
```python
if shared_mconfig_changed or magmad_changed:
   restart things

# process other services
```

2021-12-13 14:07 UTC, themarwhal requested changes
looks like the lte-test check is failing on CI. The GitHub action checks use a different env than the magma VM so maybe something is missing there: https://github.com/magma/magma/blob/master/.github/workflows/agw-workflow.yml#L52

2021-12-13 14:41 UTC, themarwhal commented on orc8r/gateway/python/magma/magmad/config_manager.py
> +        shared_mconfig = 'shared_mconfig'
Let's move this up to the top of the file as other consts are defined that way.
See https://github.com/magma/magma/blob/master/orc8r/gateway/python/magma/magmad/config_manager.py#L29

2021-12-13 22:15 UTC, themarwhal commented
Would be great if you could file an issue for removing the config dependency for lte-test and take that on. :)

2021-12-13 22:24 UTC, themarwhal commented on orc8r/gateway/python/magma/magmad/config_manager.py
> +            logging.info("Restarting dynamic Services.")
```suggestion
            logging.info("Restarting dynamic services due to config change")
```

2021-12-13 22:38 UTC, ankitbhadoria21 commented
> Would be great if you could file an issue for removing the config dependency for lte-test and take that on. :)

I would create a issue and add it to the backlog, and try to pick it up later :)

2021-12-13 23:29 UTC, closed without merging