refactor(orc8r): Segregation of tenants servicer as internal
magma/magma pull request #10902
Opened 2021-12-16 09:35 UTC by shivesh-wavelabs

## Summary

Segregation of tenants servicer as internal only for security reasons.

Created orc8r/cloud/go/services/tenants/servicers/internal directory and Updated TenantsService gRPC Servicer as internal. Moved orc8r/protos/tenants.proto to orc8r/cloud/go/services/tenants/protos/tenants.proto

## Test Plan

All UTs passed successfully.

2022-01-07 15:43 UTC, bbarritt commented
@hcgatewood a reminder on this PR review request

2022-01-26 23:15 UTC, hcgatewood reviewed
Lgtm. Will review in more detail tmrw

2022-01-26 23:15 UTC, hcgatewood commented on orc8r/cloud/go/services/tenants/client_api.go
> +	common_protos "magma/orc8r/lib/go/protos"
One nit: let's not alias this one (so it's just `protos`), and instead alias the the more-specific protos (so e.g. `tenant_protos`)

2022-01-27 20:19 UTC, christinewang5 commented
Hmm why the extra `protected` folder in `magma/orc8r/cloud/go/services/tenants/servicers/protected/servicer.go`? All the other services follow the pattern `magma/orc8r/cloud/go/services/**/servicers/servicer.go`?

2022-01-27 21:32 UTC, hcgatewood requested changes
Lgtm, just make that 1 readability change then I'm content 👍

2022-01-27 21:34 UTC, hcgatewood commented
> Hmm why the extra `protected` folder in `magma/orc8r/cloud/go/services/tenants/servicers/protected/servicer.go`? All the other services follow the pattern `magma/orc8r/cloud/go/services/**/servicers/servicer.go`?

Reasonable question. For context, we're moving all servicers into `**/servicers/{protected,external}/` to clearly denote whether the servicer is for internal Orc8r usage vs. southbound exposed to the world. If you wanna read more: https://fb.quip.com/Bb6cA6G9rRIx

2022-02-01 16:09 UTC, shivesh-wavelabs commented
Hi @hcgatewood, could you review this PR.

2022-02-01 22:18 UTC, hcgatewood commented
Hi @shivesh-wavelabs, I still am reading a lot of "common_protos" throughout the change. Here's my request to rename those https://github.com/magma/magma/pull/10902#discussion_r793129459

2022-02-02 04:53 UTC, shivesh-wavelabs commented
> Hi @shivesh-wavelabs, I still am reading a lot of "common_protos" throughout the change. Here's my request to rename those [#10902 (comment)](https://github.com/magma/magma/pull/10902#discussion_r793129459)

@hcgatewood  i have introduced tenants_protos and removed common_protos from all the places.
could you review this PR.

2022-02-02 18:37 UTC, hcgatewood approved these changes

2022-02-02 18:37 UTC, merged