refactor(feg): Segregation of CentralSessionController servicer as external
magma/magma pull request #11068
Opened 2022-01-06 11:38 UTC by shivesh-wavelabs

Signed-off-by: shivesh-wavelabs <shivesh.ojha@wavelabs.ai>

## Summary
This PR deals with the segregation of CentralSessionController's external gRPC servicers implementation.
These changes are part of the ongoing work which details the distinction between Orc8r-external gRPC endpoints vs. external, gateway-oriented gRPC endpoints.
Moved CentralSessionController implementation from  feg/gateway/services/session_proxy/servicers/ to  feg/gateway/services/session_proxy/servicers/southbound/

## Test Plan
Verified existing UT cases.

2022-01-07 01:01 UTC, emakeev commented
I am not sure, I understand the purpose of this PR. 

session_proxy provides this gRPC service: https://github.com/magma/magma/blob/master/lte/protos/session_manager.proto#L670-L680
And the service is getting registered here: https://github.com/magma/magma/blob/master/feg/gateway/services/session_proxy/session_proxy/main.go#L74-L75

This service is used by other gateways (AGW, CWAG) and orc8r only facilitates inter-gateway/inter-network RPC.
So, in terms of directionality, it's rather east/west bound (GW to GW) then southbound (cloud to GW) service and it runs on a GW (FeG).

What is the reason for moving implementation files under 'southbound' directory? What does it accomplish?
Maybe I am missing some feature request/issue (if this is the case, please reference it in the PR comments), if not - could you provide some explanation in your PR request?

2022-01-07 02:15 UTC, emakeev requested changes
It seems like this change doesn't actually do anything useful and a bit confuses codebase of already complicated enough component. Let's discuss it with FeG team first.

2022-01-16 11:04 UTC, sabithaatla reviewed
Changes not required

2022-02-03 04:09 UTC, closed without merging

2022-02-03 17:34 UTC, sabithaatla commented
Closing this PR as new PR created for all the FegRelay servicers.
https://github.com/magma/magma/pull/11414