chore: Bump @fbcnms/platform-server to 0.2.2 to pick up pug-code-gen bump from 2.0.2 to 3.0.2
magma/magma pull request #11168
Opened 2022-01-14 19:36 UTC by lucasgonze

## Summary

Bump @fbcnms/platform-server to 0.2.2 to pick up pug-code-gen bump from 2.0.2 to 3.0.2

Fixes https://github.com/ospoco/magma-issue-tracker/issues/30

## Test Plan

```
cd nms
yarn run test
...
Test Suites: 37 passed, 37 total
Tests:       103 passed, 103 total
```

## Additional Information

- [ ] This change is backwards-breaking

2022-01-14 21:50 UTC, andreilee requested changes
CI check `build-all / nms-build job` is failing, and you'll want to rebase. This looks fine, otherwise.

2022-01-19 01:52 UTC, lucasgonze commented
There is one CI check failing, `Cannot get `property `hardware_id` is missing in undefined `. I have talked it over with Quentin in https://github.com/magma/magma/issues/11200. He says 

> I think I know what the issue is for the missing git command. We need to add the checkout module on push. 

That is a CI problem, not a problem in the PR.

2022-01-28 21:38 UTC, themarwhal commented
Hi @lucasgonze ! Please only label a PR as ready2merge once it has been approved and passes all checks.

2022-01-28 21:56 UTC, lucasgonze commented
> Hi @lucasgonze ! Please only label a PR as ready2merge once it has been approved and passes all checks.

The failing check is this CI bug: "property hardware_id is missing" in GitHub Actions #11221. It is probably not related to the content of the merge.

2022-01-31 22:58 UTC, lucasgonze commented
Closing in favor of https://github.com/magma/magma/pull/11329, which picks up a later version of platform-server.

2022-01-31 22:58 UTC, closed without merging