fix(mme): Update GetENBState to remove S1AP state mgr dependency
magma/magma pull request #11320
Opened 2022-01-28 18:16 UTC by ardzoht

Signed-off-by: Alex Rodriguez <alexrod@fb.com>

## Summary

- Removes `get_s1ap_state` usage from S1AP GRPC service which was causing segfault due to `s1ap_state` nullptr, closes #8450 
- Refactors `S1apServiceImpl::GetENBState` for using direct access to redis to construct GRPC response 
- Formatting changes

## Test Plan

- Testing on local environment to ensure eNB state is retrieved by `enodebd` service
- Pending: Add unit test / integ test for `GetENBState` endpoint

## Additional Information

- [ ] This change is backwards-breaking

2022-01-31 17:55 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/grpc_service/S1apServiceImpl.cpp
> +  }
This type of design has two major issues:

1. GRPC servicer is not the owner of the state and it should not rely on Redis backend to fetch it. The actual owner may evolve and change how/when these states are updated/refactored on Redis.

2. This breaks the parity between stateful and stateless. E.g., if someone disables stateless feature, eNB state will no longer be read.

2022-01-31 17:57 UTC, ulaskozat requested changes
@ardzoht I did not raise this concern during the last meeting, but the change you are doing here needs to be discussed at a higher architectural level.

2022-01-31 18:01 UTC, ulaskozat commented
The motivating idea for this particular change is to eliminate unnecessary ITTI messages. Then, why don't we consider making this a push rather than pull model? i.e., MME makes the rpc call to deliver the eNB states.

2022-02-01 00:59 UTC, ardzoht commented
> The motivating idea for this particular change is to eliminate unnecessary ITTI messages. Then, why don't we consider making this a push rather than pull model? i.e., MME makes the rpc call to deliver the eNB states.

There are currently no ITTI messages being passed, motivating idea for this is that there is an issue when the RPC call is done to MME and the `s1ap_state` is null: https://sentry.io/organizations/lf-9c/issues/2897744515/?project=5754002&referrer=github_integration (this is happening on service initialization, likely due to the gRPC service being initialized and the S1AP task not having populated state yet), and so the service crashes.

Couple of remarks on the gRPC service and how state is used:

1. Push model seems like a good approach given that the MME initiates communication, but with the expectation this should be done once all local state on MME is populated.
2. Ideally an approach to take for MME state is to define Redis as a first class citizen for storage (no sync between local state and Redis, no stateless vs stateful modes), obviously this is out of scope for this change but something to keep in mind while thinking on the ownership of the states.
cc @ssanadhya

2022-03-25 02:47 UTC, closed without merging