chore(nms): Upgrade @fbcnms/platform-server from 0.2.0 to 0.3.0
magma/magma pull request #11329
Opened 2022-01-31 13:47 UTC by spikey979

Signed-off-by: Kristijan <spikey979@gmail.com>

chore(nms): Upgrade @fbcnms/platform-server from 0.2.0 to 0.3.0

## Summary

   If a remote attacker was able to control the pretty option of the pug compiler, e.g. if you spread a user provided object such as the query parameters of a request into the pug template inputs, it was possible for them to achieve remote code execution on the node.js backend.
   pug_code_gen package is indirectly used in package pug v2.0.3. which is used in  @fbcnms/platform-server v0.2.0.  @fbcnms/platform-server needs to be upgraded to version 0.3.0 so pug_code_gen v2.0.2 is no longer needed. 

## Test Plan
ran in /magma/nms folder:
yarn run eslint
yarn run flow
yarn run test

## Additional Information

PR is fix for dependabot alert: https://github.com/magma/magma/security/dependabot/nms/yarn.lock/pug-code-gen/open

2022-02-03 19:45 UTC, andreilee requested changes
Could you rebase the changes? Looks fine otherwise.

2022-02-04 06:53 UTC, spikey979 commented
I rebased the changes

2022-02-04 20:09 UTC, lucasgonze commented
Blocked on https://github.com/facebookincubator/fbc-js-core/pull/159

Then platform-server needs to go to 0.3.1 and sequelize-models to 0.1.13

2022-02-09 01:08 UTC, andreilee commented
Superceded by https://github.com/magma/magma/pull/11435

2022-02-09 01:08 UTC, closed without merging