docs(orc8r): Removed install orc8r managed page
magma/magma pull request #11383
Opened 2022-02-02 15:35 UTC by christinewang5

## Summary
`Managed Orc8r Deployment via Orcl` is no longer used and is not the primary method to deploy, so is generally confusing to leave in the docs.

2022-02-02 15:39 UTC, themarwhal approved these changes

2022-02-02 18:44 UTC, hcgatewood requested changes
Awesome! Looks like there are a couple references to this page as well, both in other pages and in the sidebars.json. Can you remove those as well?

2022-02-07 15:51 UTC, themarwhal commented
Removing `ready2merge` as it still needs Hunter's stamp

2022-02-08 00:04 UTC, hcgatewood approved these changes

2022-02-08 00:04 UTC, merged