fix(agw) wrong state transition in Sercomm
magma/magma pull request #11432
Opened 2022-02-04 14:49 UTC by WojSad

Signed-off-by: Wojciech Sadowy <wojciech.sadowy@freedomfi.com>

fix(agw) wrong state transition in Sercomm

## Summary

After acs-triggered reboot Sercomm's (freedomfi_one) state machine
was trying to enter an undefined state 'wait_empty' raising an error
Changed to 'wait_inform' which is the type of message that is actually sent after
the reboot

## Test Plan

tests updated

2022-02-07 15:35 UTC, xbend commented
@ulaskozat 
This change should be reviewable now. WPS python checks will not pass on AGW python code, mme test failure is related to a bug present in master cpp code.

2022-02-09 17:38 UTC, ardzoht requested changes
minor change requested, once that's updated I'll approve the PR

2022-02-09 17:38 UTC, ardzoht commented on lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
> +            desired_cfg.set_parameter(name, value=val)
pass keyword argument to `name` as well to be consistent

2022-02-11 09:11 UTC, WojSad commented on lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
> +            desired_cfg.set_parameter(name, value=val)
done

2022-02-11 15:11 UTC, xbend commented
@ardzoht 
Requested changes have been addressed.

2022-02-14 17:24 UTC, ardzoht approved these changes
lgtm

2022-02-14 17:24 UTC, merged