docs: Design proposal for Converged GTP tunnel setup
magma/magma pull request #11462
Opened 2022-02-08 14:57 UTC by prabinakpattnaik

Signed-off-by: prabinak<prabinak@wavelabs.ai>

## Summary

Design proposal for add support for to make GTP tunnel operations by Sessiond for 4G Call as similar to 5G Call Flows.

## Additional Information

2022-02-08 15:02 UTC, electronjoe requested changes

2022-02-08 15:02 UTC, electronjoe commented on docs/readmes/proposals/p025_Converged_GTP_Tunnel_Setup.md
> +### Regration Testing
I believe you meant `Regression Testing`?

2022-02-08 15:03 UTC, electronjoe commented
Please link to your GH Issue for this proposal in your PR description.

That and one nit typo - otherwise LGTM for review of the design over on the GH Issue.

2022-02-08 15:04 UTC, prabinakpattnaik commented on docs/readmes/proposals/p025_Converged_GTP_Tunnel_Setup.md
> +### Regration Testing
Yes, Sorry for typo

2022-02-08 15:04 UTC, prabinakpattnaik commented on docs/readmes/proposals/p025_Converged_GTP_Tunnel_Setup.md
> +### Regration Testing
I will fix it now

2022-02-08 17:09 UTC, uri200 reviewed
i remember that the idea of calling directly ovs from mme was to reduce the amount of messages and avoid converting sessiónd as just a pass through.

Can you describe the new call flow? Is this change saving any messages or i reodicing even more?  Does this change implies session on sessiond modified it's state?

2022-02-08 17:15 UTC, uri200 commented
Please can you add a diagram with the resulting callflows to see how it will look like? 

You can use mermaid for that so it is easy to edit

https://mermaid-js.github.io/mermaid/#/./sequenceDiagram

2022-02-11 21:39 UTC, prabinakpattnaik commented
@uri200, I have attached four call flows diagram for gets more details about gRPC messages. For GTP tunnel creation and Deletion, we can use existing gRPC messages. For GTP Data Notification and Idle Mode session, need to add new gRPC methods.
![GTP_tunnel_Creation](https://user-images.githubusercontent.com/69528542/153673895-01d1b242-4dff-476a-9dfe-baa2554eb6fe.png)
![GTP_tunnel_Deletion](https://user-images.githubusercontent.com/69528542/153673903-f52ed19a-b881-4488-80e9-00320e1c2c37.png)
![Idle_Session_Paging_Notification](https://user-images.githubusercontent.com/69528542/153673907-8ce43f2f-de95-4f78-847c-bf8380df586a.png)
![Notification_GTP_flows](https://user-images.githubusercontent.com/69528542/153673909-a2601873-a9a5-402a-8d73-7da8135d729d.png)

2022-02-11 22:19 UTC, uri200 commented
Thanks @prabinakpattnaik . That really helps. Can you add the call flows to the proposal (i think they are just on the comments)

The changes make sense. I think the idea of MME - OVS communication was to reduce the amount of messages and to avoid sessiond-pipelined become just a transit for a message.  

For Create/Terminate events that make sense. They are low frequency events and we don't gain much contacting OVS from MME directly. We still have to contact sessiond and pipelined to create and terminate session.  

But for high frequency events like like `GTP Data Notification`  we go from 1 message to 3 and we have to now go to 3 different systems just to send a message to a service that is sitting next to MME.

Would it make sense to leave `GTP Data Notification` as it is since it looks like it doesn't need any specific information about the session?

2022-03-02 19:09 UTC, ekowtaylor commented
@prabinakpattnaik are you still working on this? How can I help?

2022-03-03 16:28 UTC, ekowtaylor commented
@prabinakpattnaik do you still plan to move forward with this change? If yes then please reopen and rebase.

2022-03-07 19:59 UTC, prabinakpattnaik commented
Sorry for late response. This is on going task. I will update soon.

2022-05-11 17:43 UTC, Neudrino reviewed
The graphics look very strange. One should probably use [mermaid diagrams](https://github.com/magma/magma/wiki/Contributing-Documentation#diagrams-within-the-documentation) for this purpose.

2022-11-22 11:54 UTC, closed without merging