test(mme): refactoring function is_num_sessions_valid() inside spgw_test_util
magma/magma pull request #11482
Opened 2022-02-09 10:47 UTC by thhung

Signed-off-by: Hung NGUYEN <nguyen.thanh.hung.91@gmail.com>

## Summary

- Refactoring the function is_num_sessions_valid inside the unittest of spgw into 2 functions:

1. is_num_ue_contexts_valid(): validating the number of ue contexts for a given ue
2. is_num_teids_valid(): validating the number of teid of a given ue

## Test Plan

- make test_oai

## Additional Information

- [ ] This change is backwards-breaking

2022-02-11 21:44 UTC, ssanadhya commented on lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
> +bool is_num_ue_contexts_valid(uint64_t imsi64, int expected_num_ue_contexts) {
No need for Imsi here

```suggestion
bool is_num_ue_contexts_valid(int expected_num_ue_contexts) {
```

2022-02-11 21:47 UTC, ssanadhya reviewed
@thhung , thanks for adding these functions! Please replace usage of `is_num_sessions_valid` with these new ones in other tests too.

2022-02-14 07:11 UTC, rsarwad commented on lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_with_injected_state.cpp
> +  ASSERT_TRUE(is_num_teids_valid(test_imsi64, 1));
Can we rename as is_num_cp_teids_valid to indicate that we are validating control plane teids

2022-02-14 11:26 UTC, thhung commented on lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
> +bool is_num_ue_contexts_valid(uint64_t imsi64, int expected_num_ue_contexts) {
Removed

2022-02-14 16:36 UTC, thhung commented on lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_with_injected_state.cpp
> +  ASSERT_TRUE(is_num_teids_valid(test_imsi64, 1));
Thanks for your review. I will rename this function to clarify it.

2022-02-17 19:04 UTC, ssanadhya requested changes

2022-02-17 19:04 UTC, ssanadhya commented on lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.h
>  bool is_num_sessions_valid(uint64_t imsi64, int expected_num_ue_contexts,
Please remove this function as it is replaced by the new functions in this PR

2022-02-18 16:50 UTC, ssanadhya approved these changes
LGTM

2022-02-18 17:21 UTC, merged