chore(ctraced): ctraced is bazelified
magma/magma pull request #11520
Opened 2022-02-10 20:59 UTC by christinewang5

ran `bazel run //orc8r/gateway/python/magma/ctraced:ctraced`

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/25142344/153495232-dcbe122a-c199-4220-95a2-bbf1c1981536.png">

https://github.com/magma/magma/issues/11413

2022-02-10 21:01 UTC, christinewang5 commented
Hey @nstng! Have you seen this log before when running bazel run for other services?
```
INFO:root:The 'orc8r' distribution was not found and is required by the application
```

2022-02-10 21:22 UTC, themarwhal commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    ],
@nstng What is the best way to determine whether only ORC8R_ROOT is needed or both?

2022-02-10 21:23 UTC, themarwhal commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    deps = DEPS,
let's just embed DEPS and SRCS... (We're planning on cleaning up the rest of services soon)

2022-02-11 07:12 UTC, nstng commented
> Hey @nstng! Have you seen this log before when running bazel run for other services?
> 
> ```
> INFO:root:The 'orc8r' distribution was not found and is required by the application
> ```

Hi @christinewang5, yes, your service needs access to an orc8r setup. You can can run your service in the magma-vm and additionally setup the orc8r. See https://docs.magmacore.org/docs/basics/quick_start_guide. In some cases this was causing more service interaction and made additional missing dependencies visible. In your case it looks to me like your service has already started (listening on address 127...). But testing this is in general a good idea.

2022-02-11 07:30 UTC, nstng commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    ],
@christinewang5 @themarwhal

In general: if a source file in @MAGMA_ROOT/orc8r/gateway/python is needed, then an orc8r root is needed. Same for lte sources.
More specific: ctraced is an orc8r service so an ORC8R_ROOT will be needed. LTE_ROOT only if there are lte dependencies - and if the they transitive then it is not easy to see.
From logging: in this case if ORC8R_ROOT is missing, you get
`    from magma.common.sentry import sentry_init
ModuleNotFoundError: No module named 'magma'`
This is, bazel can not even find the magma module. As the common sub-module resides in the orc8r, this indicates the missing import. On the other hand, if you add the orc8r root but remove the sentry dependency, you get:
`    from magma.common.sentry import sentry_init
ModuleNotFoundError: No module named 'magma.common.sentry'`
This is, bazel knows about the magma module and is missing a source file.

2022-02-11 07:31 UTC, nstng commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    ],
@christinewang5 in this case LTE_ROOT is not needed. (for testing this manually, see previous reply)

2022-02-11 08:01 UTC, nstng requested changes

2022-02-11 08:01 UTC, nstng commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +load("@python_deps//:requirements.bzl", "requirement")
`requirement` is not used - the load line can be removed. If you do not see this marked in your ide then an extension might be missing (yellow underscore). I assume "bazel-stack-vscode" provides this feature.

2022-02-11 08:01 UTC, nstng commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    "//orc8r/protos:ctraced_python_proto",
The proto libraries are a subset of the grpc libraries, i.e., the proto libraries are not needed here - this line can be removed and also the ctraced_python_proto target from the lte/proto package.

2022-02-11 08:01 UTC, nstng commented on orc8r/protos/BUILD.bazel
> +python_proto_library(
See comment above, this target is not needed.

2022-02-11 08:01 UTC, nstng commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    "//orc8r/protos:ctraced_python_proto",
(This is always a little misleading, because the first missing dependency is the proto library and if afterwards the grpc library is needed then the proto library becomes obsolete.)

2022-02-11 08:01 UTC, nstng commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    "//orc8r/protos:mconfig_python_proto",
The two dependencies seem to be unnecessary.
`mconfigs_python_proto` is a dependency in `main.py` but seems to be added transitively - we are still unsure how to handle these, because it is not easy to see if a direct dependency is already covered transitively. In most cases we have not added these.
I do not see a usage of `mconfig_python_proto`. Should be removed.

2022-02-11 08:01 UTC, nstng commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    deps = DEPS,
And afterwards `bazel run //:buildifier` should be able to sort the entries.

2022-02-11 08:01 UTC, nstng commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +py_binary(
Sorry for not updating the issue - we started to follow a new design pattern. The binary only has the main.py as a source and all other source files as a dependent py_library. See `orc8r/gateway/python/magma/magmad` for an example.

2022-02-14 15:25 UTC, christinewang5 commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    ],
Hmm when I run `bazel run //orc8r/gateway/python/magma/ctraced:ctraced` it still asks for LTE_ROOT


<img width="2689" alt="image" src="https://user-images.githubusercontent.com/25142344/153892923-2d27cd22-853d-450b-be49-709b53251a01.png">

2022-02-14 15:35 UTC, nstng commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    ],
Hi, could it be that you just removed the initialization of LTE_ROOT, but not the usage in the deps list?

2022-02-14 15:56 UTC, christinewang5 commented on orc8r/gateway/python/magma/ctraced/BUILD.bazel
> +    ],
Ah yes, thanks for that catch

2022-02-15 07:34 UTC, nstng approved these changes
Looks good

2022-02-15 13:52 UTC, themarwhal approved these changes

2022-02-15 20:29 UTC, merged