make GCC warnings disappear
magma/magma pull request #11670
Opened 2022-02-18 00:14 UTC by tenpercent

https://github.com/magma/magma/issues/10166

## Summary

Looks like pointers of functions with different function signatures have been assigned.

```
[lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c#L36](https://github.com/magma/magma/commit/005c5f378725a43d3040b380796cd8fade8c7bad#annotation_2776830515)
initialization of 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  struct in6_addr *, uint32_t,  uint32_t,  Imsi_t,  struct ip_flow_dl *, uint32_t,  char *)' {aka 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  struct in6_addr *, unsigned int,  unsigned int,  struct <anonymous>,  struct ip_flow_dl *, unsigned int,  char *)'} from incompatible pointer type 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  uint32_t,  uint32_t,  Imsi_t,  struct ip_flow_dl *, uint32_t,  char *)' {aka 'int (*)(struct in_addr,  struct in6_addr *, int,  struct in_addr,  unsigned int,  unsigned int,  struct <anonymous>,  struct ip_flow_dl *, unsigned int,  char *)'} [-Wincompatible-pointer-types]

[lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c#L37](https://github.com/magma/magma/commit/005c5f378725a43d3040b380796cd8fade8c7bad#annotation_2776830518)
initialization of 'int (*)(struct in_addr,  struct in6_addr *, struct in_addr,  struct in6_addr *, uint32_t,  uint32_t,  struct ip_flow_dl *)' {aka 'int (*)(struct in_addr,  struct in6_addr *, struct in_addr,  struct in6_addr *, unsigned int,  unsigned int,  struct ip_flow_dl *)'} from incompatible pointer type 'int (*)(struct in_addr,  struct in_addr,  struct in6_addr *, uint32_t,  uint32_t,  struct ip_flow_dl *)' {aka 'int (*)(struct in_addr,  struct in_addr,  struct in6_addr *, unsigned int,  unsigned int,  struct ip_flow_dl *)'} [-Wincompatible-pointer-types]

[lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c#L40](https://github.com/magma/magma/commit/005c5f378725a43d3040b380796cd8fade8c7bad#annotation_2776830521)
initialization of 'int (*)(Imsi_t,  struct in_addr,  struct in6_addr *)' {aka 'int (*)(struct <anonymous>,  struct in_addr,  struct in6_addr *)'} from incompatible pointer type 'int (*)(struct in_addr)' [-Wincompatible-pointer-types]

[lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c#L41](https://github.com/magma/magma/commit/005c5f378725a43d3040b380796cd8fade8c7bad#annotation_2776830523)
initialization of 'int (*)(struct in_addr, struct in6_addr *)' from incompatible pointer type 'int (*)(struct in_addr)' [-Wincompatible-pointer-types]
```

Added unused parameters so that signatures match.

## Test Plan

```
cd /workspaces/magma/lte/gateway
make build_oai
```
Compilation successful

2022-02-18 21:55 UTC, ardzoht requested changes
minor nits on formatting

2022-02-18 21:55 UTC, ardzoht commented on lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.h
> +int upf_add_paging_rule(Imsi_t unused0, struct in_addr ue,
```suggestion
int upf_add_paging_rule(Imsi_t unused_0, struct in_addr ue,
```

2022-02-18 21:55 UTC, ardzoht commented on lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.h
> +                        struct in6_addr* unused1);
```suggestion
                        struct in6_addr* unused_1);
```

2022-02-18 21:57 UTC, ardzoht requested changes

2022-02-18 21:57 UTC, ardzoht commented on lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c
> +                   struct in_addr enb, struct in6_addr* unused, uint32_t i_tei,
can we also update all added unused params with pattern: `unused_<type_of_param>`

2022-02-19 00:20 UTC, tenpercent commented on lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c
> +                   struct in_addr enb, struct in6_addr* unused, uint32_t i_tei,
Please see revision [e0b4607]

2022-02-19 00:27 UTC, ardzoht approved these changes
lgtm

2022-02-22 22:43 UTC, merged