chore(agw): upload journal log to sentry
magma/magma pull request #11746
Opened 2022-02-22 17:22 UTC by ajahl

Signed-off-by: Alex Jahl <alexander.jahl@tngtech.com>

## Summary

Upload journal log information to Sentry when a c service crashes.

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2022-02-23 09:07 UTC, alexzurbonsen commented on orc8r/gateway/c/common/sentry/SentryWrapper.cpp
> +#define SYS_LOG_PATH "/var/log/magma_services.log"
While reading this again: should we rename `SYS_LOG_PATH` to something that reveals that we are writing to this path and not reading from it? The current name might suggest that it is the path to the syslog file, analogous to  `MME_LOG_PATH`.

2022-02-23 09:59 UTC, ajahl commented on orc8r/gateway/c/common/sentry/SentryWrapper.cpp
> +#define SYS_LOG_PATH "/var/log/magma_services.log"
We write the file first and afterwards read it via Sentry SDK. I renamed in `JOURNAL_LOG_PATH`.

2022-02-23 11:16 UTC, alexzurbonsen approved these changes

2022-02-23 17:16 UTC, Neudrino commented
Thanks @themarwhal and @ardzoht for the insights shared today!

There were two items which I suggest to address separately in respective follow up PRs:
- providing SCTPd logs, and
- making the number of lines configurable via streamed mconfig.

2022-02-24 13:20 UTC, sebathomas commented on orc8r/gateway/c/common/sentry/SentryWrapper.cpp
> +  std::string command = "journalctl -u magma@* -n 1000 > ";
To get sctpd as well:
```suggestion
  std::string command = "journalctl -u sctpd -u magma@* -n 1000 > ";
```

2022-02-25 13:33 UTC, Neudrino approved these changes

2022-02-28 20:51 UTC, hcgatewood approved these changes
Cloud changes lgtm

2022-02-28 20:51 UTC, hcgatewood commented on orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
> +        minimum: 0
This might be unnecessary given the object's type (?)

2022-02-28 21:07 UTC, themarwhal approved these changes
Woohoo!

2022-03-01 09:39 UTC, alexzurbonsen requested changes
We should also modify the go code that translates from swagger to proto, such that it reflects the changes.

2022-03-01 09:43 UTC, sebathomas commented
Right. I think that's:
* lte/cloud/go/services/lte/servicers/builder_servicer.go
* orc8r/cloud/go/services/orchestrator/servicers/builder_servicer.go

2022-03-01 15:28 UTC, ajahl commented
> We should also modify the go code that translates from swagger to proto, such that it reflects the changes.


> Right. I think that's:
> 
> * lte/cloud/go/services/lte/servicers/builder_servicer.go
> * orc8r/cloud/go/services/orchestrator/servicers/builder_servicer.go

It's done. I modified the go files.

2022-03-02 08:47 UTC, sebathomas approved these changes
Tried it on my machine and confirmed that the number of lines is forwarded to the mconfig file in the AGW.

2022-03-02 08:51 UTC, alexzurbonsen approved these changes

2022-03-02 09:29 UTC, sebathomas commented
Just noticed the `yarn test` error in the CI. Rerunning to see if it's flaky.

2022-03-02 09:33 UTC, sebathomas requested changes
Nope, I think it's consistently red. We should fix that before merging.

2022-03-02 09:52 UTC, sebathomas approved these changes
This was not broken by the PR, it's also red on master. Opened another ticket to track that:
#11895

2022-03-02 13:49 UTC, merged