fix(mme): Null terminates string to stop buffer overflow
magma/magma pull request #11925
Opened 2022-03-03 14:06 UTC by electronjoe

Addresses one finding (more exist) of #11826.

Zero-initialized all instances of `plmn_array[PLMN_BYTES]` (so that they will be null terminated) and enlarged the array by one char to accommodate the null termination.

Fixes the finding:

```
[ RUN      ] TestAMFStateConverter.TestUEm5gmmContextToProto
=================================================================
==15482==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee811fc86 at pc 0x7f3038dada6d bp 0x7ffee811faa0 sp 0x7ffee811f248
READ of size 7 at 0x7ffee811fc86 thread T0
    #0 0x7f3038dada6c  (/lib/x86_64-linux-gnu/libasan.so.5+0x67a6c)
    #1 0x7f302e641e9b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x145e9b)
    #2 0x7f30383b85f6 in magma::lte::oai::Tai::set_mcc_mnc(char const*) bazel-out/k8-dbg/bin/lte/protos/oai/nas_state_cpp_proto_pb/lte/protos/oai/nas_state.pb.h:11239
```

## Test Plan

Using prototype Bazel build with `--config=asan` validated ASAN finding
is resolved.

Signed-off-by: Scott Moeller <electrojoe@gmail.com>

2022-03-03 14:12 UTC, lionelgo approved these changes

2022-03-03 23:59 UTC, ssanadhya approved these changes
lgtm

2022-03-04 05:13 UTC, ssanadhya commented
@electronjoe , since you modified the PLMN_BYTES macro, can you update the changes made in https://github.com/magma/magma/pull/11891/files too?

2022-03-04 05:13 UTC, ssanadhya requested changes
Please update the usage of PLMN_BYTES in `state_converter.cpp` too

2022-03-04 12:19 UTC, electronjoe commented
> Please update the usage of PLMN_BYTES in `state_converter.cpp` too

Thanks for the corrective advice Shruti! I've migrated all instances to zero-init (so that we get the null termination). Please take a look at the updated PR!

2022-03-04 13:37 UTC, LKreutzer approved these changes
Tested locally

2022-03-04 16:55 UTC, ssanadhya approved these changes
LGTM

2022-03-05 11:49 UTC, merged