ci(orc8r): Added Terraform Lint CI Check
magma/magma pull request #12081
Opened 2022-03-11 05:40 UTC by ShubhamTatvamasi

Signed-off-by: Shubham Tatvamasi <shubhamtatvamasi@gmail.com>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2022-03-15 23:03 UTC, themarwhal approved these changes
lgtm!

2022-03-15 23:04 UTC, themarwhal commented on .github/workflows/terraform-lint.yml
> +
should we add some concurrency configs? @quentinDERORY

2022-03-20 05:25 UTC, ShubhamTatvamasi commented
For common tasks such as lint check, should we start using actions from marketplace?
https://github.com/marketplace/actions/terraform-lint-action

2022-03-23 04:46 UTC, ShubhamTatvamasi commented
I have updated code, now using action from marketplace.

2022-03-23 11:16 UTC, themarwhal approved these changes

2022-03-25 11:48 UTC, Neudrino reviewed
> For common tasks such as lint check, should we start using actions from marketplace? https://github.com/marketplace/actions/terraform-lint-action

I agree that using Actions from Marketplace might be a good idea.
However, on top of that we might want to stick to the standard [ReviewDog](https://github.com/reviewdog/reviewdog/blob/master/README.md) provided linters where possible, as they provide excellent integration with Github out of the box, and avoid custom code here.

In particular for this case this would mean to us [tflint](https://github.com/marketplace/actions/run-tflint-with-reviewdog).
This would also have the advantage that it could also easily be integrated with [our existing set (and setup) of reviewdog](https://github.com/magma/magma/blob/master/.github/workflows/reviewdog-workflow.yml).

2022-03-25 11:50 UTC, Neudrino requested changes

2022-03-25 11:50 UTC, Neudrino commented on .github/workflows/terraform-lint.yml
> +on:
yamllint...
```suggestion
on:  # yamllint disable-line rule:truthy
```

2022-03-25 14:02 UTC, Neudrino approved these changes
More linters are always good and this PR LGTM in general.

We might consider to us [tflint](https://github.com/marketplace/actions/run-tflint-with-reviewdog) and integrate it with our [our existing set (and setup) of reviewdog](https://github.com/magma/magma/blob/master/.github/workflows/reviewdog-workflow.yml) linters to benefit from the excellent Github integration of reviewdog :dog:.

2022-04-22 14:03 UTC, Neudrino commented on .github/workflows/terraform-lint.yml
> +
```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number}}
  cancel-in-progress: true
```
Maybe something like this in alignment with the other linters.

2022-04-22 14:03 UTC, merged