fix(agw): Added check at delete session response to send TAU accept if eps_bearer_status flag is set to inactive for default bearer
magma/magma pull request #12275
Opened 2022-03-24 18:02 UTC by rsarwad

…

fix(agw): Added check at delete session response to send TAU accept if eps_bearer_status flag is set to inactive for default bearer
## Summary
Issue1: Flag, ue_context->tau_accept_eps_ber_cntx_status was reset when MME sends TAU accept; On failing to send TAU accept message; this flag was not reset
Resolution: Modified code to reset this flag while we delete the TAU procedure, this was taken care in PR; https://github.com/magma/magma/pull/11795. 
Issue2: With importing this PR on branch v1.7 still there was an issue with mme restart. Consider this flag is set and same is read from Redis DB and while handling attach request; it deletes the previous contexts. While handling Delete session response; we check for flag ue_context->tau_accept_eps_ber_cntx_status and proceed to delete the pdn contexts and decrement the nb_delete_sessions;
Resolution2: Added check at Delete session response to check ue_context->tau_accept_eps_ber_cntx_status and also check nb_delete_sessions

## Test Plan
Executed s1ap sanity test suite and unit test cases.
Verified the changes on both Terra VM setups, AGW: 192.168.60.19 and AGW: 10.22.162.130.

2022-03-24 19:37 UTC, ssanadhya requested changes

2022-03-24 19:37 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
> +  if (ue_context_p->nb_delete_bearer_cmd) {
Use explicit check for non-zero value. Further, shouldn't this check  happen before we reach this point in code?

```suggestion
  if (ue_context_p->nb_delete_bearer_cmd > 0) {
```

2022-03-24 19:37 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
> +      ue_context_p->nb_delete_sessions) {
Explicit check for no-zero value. Shouldn't the check happen earlier in this function call?
```suggestion
      ue_context_p->nb_delete_sessions > 0) {
```

2022-03-28 10:03 UTC, maxhbr commented on lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
> +  if ((ue_context_p->tau_accept_eps_ber_cntx_status) &&
```suggestion
  if (ue_context_p->tau_accept_eps_ber_cntx_status &&
```

2022-03-28 18:47 UTC, ssanadhya approved these changes
lgtm

2022-03-29 15:58 UTC, merged