[LoadTest][PolicyDB]: Adding load test script for policydb
magma/magma pull request #12298
Opened 2022-03-28 05:47 UTC by vikramgreddy

Signed-off-by: Vikram G <vikram.gurrappagaru@radisys.com>

## Summary
Load test script for policydb

## Test Plan
make load_test

## Additional Information

2022-03-29 20:44 UTC, ardzoht requested changes

2022-03-29 20:44 UTC, ardzoht commented on lte/gateway/python/load_tests/loadtest_policydb.py
> +            rule_ids=["p1", "p2", "p3"],
since this is the same list content can we create it outside the for loop and pass that instead?

2022-03-29 20:44 UTC, ardzoht commented on lte/gateway/python/load_tests/loadtest_policydb.py
> +            rule_ids=["p1", "p2", "p3"],
same here

2022-03-29 20:44 UTC, ardzoht commented on lte/gateway/python/load_tests/loadtest_policydb.py
> +def _build_enable_static_rules_data(imsi_list, input_file: str):
```suggestion
def _build_enable_static_rules_data(imsi_list: List[str], input_file: str):
```

2022-03-29 20:44 UTC, ardzoht commented on lte/gateway/python/load_tests/loadtest_policydb.py
> +def _build_disable_static_rules_data(imsi_list, input_file: str):
```suggestion
def _build_disable_static_rules_data(imsi_list: List[str], input_file: str):
```

2022-03-29 20:44 UTC, ardzoht commented on lte/gateway/python/load_tests/loadtest_policydb.py
> +            type=int, default=600,
let's stick to the other load tests default which is 2000 requests

2022-03-31 17:32 UTC, vikramgreddy commented on lte/gateway/python/load_tests/loadtest_policydb.py
> +            rule_ids=["p1", "p2", "p3"],
Ressolved

2022-03-31 18:31 UTC, ardzoht approved these changes
lgtm

2022-04-01 16:12 UTC, ssanadhya commented
@vikramgreddy, please look at the following guidelines to fix the failing "Semantic PR" CI check

> Oops! Looks like you failed the `Semantic PR check`.
> 
> ### Howto
> * [Instructions on formatting your PR title](https://magma.github.io/magma/docs/next/contributing/contribute_workflow#guidelines)
> * For PRs with only one commit, the commit message must also be semantic. See [Changing a commit message](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message) for a howto
> * [Guide to the different CI checks and resolution guidelines](https://docs.magmacore.org/docs/next/contributing/contribute_ci_checks)
> 
> ♻️ Updated: ❌ The check is still failing the Semantic PR after the last commit.

2022-04-01 17:16 UTC, merged