fix(nms): Fix insecure randomness
magma/magma pull request #12417
Opened 2022-04-07 08:27 UTC by spikey979

Signed-off-by: Kristijan <spikey979@gmail.com>

fix(nms): Fix insecure randomness

## Summary

Using a cryptographically weak pseudo-random number generator to generate a security-sensitive value, such as a password, makes it easier for an attacker to predict the value. A cryptographically secure pseudo-random number generator should be used instead.

## Additional Information

This is for code scanning alerts:
https://github.com/magma/magma/security/code-scanning/62
https://github.com/magma/magma/security/code-scanning/63
https://github.com/magma/magma/security/code-scanning/64
https://github.com/magma/magma/security/code-scanning/65

2022-04-08 11:46 UTC, thmsschmitt commented
![Screenshot 2022-04-08 at 13 45 47](https://user-images.githubusercontent.com/102796295/162429484-b3378357-c4e2-4816-91a5-84ce31904b60.png)
The server runs in node. You need to use https://nodejs.org/api/crypto.html instead.

2022-04-08 14:00 UTC, spikey979 commented
> ![Screenshot 2022-04-08 at 13 45 47](https://user-images.githubusercontent.com/102796295/162429484-b3378357-c4e2-4816-91a5-84ce31904b60.png) The server runs in node. You need to use https://nodejs.org/api/crypto.html instead.

If I use crypto.getRandomValues() without "winodw", in CI tests I get error: Cannot resolve name `crypto`. [cannot-resolve-name]

2022-04-08 14:09 UTC, thmsschmitt commented
You need to import it: 

```
import crypto from 'crypto';
```

also note that it has a different API then `window.crypto`. See https://nodejs.org/api/crypto.html

2022-04-27 15:06 UTC, thmsschmitt requested changes
Sorry that this takes so long.

`crypto.getRandomValues` is only available since node v17.4.0 and we are using v16.14. Also only using 4 bytes isn't great.

I suggest we use something like
`crypto.randomBytes(16).toString('hex')`

2022-04-28 06:40 UTC, thmsschmitt approved these changes

2022-04-28 06:42 UTC, spikey979 commented
@thmsschmitt thanks for helping

2022-04-28 06:47 UTC, andreilee approved these changes

2022-05-03 07:52 UTC, thmsschmitt commented
@spikey979 I'm waiting for the `ready2merge` label. It would also be good to rebase this once more.

2022-05-03 09:28 UTC, merged