style: Removed boiler-plate code from AmfUeContext, AmfPduUeContext, …
magma/magma pull request #12482
Opened 2022-04-16 15:27 UTC by just-now

Removed boiler-plate code from AmfUeContext, AmfPduUeContext, MmeUeContext timers

Signed-off-by: Anatoliy Bilenko <Anatoliy.Bilenko@gmail.com>

2022-04-22 08:36 UTC, ganeshg87 approved these changes
lgtm.

2022-04-26 09:33 UTC, ajahl approved these changes
LGTM. Can you fix the lint error?

2022-04-27 18:14 UTC, ssanadhya requested changes
@just-now , could you please add a description to this PR, i.e. summary of changes and test plan? 

For MME service, it is important to run LTE integration tests on each PR since they are not run in pre-commit CI.

cc: @ganeshg87

2022-05-03 17:49 UTC, ardzoht commented
@just-now Please provide a test plan section on the PR's description that validate your changes. Also please provide a summary of why the removed code is not needed anymore.

2022-05-03 17:51 UTC, just-now commented
Sorry for the silence.

> LGTM. Can you fix the lint error?

Sure will do.

> @just-now , could you please add a description to this PR, i.e. summary of changes and test plan?
> For MME service, it is important to run LTE integration tests on each PR since they are not run in pre-commit CI. 

Could you give an example of such a test-plan? Right now I don't feel that special tests are needed to test the patch as it introduces an "equivalent transformation" of existing code. I could be wrong, please guide me :)

2022-05-04 04:15 UTC, ssanadhya commented
> Sorry for the silence.
> 
> > LGTM. Can you fix the lint error?
> 
> Sure will do.
> 
> > @just-now , could you please add a description to this PR, i.e. summary of changes and test plan?
> > For MME service, it is important to run LTE integration tests on each PR since they are not run in pre-commit CI.
> 
> Could you give an example of such a test-plan? Right now I don't feel that special tests are needed to test the patch as it introduces an "equivalent transformation" of existing code. I could be wrong, please guide me :)

@just-now, there are two set of tests for MME service:

1. Unit tests: You can run these through `make test_oai` on the dev VM. These run in the pre-commit CI `mme test` workflow.
2. Integration tests: Please follow the [S1AP Integrations Tests readme](https://magma.github.io/magma/docs/next/lte/s1ap_tests) to run the end to end tests. These run only on the master branch, hence it is essential for PR authors to run them locally before PR is marked as ready to review.

2022-08-16 08:55 UTC, closed without merging