chore(agw): Clean up unused imports
magma/magma pull request #12630
Opened 2022-05-04 08:55 UTC by voisey

## Summary

Removes a selection of unused imports found via `cd $MAGMA_ROOT/lte/gateway/python && make check` in the magma-dev VM.

Currently includes the changes from https://github.com/magma/magma/pull/12623 so I'll rebase this PR after that one has been merged.

## Test Plan

- [ ] magma-dev: `cd $MAGMA_ROOT/lte/gateway && make test_python_service UT_PATH=python/magma/pipelined/tests/`

2022-05-05 15:47 UTC, themarwhal approved these changes
Lgtm! Were there no fixups under the orchestrator directory?

2022-05-05 19:44 UTC, uri200 requested changes
Please since this touches subcriberd_db_client, rebase to latest and run [s1ap federated integ test ](https://docs.magmacore.org/docs/next/feg/s1ap_federated_tests#s1ap-federated-integration-tests).

```
cd magma/lte/gateway
fab federated_integ_test:build_all=True

```

2022-05-06 07:57 UTC, LKreutzer approved these changes
Bazel changes lgtm - thanks for the cleanup Cameron!

2022-05-06 22:22 UTC, ardzoht approved these changes
integtests changes lgtm

2022-05-11 14:51 UTC, voisey commented
Thanks for the reviews! I've pushed a second commit removing a few more imports and reran the tests mentioned in the summary. Are there any more I should run?

@themarwhal Good point! I found one case in the orc8r, which I removed in the recent commit.

@uri200 I rebased and ran the federated integ test, which works :slightly_smiling_face:

2022-05-11 15:41 UTC, themarwhal approved these changes

2022-05-11 18:01 UTC, uri200 approved these changes

2022-05-11 18:57 UTC, koolzz approved these changes

2022-05-12 06:34 UTC, merged