chore: Bazelify the configuration module
magma/magma pull request #12693
Opened 2022-05-11 15:03 UTC by vktng

Signed-off-by: Krisztián Varga <krisztian.varga@tngtech.com>

## Summary

Bazelify the remaining files in configuration module.

FYI: The following files are only used in scripts:
-   orc8r/gateway/python/magma/common/health/health_service.py
-   orc8r/gateway/python/magma/common/health/docker_health_service.py
-   orc8r/gateway/python/magma/common/health/entities.py

## Test Plan

`bazel test orc8r/gateway/python/magma/configuration/...`

## Additional Information

- [ ] This change is backwards-breaking

2022-05-11 15:04 UTC, LKreutzer approved these changes
In pairing

2022-05-12 07:59 UTC, nstng requested changes

2022-05-12 07:59 UTC, nstng commented on orc8r/gateway/python/magma/configuration/tests/BUILD.bazel
> +    name = "mconfigs_tests",
discussed in pairing - this test only needs mconfigs.py. This file should be modeled in a separate library.

2022-05-12 09:41 UTC, nstng approved these changes
lgtm - went through changes in pairing

2022-05-12 09:41 UTC, merged