MikroTik intercell
magma/magma pull request #1272
Opened 2020-03-02 15:50 UTC by gjalves

Support for Mikrotik Intercell

2020-03-27 00:18 UTC, xjtian requested changes
Thanks for this @gjalves! Looks good to me, just need to pull in a few changes that we've made to the state machine recently.

2020-03-27 00:18 UTC, xjtian commented on lte/gateway/python/magma/enodebd/devices/experimental/cavium.py
> +    def get_msg(self) -> AcsMsgAndTransition:
Can you revert the signature change to this function please - we did a minor refactor of the state machine interface recently

2020-03-27 00:18 UTC, xjtian commented on lte/gateway/python/magma/enodebd/devices/experimental/cavium.py
> +    def get_msg(self) -> AcsMsgAndTransition:
revert this line too please

2020-03-27 00:18 UTC, xjtian commented on lte/gateway/python/magma/enodebd/devices/experimental/cavium.py
> +            'unexpected_fault': ErrorState(self)
revert this line please - we added some remediation logic to this ErrorState state

2020-07-25 00:10 UTC, 119Vik commented
Can one of the admins verify this patch?

2021-03-19 21:48 UTC, electronjoe commented
Hello @gjalves! Apologies for the latency on these reviews. I'm trying to help shepherd our oldest PRs to a resolution.

Could you address the several Codacity linting warnings on this PR - regarding e.g. unused imports?

IMO even if Magma is unable to test a PR with hardware, we should be able to assess low risk on accepting contributions like this one. I am happy to help move this forward if you are able.

2021-05-04 15:20 UTC, closed without merging