feat(nms): use proper check in status from orcestrator for lteGateways
magma/magma pull request #12735
Opened 2022-05-16 11:18 UTC by Neudrino

## Summary

Within https://github.com/magma/magma/pull/12699 a orc8r calculated status was implemented.
This PR provides the implementation to actually display this status and not calculate it (wrongly) in the frontend.

## Test Plan

- `yarn flow`
- `yarn run eslint . --quiet --fix`
- `yarn test --maxWorkers=2`

## Additional Information

- Requires https://github.com/magma/magma/pull/12699.

2022-05-16 15:22 UTC, thmsschmitt commented on nms/app/views/network/FEGServicingAccessGatewayTable.js
> +        gatewayHealth: (servicedAccessGateways[servicedAccessGatewayId] || {})
``` servicedAccessGateways[servicedAccessGatewayId]?.checked_in_recently ```

2022-05-16 15:35 UTC, sebathomas requested changes
It looks to me like this also adapts the logic for FEGs while the backend logic was only changed for AGWs. In that case, we either we need to keep the old logic for FEGs or implement the backend changes for them as well.

2022-05-16 15:35 UTC, sebathomas commented on nms/app/views/equipment/GatewayDetailStatus.js
> +  const isHealthy = gwInfo.checked_in_recently;
Could be inlined (or used for all fields).

2022-05-16 16:02 UTC, sebathomas approved these changes
As discussed in person, I was confused by the file names and the logic is only used for LTE gateways, same as in the backend.

2022-05-17 06:48 UTC, thmsschmitt approved these changes

2022-05-17 07:08 UTC, sebathomas commented
I did an E2E test with check-in interval 30 and confirmed that the status switch works correctly in NMS. :+1:

2022-05-27 09:50 UTC, sebathomas commented
This PR can finally be rebased and opened properly. :)

2022-05-30 08:54 UTC, Neudrino commented
Rebased after merge of https://github.com/magma/magma/pull/12699.

2022-05-30 09:07 UTC, thmsschmitt approved these changes

2022-05-30 10:03 UTC, merged