Check c cpp for bazelification
magma/magma pull request #12736
Opened 2022-05-16 13:51 UTC by vktng

## Summary
This PR adds a script that checks all c/c++ files if they are already bazelified or still need some work. The script is added to the CI. 

## Test Plan

CI should suffice
* test failing run: TBD
* successful run: TBD

## Additional Information

- [ ] This change is backwards-breaking

2022-05-16 14:00 UTC, nstng approved these changes
done in pairing

2022-05-16 14:00 UTC, nstng commented on bazel/scripts/check_c_cpp_bazel.sh
> +  # dead code?
will be handled in a follow up PR.

2022-05-16 15:15 UTC, LKreutzer requested changes
For some reason it seems that not all files are recognised. I added some files, e.g.:
```
orc8r/tools/o.cpp
nms/test.cpp
lte/test.c
feg/test.cpp
feg/ac.c
```
and they do not show up in the output?

2022-05-16 15:15 UTC, LKreutzer commented on .github/workflows/bazel.yml
> +    name: Check if there are not bazelified c or c++ files
Could we say "non-bazelified" instead of "not bazelified" here? 

Maybe out of scope but could we change this also for the `python_file_check`?

2022-05-16 15:15 UTC, LKreutzer commented on bazel/scripts/check_c_cpp_bazel.sh
> +# Folders and files that should not be relevant for bazel.
Nit: Could we add a newline here?

2022-05-16 15:15 UTC, LKreutzer commented on bazel/scripts/check_c_cpp_bazel.sh
> +  # dead code?
Could we make this a "TODO" ?

2022-05-16 15:15 UTC, LKreutzer commented on bazel/scripts/check_c_cpp_bazel.sh
> +The following files are not covered by a BUILD.bazel files:
Nit: Either the last "files" should be singular ("file") or no "a".

2022-05-16 15:19 UTC, nstng commented on bazel/scripts/check_c_cpp_bazel.sh
> +  # dead code?
Sure, all entries get a todo with a GH linked issue. In the planned follow up pr. This comment is just a spoiler because we already had a quick look.

2022-05-16 15:49 UTC, vktng commented
> For some reason it seems that not all files are recognised. I added some files, e.g.:
> 
> ```
> orc8r/tools/o.cpp
> nms/test.cpp
> lte/test.c
> feg/test.cpp
> feg/ac.c
> ```
> 
> and they do not show up in the output?

This happens because we use grep and the filenames you provided are substrings of already bazelified files. This should be fixed if possible.

2022-05-16 16:05 UTC, nstng commented
> > For some reason it seems that not all files are recognised. I added some files, e.g.:
> > ```
> > orc8r/tools/o.cpp
> > nms/test.cpp
> > lte/test.c
> > feg/test.cpp
> > feg/ac.c
> > ``` 
> > and they do not show up in the output?
> 
> This happens because we use grep and the filenames you provided are substrings of already bazelified files. This should be fixed if possible.

The script in this change is a heuristic - the tested file names do not seem relevant in practice (or can be neglected if actually used).

2022-05-17 11:53 UTC, vktng commented on .github/workflows/bazel.yml
> +    name: Check if there are not bazelified c or c++ files
fixed

2022-05-17 11:53 UTC, vktng commented on bazel/scripts/check_c_cpp_bazel.sh
> +# Folders and files that should not be relevant for bazel.
fixed

2022-05-17 11:53 UTC, vktng commented on bazel/scripts/check_c_cpp_bazel.sh
> +The following files are not covered by a BUILD.bazel files:
fixed

2022-05-17 13:29 UTC, LKreutzer approved these changes

2022-05-17 15:22 UTC, merged