Freediameter build
magma/magma pull request #12913
Opened 2022-06-05 15:46 UTC by gjalves

fix(agw): Change path of patch file

## Summary

Change path of 0001-opencoord.org.freeDiameter.patch from lte/gateway/c/oai/patches/ to lte/gateway/c/core/oai/patches/

## Test Plan

When manually try to build freediameter using third_party/build/bin/freediameter_build.sh, the script fails with error

`./freediameter_build.sh: line 62: /home/gustavo-alves/devel/magma-gj//lte/gateway/c/oai/patches/0001-opencoord.org.freeDiameter.patch: No such file or directory`

After the patch, compilation works fine

2022-06-05 16:25 UTC, maxhbr commented
good catch, but shouldn't this script also apply `0002-opencoord.org.freeDiameter.patch`?

2022-06-05 18:58 UTC, gjalves commented
Thanks @maxhbr , you are right. I´ve just added and tested with the other patch.

2022-06-05 19:47 UTC, maxhbr approved these changes
LGTM

2022-07-05 12:54 UTC, gjalves commented
I´m facing some permission trouble setting the label as ready2merge. Someone can do the favor? Thanks.

2022-07-05 13:04 UTC, maxhbr requested changes
shellcheck is right, you should add quotes to prevent word-splitting

2022-07-05 13:04 UTC, maxhbr commented on third_party/build/bin/freediameter_build.sh
> +patch -p1 < $MAGMA_ROOT/lte/gateway/c/core/oai/patches/0001-opencoord.org.freeDiameter.patch
```suggestion
patch -p1 < "$MAGMA_ROOT/lte/gateway/c/core/oai/patches/0001-opencoord.org.freeDiameter.patch"
```

2022-07-05 13:04 UTC, maxhbr commented on third_party/build/bin/freediameter_build.sh
> +patch -p1 < $MAGMA_ROOT/lte/gateway/c/core/oai/patches/0002-opencoord.org.freeDiameter.patch
```suggestion
patch -p1 < "$MAGMA_ROOT/lte/gateway/c/core/oai/patches/0002-opencoord.org.freeDiameter.patch"
```

2022-07-05 13:30 UTC, maxhbr approved these changes
LGTM

2022-07-05 13:49 UTC, Neudrino commented
@gjalves: The DCO check is still failing. See the first comment on the PR on how to fix it, please.

2022-07-05 17:15 UTC, gjalves commented
@Neudrino , I hope now everything should be fine.

2022-07-06 06:45 UTC, merged