fix: agw: datapath: handling of end-marker
magma/magma pull request #12943
Opened 2022-06-09 06:48 UTC by pshelar

GTP module can panic kernel on receiving end-marker packet.
Following PR gracefully handles the packet and pass it to control-plane
process.

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>

## Summary

## Test Plan
Used the script from #12528 and pcap from lab test.

## Additional Information

- [ ] This change is backwards-breaking

2022-06-10 12:27 UTC, vktng reviewed
Hi @pshelar,

I was able to reproduce the problem with the tests in #12528 and verify that your change solves this problem.
A couple of question:
 1) Does it make sense to consolidate the patches? gtp.c is patched here and was introduced in patch 0003, should this be merged?
 2) Should a cleaned-up test from #12528 be added?
 3) What is the process to update the patched OVS packages in the artifactory?
 4) Out of scope here, but OVS claims to support GTP. (See link: https://docs.openvswitch.org/en/latest/faq/configuration/) "Q: Does Open vSwitch support GTP-U?" Is this something else?

2022-06-10 13:36 UTC, vktng commented
I have run the sudo tests locally and one of them is failing: `lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py`
Could you please take a look?

2022-06-10 13:37 UTC, vktng requested changes
See comments above.

2022-06-10 18:27 UTC, nstng commented
> > I have run the sudo tests locally and one of them is failing: `lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py` Could you please take a look?
> 
> The patch does not change any user interface, so its highly unlikely its related to this change. Can you reproduce it? what is error log?

Hi @pshelar, it seems to be reproducible - the test fails after `openvswitch-datapath-dkms_2.15.4-9_all.deb` is installed.

```
lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py::ClassifierMmeTest::test_add_tunnel_ip_flow_dl FAILED
lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py::ClassifierMmeTest::test_delete_tunnel_ip_flow_dl PASSED
lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py::ClassifierMmeTest::test_detach_default_tunnel_flows PASSED
lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py::ClassifierMmeTest::test_discard_tunnel_ip_flow_dl FAILED
lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py::ClassifierMmeTest::test_resume_tunnel_ip_flow_dl FAILED
```
The failures are snapshot diffs. Example diff for `test_add_tunnel_ip_flow_dl`:
```
E   AssertionError: Snapshot mismatch with error:
E   --- previous snapshot
E   
E   +++ current snapshot
E   
E   @@ -1,10 +1,10 @@
E   
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,tun_id=0x1,in_port=1 actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,set_field:0x186a0->reg9,load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,tun_id=0x2,in_port=1 actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,set_field:0x186a1->reg9,load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   + cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,tun_id=0x1,in_port=ANY actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,set_field:0x186a0->reg9,load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   + cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,tun_id=0x2,in_port=ANY actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,set_field:0x186a1->reg9,load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E     cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,arp,in_port=LOCAL,arp_tpa=192.168.128.30 actions=load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E     cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,arp,in_port=15577,arp_tpa=192.168.128.30 actions=load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E     cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,arp,in_port=LOCAL,arp_tpa=192.168.128.31 actions=load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E     cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,arp,in_port=15577,arp_tpa=192.168.128.31 actions=load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=5,tcp,in_port=LOCAL,nw_src=192.168.129.64,nw_dst=192.168.128.12,tp_src=5002,tp_dst=0 actions=load:0x186a0->NXM_NX_TUN_ID[],load:0xc0a83cb2->NXM_NX_TUN_IPV4_DST[],set_field:0x1->reg8,set_field:0x1->reg9,load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=5,tcp,in_port=15577,nw_src=192.168.129.64,nw_dst=192.168.128.12,tp_src=5002,tp_dst=0 actions=load:0x186a0->NXM_NX_TUN_ID[],load:0xc0a83cb2->NXM_NX_TUN_IPV4_DST[],set_field:0x1->reg8,set_field:0x1->reg9,load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,udp,in_port=LOCAL,nw_src=192.168.129.4,nw_dst=192.168.128.111,tp_src=5060,tp_dst=80 actions=load:0x186a1->NXM_NX_TUN_ID[],load:0xc0a83cb2->NXM_NX_TUN_IPV4_DST[],set_field:0x1->reg8,set_field:0x2->reg9,load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,udp,in_port=15577,nw_src=192.168.129.4,nw_dst=192.168.128.111,tp_src=5060,tp_dst=80 actions=load:0x186a1->NXM_NX_TUN_ID[],load:0xc0a83cb2->NXM_NX_TUN_IPV4_DST[],set_field:0x1->reg8,set_field:0x2->reg9,load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   + cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=5,tcp,in_port=LOCAL,nw_src=192.168.129.64,nw_dst=192.168.128.12,tp_src=5002,tp_dst=0 actions=load:0x186a0->NXM_NX_TUN_ID[],load:0xc0a83cb2->NXM_NX_TUN_IPV4_DST[],set_field:0xffffffff->reg8,set_field:0x1->reg9,load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   + cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=5,tcp,in_port=15577,nw_src=192.168.129.64,nw_dst=192.168.128.12,tp_src=5002,tp_dst=0 actions=load:0x186a0->NXM_NX_TUN_ID[],load:0xc0a83cb2->NXM_NX_TUN_IPV4_DST[],set_field:0xffffffff->reg8,set_field:0x1->reg9,load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   + cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,udp,in_port=LOCAL,nw_src=192.168.129.4,nw_dst=192.168.128.111,tp_src=5060,tp_dst=80 actions=load:0x186a1->NXM_NX_TUN_ID[],load:0xc0a83cb2->NXM_NX_TUN_IPV4_DST[],set_field:0xffffffff->reg8,set_field:0x2->reg9,load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   + cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,udp,in_port=15577,nw_src=192.168.129.4,nw_dst=192.168.128.111,tp_src=5060,tp_dst=80 actions=load:0x186a1->NXM_NX_TUN_ID[],load:0xc0a83cb2->NXM_NX_TUN_IPV4_DST[],set_field:0xffffffff->reg8,set_field:0x2->reg9,load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
```

2022-06-10 19:01 UTC, pshelar commented
> Hi @pshelar, it seems to be reproducible - the test fails after `openvswitch-datapath-dkms_2.15.4-9_all.deb` is installed.

Did you install only datapath package or installed all required OVS packages?

2022-06-10 19:31 UTC, nstng commented
> Did you install only datapath package or installed all required OVS packages?

We run the tests on the magma vm. The tests were green before we installed any packages.
* Krisz installed all packages created by `third_party/gtp_ovs/ovs-gtp-patches/2.15/build.sh` (technically the packages were upgraded, as the vm already had older versions installed)
* I installed/upgraded only `openvswitch-datapath-dkms_2.15.4-9_all.deb` (my assumption was that this is the only relevant packae, as it contains `gtp.c`).

We have the same test results.

2022-06-27 02:42 UTC, pshelar commented
> > Did you install only datapath package or installed all required OVS packages?
> 
> We run the tests on the magma vm. The tests were green before we installed any packages.
> 
> * Krisz installed all packages created by `third_party/gtp_ovs/ovs-gtp-patches/2.15/build.sh` (technically the packages were upgraded, as the vm already had older versions installed)
> * I installed/upgraded only `openvswitch-datapath-dkms_2.15.4-9_all.deb` (my assumption was that this is the only relevant packae, as it contains `gtp.c`).
> 
> We have the same test results.


@nstng I installed all four OVS packages (datapath, lib, command and vswitch), restarted the VM using  `vagrant reload` and ran `make test_python` on latest master. I dont see the failre, it might be unstable test. can you retry it again.

2022-06-27 07:16 UTC, nstng commented
> @nstng I installed all four OVS packages (datapath, lib, command and vswitch), restarted the VM using `vagrant reload` and ran `make test_python` on latest master. I don't see the failure, it might be unstable test. can you retry it again.

@pshelar TL;DR I can still reproduce it - have you restarted the VM after installing the ovs packages?

Detailed experiments:
* check out and update master
* vagrant destroy all lte/gatway VMs
* vagrant up magma
* switch gtp-end-mark
* vagrant ssh magma
* mkdir /home/vagrant/ovsbuild
* cd magma && ./third_party/gtp_ovs/ovs-gtp-patches/2.15/build.sh /home/vagrant/ovsbuild
* switch master
* run test -> green
  ./bazel/scripts/run_sudo_tests.sh lte/gateway/python/magma/pipelined/tests:test_classifier_mme_flow_dl
* snapshot vm
* ~/ovsbuild$ sudo apt install ./openvswitch-datapath-dkms_2.15.4-9_all.deb
* run test -> green
* restart vm
* run test -> red (five times)
* ~/ovsbuild$ sudo apt install ./libopenvswitch_2.15.4-9_amd64.deb
* ~/ovsbuild$ sudo apt install ./openvswitch-common_2.15.4-9_amd64.deb
* ~/ovsbuild$ sudo apt install ./openvswitch-switch_2.15.4-9_amd64.deb
* run test -> red (one time)
* restart vm
* run test -> red (three times)
* restore snapshot (basically restore installed ovs .debs)
* run test -> green (three times)

Failing tests always fail with the same result:
```
lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py::ClassifierMmeTest::test_add_tunnel_ip_flow_dl FAILED                     [ 20%]
lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py::ClassifierMmeTest::test_delete_tunnel_ip_flow_dl PASSED                  [ 40%]
lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py::ClassifierMmeTest::test_detach_default_tunnel_flows PASSED               [ 60%]
lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py::ClassifierMmeTest::test_discard_tunnel_ip_flow_dl FAILED                 [ 80%]
lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py::ClassifierMmeTest::test_resume_tunnel_ip_flow_dl FAILED                  [100%]

======================================================================= FAILURES ========================================================================
_____________________________________________________ ClassifierMmeTest.test_add_tunnel_ip_flow_dl ______________________________________________________

self = <test_classifier_mme_flow_dl.ClassifierMmeTest testMethod=test_add_tunnel_ip_flow_dl>

    def test_add_tunnel_ip_flow_dl(self):
    
        # Need to delete all default flows in table 0 before
        # install the specific flows test case.
        self.test_detach_default_tunnel_flows()
    
        dest_ip = IPAddress(
            version=IPAddress.IPV4,
            address=socket.inet_pton(socket.AF_INET, "192.168.128.12"),
        )
        src_ip = IPAddress(
            version=IPAddress.IPV4,
            address=socket.inet_pton(socket.AF_INET, "192.168.129.64"),
        )
        ip_flow_dl = IPFlowDL(
            set_params=71, tcp_dst_port=0,
            tcp_src_port=5002, udp_dst_port=0, udp_src_port=0, ip_proto=6,
            dest_ip=dest_ip, src_ip=src_ip, precedence=65530,
        )
    
        seid1 = 5000
        ue_ip_addr = "192.168.128.30"
        self.classifier_controller.gtp_handler(
            0, 65525, 1, 100000, self.EnodeB_IP,
            ue_ip_addr,
            seid1, ip_flow_dl=ip_flow_dl,
        )
    
        dest_ip = IPAddress(
            version=IPAddress.IPV4,
            address=socket.inet_pton(socket.AF_INET, "192.168.128.111"),
        )
        src_ip = IPAddress(
            version=IPAddress.IPV4,
            address=socket.inet_pton(socket.AF_INET, "192.168.129.4"),
        )
    
        ip_flow_dl = IPFlowDL(
            set_params=70, tcp_dst_port=0,
            tcp_src_port=0, udp_dst_port=80, udp_src_port=5060, ip_proto=17,
            dest_ip=dest_ip, src_ip=src_ip, precedence=65525,
        )
    
        seid2 = 5001
        ue_ip_addr = "192.168.128.31"
        self.classifier_controller.gtp_handler(
            0, 65525, 2, 100001, self.EnodeB_IP,
            ue_ip_addr,
            seid2, ip_flow_dl=ip_flow_dl,
        )
    
        snapshot_verifier = SnapshotVerifier(
            self, self.BRIDGE,
            self.service_manager,
        )
        with snapshot_verifier:
>           pass

lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py:161: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bazel-bin/lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.runfiles/__main__/lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py:690: in __exit__
    assert_bridge_snapshot_match(
bazel-bin/lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.runfiles/__main__/lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py:554: in assert_bridge_snapshot_match
    fail(
bazel-bin/lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.runfiles/__main__/lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py:487: in fail
    return test_case.fail(msg)
E   AssertionError: Snapshot mismatch with error:
E   --- previous snapshot
E   
E   +++ current snapshot
E   
E   @@ -1,10 +1,10 @@
E   
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,tun_id=0x1,in_port=1 actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,set_field:0x186a0->reg9,load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,tun_id=0x2,in_port=1 actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,set_field:0x186a1->reg9,load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   + cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,tun_id=0x1,in_port=ANY actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,set_field:0x186a0->reg9,load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   + cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,tun_id=0x2,in_port=ANY actions=mod_dl_src:02:00:00:00:00:01,mod_dl_dst:ff:ff:ff:ff:ff:ff,set_field:0x186a1->reg9,load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E     cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,arp,in_port=LOCAL,arp_tpa=192.168.128.30 actions=load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E     cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,arp,in_port=15577,arp_tpa=192.168.128.30 actions=load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E     cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,arp,in_port=LOCAL,arp_tpa=192.168.128.31 actions=load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E     cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,arp,in_port=15577,arp_tpa=192.168.128.31 actions=load:0x1389->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=5,tcp,in_port=LOCAL,nw_src=192.168.129.64,nw_dst=192.168.128.12,tp_src=5002,tp_dst=0 actions=load:0x186a0->NXM_NX_TUN_ID[],load:0xc0a83cb2->NXM_NX_TUN_IPV4_DST[],set_field:0x1->reg8,set_field:0x1->reg9,load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=5,tcp,in_port=15577,nw_src=192.168.129.64,nw_dst=192.168.128.12,tp_src=5002,tp_dst=0 actions=load:0x186a0->NXM_NX_TUN_ID[],load:0xc0a83cb2->NXM_NX_TUN_IPV4_DST[],set_field:0x1->reg8,set_field:0x1->reg9,load:0x1388->OXM_OF_METADATA[],resubmit(,ingress(main_table))
E   - cookie=0x0, table=classifier(main_table), n_packets=0, n_bytes=0, priority=10,udp,in_por [...]

2022-07-05 15:11 UTC, sebathomas commented
It seems the versions uploaded to Artifactory at the moment are no longer compatible with all necessary dependencies:
```
$ sudo apt install openvswitch-doc openvswitch-pki openvswitch-test openvswitch-datapath-dkms openvswitch-common openvswitch-switch

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openvswitch-pki : Depends: openvswitch-common (< 2.15.4-8.1~) but 2.15.4-9 is to be installed
E: Unable to correct problems, you have held broken packages.

```

2022-07-06 06:19 UTC, sebathomas commented
> > It seems the versions uploaded to Artifactory at the moment are no longer compatible with all necessary dependencies:
> > ```
> > $ sudo apt install openvswitch-doc openvswitch-pki openvswitch-test openvswitch-datapath-dkms openvswitch-common openvswitch-switch
> > ```
> 
> Do you need the pki package for any specific reason? AFAIK AGW does not need it.

I'm trying to build a new magma-dev base image (#13179) and it's part of the Ansible preburn steps ("Install common Magma dependencies"). But I can try an installation without it.

2022-07-18 09:57 UTC, sebathomas commented
Unfortunately, we also get these sudo test failures when trying to build the new magma-dev base image (and not including the patch from this PR). We may have to use the old openvswitch version for that one.

2022-07-20 16:12 UTC, sebathomas commented
Update about the tests: I think we understand a little better what is going on. In short, it seems like the installation of the kernel modules is a bit tricky and can silently fail, while the patch itself is fine.

We noticed that the test failed because the module `vport_gtp` was not installed correctly (both in Nils' test setup from https://github.com/magma/magma/pull/12943#issuecomment-1166972993 and in the new dev VM). It can be fixed by reinstalling openvswitch-datapath-dkms when all requirements are met (I think it needs kernel headers and some more extras). To fix the issue in the test setup, you need to restart the VM after the build and before the installation - probably because the build process installs some additional kernel / header / module requirements that need a restart:

> * check out and update master
> * vagrant destroy all lte/gatway VMs
> * vagrant up magma
> * switch gtp-end-mark
> * vagrant ssh magma
> * mkdir /home/vagrant/ovsbuild
> * cd magma && ./third_party/gtp_ovs/ovs-gtp-patches/2.15/build.sh /home/vagrant/ovsbuild
> * **restart VM**
> * switch master
> * run test -> green
>   ./bazel/scripts/run_sudo_tests.sh lte/gateway/python/magma/pipelined/tests:test_classifier_mme_flow_dl
> * snapshot vm
> * ~/ovsbuild$ sudo apt install ./openvswitch-datapath-dkms_2.15.4-9_all.deb
> * run test -> green
> * restart vm
> * run test -> red (five times)
> [...]

We confirmed that the tests are green both with the ovsbuild packages from the branch and with the uploaded 2.15.4-9 packages on artifactory.

2022-07-20 16:50 UTC, maxhbr requested changes
Patchfiles are conflicting

2022-07-20 16:50 UTC, maxhbr commented on third_party/gtp_ovs/ovs-gtp-patches/2.15/0025-ovs-gtp-fix-handling-of-End-marker-packet.patch
> +-openvswitch (2.15.4-8) unstable; urgency=low
```suggestion
-openvswitch (2.15.4-9-magma) unstable; urgency=low
```

2022-07-20 16:50 UTC, maxhbr commented on third_party/gtp_ovs/ovs-gtp-patches/2.15/0025-ovs-gtp-fix-handling-of-End-marker-packet.patch
> ++openvswitch (2.15.4-9) unstable; urgency=low
```suggestion
+openvswitch (2.15.4-10-magma) unstable; urgency=low
```

2022-07-20 16:56 UTC, nstng commented
> Update about the tests: I think we understand a little better what is going on. In short, it seems like the installation of the kernel modules is a bit tricky and can silently fail, while the patch itself is fine.

Can reproduce. If doing a restart between building the packages and installing them keeps the test green.

Would have never guessed that - nice finding! thank you

2022-10-25 05:58 UTC, nstng commented
Should be handled in #12943. Will close for now. @panyogesh, if I misunderstood, please reopen.

2022-10-25 05:58 UTC, closed without merging