docs(agw): Updated quick start guide to add ipv6 range in /etc/vbox/networks.conf
magma/magma pull request #13100
Opened 2022-06-28 10:43 UTC by pruthvihebbani

Signed-off-by: Pruthvi Hebbani <pruthvi.hebbani@radisys.com>

docs(agw): Updated quick start guide to add ipv6 range in /etc/vbox/networks.conf

## Summary

Updated quick start guide to add ipv6 range in /etc/vbox/networks.conf

2022-06-28 11:32 UTC, Neudrino requested changes
- This change will also be needed in the current master version of the documentation.
- No test plan was given.
  - Expected result should be given.
  - Test plan should be executed and actual result should be given.

2022-06-28 16:23 UTC, ssanadhya approved these changes
Lgtm

2022-06-29 10:22 UTC, nstng commented on docs/docusaurus/versioned_docs/version-1.7.0/basics/quick_start_guide.md
>  We'll be setting up the LTE AGW VM in this tab.
My understanding is that this should not be added to the 1.7 documentation. 1.7 does not have this change. I assume the change will not be back ported to 1.7, right?

2022-06-29 11:55 UTC, Neudrino approved these changes
Did you know that there is a ["Re-request review" feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review), which should be used to bring PRs to reviewers attention again?
Otherwise, they will not know, that the PR is ready for another review.

![grafik](https://user-images.githubusercontent.com/13189449/176430172-70870c5c-d0ac-4e71-8ace-045e24bc7413.png)

2022-06-29 12:25 UTC, pruthvihebbani commented
> Did you know that there is a ["Re-request review" feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review), which should be used to bring PRs to reviewers attention again? Otherwise, they will not know, that the PR is ready for another review.
> 
> ![grafik](https://user-images.githubusercontent.com/13189449/176430172-70870c5c-d0ac-4e71-8ace-045e24bc7413.png)

I was not aware of this. Thanks for the info @Neudrino

2022-06-29 12:27 UTC, merged