fix(agw): Migrate hash list of enb_description_t to protobuf_map
magma/magma pull request #13128
Opened 2022-06-29 11:38 UTC by rsarwad

Modified code to replace hashlist with protobuf map for enb_description_t in s1ap module
The PR partially addresses the issue, https://github.com/magma/magma/issues/11190

Test Plan
Executed s1ap sanity test suite and unit test case.
Verified manually with test_attact_detach_with_mme_restart.py test case, to check whether contents of enb_description are written correctly into DB.

2022-07-05 07:06 UTC, LKreutzer approved these changes
Bazel changes lgtm

2022-07-06 18:02 UTC, ssanadhya requested changes

2022-07-06 18:02 UTC, ssanadhya commented on lte/gateway/c/core/oai/include/state_converter.hpp
> +        OAILOG_ERROR(log_task_level, "Key %lu not found on %s hashtable",
```suggestion
        OAILOG_ERROR(log_task_level, "Key %lu without value in %s map",
```

2022-07-06 18:02 UTC, ssanadhya commented on lte/gateway/c/core/oai/include/state_converter.hpp
> +        OAILOG_ERROR(log_task_level, "Failed to insert node on hashtable %s",
```suggestion
        OAILOG_ERROR(log_task_level, "Failed to insert key in map %s",
```

2022-07-06 18:02 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
> +    if (magma::PROTO_MAP_OK != rc) {
Keep the variable on left hand side of comaprision
```suggestion
    if (rc != magma::PROTO_MAP_OK ) {
```

2022-07-06 18:02 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
>      OAILOG_ERROR(LOG_S1AP, "Could not find eNB hashlist!\n");
```suggestion
    OAILOG_ERROR(LOG_S1AP, "Could not find eNB map!\n");
```

2022-07-06 18:02 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
> +  return;  // always return false to make sure it runs on all elements
Please fix the comment.

2022-07-06 18:02 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
> -    // remove all the mme_ue_s1ap_ids
Keep the comment in line 212, since it is describing the logic in following lines

2022-07-06 18:02 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
> +                            hash_table_ts_t* s1ap_ue_state) {
1. Since this function operates on one entry, name it as a checker
2. Rename the parameters for better readability

```suggestion
bool check_imsi_for_mme_ue_id(uint32_t mme_ue_id, uint64_t const comp_s1ap_id,
                            hash_table_ts_t* s1ap_ue_state) {
```

2022-07-06 18:02 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
>          keyP, *num_ues_checked);
Move this log to the caller

2022-07-06 18:02 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
> +      get_mme_ue_ids_no_imsi(ue_itr->first, ue_itr->second, &num_ues_checked,
Update `mme_ue_id_no_imsi_list` here

2022-07-06 18:02 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
> +char S1AP_ENB_COLL[] = "s1ap_eNB_coll";
Why remove `constexpr` from here?

2022-07-12 05:05 UTC, ssanadhya approved these changes
Lgtm

2022-07-12 05:05 UTC, merged