fix(agw): cpp migration of SPGW files
magma/magma pull request #13213
Opened 2022-07-06 14:07 UTC by pruthvihebbani

fix(agw): cpp migration of SPGW files

## Summary

Migrated all the files under spgw task to cpp/hpp and fixed all the errors and warnings

## Test Plan

- Verified test_oai
- Verified s1ap sanity suite

2022-07-06 18:35 UTC, ssanadhya requested changes

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/s11_causes.c
> - * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
Please move instead of deleting and re-adding

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/pgw_procedures.cpp
> +      (pgw_ni_cbr_proc_t*)calloc(1, sizeof(pgw_ni_cbr_proc_t));
Please address lint warning

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.hpp
> -void populate_sgi_end_point_update(
Nice clean up!

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.hpp
> +void sgw_process_release_access_bearer_request(
Move this function close to other release access bearer calls

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/spgw_config.cpp
>  #include "lte/gateway/c/core/common/assertions.h"
Sort alphabetically

```suggestion
#include "lte/gateway/c/core/common/assertions.h"
#include "lte/gateway/c/core/common/dynamic_memory_check.h"
```

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/test/spgw_task/state_creators.hpp
> +#include "lte/gateway/c/core/oai/tasks/sgw/sgw_defs.hpp"
Can this be moved out of the `extern "C"` block?

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_dedicated_bearer.cpp
> +#include "lte/gateway/c/core/oai/tasks/sgw/pgw_procedures.hpp"
Move these to after the extern "C" block, along with "spgw_test_util.h". Ref: [Ordering of headers style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/pgw_config.cpp
> -/*! \file spgw_config.c
Nice clean up!

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
> +#ifdef __cplusplus
Please sort alphabetically

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
> -      module, S11_NW_INITIATED_DEACTIVATE_BEARER_REQUEST);
This function is used by both SPGW task and SGW_S8 task, so need to specify the right sender task based on the `module` parameter.

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
> +  message_p = itti_alloc_new_message(TASK_SPGW_APP,
Can we use the task name related to `module` ?

2022-07-06 18:35 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/sgw_paging.cpp
> +#include "lte/gateway/c/core/oai/tasks/sgw/sgw_paging.hpp"
Can we also sort these alphabetically as part of this change?

2022-07-07 08:42 UTC, LKreutzer approved these changes

2022-07-07 08:42 UTC, LKreutzer commented on lte/gateway/c/core/oai/tasks/sgw/pgw_config.cpp
> +          return RETURNerror;
Nice catch! :+1:

2022-07-07 08:42 UTC, LKreutzer commented on lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
> +      (sgw_eps_bearer_ctxt_t*)calloc(1, sizeof(sgw_eps_bearer_ctxt_t));
It would be great if we could fix all the C-style cast warnings as suggested

2022-07-07 08:42 UTC, LKreutzer commented on lte/gateway/c/core/BUILD.bazel
> +    "oai/tasks/sgw/pgw_handlers.hpp",
Bazel changes lgtm, thanks for the clean up!

2022-07-08 14:15 UTC, pruthvihebbani commented
In this PR I have moved files from c->cpp using mv command due to which the files are treated as new additions and the history is getting lost. Once this PR gets approved, I will close this and create a new PR where I will use git mv to rename the files. Rest of the changes will remain the same.

2022-07-08 16:13 UTC, ssanadhya commented
> In this PR I have moved files from c->cpp using mv command due to which the files are treated as new additions and the history is getting lost. Once this PR gets approved, I will close this and create a new PR where I will use git mv to rename the files. Rest of the changes will remain the same.

Only "s11_causes.c" is showing up as new addition. All other files, e.g. pgw_config.c->pgw_config.cpp, are showing as moved/renamed. So it should be possible to fix this one file in this PR itself. No need to duplicate effort by creating a new PR.

2022-07-08 16:22 UTC, pruthvihebbani commented
> > In this PR I have moved files from c->cpp using mv command due to which the files are treated as new additions and the history is getting lost. Once this PR gets approved, I will close this and create a new PR where I will use git mv to rename the files. Rest of the changes will remain the same.
> 
> Only "s11_causes.c" is showing up as new addition. All other files, e.g. pgw_config.c->pgw_config.cpp, are showing as moved/renamed. So it should be possible to fix this one file in this PR itself. No need to duplicate effort by creating a new PR.

They show as renamed but git log does not show the full history of this file. For eg:
![image](https://user-images.githubusercontent.com/38202471/178031657-9ac63bbb-278b-4482-abdf-aa5c13263aa3.png)

2022-07-08 16:35 UTC, ssanadhya commented
> > > In this PR I have moved files from c->cpp using mv command due to which the files are treated as new additions and the history is getting lost. Once this PR gets approved, I will close this and create a new PR where I will use git mv to rename the files. Rest of the changes will remain the same.
> > 
> > 
> > Only "s11_causes.c" is showing up as new addition. All other files, e.g. pgw_config.c->pgw_config.cpp, are showing as moved/renamed. So it should be possible to fix this one file in this PR itself. No need to duplicate effort by creating a new PR.
> 
> They show as renamed but git log does not show the full history of this file. For eg: ![image](https://user-images.githubusercontent.com/38202471/178031657-9ac63bbb-278b-4482-abdf-aa5c13263aa3.png)

@pruthvihebbani , Please try `git log --follow`

2022-07-11 16:51 UTC, pruthvihebbani commented
In this PR instead of git mv command mv command was used to rename the files. This was erasing the file commit history. Created a new PR https://github.com/magma/magma/pull/13264 to address this as modifying this PR was becoming messy

2022-07-11 16:51 UTC, closed without merging