[AGW] Write per subscriber APN specific data into subscriberDB store when MME receives Update Location Answer
magma/magma pull request #13290
Opened 2022-07-13 18:52 UTC by vroon2703

## Summary

This PR will have the following code: 

1. SQLite functions that allow adding subscribers 
2. Changes to MME that will call the sqlite function to add apn information of subscribers as part of update location. 

## Test Plan
TODO

2022-07-13 19:20 UTC, vroon2703 commented on lte/gateway/c/core/oai/lib/s6a_proxy/s6a_client_api.cpp
> +
Here I need to get the apn information from response. How can I know what response looks like? How do I know what subscriber data looks like? Is this from proto? 
Do I populate the information in subscriber data by checking if the data actually exists in response.

2022-07-13 19:20 UTC, vroon2703 commented on lte/gateway/c/core/oai/lib/store/CMakeLists.txt
> +target_link_libraries(store MAGMA_CONFIG COMMON tacopie protobuf) #not sure of this.
What are target link libraries. What else do I need to link here?

2022-07-13 19:22 UTC, vroon2703 commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +void SqliteStore::add_subscriber(const SubscriberData& subscriber_data) {
what is the input here? What is the data structure type for subscriber data.

2022-07-13 19:23 UTC, vroon2703 commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +  data_str = subscriber_data.SerializeToString();
I am not sure if I need to define this function again. How does subscriber data already have the function SerializeToString?

2022-07-13 19:27 UTC, vroon2703 commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +std::string SqliteStore::to_str(sid_pb) {
need to add the type here

2022-07-18 12:37 UTC, maxhbr commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +#include "lte/gateway/c/core/oai/lib/store/sqlite.hpp"
missing license header

2022-07-19 21:17 UTC, ssanadhya commented
@vroon2703 , since this PR is adding the SQlite3 dependency on MME service, please include the correct library name in 
1. Packaging script [build-magma.sh](https://github.com/magma/magma/blob/master/lte/gateway/release/build-magma.sh#L152)
2. VM provisioning script for [magma dev VM](https://github.com/magma/magma/blob/master/lte/gateway/deploy/roles/magma/tasks/main.yml#L190)

2022-07-20 22:20 UTC, ssanadhya requested changes
Can you add a snapshot of the newly created database entries in the test plan?

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> + */
Please use the Magma Authors copyright here

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/sqlite.hpp
> + */
Please use the Magma copyright here, since this is a new file getting added as part of Magma project.

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/test/lib/test_ula_subData.cpp
> +#include <string.h>
Include Magma copyright header here too

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.cpp
> +    std::cout << "No APN configurations received" << std::endl;
Just return from here. 

Then you can do without encapsulating the rest of the function description in else brace

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.cpp
> +        // (magma::lte::AggregatedMaximumBitrate*)apn.mutable_ambr());
Remove commented code

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.cpp
> +        if (apn.ambr().unit() != 0) {
No need for this check as value 0 indicates enum type BPS

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.cpp
> +      if (apn.pdn() != 0) {
No need for this check as 0 indicates a valid enum type

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.cpp
> +      if (apn.served_party_ip_address_size() > 0) {
Add a comment that only one IP address is assigned in the current implementation

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/s6a_proxy/s6a_client_api.cpp
> +            "", 2);  // hardcoded here, todo get the db location for the sqlite
The location of db should be same as what SubscriberDB is using currently

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/s6a_proxy/s6a_client_api.cpp
> +        magma::lte::SubscriberID sub_id = magma::lte::SubscriberID();
No need to create a new object here. We can just use the member object in `sub_data`

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/s6a_proxy/s6a_client_api.hpp
> +
Was this added by mistake or from formatter?

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/CMakeLists.txt
> +
Too many new lines

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/CMakeLists.txt
> +
Too many newlines

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/CMakeLists.txt
> +set(APN_CPP_PROTOS apn)
```suggestion
set(SUB_LTE_PROTOS subscriberdb apn)
set(SUB_ORC8R_PROTOS digest)
```

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/sqlite.hpp
> +      SubscriberData& subscriber_data);  // TODO: add the parameters
Clean up the TODO comment

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/sqlite.hpp
> +  void delete_subscriber();  // TODO: add the parameters
```suggestion
  void delete_subscriber();  // TODO(vroon2703): add the parameters
```

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/test/lib/CMakeLists.txt
> +    )
No need for target_include_directories here.

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/test/lib/CMakeLists.txt
> +set(MCONFIG_OUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/lte/protos")
Why do we need to generate these protos as part of test, but not as part of the original library?

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +  std::string sid_s = _to_str(subscriber_data);
`sid_s` refers to the sid field in SubscriberData

```suggestion
  std::string sid_s = _to_str(subscriber_data.sid());
```

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +// function is hardcoded for now, will fix
What is hardcoded here?

2022-07-20 22:20 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +        SQLITE_STATIC);  // REVIEW THAT THE PARAMETERS HERE ARE CORRECT
Remove comment

2022-07-21 18:11 UTC, ardzoht requested changes

2022-07-21 18:11 UTC, ardzoht commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +  int rc2 = sqlite3_prepare_v2(db, sql, strlen(sql), &stmt, &pzTail);
```suggestion
  int rc_prep = sqlite3_prepare_v2(db, sql, strlen(sql), &stmt, &pzTail);
```

2022-07-21 18:11 UTC, ardzoht commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +  int rc = sqlite3_open(db_location, &db);
you can just pass `db_location_s.c_str()` here instead of creating separate var

2022-07-21 18:11 UTC, ardzoht commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +void SqliteStore::add_subscriber(SubscriberData& subscriber_data) {
can we pass const for SubscriberData here ?

2022-07-21 18:11 UTC, ardzoht commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +  for (std::string db_location_s : _db_locations) {
```suggestion
  for (auto db_location_s : _db_locations) {
```

2022-07-21 18:11 UTC, ardzoht commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +  int rc = sqlite3_open(db_location, &db);
```suggestion
  int rc_open = sqlite3_open(db_location, &db);
```

2022-07-21 18:11 UTC, ardzoht commented on lte/gateway/c/core/oai/test/lib/test_ula_subData.cpp
> +    magma::feg::UpdateLocationAnswer &ula_object,
pass const reference here

2022-07-27 17:10 UTC, ardzoht commented on lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
> +	return flag
```suggestion
	return EpcConfig.CloudSubscriberdbEnabled
```

2022-07-27 17:10 UTC, ardzoht commented on lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
> +	}
Should we return a default for these cases?

2022-07-29 06:36 UTC, rsarwad commented on lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
> +        self._subscriber_client.wait_for_changes()
Do we need "wait_for_changes()" to be called because adding subscriber through subscriber_client is commented?

2022-07-29 06:40 UTC, rsarwad commented on lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
> +        print("not adding subscriber again")
This fun() mainly generates IMSI and IMEI for all users as indicated in num_ues. So what's this log indicate?

2022-07-29 06:48 UTC, rsarwad commented on lte/gateway/python/integ_tests/s1aptests/test_attach_detach_cloud.py
> +        num_ues = 1
Can we configure num_ues to 2, as detach_type and wait_for_s1 are used set to different values for each UE

2022-07-29 06:50 UTC, rsarwad commented on lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
> +        # self._sub_util.config_apn_data(imsi, apn_list)
Since the invoking of configAPN is guarded with flag, cloud. Do we need to comment this line?

2022-07-29 06:51 UTC, rsarwad commented on lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
> +            if not cloud:
I think similar changes would needed for fun, configUEDevice_ues_same_imsi

2022-07-29 06:54 UTC, rsarwad commented on lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
> +
Remove extra spaces

2022-07-30 05:00 UTC, ssanadhya requested changes
@vroon2703 , it will be good to split the S1ap integration tests into a separate PR . This PR should focus on writing APN info in subscriberDB , along with unit tests and changes in Ansible files to install sqlite library in gateway VM. This will make it easier to review and merge

2022-07-30 05:00 UTC, ssanadhya commented on lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
> +		glog.Infof("Cloud Authentication enabled, not streaming subscriber data")
```suggestion
		glog.Infof("Cloud Authentication disabled, streaming subscriber data")
```

2022-07-30 05:00 UTC, ssanadhya commented on lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
> +		glog.Infof("Cloud Authentication enabled, not streaming subscriber data")
```suggestion
		glog.Infof("Cloud Authentication disabled, streaming subscriber data")
```

2022-07-30 05:00 UTC, ssanadhya commented on lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
> +		glog.Infof("Cloud Authentication enabled, not streaming subscriber data")
```suggestion
		glog.Infof("Cloud Authentication disabled, streaming subscriber data")
```

2022-07-30 05:00 UTC, ssanadhya commented on lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
> +		glog.Infof("Cloud Authentication NOT enabled,  streaming subscriber data")
```suggestion
		glog.Infof("Cloud Authentication disabled,  streaming subscriber data")
```

2022-07-30 05:00 UTC, ssanadhya commented on lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
> +		fmt.Errorf("Load network for network %s: %w", networkID, err)
```suggestion
		fmt.Errorf("Load error for network %s: %w", networkID, err)
```

2022-07-30 05:00 UTC, ssanadhya commented on lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
> +	}
Good point @ardzoht ! The default should be the safer approach, i.e. no subscriber data is streamed. Hence `return true` . cc: @vroon2703

2022-07-30 05:00 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.cpp
> +    std::cout << "CONVERTING ULA TO SUBSCRIBER DATA" << std::endl;
```suggestion
    std::cout << "Converting ULA to Subscriber Data object" << std::endl;
```

2022-07-30 05:00 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +  }
This should still return some value.

2022-07-30 05:00 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +  std::string sid_s = _to_str(subscriber_data);
I missed the part that `_to_str` is returning the SID sub-field of SubscriberData. Resolving this conversation.

2022-07-30 05:00 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/store/sqlite.cpp
> +  const char* sid = sid_s.c_str();
`sid_s` is only being used once. Can we modify `_to_str` to return a C string instead of std::string.

2022-11-14 04:20 UTC, closed without merging