chore(agw): MME rename files from c to cpp in nas/esm/msg folder
magma/magma pull request #13319
Opened 2022-07-18 11:21 UTC by vikramgreddy

Signed-off-by: Vikram G <vikram.gurrappagaru@radisys.com>

## Summary
In order to use the protobuf map, it's required to migrate all c files to cpp. Doing so will result in huge changes. So we planned to commit a small chunk of changes. This PR is for renaming c to cpp in nas/esm/msg folder

## Test Plan
make test_oai

## Additional Information

2022-07-19 06:26 UTC, rsarwad commented on lte/gateway/c/core/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextAccept.cpp
> +#endif
Leave a blank space after extern directive. 
Address at all locations

2022-07-19 16:59 UTC, ssanadhya requested changes
Most of the changes look good. Two changes to make:
- Please follow the  [Google C++ style guide](#include "lte/gateway/c/core/oai/common/common_utility_funs.hpp") for re-ordering the include headers
- Run `make format_all` to see if that addresses the comment from @rsarwad

2022-07-19 16:59 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextAccept.cpp
> +#include "lte/gateway/c/core/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextAccept.hpp"
Move this include to the top. See the style reference at [Google C++ Style Guide](#include "lte/gateway/c/core/oai/common/common_utility_funs.hpp")

2022-07-19 16:59 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextAccept.cpp
> +#include "lte/gateway/c/core/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextAccept.hpp"
Please apply this to all the other files in this PR

2022-07-20 06:17 UTC, nstng commented
Bazel Build & Test is currently failing - this current error should be solved by a rebase - please do the rebase. After the test run successfully I will go on with the Bazel review.

2022-07-22 06:40 UTC, vikramgreddy commented on lte/gateway/c/core/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextAccept.cpp
> +#include "lte/gateway/c/core/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextAccept.hpp"
Done

2022-07-22 07:47 UTC, rsarwad reviewed
Changes look good to me. Once you execute s1ap sanity test suite, update the test plan to indicate the same

2022-07-27 15:11 UTC, nstng approved these changes
bazel changes lgtm

2022-08-01 07:12 UTC, vikramgreddy commented
> 

Done

2022-08-01 22:54 UTC, ssanadhya approved these changes
Lgtm

2022-08-01 22:54 UTC, merged