chore: Remove initflag package
magma/magma pull request #13446
Opened 2022-07-28 09:42 UTC by LKreutzer

Signed-off-by: Lars Kreutzer <lars.kreutzer@tngtech.com>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2022-07-28 11:07 UTC, crasu requested changes

2022-07-28 11:07 UTC, crasu commented on orc8r/lib/go/initflag/syslog.go
> -const syslogFlag = "stderr2syslog"
This seems to be used in the magma openwrt deployment here:
./openwrt/gateway/configs/etc/init.d/magma.template

2022-07-28 11:08 UTC, crasu commented on orc8r/lib/go/initflag/syslog.go
> -const syslogFlag = "stderr2syslog"
I do not know anything about this openwrt stuff.

2022-08-04 13:39 UTC, nstng commented
converted to draft - initflag still needed in other places. needs to be adapted

2022-08-05 07:10 UTC, LKreutzer commented
Changed the commit to only remove the side-effect imports in the Go code but the package itself since it is still used in the openwrt code.

2022-08-08 07:49 UTC, LKreutzer commented
Added commit to also remove the imports in the bazel code.

2022-08-08 09:48 UTC, closed without merging

2022-08-08 10:07 UTC, LKreutzer commented
As discussed with @crasu @sebathomas @jheidbrink @alexzurbonsen:

- Add initflag functionality to bazel in https://github.com/magma/magma/pull/13532
- Closing this PR and move refactoring of initflag functionality to future task.