chore: py production scripts are bazelified
magma/magma pull request #13451
Opened 2022-07-28 11:48 UTC by nstng

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2022-08-04 15:34 UTC, vktng reviewed
I have verified that all script in the magma deb are bazelified.
I have run all bazel targets and they do not have ModuleNotFound issues.
I have done the documented preparations for Make execution. The scripts have problems when executed with sudo (and this is sometimes needed). Some examples:
`sudo create_oai_certs.py`
```
Traceback (most recent call last):
File "/usr/local/bin/create_oai_certs.py", line 22, in <module>
	import envoy
ImportError: No module named envoy
```

`sudo dp_probe_cli.py -i 5 -d UL stats`
```
sudo: dp_probe_cli.py: command not found
```

Scripts with similar problems:

- config_stateless_agw
- create_oai_certs
- dp_probe_cli
- generate_dnsd_config
- packet_tracer_cli
- pipelined_cli
- generate_fluent_bit_config
- generate_nghttpx_config

Other then the scripts that need sudo the output of the Bazel counterparts were the same, except in one case:
`loadtest_pipelined.py activate_flows --num_of_ues 10 --import_path /`
With Bazel:
```
Preparing activate_flows load test...
QOS Enabled
open lte/protos/lte/protos/pipelined.proto: no such file or directory
Done
```
With Make:
```
Preparing activate_flows load test...
QOS Enabled
Done
```

There are also some scripts that are just broken anyway, for example:
`mobility_dhcp_cli.py`
```
		Traceback (most recent call last):
		  File "/home/vagrant/magma/bazel-bin/lte/gateway/python/scripts/mobility_dhcp_cli.runfiles/__main__/lte/gateway/python/scripts/mobility_dhcp_cli.py", line 208, in <module>
		    main()
		  File "/home/vagrant/magma/bazel-bin/lte/gateway/python/scripts/mobility_dhcp_cli.runfiles/__main__/lte/gateway/python/scripts/mobility_dhcp_cli.py", line 125, in main
		    cli = DhcpClientCLI()
		  File "/home/vagrant/magma/bazel-bin/lte/gateway/python/scripts/mobility_dhcp_cli.runfiles/__main__/lte/gateway/python/scripts/mobility_dhcp_cli.py", line 37, in __init__
		    self.dhcp_client_state = store.MacToIP()  # mac => DHCP_State
		TypeError: __init__() missing 1 required positional argument: 'client'
```

2022-08-08 12:03 UTC, vktng commented
> I have verified that all script in the magma deb are bazelified. I have run all bazel targets and they do not have ModuleNotFound issues. I have done the documented preparations for Make execution. The scripts have problems when executed with sudo (and this is sometimes needed). Some examples: `sudo create_oai_certs.py`
> 
> ```
> Traceback (most recent call last):
> File "/usr/local/bin/create_oai_certs.py", line 22, in <module>
> 	import envoy
> ImportError: No module named envoy
> ```
> 
> `sudo dp_probe_cli.py -i 5 -d UL stats`
> 
> ```
> sudo: dp_probe_cli.py: command not found
> ```
> 
> Scripts with similar problems:
> 
>     * config_stateless_agw
> 
>     * create_oai_certs
> 
>     * dp_probe_cli
> 
>     * generate_dnsd_config
> 
>     * packet_tracer_cli
> 
>     * pipelined_cli
> 
>     * generate_fluent_bit_config
> 
>     * generate_nghttpx_config
> 
> 
> Other then the scripts that need sudo the output of the Bazel counterparts were the same, except in one case: `loadtest_pipelined.py activate_flows --num_of_ues 10 --import_path /` With Bazel:
> 
> ```
> Preparing activate_flows load test...
> QOS Enabled
> open lte/protos/lte/protos/pipelined.proto: no such file or directory
> Done
> ```
> 
> With Make:
> 
> ```
> Preparing activate_flows load test...
> QOS Enabled
> Done
> ```
> 
> There are also some scripts that are just broken anyway, for example: `mobility_dhcp_cli.py`
> 
> ```
> 		Traceback (most recent call last):
> 		  File "/home/vagrant/magma/bazel-bin/lte/gateway/python/scripts/mobility_dhcp_cli.runfiles/__main__/lte/gateway/python/scripts/mobility_dhcp_cli.py", line 208, in <module>
> 		    main()
> 		  File "/home/vagrant/magma/bazel-bin/lte/gateway/python/scripts/mobility_dhcp_cli.runfiles/__main__/lte/gateway/python/scripts/mobility_dhcp_cli.py", line 125, in main
> 		    cli = DhcpClientCLI()
> 		  File "/home/vagrant/magma/bazel-bin/lte/gateway/python/scripts/mobility_dhcp_cli.runfiles/__main__/lte/gateway/python/scripts/mobility_dhcp_cli.py", line 37, in __init__
> 		    self.dhcp_client_state = store.MacToIP()  # mac => DHCP_State
> 		TypeError: __init__() missing 1 required positional argument: 'client'
> ```

To solve the sudo problems I executed the scripts with the following command:
`sudo -E env "PATH=$PATH" some_script.py [args]`
This way I verified that all the scripts that require sudo behave the same with Make as with Bazel if we preserve the `PATH` variable.
The only difference that remains is with `loadtest_pipelined.py` as mentioned before.

2022-08-11 09:00 UTC, nstng commented
> To solve the sudo problems I executed the scripts with the following command: `sudo -E env "PATH=$PATH" some_script.py [args]` This way I verified that all the scripts that require sudo behave the same with Make as with Bazel if we preserve the `PATH` variable. The only difference that remains is with `loadtest_pipelined.py` as mentioned before.

I think `sudo source /etc/environment` should have been solved this - I forgot the `sudo` in the description (added).

2022-08-15 10:57 UTC, nstng commented
The status of the scripts in a production environment based on a magma .deb setup is described in #13606.

The current review shows that the only difference in behavior can be found in `loadtest_pipelined.py` - this script does not work in a production environment (see #13606).

I recommend to merge this state (if there are no further issues found) and adapt bazelified scripts when working on issues originating from #13606.

2022-08-16 10:05 UTC, vktng commented on lte/gateway/python/magma/mobilityd/BUILD.bazel
> +    deps = [
Empty deps.

2022-08-16 10:06 UTC, vktng commented on lte/gateway/python/magma/mobilityd/BUILD.bazel
> +    deps = [
Can be formatted to use 1 line.

2022-08-16 10:10 UTC, vktng commented on lte/gateway/python/scripts/BUILD.bazel
> +        "{}orc8r/gateway/python/scripts".format(MAGMA_ROOT),
Could be a variable like the other roots.

2022-08-16 10:11 UTC, vktng commented on lte/gateway/python/scripts/BUILD.bazel
> +    deps = [
Can be formatted to use 1 line.

2022-08-16 10:19 UTC, vktng requested changes
Please address the comments regarding formatting. Otherwise LGTM.

2022-08-16 11:44 UTC, nstng commented
review changes addressed.

2022-08-17 08:29 UTC, vktng commented on lte/gateway/python/scripts/BUILD.bazel
> +        "{}orc8r/gateway/python/scripts".format(MAGMA_ROOT),
Please use the SCRIPTS_ROOT variable.

2022-08-17 09:18 UTC, nstng commented on lte/gateway/python/scripts/BUILD.bazel
> +        "{}orc8r/gateway/python/scripts".format(MAGMA_ROOT),
oO thanks for finding this one

2022-08-17 09:21 UTC, nstng commented on lte/gateway/python/scripts/BUILD.bazel
> +        "{}orc8r/gateway/python/scripts".format(MAGMA_ROOT),
pushed

2022-08-17 09:42 UTC, vktng approved these changes
LGTM.

2022-08-17 11:10 UTC, merged