chore(lte): Bazelify the S1AP nonsanity tests
magma/magma pull request #13497
Opened 2022-08-04 10:15 UTC by vktng

## Summary

This PR bazelifies the nonsanity integration tests and adds them to the wrapper script for convenient execution.

## Test Plan

Execute the script with different flags and parameters. You can get the help message with this command:
`"${MAGMA_ROOT}"/bazel/scripts/run_integ_tests.sh --help`
```
Executes all integration tests.
Usage:
   run_integ_tests.sh --help
      Display this help message.
   run_integ_tests.sh
      Execute all precommit and extended integration tests in the magma repository.
   run_integ_tests.sh path_to_tests_directory:bazel_test_target_name
      Execute the specified test.
List tests:
   run_integ_tests.sh --list
      List all integration tests.
   run_integ_tests.sh --list-precommit
      List the precommit integration tests.
   run_integ_tests.sh --list-extended
      List the precommit integration tests.
   run_integ_tests.sh --list-nonsanity
      List the nonsanity integration tests.
   run_integ_tests.sh --list-traffic-server
      List all integration tests that use the traffic server.
Execute precommit:
   run_integ_tests.sh --precommit
      Run all precommit integration tests.
Execute extended:
   run_integ_tests.sh --extended
      Run all extended integration tests.
   run_integ_tests.sh --setup-extended
      Execute the setup test for the extended tests.
   run_integ_tests.sh --teardown-extended
      Execute the teardown test for the extended tests.
   run_integ_tests.sh --skip-setup-teardown-extended
      Execute all precommit and extended integration tests in the magma repository,
      except the setup and teardown for extended tests.
      Should be combined with an extended test target or --extended.
   run_integ_tests.sh --skip-setup-teardown-extended path_to_tests_directory:bazel_test_target_name
      Execute the specified test, without executing
      the setup and teardown for extended tests.
Execute nonsanity:
   run_integ_tests.sh --nonsanity
      Run all nonsanity integration tests.
   run_integ_tests.sh --setup-nonsanity
      Execute the setup test for the nonsanity tests.
   run_integ_tests.sh --teardown-nonsanity
      Execute the teardown test for the nonsanity tests.
   run_integ_tests.sh --skip-setup-teardown-nonsanity
      Execute all precommit and extended integration tests in the magma repository,
      except the setup and teardown for nonsanity tests.
      Should be combined with a nonsanity test target or --nonsanity.
   run_integ_tests.sh --skip-setup-teardown-nonsanity --nonsanity
      Execute the nonsanity tests, without executing
      the setup and teardown for them.
   run_integ_tests.sh --skip-setup-teardown-nonsanity path_to_tests_directory:bazel_test_target_name
      Execute the specified test, without executing
      the setup and teardown for nonsanity tests.
```

These tests are really flaky, but most of them passed at least once.
There are 3 tests that I never managed to make green, not even with Make:

1. test_activate_deactivate_multiple_dedicated
2. test_sctp_shutdown_while_mme_is_stopped
3. test_3495_timer_for_dedicated_bearer_with_mme_restart

## Additional Information

- [ ] This change is backwards-breaking

2022-08-04 12:33 UTC, LKreutzer requested changes
Will continue to review at a later point.

2022-08-04 12:33 UTC, LKreutzer commented on bazel/scripts/run_integ_tests.sh
> +NORMAL='\033[0m'
Here `NORMAL` is the same as `NO_COLOR`. Perhaps we could just rename this to `NO_FORMATTING` and then we only need it once?

2022-08-04 12:33 UTC, LKreutzer commented on lte/gateway/python/integ_tests/s1aptests/BUILD.bazel
> +
All non-sanity tests from the `defs.mk` are covered. :+1:

2022-08-04 12:33 UTC, LKreutzer commented on lte/gateway/python/integ_tests/s1aptests/BUILD.bazel
> +    size = "medium",  # is it tho?
Can we remove the comment?

2022-08-04 12:41 UTC, vktng commented on lte/gateway/python/integ_tests/s1aptests/BUILD.bazel
> +    size = "medium",  # is it tho?
Yes, I forgot to remove it.

2022-08-04 12:42 UTC, vktng commented on bazel/scripts/run_integ_tests.sh
> +NORMAL='\033[0m'
Sure.

2022-08-05 13:39 UTC, LKreutzer reviewed
Manual test run results:
```
SUMMARY: 43/56 tests were successful.
  //lte/gateway/python/integ_tests/s1aptests:test_s1_handover_cancel: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_s1_handover_failure: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_ics_drop_with_mme_restart: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_no_auth_response_with_mme_restart: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_secondary_pdn_with_dedicated_bearer_multiple_services_restart: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_standalone_pdn_conn_req_with_apn_correction: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_s1_handover_ping_pong: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_esm_info_timerexpiration_max_retries: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_mme_restart_detach_multi_ue: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_no_identity_rsp_with_mme_restart: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_esm_info_with_apn_correction: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_ipv4v6_secondary_pdn_with_ded_bearer: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_ics_failure_with_mme_restart: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_paging_request: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_with_corrupt_stateless_mme: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_ipv6_secondary_pdn_rs_retransmit: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_s1_handover_timer_expiry: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_send_error_ind_for_erab_setup_req: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_paging_with_mme_restart: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_non_nat_dp_ul_tcp: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_enb_partial_reset_multi_ue_with_mme_restart: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_multi_enb_paging_request: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_concurrent_secondary_pdns: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_esm_information_timerexpiration: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_activate_deactivate_multiple_dedicated: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_3495_timer_for_default_bearer_with_mme_restart: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_no_smc_with_mme_restart_reattach: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_no_auth_resp_with_mme_restart_reattach: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_rar_activation_reject: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_send_error_ind_for_dl_nas_with_auth_req: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_ipv4v6_secondary_pdn_with_ded_bearer_multi_ue: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_no_esm_information_rsp_with_mme_restart: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_ipv4v6_secondary_pdn: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_service_without_mac: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_ipv4v6_secondary_pdn_multi_ue: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_ipv4v6_secondary_pdn_rs_retransmit: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_outoforder_erab_setup_rsp_dedicated_bearer: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_complete_after_ics_timer_expiry: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_3495_timer_for_dedicated_bearer_with_mme_restart: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_ipv6: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_continuous_random_attach: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_sctp_shutdown_while_mme_is_stopped: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_and_mme_restart_loop_detach_and_mme_restart_loop_multi_ue: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_concurrent_secondary_pdn_reject: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_inactive_tau_with_combined_tala_update_reattach: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_ipv4v6_secondary_pdn_spgw_initiated_ded_bearer: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_auth_mac_failure: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_multi_enb_multi_ue_diff_tac: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_active_tau_with_combined_tala_update_reattach: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_agw_offload_idle_active_ue: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_enb_partial_reset_with_unknown_ue_s1ap_ids: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_no_attach_complete_with_mme_restart: FAILED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_with_ipv6_pcscf_and_dns_addr: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_ipv6_secondary_pdn_with_ded_bearer: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_enb_partial_reset_multi_ue: PASSED
  //lte/gateway/python/integ_tests/s1aptests:test_attach_detach_with_pco_ipcp: PASSED
```

2022-08-05 14:58 UTC, LKreutzer reviewed
I am seeing some passes in the second run. I still think it would be really useful to have an option to rerun failing tests with a default of two reruns (i.e. 3 runs overall if two are failing).

2022-08-05 15:09 UTC, vktng commented
> I am seeing some passes in the second run. I still think it would be really useful to have an option to rerun failing tests with a default of two reruns (i.e. 3 runs overall if two are failing).

I can add the functionality if it is really warranted and while I am at it I can add the option to specify multiple targets, but shouldn't this be in a separate PR then? There are a lot of changes here already.

2022-08-05 15:13 UTC, LKreutzer commented
> > I am seeing some passes in the second run. I still think it would be really useful to have an option to rerun failing tests with a default of two reruns (i.e. 3 runs overall if two are failing).
> 
> I can add the functionality if it is really warranted and while I am at it I can add the option to specify multiple targets, but shouldn't this be in a separate PR then? There are a lot of changes here already.

Please create a follow up issue so we don't lose track and can discuss it later.

2022-08-05 15:27 UTC, LKreutzer commented
Passed after rerun:
```
//lte/gateway/python/integ_tests/s1aptests:test_s1_handover_cancel: PASSED
//lte/gateway/python/integ_tests/s1aptests:test_attach_detach_non_nat_dp_ul_tcp: PASSED
//lte/gateway/python/integ_tests/s1aptests:test_no_smc_with_mme_restart_reattach: PASSED
//lte/gateway/python/integ_tests/s1aptests:test_attach_service_without_mac: PASSED
//lte/gateway/python/integ_tests/s1aptests:test_outoforder_erab_setup_rsp_dedicated_bearer: PASSED
```

Failed after rerun:
```
//lte/gateway/python/integ_tests/s1aptests:test_attach_mme_restart_detach_multi_ue: FAILED
//lte/gateway/python/integ_tests/s1aptests:test_paging_with_mme_restart: FAILED
//lte/gateway/python/integ_tests/s1aptests:test_activate_deactivate_multiple_dedicated: FAILED
//lte/gateway/python/integ_tests/s1aptests:test_sctp_shutdown_while_mme_is_stopped: FAILED
//lte/gateway/python/integ_tests/s1aptests:test_concurrent_secondary_pdn_reject: FAILED
//lte/gateway/python/integ_tests/s1aptests:test_attach_inactive_tau_with_combined_tala_update_reattach: FAILED
//lte/gateway/python/integ_tests/s1aptests:test_3495_timer_for_dedicated_bearer_with_mme_restart: FAILED
//lte/gateway/python/integ_tests/s1aptests:test_no_attach_complete_with_mme_restart: FAILED
```

2022-08-08 14:36 UTC, nstng approved these changes
lgtm - tested vs bazel magma.deb file
three tests are failing too - also in make (this is OK for now as the tests are not running in CI)

2022-08-08 15:37 UTC, LKreutzer approved these changes

2022-08-08 15:37 UTC, merged