fix(agw): Migrate hash list of state_ue to protobuf_map
magma/magma pull request #13508
Opened 2022-08-04 13:47 UTC by rsarwad

## Summary
Modified code to replace hashtable with protobuf map for state_ue hash table in s1ap module
The PR partially addresses the issue, https://github.com/magma/magma/issues/11190
## Test Plan
Executed s1ap sanity test suite and unit test case.
Verified manually with test_attact_detach_with_mme_restart.py test case, to check whether contents of map, state ue map is correctly formed after mme recovery

2022-08-08 06:26 UTC, pruthvihebbani requested changes

2022-08-08 06:26 UTC, pruthvihebbani commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
> +    auto* ue_context = new ue_description_t();
Add NULL check for ue_context

2022-08-08 06:26 UTC, pruthvihebbani commented on lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_converter.cpp
> +  ue_description_t* final_ue = new ue_description_t();
Add NULL check

2022-08-22 09:48 UTC, pruthvihebbani commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
> +  map_uint64_ue_description_t* s1ap_ue_state = get_s1ap_ue_state();
Add NULL check for s1ap_ue_state

2022-08-22 09:54 UTC, pruthvihebbani requested changes

2022-08-22 09:54 UTC, pruthvihebbani commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
> +  map_uint64_ue_description_t* s1ap_ue_state = get_s1ap_ue_state();
Add NULL check

2022-08-22 09:54 UTC, pruthvihebbani commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
> +  map_uint64_ue_description_t* s1ap_ue_state = get_s1ap_ue_state();
General comment: Add NULL check for s1ap_ue_state after get_s1ap_ue_state()

2022-08-23 04:43 UTC, pruthvihebbani approved these changes
LGTM

2022-09-01 14:00 UTC, ajahl commented on lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_converter.cpp
> +  EXPECT_TRUE(ue != nullptr);
I think, the nullptr check here is not required when using `new ...` since C++ returns an instance or throws a std::bad_alloc exception.

2022-09-02 04:09 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
> +  if (magma::PROTO_MAP_OK != rc) {
```suggestion
  if (rc != magma::PROTO_MAP_OK) {
```

2022-09-02 04:09 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
> +    if (PROTO_MAP_OK != rc) {
```suggestion
    if (rc != PROTO_MAP_OK) {
```

2022-09-02 04:09 UTC, ssanadhya commented on lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.cpp
> +    if (magma::PROTO_MAP_OK != rc) {
```suggestion
    if (rc != magma::PROTO_MAP_OK) {
```

2022-09-02 04:56 UTC, ssanadhya approved these changes
Lgtm, please address the nit comments

2022-09-02 07:32 UTC, merged