fix(mme): Add libsqlite3 dependency in containers for OAI pipeline
magma/magma pull request #13575
Opened 2022-08-11 03:57 UTC by ssanadhya

Signed-off-by: Shruti Sanadhya <ssanadhya@fb.com>

## Summary

The changes in PR https://github.com/magma/magma/pull/13470 require libsqlite to be present on all dev containers. This PR adds the changes in https://github.com/magma/magma/pull/13470#issuecomment-1209363734 to make it work on Magma-OAI-Jenkins CI pipeline.

## Test Plan

N/A

2022-08-11 16:45 UTC, ssanadhya commented
@rdefosse , can you help me understand why this PR is failing on Magma-OAI-Jenkins pipeline? The [logs](https://jenkins-oai.eurecom.fr/job/MAGMA-MME-production/17571/artifact/build_results_magma_oai_mme.html) only show warnings, no errors.

2022-08-15 14:35 UTC, nstng commented
> @rdefosse , can you help me understand why this PR is failing on Magma-OAI-Jenkins pipeline? The [logs](https://jenkins-oai.eurecom.fr/job/MAGMA-MME-production/17571/artifact/build_results_magma_oai_mme.html) only show warnings, no errors.

for me `apt list libsqlite3x` has no candidates on ubuntu 20.04

2022-08-16 06:30 UTC, sebathomas commented
Maybe it should be this package in Ubuntu Focal?
https://packages.ubuntu.com/focal/libsqlite3-0

2022-08-16 07:12 UTC, rdefosse requested changes

2022-08-16 07:12 UTC, rdefosse commented on ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
> +      libsqlite3x \
@ssanadhya 

Sorry. It should be `libsqlite3-0`.

2022-08-16 07:12 UTC, rdefosse commented on ci-scripts/docker/Dockerfile.mme.ci.rhel8
> +      libsqlite3x \
@ssanadhya 

Sorry, it should be just `sqlite`

2022-08-16 07:12 UTC, rdefosse commented on lte/gateway/docker/mme/Dockerfile.rhel8
> +    libsqlite3x \
Sorry. It should be `sqlite`

2022-08-16 07:12 UTC, rdefosse commented on lte/gateway/docker/mme/Dockerfile.rhel8
> +    libsqlite3x-devel \
and `sqlite-devel`

2022-08-16 07:12 UTC, rdefosse commented on lte/gateway/docker/mme/Dockerfile.rhel8
> +      libsqlite3x \
And here just `sqlite`

2022-08-16 22:03 UTC, ssanadhya commented
Thanks for the review @rdefosse ! I have revised the PR and all required CI checks are green now. Could you please approve and merge this?

2022-08-17 07:14 UTC, rdefosse approved these changes

2022-08-17 07:14 UTC, merged