chore(ci): Mitigate Vagrant cloud rate limiting errors by logging in
magma/magma pull request #13734
Opened 2022-08-25 13:05 UTC by LKreutzer

Co-authored-by: Lars Kreutzer lars.kreutzer@tngtech.com
Co-authored-by: Krisztián Varga krisztian.varga@tngtech.com

Signed-off-by: Lars Kreutzer <lars.kreutzer@tngtech.com>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2022-08-25 15:44 UTC, nstng requested changes
making sure this is not merged before secret is on magma

2022-08-29 08:38 UTC, nstng commented
from discussion: please check behavior on forks if secret is not present

2022-08-29 11:16 UTC, LKreutzer commented
> from discussion: please check behavior on forks if secret is not present
@nstng added if conditional to check that the secret exists (tested the conditional in dummy workflow).

2022-08-30 05:49 UTC, nstng approved these changes

2022-08-30 05:50 UTC, merged