fix(agw): Fixed compilation error on inclusion of proto_map.h file
magma/magma pull request #13764
Opened 2022-08-29 09:11 UTC by rsarwad

## Summary
fix(agw): Fixed compilation error on inclusion of proto_map.h file  and removed unused file, sgw.h and unused structure, predefined_pcc_rules 

## Test Plan
Executed s1ap sanity test suite and unit test cases

2022-08-31 15:56 UTC, ajahl approved these changes

2022-09-01 04:39 UTC, ssanadhya requested changes
Please review the order of includes in [style guide]((https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2022-09-01 04:39 UTC, ssanadhya commented on lte/gateway/c/core/oai/test/spgw_task/spgw_procedures_test_fixture.cpp
> +#include "lte/gateway/c/core/oai/tasks/sgw/sgw_defs.hpp"
This should be outside `extern "C"` block

2022-09-01 04:39 UTC, ssanadhya commented on lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
> +#include "lte/gateway/c/core/oai/include/sgw_context_manager.hpp"
Move this after the `extern "C"` block as per [style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2022-09-01 04:39 UTC, ssanadhya commented on lte/gateway/c/core/oai/include/sgw_context_manager.hpp
> +#include "lte/gateway/c/core/oai/include/spgw_state.hpp"
This should be after the `extern "C"` block as per the [style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2022-09-01 04:39 UTC, ssanadhya commented on lte/gateway/c/core/oai/include/sgw_s8_state.hpp
> +#include "lte/gateway/c/core/oai/include/spgw_types.hpp"
This should be after the `extern "C"` block as per the [style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2022-09-01 04:39 UTC, ssanadhya commented on lte/gateway/c/core/oai/include/spgw_state.hpp
> +#include "lte/gateway/c/core/oai/include/spgw_types.hpp"
This should be after the `extern "C"` block as per the [style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2022-09-01 04:39 UTC, ssanadhya commented on lte/gateway/c/core/oai/include/spgw_types.hpp
>  #define FILE_SPGW_TYPES_SEEN
Please replace with `#pragma once`

2022-09-01 04:39 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.hpp
> +#include "lte/gateway/c/core/oai/include/spgw_state.hpp"
This should be after the C headers as per the [style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2022-09-01 04:39 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
> +
This should be after the `extern "C"` block as per the [style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2022-09-03 05:49 UTC, ssanadhya approved these changes
Lgtm

2022-09-03 05:52 UTC, ssanadhya commented
@rsarwad , could you please resolve CI failures on this PR?

2022-09-05 04:22 UTC, rsarwad commented
Hi @ssanadhya, the signoffing of an commit was missing on intermediate commit. Fixing it lead to some other errors. So closing this PR and raised new PR, https://github.com/magma/magma/pull/13833

2022-09-05 04:22 UTC, closed without merging