fix(cwf): the ovs python dependency should be 'python3-openvswitch'
magma/magma pull request #13810
Opened 2022-09-02 06:57 UTC by maxhbr

2022-09-02 07:02 UTC, sebathomas approved these changes

2022-09-02 08:05 UTC, crasu reviewed
CWAG Integ test execution is missing

2022-09-02 08:30 UTC, maxhbr commented
The tests are running on https://github.com/maxhbr/magma/actions/runs/2977683059

2022-09-02 08:35 UTC, sebathomas commented
CWAG changes need the tag "cwg" in the title (commit and/or PR), not "cwf", that's why the CI is red.

(I think this happens in almost every related PR, cwf would be more intuitive.)

2022-09-08 14:48 UTC, sebathomas commented
What about this PR? As far as I know, uploading the Python 2 package to artifactory fixed the issues on v1.8 but it's still unclear to me why we need that package, and if anything should be done here.

2022-09-08 17:30 UTC, maxhbr commented
Independent of the releasing issue, this is a good change that harmonizes dependencies

2022-09-08 20:36 UTC, crasu approved these changes

2022-09-09 06:33 UTC, sebathomas commented
It did seem to break pipelined in the integ test run above:
https://github.com/maxhbr/magma/actions/runs/2977683059

2022-09-09 08:10 UTC, crasu commented
> It did seem to break pipelined in the integ test run above: https://github.com/maxhbr/magma/actions/runs/2977683059

Good catch we should fix this first.

2022-09-09 08:11 UTC, crasu requested changes
Ci needs to be fixed first

2022-09-12 03:05 UTC, MoritzThomasHuebner commented on cwf/gateway/deploy/roles/ovs/tasks/debian.yml
> +       - python3-openvswitch
In line 40 above it states version "2.12.0", however, the logs in the integ tests indicate we are now using "2.15.4-9". "2.12.0" is the version of the _old_ `python-openvswitch`

2022-09-12 04:12 UTC, MoritzThomasHuebner commented
I started the `cwf` machine using this PR to see why the tests have been failing. Apparently, this is because the `ocs2` and `pcrf2` services are constantly restarting.

```
vagrant@cwag-dev:~$ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS                          PORTS     NAMES
76bc4b763185   cwf_gateway_sessiond:latest    "sh -c 'mkdir -p /va…"   13 minutes ago   Up 13 minutes (unhealthy)                 sessiond
07ae30a9ec64   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes                             swx_proxy
8e88c7535c8f   cwf_gateway_pipelined:latest   "python3.8 -m magma.…"   13 minutes ago   Up 13 minutes (healthy)                   policydb
19d2b143010e   cwf_gateway_python:latest      "python3.8 -m magma.…"   13 minutes ago   Up 13 minutes                             state
2ab6f92b9e89   cwf_gateway_python:latest      "python3.8 -m magma.…"   13 minutes ago   Up 13 minutes (healthy)                   directoryd
382add07dd2e   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes                             session_proxy
3e25421a2c5f   cwf_gateway_pipelined:latest   "python3.8 -m magma.…"   13 minutes ago   Up 13 minutes                             monitord
11aaaedc8696   cwf_gateway_python:latest      "python3.8 -m magma.…"   13 minutes ago   Up 13 minutes                             magmad
f3a1021f9ee8   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes                             hss
1cb732d11843   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes                             ocs
c82b08b89884   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Restarting (1) 14 seconds ago             ocs2
7441c0be605a   cwf_gateway_python:latest      "python3.8 -m magma.…"   13 minutes ago   Up 13 minutes                             eventd
2b0f19c30c91   cwf_cwag_go:latest             "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes                             uesim
af2f810fd140   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Restarting (1) 14 seconds ago             pcrf2
8e2dadc361ce   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes (healthy)                   aaa_server
346560ce5c5b   cwf_gateway_python:latest      "/bin/bash -c '/usr/…"   13 minutes ago   Up 13 minutes                             redis
90dc32fcc8b6   cwf_gateway_go:latest          "/bin/bash -c 'envsu…"   13 minutes ago   Up 13 minutes (healthy)                   radius
c0a63b17cb23   cwf_gateway_python:latest      "/bin/bash -c '/usr/…"   13 minutes ago   Up 13 minutes                             td-agent-bit
304bc2f644f5   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes (healthy)                   eap_sim
5ae58e911790   cwf_gateway_pipelined:latest   "sh -c '/usr/bin/ovs…"   13 minutes ago   Up 13 minutes (healthy)                   pipelined
5e3052d9ea9e   cwf_gateway_python:latest      "sh -c '/usr/local/b…"   13 minutes ago   Up 13 minutes                             control_proxy
2bb7ced1135c   cwf_gateway_pipelined:latest   "python3.8 -m magma.…"   13 minutes ago   Up 13 minutes                             redirectd
f77c19399fb9   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes                             pcrf
c7dfc01a124f   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes                             radiusd
bf2b7b2f29cf   cwf_cwag_go:latest             "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes                             health
c9ec5df2601b   cwf_nginx:latest               "/docker-entrypoint.…"   13 minutes ago   Up 13 minutes                             ingress
45091807cd79   cwf_gateway_go:latest          "envdir /var/opt/mag…"   13 minutes ago   Up 13 minutes (healthy)                   eap_aka
```

```
vagrant@cwag-dev:~$ docker logs ocs2
I0912 03:56:57.276685       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/service_registry.yml'
I0912 03:56:57.277874       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/service_registry.yml'
2022/09/12 03:56:57 ------ Reading Gy configuration a couple of times ------
I0912 03:56:57.573421       1 service_config.go:110] Successfully loaded structured '::magmad' service configs from '/etc/magma/magmad.yml'
2022/09/12 03:56:57 Invalid Gy Server Retry Count for server (127.0.0.1:50001): 0, must be >0. Will be set to 1
2022/09/12 03:56:57 Invalid Gy Retransmit Count for server (127.0.0.1:50001): 0, must be >0. Will be set to 1
2022/09/12 03:56:57 ServerIndex value (1) is bigger than the amount Gy servers configured (1)
I0912 03:56:58.027220       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/service_registry.yml'
I0912 03:56:58.045410       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/service_registry.yml'
2022/09/12 03:56:58 ------ Reading Gy configuration a couple of times ------
I0912 03:56:58.248137       1 service_config.go:110] Successfully loaded structured '::magmad' service configs from '/etc/magma/magmad.yml'
2022/09/12 03:56:58 Invalid Gy Server Retry Count for server (127.0.0.1:50001): 0, must be >0. Will be set to 1
2022/09/12 03:56:58 Invalid Gy Retransmit Count for server (127.0.0.1:50001): 0, must be >0. Will be set to 1
2022/09/12 03:56:58 ServerIndex value (1) is bigger than the amount Gy servers configured (1)
I0912 03:56:58.694791       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/service_registry.yml'
I0912 03:56:58.695237       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/service_registry.yml'
2022/09/12 03:56:58 ------ Reading Gy configuration a couple of times ------
(...)
```

```
vagrant@cwag-dev:~$ docker logs pcrf2
I0912 03:56:57.458992       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/service_registry.yml'
I0912 03:56:57.461885       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/service_registry.yml'
2022/09/12 03:56:57 ------ Reading Gx configuration a couple of times ------
I0912 03:56:57.645577       1 service_config.go:110] Successfully loaded structured '::magmad' service configs from '/etc/magma/magmad.yml'
2022/09/12 03:56:57 Invalid Gx Server Retry Count for server (127.0.0.1:50003): 0, must be >0. Will be set to 1
2022/09/12 03:56:57 Invalid Gx Retransmit Count for server (127.0.0.1:50003): 0, must be >0. Will be set to 1
2022/09/12 03:56:57 ServerIndex value (1) is bigger than the amount Gx servers configured (1)
I0912 03:56:58.173112       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/service_registry.yml'
I0912 03:56:58.180833       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/service_registry.yml'
2022/09/12 03:56:58 ------ Reading Gx configuration a couple of times ------
I0912 03:56:58.293223       1 service_config.go:110] Successfully loaded structured '::magmad' service configs from '/etc/magma/magmad.yml'
2022/09/12 03:56:58 Invalid Gx Server Retry Count for server (127.0.0.1:50003): 0, must be >0. Will be set to 1
2022/09/12 03:56:58 Invalid Gx Retransmit Count for server (127.0.0.1:50003): 0, must be >0. Will be set to 1
2022/09/12 03:56:58 ServerIndex value (1) is bigger than the amount Gx servers configured (1)
I0912 03:56:58.722888       1 service_config.go:161] Successfully loaded '::service_registry' service configs from '/etc/magma/ser [...]

2022-09-26 08:28 UTC, maxhbr commented
This change has not sufficient impact to be worth to be continued. Maybe some one else will clean up this inconsistency at some point.

2022-09-26 08:28 UTC, closed without merging