[DOC]:Upgrading magma version to 1.8.0
magma/magma pull request #13869
Opened 2022-09-07 19:50 UTC by tmdzk

Signed-off-by: tmdzk <timodzik@gmail.com>

Upgrading magma version to 1.8.0

## Summary

In documentation we're referencing a lot of times the version (that is unfortunately hardcoded) every time we get a new version we have to bump those

In the future we HAVE to create an .env file at the root of magma/ with handy variables like $STABLE_VERSION, or have CI do the changes for us

## Test Plan

Make sure doc is not broken 

## Additional Information

2022-09-07 19:51 UTC, tmdzk commented
@ShubhamTatvamasi I need you for the latest helm/docker ids. Please do not merge this until we changed the helm charts vers AND we have a release candidate

2022-09-08 09:25 UTC, voisey requested changes

2022-09-08 09:25 UTC, voisey commented on docs/readmes/howtos/5g_nsa_support.md
> +The E-RAB Modification Indication and E-RAB Modification Confirmation messages were added to the MAGMA code-base in v1.8. Functioning of these messages are explained as below:
This looks like something that should be kept to v1.5.

2022-09-08 09:25 UTC, voisey commented on docs/readmes/lte/build_install_magma_pkg_in_agw.md
> +    You will need only the ones that say `magma_1.1.XXX` and `magma-sctpd_1.1.XXX` (for v1.8 versions)
The package names here are still specific to 1.1.

2022-09-08 09:25 UTC, voisey commented on docs/readmes/lte/deploy_install.md
> +> NOTE: Debian-based AGW deployments are no longer supported as of v1.8. If you want to install to Debian, refer to [v1.5 of the documentation](https://magma.github.io/magma/versions).
This looks like it should be kept as v1.6.

2022-09-08 11:04 UTC, jheidbrink commented on docs/readmes/basics/prerequisites.md
> +git checkout v1.8
I think this doesn't need updating.

2022-09-08 11:07 UTC, jheidbrink commented on docs/readmes/basics/prerequisites.md
> +git checkout v1.8
Then again, doesn't hurt probably, nevermind.

2022-09-22 07:28 UTC, voisey requested changes
To get the semantic PR title check to pass, can you please change the title of the PR from "[DOC]:" to "docs:"?

2022-09-22 07:28 UTC, voisey commented on docs/readmes/orc8r/deploy_intro.md
>  Verified with Terraform version `1.0.11`.
Looks like a merge conflict was pushed

2022-09-22 20:18 UTC, tmdzk commented
> docs/readmes/orc8r/deploy_intro.md

that's so so weird it's not showing up locally

2022-09-23 06:53 UTC, voisey approved these changes
The changes look good, but note that you still need to change the PR prefix.

2022-10-04 12:10 UTC, voisey commented
Hi @tmdzk, what's the status here?

2022-10-04 12:25 UTC, merged