feat(agw): Basic eDRX support
magma/magma pull request #13961
Opened 2022-09-19 21:40 UTC by gjalves

Signed-off-by: Gustavo Junior Alves <gustavo@radtonics.com>

## Summary

Support for eDRX protocol parsing.

Some devices cannot attach to OAI, like CPE Intelbras ICW 4002, because of missing support for eDRX. This patch implements enough features to allow the connection.

## Test Plan

A device using eDRX got the error `EMMAS-SAP - Sending Attach Reject for ue_id = 834, emm_cause = (99)`  and abort. This fix allow the successful connection

2022-09-21 04:47 UTC, ssanadhya requested changes, later dismissed

2022-09-21 04:47 UTC, ssanadhya commented on lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008.h
> +int encode_edrx_parameter_ie(edrx_parameter_t* edrxparameter,
This function is declared but never defined. Could you please add a definition for this too?

2023-09-22 14:48 UTC, Akshayp77 commented
Hi @gjalves, changes looks good, can you rebase it.

2023-09-25 02:19 UTC, panyogesh approved these changes
LGTM

2023-09-25 02:29 UTC, panyogesh commented
@ssanadhya : Can you please review and approve the PR. Its waiting for the approval.

2025-03-14 18:20 UTC, jordanvrtanoski approved these changes

2025-03-14 19:34 UTC, merged