Integ tests magma deb for specific magma package
magma/magma pull request #13983
Opened 2022-09-21 14:21 UTC by ajahl

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2022-09-26 14:55 UTC, tmdzk requested changes
You'll have to add the var to: https://github.com/magma/magma/blob/master/lte/gateway/deploy/agw_install_ubuntu.sh#L199 too or setup a default one

2022-09-28 08:57 UTC, voisey commented on .github/workflows/build_all.yml
> +    needs:
Could you put this onto one line, i.e. `needs: agw-build`, please?

2022-09-28 09:10 UTC, ajahl commented
> You'll have to add the var to: https://github.com/magma/magma/blob/master/lte/gateway/deploy/agw_install_ubuntu.sh#L199 too or setup a default one

We set a default.

2022-09-28 15:24 UTC, sebathomas approved these changes

2022-09-28 17:22 UTC, nstng approved these changes

2022-09-29 08:23 UTC, tmdzk approved these changes

2022-09-29 08:24 UTC, merged