Fix gateways statuses #1158
magma/magma pull request #1398
Opened 2020-03-30 12:31 UTC by vladiskuz

Show green circle for gateway when the enodeB is connected and MME is
connected.
Show yellow circle when RF transmit is disabled, if the enodeB is
disconnected or if the MME is disconnected - this indicates a fault with
the radio configuration which will not impact the site (since transmit
is disabled)
Show gray circle  when backhaul is down.
Show red circle in any other scenario when RF is enabled.

2020-03-30 19:00 UTC, xjtian requested changes

2020-03-30 19:00 UTC, xjtian commented on symphony/app/fbcnms-projects/magmalte/app/components/GatewaySummaryFields.js
> +            isActive={gateway.gpsConnected}
You should revert this line - the conditional is legit, the problem with this icon is actually where we're getting the data from to determine if GPS is connected.

We've started on a big redesign of the NMS which fixing this will roll into

2020-03-30 19:00 UTC, xjtian commented on symphony/app/fbcnms-projects/magmalte/app/components/Gateways.js
> +              !gateway.mmeConnected
this conditional should be !(TX enabled) && (!mme connected || !tx on) - yellow should only show up for sites that aren't configured to transmit

2020-04-02 02:42 UTC, xjtian approved these changes

2020-07-25 00:10 UTC, 119Vik commented
Can one of the admins verify this patch?

2021-01-07 01:20 UTC, karthiksubraveti commented
@vladiskuz code has changed quite a bit, I believe we already show green circle for enodeb Status, 
<img width="1660" alt="Screen Shot 2021-01-06 at 5 20 17 PM" src="https://user-images.githubusercontent.com/8224854/103839088-74f24f00-5043-11eb-947e-b4f0bc49648f.png">

Is there something missing that this PR addresses. Thanks.

2021-01-13 10:30 UTC, vladiskuz commented
@karthiksubraveti yes, obviously the code base has changed. I proposed my PR more then half year ago and nobody review it.

2021-01-30 17:07 UTC, amarpad commented
Thanks for the pull request and sorry for the delayed review, we moved to a new NMS, so will close out the request

2021-01-30 17:07 UTC, closed without merging