fix(orc8r): Updated helm to show orc8r version on NMS dashboard.
magma/magma pull request #14056
Opened 2022-09-30 14:55 UTC by tapasmishra

## Summary

Fixes #13902 

## Test Plan

Deploy the orc8r using the fixed helm and you should be able to see the version. 

## Additional Information

- [ ] This change is backwards-breaking

2022-09-30 14:58 UTC, ShubhamTatvamasi approved these changes

2022-10-24 09:51 UTC, voisey commented
What's the status here? It looks like a rebase might be needed to get the CI to run.

2023-02-20 10:23 UTC, voisey commented
Hey @tapasmishra, could you please rebase this and then set the "ready2merge" label if you think it's good to go?

2023-06-16 08:47 UTC, maxhbr commented
> Hey @tapasmishra, could you please rebase this and then set the "ready2merge" label if you think it's good to go?

Hey @tapasmishra, you never set "ready2merge" here, still not good to go?

2023-06-20 09:53 UTC, maxhbr requested changes

2023-06-20 09:53 UTC, maxhbr commented on .github/workflows/build_all.yml
> +    secrets: inherit
this adds an independent fix to some completely unrelated PR. The title does not even mention this. Please keep such stuff separated.

2024-06-03 11:16 UTC, closed without merging