fix(ci): fix test interdependency in test attach detach rar tcp data
magma/magma pull request #14230
Opened 2022-10-20 13:23 UTC by crasu

## Summary

* Fix for test_attach_detach_rar_tcp_data.
* Removed for loop

You probably want to review each commit in this pr separately.

## Test Plan

- [x] Ran the testcase (test_attach_detach_rar_tcp_data)
- [x] [Ran the integ test suite in ci ](https://github.com/crasu/magma/actions/runs/3289965904)

## Additional Information

Before the change the test was expecting an already existing gtp port g_8d3ca8c0. This port is usally created by other tests and only deleted during cleanup of a failed test. This caused the flaky retry for this test to always fail since after a cleanup the g_8d3ca8c0 would never exists.

As the g_8d3ca8c0 port is setup during flow creation, we now determine the port number after the flows has been created.

2022-10-20 13:23 UTC, crasu commented
Blocked until Integ run is completed.

2022-10-20 13:57 UTC, mpfirrmann requested changes
The loop is not really removed. Line 53 with `num_ues=1`.

2022-10-20 14:13 UTC, crasu commented
> The loop is not really removed. Line 53 with `num_ues=1`.

Sry failed rebase

2022-10-20 15:04 UTC, mpfirrmann approved these changes

2022-10-20 17:50 UTC, koolzz approved these changes
LGTM,
The loop change part is just style refactor doesn't actually fix the testcase. In these situations, I recommend putting that as a separate PR next time. Easier to review and easier to merge

2022-10-21 11:48 UTC, crasu commented
Integ run failed with test_3485_timer_for_default_bearer_with_mme_restart failing. But there is a [seperate](https://github.com/magma/magma/pull/14177) issue to fix this test.

2022-10-21 12:22 UTC, merged