fix(agw): Converted sgs task files to cpp
magma/magma pull request #14339
Opened 2022-11-02 05:11 UTC by VinashakAnkitAman

## Title
fix(agw): Converted sgs task files to cpp [Extension to Github Issue: #13096]

## Summary
Migrated all the files related to ha task in the folders `magma/lte/gateway/c/core/oai/tasks/sgs/` and `magma/lte/gateway/c/core/oai/include/` to `cpp/hpp` and fixed all the compilation errors and warnings.

## Test plan
Verified compilation with following:
make build_oai;
make test_oai;
bazel build --config=production //lte/gateway/c/core:agw_of
export FEATURES=mme_oai; make build_oai

Verified with sanity and in CI

Signed-off-by: VinashakAnkitAman <ankit.aman@radisys.com>

2022-11-02 08:47 UTC, LKreutzer requested changes
The CI is failing with 

```
ERROR: /workspaces/magma/lte/gateway/c/core/oai/test/amf/BUILD.bazel:100:8: Linking lte/gateway/c/core/oai/test/amf/amf_encode_decode_test failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-fastbuild/bin/lte/gateway/c/core/oai/test/amf/amf_encode_decode_test-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld.lld: error: bazel-out/k8-fastbuild/bin/_solib_k8/liblte_Sgateway_Sc_Score_Sliblib_Uagw_Uof.so: undefined reference to display_backtrace()
ld.lld: error: bazel-out/k8-fastbuild/bin/_solib_k8/liblte_Sgateway_Sc_Score_Sliblib_Uagw_Uof.so: undefined reference to log_message(log_thread_ctxt_s*, log_level_t, log_proto_t, char const*, unsigned int, char const*, ...)
collect2: error: ld returned 1 exit status
```
There are likely some extern C statements missing.

2022-11-02 14:04 UTC, ajahl commented on lte/gateway/c/core/oai/oai_mme/oai_mme.c
>  #include "lte/gateway/c/core/oai/oai_mme/oai_mme.h"
The own header should be on top.

2022-11-02 14:04 UTC, ajahl commented on lte/gateway/c/core/oai/tasks/grpc_service/CSFBGatewayServiceImpl.cpp
>  #include "lte/gateway/c/core/oai/tasks/grpc_service/CSFBGatewayServiceImpl.hpp"
The own header should be on top.

2022-11-02 14:04 UTC, ajahl commented on lte/gateway/c/core/oai/tasks/grpc_service/SMSOrc8rGatewayServiceImpl.cpp
>  #include "lte/gateway/c/core/oai/tasks/grpc_service/SMSOrc8rGatewayServiceImpl.hpp"
The own header should be on top.

2022-11-02 14:04 UTC, ajahl commented on lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
>  #include "lte/gateway/c/core/oai/lib/3gpp/3gpp_23.003.h"
Can you move `#include "lte/gateway/c/core/oai/lib/3gpp/3gpp_29.274.h"` from line 29 to the right position.

2022-11-02 14:04 UTC, ajahl commented on lte/gateway/c/core/oai/tasks/nas/nas_proc.cpp
>  #include "lte/gateway/c/core/oai/tasks/nas/api/mme/mme_api.hpp"
The own header #include `"lte/gateway/c/core/oai/tasks/nas/nas_proc.hpp"` (line 66) should be on top.

2022-11-02 14:04 UTC, ajahl commented on lte/gateway/c/core/oai/tasks/nas/nas_proc.cpp
> +#include "lte/gateway/c/core/oai/include/sgs_messages_types.hpp"
Line 53 can be removed. There is no need to include headers in the implementation file when they already exist in the corresponding header file. There are more includes in this file that are already contained in the header file.

2022-11-07 05:06 UTC, rsarwad commented on lte/gateway/c/core/oai/tasks/nas/api/mme/mme_api.hpp
> +#endif
This fun() need not be under extern C as it's definition and callee are in cpp files

2022-11-07 05:11 UTC, rsarwad commented on lte/gateway/c/core/oai/lib/sms_orc8r_client/sms_orc8r_client_api.hpp
>  void send_smo_uplink_unitdata(const itti_sgsap_uplink_unitdata_t* msg);
This fun() need not be under extern C

2022-11-07 05:11 UTC, rsarwad commented on lte/gateway/c/core/oai/tasks/grpc_service/CSFBGatewayServiceImpl.cpp
>   */
Leave space above

2022-11-09 04:40 UTC, VinashakAnkitAman commented on lte/gateway/c/core/oai/lib/sms_orc8r_client/sms_orc8r_client_api.hpp
>  void send_smo_uplink_unitdata(const itti_sgsap_uplink_unitdata_t* msg);
This function is called from file `tasks/sms_orc8r/sms_orc8r_task.c` and this is why kept under extern c, otherwise throws undefined reference error.

2022-11-16 04:43 UTC, VinashakAnkitAman commented
> The CI is failing with
> 
> ```
> ERROR: /workspaces/magma/lte/gateway/c/core/oai/test/amf/BUILD.bazel:100:8: Linking lte/gateway/c/core/oai/test/amf/amf_encode_decode_test failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-fastbuild/bin/lte/gateway/c/core/oai/test/amf/amf_encode_decode_test-2.params
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
> ld.lld: error: bazel-out/k8-fastbuild/bin/_solib_k8/liblte_Sgateway_Sc_Score_Sliblib_Uagw_Uof.so: undefined reference to display_backtrace()
> ld.lld: error: bazel-out/k8-fastbuild/bin/_solib_k8/liblte_Sgateway_Sc_Score_Sliblib_Uagw_Uof.so: undefined reference to log_message(log_thread_ctxt_s*, log_level_t, log_proto_t, char const*, unsigned int, char const*, ...)
> collect2: error: ld returned 1 exit status
> ```
> 
> There are likely some extern C statements missing.

Hi @LKreutzer The CI checks are passing now. Can you please approve the PR.

2022-11-16 04:55 UTC, rsarwad approved these changes
LGTM

2022-11-16 07:23 UTC, LKreutzer approved these changes
Bazel changes lgtm!

2022-11-17 13:41 UTC, merged