fix(agw): Converted sctp task files to cpp
magma/magma pull request #14356
Opened 2022-11-04 04:50 UTC by VinashakAnkitAman

## Title
fix(agw): Converted sctp task files to cpp [Extension to Github Issue: #13096]

## Summary
Migrated all the files related to ha task in the folders `magma/lte/gateway/c/core/oai/tasks/sctp/` and `magma/lte/gateway/c/core/oai/include/` to `cpp/hpp` and fixed all the compilation errors and warnings.

## Test plan
Verified compilation with following:
make clean; make build_oai;
make clean; make test_oai;
make clean; make test_oai BUILD_TYPE=Debug OAI_TESTS=test_amf_app
make clean; bazel build --config=production //lte/gateway/c/core:agw_of
make clean; bazel test //lte/gateway/c/core/oai/test/amf:amf_stateless_test
make clean; export FEATURES=mme_oai; make build_oai

Verified with sanity and in CI

Signed-off-by: VinashakAnkitAman <ankit.aman@radisys.com>

2022-11-04 04:58 UTC, pruthvihebbani requested changes

2022-11-04 04:58 UTC, pruthvihebbani commented on lte/gateway/c/core/oai/tasks/sctp/sctp_itti_messaging.cpp
> +#include "lte/gateway/c/core/oai/tasks/sctp/sctp_itti_messaging.hpp"
Move this include to the top

2022-11-04 06:44 UTC, rsarwad approved these changes
LGTM

2022-11-04 06:55 UTC, nstng approved these changes
bazel changes lgtm!

2022-11-14 10:22 UTC, pruthvihebbani approved these changes
LGTM

2022-11-14 10:23 UTC, merged