fx(agw): Modified code in sgw_s8 task to port ue context hash table to protobuf map
magma/magma pull request #14406
Opened 2022-11-10 09:29 UTC by rsarwad

## Summary
fx(agw): Modified code in sgw_s8 task to port ue context hash table to protobuf map
Removed dependency of spgw task and sgw_s8 task on hash table
## Test Plan
Executed unit test cases and built with "make build_oai" and executed s1ap sanity test suite
We will not be able to verify inbound roaming feature in local setup.
## Additional Information
Needs to be tested federated integ_tests once PCRF is integrated

2022-11-10 10:05 UTC, pruthvihebbani requested changes

2022-11-10 10:05 UTC, pruthvihebbani commented on lte/gateway/c/core/oai/tasks/sgw/spgw_state.cpp
> +  free_cpp_wrapper((void**)ptr);
Please finx cpplint errors

2022-11-10 10:05 UTC, pruthvihebbani commented on lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.cpp
> +      new google::protobuf::Map<unsigned long int, struct spgw_ue_context_s*>();
Fix this error

2022-11-10 11:38 UTC, pruthvihebbani approved these changes
LGTM

2022-11-14 17:19 UTC, ajahl commented on lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.cpp
>  #ifdef __cplusplus
Please move this header https://github.com/magma/magma/blob/a49ee7522c670afb058d56023000e1c2c530435e/lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.cpp#L71 to the top of the include list

2022-11-14 17:19 UTC, ajahl commented on lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp
can you move https://github.com/magma/magma/blob/a49ee7522c670afb058d56023000e1c2c530435e/lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp#L15 to the top, please

2022-11-14 17:19 UTC, ajahl commented on lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp
>    spgw_ue_context_t* ue_context_p = NULL;
```cpp
spgw_ue_context_t* ue_context_p = nullptr;
```

2022-11-14 17:19 UTC, ajahl commented on lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp
please change
https://github.com/magma/magma/blob/a49ee7522c670afb058d56023000e1c2c530435e/lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp#L226
to
```cpp
sgw_s11_teid_t* s11_teid_p = nullptr;
```

2022-11-23 15:49 UTC, ajahl approved these changes

2022-11-28 14:05 UTC, merged