chore(ci): Use pre-built buildifier in CI
magma/magma pull request #14639
Opened 2022-12-07 10:29 UTC by LKreutzer

Signed-off-by: Lars Kreutzer <lars.kreutzer@tngtech.com>

## Summary

- Resolves #14551
- Download pre-built buildifier from release and use in CI job.

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2022-12-07 16:39 UTC, vktng requested changes

2022-12-07 16:39 UTC, vktng commented on bazel/scripts/run_buildifier.sh
> +BUILDIFIER_MODE="$1"
Add default: "${1:-}"

2022-12-07 16:39 UTC, vktng commented on bazel/scripts/run_buildifier.sh
> +        BUILDIFIER_OPTIONS="-mode=diff --lint=warn --warnings=-unused-variable -v=true"
Convert this into an array.

2022-12-07 16:39 UTC, vktng commented on bazel/scripts/run_buildifier.sh
> +        BUILDIFIER_OPTIONS="-mode=fix --lint=fix --warnings=all"
Same.

2022-12-07 16:39 UTC, vktng commented on bazel/scripts/run_buildifier.sh
> +# shellcheck disable=SC2086
This will not be needed if we use arrays.

2022-12-08 08:20 UTC, LKreutzer commented on bazel/scripts/run_buildifier.sh
> +BUILDIFIER_MODE="$1"
Adressed all of the comments.

2022-12-08 09:49 UTC, vktng approved these changes
LGTM.

2022-12-08 09:52 UTC, merged