ci: promote debian packages to magma-packages-prod
magma/magma pull request #14718
Opened 2022-12-16 21:13 UTC by ajahl

Signed-off-by: Alex Jahl <alexander.jahl@tngtech.com>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2022-12-20 12:05 UTC, LKreutzer requested changes
Is there a way to test this?

2022-12-20 12:05 UTC, LKreutzer commented on .github/workflows/debian-packages-promote.yml
> +      distribution:
Should this be a choice or a string input?

2022-12-20 12:05 UTC, LKreutzer commented on .github/workflows/debian-packages-promote.yml
> +      distribution: ${{ inputs.distribution || 'focal-ci' }}
Is the `||` really needed since we already have a default defined at the input?

2022-12-20 12:05 UTC, LKreutzer commented on .github/workflows/debian-packages-promote.yml
> +          echo "User is not a member of the team"
Could we clarify the message? E.g. "User is not a member of the `approvers-ci` group."

2022-12-20 12:05 UTC, LKreutzer commented on .github/workflows/debian-packages-promote.yml
> +          if [ ${{ env.distribution }} != 'focal-ci' ] && [[ ! ${{ env.distribution }} =~ ^focal-1\.[0-9]+\.[0-9]+$ ]]; then
Nit: To make this line a bit shorter could we at least move the `then` to the next line?

2022-12-20 12:05 UTC, LKreutzer commented on .github/workflows/debian-packages-promote.yml
> +        if: steps.jfrog-setup.conclusion == 'success' && github.event_name == 'workflow_dispatch'
`&& github.event_name == 'workflow_dispatch'` is not needed because this is always true.

2022-12-20 13:02 UTC, ajahl commented on .github/workflows/debian-packages-promote.yml
> +      distribution:
type is set to `string`

2022-12-20 13:04 UTC, LKreutzer commented on .github/workflows/debian-packages-promote.yml
> +      distribution:
Sorry, maybe I phrased the question wrong: Does it make sense that this is a string? Or is there only a fixed set of sensible options for this input?

2022-12-20 13:04 UTC, ajahl commented
> Is there a way to test this?

@LKreutzer Therefore we need a test folder as target in the artifactory.

2022-12-20 13:05 UTC, ajahl commented on .github/workflows/debian-packages-promote.yml
> +          echo "User is not a member of the team"
is changed

2022-12-20 13:05 UTC, ajahl commented on .github/workflows/debian-packages-promote.yml
> +      distribution: ${{ inputs.distribution || 'focal-ci' }}
You are right.

2022-12-20 13:25 UTC, ajahl commented on .github/workflows/debian-packages-promote.yml
> +      distribution:
I think, string is ok here since the workflow has an extra job that checks if the input follows the allowed syntax (focal-1.x.y).

2022-12-31 13:16 UTC, ajahl commented
@mpfirrmann, @nstng The required test folder `magma-packages-tmp` is now available in the artifactory. I run the workflow and the copy operation has been performed successfully ([Workflow run](https://github.com/magma/magma/actions/runs/3809126108/jobs/6480258247), [Artifactory](https://linuxfoundation.jfrog.io/ui/native/magma-packages-tmp/)).

But why the artifactory creates a `focal-1.6.0` folder in the `dists` directory?

2023-01-04 11:00 UTC, mpfirrmann commented
> @mpfirrmann, @nstng The required test folder `magma-packages-tmp` is now available in the artifactory. I run the workflow and the copy process has been performed successfully ([Workflow run](https://github.com/magma/magma/actions/runs/3809126108/jobs/6480258247), [Artifactory](https://linuxfoundation.jfrog.io/ui/native/magma-packages-tmp/)).
> 
> But why the artifactory creates a `focal-1.6.0` folder in the sub-directory `dists`?

My understanding: 

- The `/dists/focal-*` subfolders are created by jFrog based on the metadata in the uploaded packages. 
- The `/dists/focal-1.6/main/binary-amd64/Packages` has on entry for `magma-libfluid_0.1.0.6-1_amd64.deb`. In [its metadata](https://linuxfoundation.jfrog.io/ui/repos/tree/Properties/magma-packages-tmp/pool/focal-ci/magma-libfluid_0.1.0.6-1_amd64.deb) we find `deb.distribution=focal-1.6.0`.
- However, looking at the different `/dists/focal-ci/main/binary-$ARCH/Packages` I'm not quite sure, how and why some packages get sorted in these lists or not.

2023-01-04 11:08 UTC, nstng commented
> @nstng, how accurate is my understanding here?

@mpfirrmann I agree with your analysis - do you have an example of a package that you are missing/not expecting in `/dists/focal-ci/main/binary-$ARCH/Packages`

2023-01-04 11:16 UTC, mpfirrmann commented
> @mpfirrmann I agree with your analysis - do you have an example of a package that you are missing/not expecting in `/dists/focal-ci/main/binary-$ARCH/Packages`

I just double checked: The metadata-sorting is done correctly, but they do not always coincide with the naming of the packages. For example the `python3-websocket-client-1.4.2_all.deb` has a `deb.architecture=amd64` and not `all` what the filename would suggest. 
I was just counting packages and some numbers didn't add up.

2023-01-05 07:47 UTC, LKreutzer approved these changes

2023-01-30 13:35 UTC, nstng commented
Closed in favor of #14914

2023-01-30 13:35 UTC, closed without merging