fix(orc8r): fix error messages in go http endpoints in orc8r
magma/magma pull request #14758
Opened 2022-12-23 01:56 UTC by wolfseb

Signed-off-by: Sebastian Wolf <sebastian.wolf@tngtech.com>
Part of #14707.

## Summary

The method `echo.NewHTTPError` takes the error as a string. Currently, however, it is passed as an error object. This PR fixes this in the orc8r codebase. The following changes are made:

* `err` --> `err.Error()`
* `fmt.Errorf("text: %w", err)` --> `fmtSprintf("text: %v", err)`
* `fmt.Errorf(...)` --> `fmt.,Sprintf(...)`

## Additional Information

- [ ] This change is backwards-breaking

2022-12-23 08:59 UTC, sebathomas commented on orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_config_handler.go
> +		return echo.NewHTTPError(sendErr.Code, fmt.Sprintf("%s", sendErr.Message))
I think you could return `sendErr` directly. This is already a `HTTPError`.

2022-12-23 09:16 UTC, sebathomas commented on orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_config_handler.go
> +		return echo.NewHTTPError(sendErr.Code, fmt.Sprintf("%s", sendErr.Message))
Same here.

2022-12-23 09:17 UTC, sebathomas commented on orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_receiver_handlers.go
> +		return echo.NewHTTPError(sendErr.Code, fmt.Sprintf("%s", sendErr.Message))
And here.

2022-12-23 09:18 UTC, sebathomas approved these changes
Some small points but looking good. :+1:

2022-12-23 09:32 UTC, sebathomas requested changes
I think the latest change was a misunderstanding. The idea is that you can return `sendErr` directly, not `echo.NewHTTPError(sendErr.Code, sendErr)`.

2023-01-02 21:06 UTC, wolfseb commented
> I think the latest change was a misunderstanding. The idea is that you can return `sendErr` directly, not `echo.NewHTTPError(sendErr.Code, sendErr)`.

Done. Is it ok now @sebathomas ?

2023-01-03 08:12 UTC, sebathomas approved these changes

2023-01-03 09:11 UTC, merged