fix(ci): adapt syntax of messages sent to Slack
magma/magma pull request #14794
Opened 2023-01-03 14:48 UTC by mpfirrmann

## Summary

This is an attempt to improve the formatting of the fail messages sent to the `#ci` Slack channel. 
Currently, square brackets are used to indicate links is not [Slack syntax](https://api.slack.com/reference/surfaces/formatting#linking-urls), see i.e. in message:
`CWF integration test: tests failed on [09c1ef43024d5b784812411b036ccebb81639473](https://github.com/magma/magma/commits/09c1ef43024d5b784812411b036ccebb81639473): fix(ci): remove print typo in package.sh (#14771)`

## Test Plan

- Wait for failing CI tests and check `#ci`.
- Format the messages better if needed.

## Additional Information

- [ ] This change is backwards-breaking

2023-01-03 15:03 UTC, LKreutzer requested changes
I would prefer to use `https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}` everywhere. The benefit of this is that you can click on the link go to the failing run directly. IMO the SHA does not give you much information and finding the right runs can be very difficult. I would suggest to remove the SHA messages in favor of the run id messages.

2023-01-03 15:42 UTC, mpfirrmann commented
> I would prefer to use `https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}` everywhere. The benefit of this is that you can click on the link go to the failing run directly. IMO the SHA does not give you much information and finding the right runs can be very difficult. I would suggest to remove the SHA messages in favor of the run id messages.

Ok, I agree with your point linking to the failing run. However, I do feel that the commit hash or PR title is a valuable human readable piece of information. Especially if a single PR breaks multiple runs in CI it is immediately clear without going through all the runs. There are also runs triggered by `repository dispatch` i.e. [AGW Test LTE Integration With Bazel Debian Build](https://github.com/magma/magma/actions/workflows/lte-integ-test-bazel-magma-deb.yml) which do not display the corresponding commit.
Why not combine both information? For example

`Bazel Debian LTE integration test failed in run $LINK_TO_RUN from commit $SHA: $COMMIT_MESSAGE`

2023-01-03 15:55 UTC, LKreutzer commented
> Why not combine both information? For example
> `Bazel Debian LTE integration test failed in run $LINK_TO_RUN from commit $SHA: $COMMIT_MESSAGE`

Sound good :+1:

2023-01-10 09:36 UTC, LKreutzer reviewed
- What syntax is the `<|>`? 
- Do we have a test run from a fork with the secret to see that this is displayed correctly?
  - But it may be fine to merge and adapt if it should fail.

2023-01-10 13:48 UTC, mpfirrmann commented
> * What syntax is the `<|>`?
> 
>     * Do we have a test run from a fork with the secret to see that this is displayed correctly?
>       
>       * But it may be fine to merge and adapt if it should fail.

I got this syntax from the Slack API docs, https://api.slack.com/reference/surfaces/formatting#linking-urls.
This was not tested since I don't have access to the secret.

2023-01-10 13:54 UTC, LKreutzer commented
> > * What syntax is the `<|>`?
> >   
> >   * Do we have a test run from a fork with the secret to see that this is displayed correctly?
> >     
> >     * But it may be fine to merge and adapt if it should fail.
> 
> I got this syntax from the Slack API docs, https://api.slack.com/reference/surfaces/formatting#linking-urls. This was not tested since I don't have access to the secret.

Hm, manually I cannot get this to work in Slack. But might be different with the API. Lgtm

2023-01-10 13:55 UTC, LKreutzer approved these changes

2023-01-10 13:56 UTC, mpfirrmann commented
> > > * What syntax is the `<|>`?
> > >   
> > >   * Do we have a test run from a fork with the secret to see that this is displayed correctly?
> > >     
> > >     * But it may be fine to merge and adapt if it should fail.
> > 
> > 
> > I got this syntax from the Slack API docs, https://api.slack.com/reference/surfaces/formatting#linking-urls. This was not tested since I don't have access to the secret.
> 
> Hm, manually I cannot get this to work in Slack. But might be different with the API. Lgtm

I noticed that as well. I'll monitor the `#ci` channel and see if this does improve the message formatting or if we would have to just live with the bare links.

2023-01-10 13:57 UTC, merged