fix(agw): Upgrade ASN library to the new version
magma/magma pull request #15369
Opened 2024-01-25 06:57 UTC by ganeshg87

## Summary

Upgrade the ASN library to the new version

## Test Plan

 upgrading asn1 compiler 
 -----------------------

 Step 1: Apply Patch to Magma Repo

 	# Navigate to the Magma repository
	cd magma

	# Apply the patch
	git apply upgrade_asn.patch

 Step 2: Build and Install ASN.1 Compiler (asn1c) from mouse07410

	# Clone the asn1c repository from mouse07410
	git clone https://github.com/mouse07410/asn1c.git

	# Navigate to the cloned repository
	cd asn1c

	# Configure with default settings
	test -f configure || autoreconf -iv
	./configure

	# Build the compiler
	make

	# Install the compiler into a standard location
	sudo make install
	
Step 3: Build Magma Code Base
	# Navigate back to the Magma repository if you're not already there
	cd path/to/magma

	# Build the Magma code base
## Additional Information

- [ ] This change is backwards-breaking

## Security Considerations

2024-01-25 10:26 UTC, rdefosse requested changes
@ganeshg87 

looks good to me.

could you please also patch these 2 files?

```bash
diff --git a/lte/gateway/docker/mme/Dockerfile.rhel8 b/lte/gateway/docker/mme/Dockerfile.rhel8
index 1903b2f412..709b918fb6 100644
--- a/lte/gateway/docker/mme/Dockerfile.rhel8
+++ b/lte/gateway/docker/mme/Dockerfile.rhel8
@@ -150,7 +150,7 @@ RUN  git clone --recurse-submodules -b v1.15.0 https://github.com/grpc/grpc && \
      wget https://www.gnupg.org/ftp/gcrypt/gnutls/v3.1/gnutls-3.1.23.tar.xz && \
      git clone https://liblfds.org/git/liblfds && \
      git clone https://gitea.osmocom.org/cellular-infrastructure/libgtpnl && \
-     git clone https://github.com/OPENAIRINTERFACE/asn1c.git && \
+     git clone https://github.com/mouse07410/asn1c.git && \
      git clone https://github.com/OPENAIRINTERFACE/opencord.org.freeDiameter.git freediameter && \
      git clone https://github.com/nlohmann/json.git
 
@@ -275,8 +275,8 @@ RUN cd libgtpnl && \
 
 #####  asn1c
 RUN cd asn1c && \
-    # Moved git clone https://github.com/OPENAIRINTERFACE/asn1c.git && \
-    git checkout f12568d617dbf48497588f8e227d70388fa217c9 && \
+    # Moved git clone https://github.com/mouse07410/asn1c.git && \
+    git checkout ebed802 && \
     autoreconf -iv && \
     ./configure && \
     make -j`nproc` && \
diff --git a/lte/gateway/docker/mme/Dockerfile.ubuntu18.04 b/lte/gateway/docker/mme/Dockerfile.ubuntu18.04
index 8f93634753..3c52a74f01 100644
--- a/lte/gateway/docker/mme/Dockerfile.ubuntu18.04
+++ b/lte/gateway/docker/mme/Dockerfile.ubuntu18.04
@@ -84,7 +84,7 @@ RUN  git clone --recurse-submodules -b v1.15.0 https://github.com/grpc/grpc && \
      wget https://www.gnupg.org/ftp/gcrypt/gnutls/v3.1/gnutls-3.1.23.tar.xz && \
      git clone https://liblfds.org/git/liblfds && \
      git clone https://gitea.osmocom.org/cellular-infrastructure/libgtpnl && \
-     git clone https://github.com/OPENAIRINTERFACE/asn1c.git && \
+     git clone https://github.com/mouse07410/asn1c.git && \
      git clone https://github.com/OPENAIRINTERFACE/opencord.org.freeDiameter.git freediameter && \
      git clone https://github.com/nlohmann/json.git
 
@@ -207,8 +207,8 @@ RUN cd libgtpnl && \
 
 #####  asn1c
 RUN cd asn1c && \
-    # Moved git clone https://github.com/OPENAIRINTERFACE/asn1c.git && \
-    git checkout f12568d617dbf48497588f8e227d70388fa217c9 && \
+    # Moved git clone https://github.com/mouse07410/asn1c.git && \
+    git checkout ebed802 && \
     autoreconf -iv && \
     ./configure && \
     make -j`nproc` && \
```

I've built and tested manually with these 2 modifications.

2024-01-29 06:18 UTC, ganeshg87 commented
@rdefosse , 
updated docker files and included in patch. please have a look 

Thanks
Ganesh

2024-01-29 09:35 UTC, rdefosse approved these changes

2024-03-19 07:01 UTC, Sujay-Radtonics commented
@ganeshg87 , Can you please give an example which can help us confirm that generated files are using new ASN library ?

2024-11-12 17:44 UTC, lucasgonze approved these changes
![image](https://github.com/user-attachments/assets/b54b76c6-d8ae-440d-8c96-972c17f39483)
 That's what we want

2024-12-02 14:05 UTC, panyogesh commented
Test Reports and other details in the [Link](https://drive.google.com/drive/folders/1Y4Q1i9n2aUnjxT--_zcBdGMQaOl2FGwU?usp=sharing
)

2025-03-23 21:03 UTC, merged