Add Gateway detail status
magma/magma pull request #1819
Opened 2020-06-15 19:16 UTC by HannaFar

Add Gateway detail status component
https://www.figma.com/file/hw8iheccicYs6tW7gsFsPK/Magma---Client-Facing-Final-Design?node-id=219%3A4079

2020-06-15 19:46 UTC, murtadha requested changes
This looks great :) a few comments/nits back to your review

2020-06-15 19:46 UTC, murtadha commented on symphony/app/fbcnms-projects/magmalte/app/components/KPIGrid.js
> +  status?: Status
nit, just inline the status enum since it's not used elsewhere :)
```suggestion
  status?: 'Disabled' | 'Enabled' | 'Down'
```

2020-06-15 19:46 UTC, murtadha commented on symphony/app/fbcnms-projects/magmalte/app/components/KPIGrid.js
> +          <Grid item xs key={'data-' + i + '-' + j}>
you can make this easier to read:
```suggestion
          <Grid item xs key={`data-${i}-${j}`}>
```

2020-06-15 19:46 UTC, murtadha commented on symphony/app/fbcnms-projects/magmalte/app/components/KPIGrid.js
> +      <Grid key={'row-' + i} container direction='row'>
does the key need to be a complicated string, or enough to just do `key={i}`, which is what I've usually done :)

2020-06-15 19:46 UTC, murtadha commented on symphony/app/fbcnms-projects/magmalte/app/components/KPIGrid.js
> +    props.data.map((row, i) => (
looks like `kpiGrid` is an array that just has one item, which is an array in itself. Do we need to wrap it in an array, or enough to just render the inner array?
```suggestion
  const kpiGrid = props.data.map((row, i) => (
  ...
```

2020-06-15 19:46 UTC, murtadha commented on symphony/app/fbcnms-projects/magmalte/app/views/equipment/GatewayDetailStatus.js
> +import React from 'react'
re-arrange this such that modules imports (uppercase) are in a block, and functions (lowercase) are in another
```suggestion
import KPIGrid from '../../components/KPIGrid'
import React from 'react'

import isGatewayHealthy from '../../components/GatewayUtils'
```

2020-06-15 19:46 UTC, murtadha commented on symphony/app/fbcnms-projects/magmalte/app/views/equipment/GatewayDetailStatus.js
> +      gwInfo.status.checkin_time === null)
is this condition really trying to check if `checkin_time === null`?

2020-06-15 19:46 UTC, murtadha commented on symphony/app/fbcnms-projects/magmalte/app/components/KPIGrid.js
> +type Status = 'Disabled' | 'Enabled' | 'Down';
should the values be Disabled, Up, Down?

2020-06-18 07:21 UTC, xjtian commented
Peep the CI failures for eslint and flow: https://app.circleci.com/pipelines/github/facebookincubator/magma/6261/workflows/f564704a-eb13-453e-b8f4-a1c3bdfe858f/jobs/43727/steps, https://app.circleci.com/pipelines/github/facebookincubator/magma/6261/workflows/f564704a-eb13-453e-b8f4-a1c3bdfe858f/jobs/43726/steps

2020-06-23 08:52 UTC, xjtian approved these changes

2020-06-23 13:42 UTC, karthiksubraveti commented on symphony/app/fbcnms-projects/magmalte/app/components/KPIGrid.js
> +export default function KPIGrid(props: Props) {
@HannaFar  minor nit: This component could be merged with KPI Tray component or replace KPI Tray component.

2020-06-23 22:15 UTC, closed without merging