[magma][testcontroller]Added subscriber state to testcontroller
magma/magma pull request #1988
Opened 2020-07-20 15:05 UTC by gammaseeker

## Summary

Added two states in testcontroller that will flip the subscriber state from inactive, run a traffic test that is expected to fail, flip subscriber state to active and run a traffic test that should succeed.

## Test Plan

All unit tests successfully ran and passed

2020-07-21 09:02 UTC, mpgermano requested changes

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +			subscriberInactiveState: makeSubscriberStateHandler("INACTIVE", trafficTest5State1),
Pass in the const definition of "INACTIVE" from `lte/cloud/go/services/subscriberdb/obsidian/models` rather than the string literal

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +			subscriberActiveState: makeSubscriberStateHandler("ACTIVE", trafficTest6State1),
Likewise, pass in the const definition of "ACTIVE" from lte/cloud/go/services/subscriberdb/obsidian/models` rather than the string literal

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +		// TODO Add postToSlack later
Since this PR already implements the full functionality needed for these tests, let's include the slack notifications in this PR

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +		// TODO Add postToSlack later
Include slack notifications

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
>  			// TODO Add postToSlack later
Include notifications

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd_test.go
> +	// Detach network
Nit: `Detach subscriber`

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd_test.go
> +	// Attach network
Nit `Attach subscriber`

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +	subscriberInactiveState = "sub_inactive"
Nit: `subscriberInactiveState = "subscriber_inactive`

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +	subscriberActiveState = "sub_active"
Nit: `subscriberActiveState = "subscriber_active"`

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd_test.go
> +func Test_EnodebdE2ETestStateMachine_SubscriberState(t *testing.T) {
It looks to me like this test is duplicating the happy path test. I'd use this test to test error cases like if traffic succeeds when subscriber is inactive or vice versa.

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +	newConfig := cfg.(*subscribermodels.LteSubscription)
When type converting, it's always good to make sure the conversion worked:
```
newConfig, ok := cfg.(*subscribermodels.LteSubscription)
if !ok {
   handleError
   return ...
}
newConfig.State = desiredState
...

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +		_ = configurator.CreateOrUpdateEntityConfig(*config.NetworkID, lte.SubscriberEntityType, *config.SubscriberID, cfg)
Let's at least catch this error and log it:
```
err = configurator.CreateOrUpdateEntityConfig(*config.NetworkID, lte.SubscriberEntityType, *config.SubscriberID, cfg)
if err != nil {
  glog.Error(err)
}
return checkForUpgradeState, 10 * time.Minute, err
```

2020-07-21 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
>  	resp, err := gatewayClient.GenerateTraffic(*config.NetworkID, trafficGWID, config.Ssid, config.SsidPw)
We should try to differentiate between an error and traffic not being generated. For example there's a difference between a connection error from orc8r to gateway (and thus the CLI not being run) versus the CLI (expectedly) not being able to send traffic. Without this  differentiation our results might not be accurate.

Rather than parsing the error, I'd try to have the response return a code corresponding to traffic success/failure.

2020-07-21 20:11 UTC, gammaseeker commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
>  	resp, err := gatewayClient.GenerateTraffic(*config.NetworkID, trafficGWID, config.Ssid, config.SsidPw)
Looking into this

2020-07-22 09:02 UTC, mpgermano requested changes
Insync-checkin is failing as well

2020-07-22 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd_test.go
> +	// Traffic test should not succeeded due to inactive subscriber
Nit `should not succeed`

2020-07-22 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd_test.go
> +	mockMagmad.On("GenerateTraffic", "n1", "g2", "magmawifi", "magmamagma").Return(mockGenericCommandResp, errors.New("")).Once()
Mock expectations should be declared before the functions that rely on them (in this case `sm.Run(...)`

2020-07-22 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +			return successState, 1 * time.Minute, err
I don't think we should return the error here unless it's unexpected

2020-07-22 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd_test.go
>  	// ---
This function is still only testing the behavior when things flow properly. Please add error cases to test the error logic of the traffic handler and subscriber state handler

2020-07-22 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +
Nit: delete newline

2020-07-22 09:02 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +		return checkForUpgradeState, 1 * time.Minute, err
`err` here is always `nil`. We should instead return an error here. This make more intuitive sense by returning an error anytime the test doesn't succeed (i.e. it's weird to return an error despite the test achieving the expected behavior as we have currently in line 450).

2020-07-22 22:14 UTC, gammaseeker commented
Before you approve this, I want to expand my unit tests to differentiate traffic test failures either due to being unable to connect to an AGW vs the traffic script itself failing. It's ~7:15pm EDT rn, gunna call it a day and knock this out tmm morning.

2020-07-23 15:19 UTC, gammaseeker commented
Ready for review

2020-07-25 00:09 UTC, 119Vik commented
Can one of the admins verify this patch?

2020-07-28 09:39 UTC, mpgermano commented
Fix failing unit tests (cloud-test and insync-checkin). Looks good otherwisse.

2020-07-28 20:10 UTC, mpgermano approved these changes

2020-07-29 20:19 UTC, merged