[CI]Run xwfm-test on master
magma/magma pull request #2069
Opened 2020-07-25 01:26 UTC by tmdzk

## Summary

Run xwfm-test on master 

## Test Plan

Let CI run, maje sure xwfm workflow has been created and xwfm-test ran successfully

## Additional Information

- [ ] This change is backwards-breaking

2020-07-25 01:27 UTC, 119Vik commented
Can one of the admins verify this patch?

2020-07-25 01:34 UTC, xjtian requested changes

2020-07-25 01:34 UTC, xjtian commented on .circleci/config.yml
> +            docker login -u ${XWF_ARTIFACTORY_USER} -p ${XWF_ARTIFACTORY_API_KEY} facebookconnectivity-openflow-xwfm-docker.jfrog.io
put the docker registry in an env var

2020-07-25 01:34 UTC, xjtian commented on .circleci/config.yml
> +          command: pyenv global 3.7.0
is this actually necessary?

2020-07-25 01:34 UTC, xjtian commented on .circleci/config.yml
> +            docker-compose build --parallel && docker-compose up -d && docker exec tests pytest --log-cli-level=info code/tests.py --type=analytic && docker-compose down
we don't have to worry about the docker-compose down

2020-07-25 19:41 UTC, tmdzk commented
https://app.circleci.com/pipelines/github/magma/magma/33/workflows/528e8200-22ed-426a-9267-fc6f1018bb58/jobs/411

Ready to be merged

2020-07-27 23:05 UTC, xjtian approved these changes

2020-07-27 23:05 UTC, merged