[orc8r][sev_fix][migration_required] Add default APN configurator migration
magma/magma pull request #2100
Opened 2020-07-28 22:31 UTC by hcgatewood

## Summary

Note: this diff does not actually require a migration, but since a previous diff should have required a migration, I'll add the `[migration_required]` tag above to include this in the list of migrations required for the next release.

As part of the APN updates, every subscriber is now expected to be associated with an APN.

The required configurator migration was not performed before the relevant AGW changes were shipped, resulting in S205307. This diff provides the stable fix for the SEV.

See `m010_default_apns/main.go` for full details, but tl;dr this migration creates a default APN per network (if not exist), and associates each APN-lacking subscriber with the default APN.

## Test Plan

Ran locally with new copy of prod db. Included verification fn confirmed that each subscriber now had an associated APN, and, in the subset of cases that were logged for manual verification, that was always the default oai.ipv4 APN.

See the full output from my local run on the prod db copy at P136079055. Abbreviated output below

```
root@993d2eaf047e:/# /var/opt/magma/bin/m010_default_apns -verify

I0718 06:15:54.606951     461 main.go:131] BEGIN MIGRATION
I0718 06:15:54.616219     461 main.go:230] [RUN] INSERT INTO cfg_entities (pk,network_id,type,"key",graph_id,config) VALUES ($1,$2,$3,$4,$5,$6) [c3627343-65af-4367-a10a-fa84f5be24d9 mesh_waw_prod apn oai.ipv4 b2648c3b-e421-47eb-b9ef-cc19f096f0ee [123 34 97 109 98 114 34 58 123 34 109 97 120 95 98 97 110 100 119 105 100 116 104 95 100 108 34 58 50 48 48 48 48 48 48 48 48 44 34 109 97 120 95 98 97 110 100 119 105 100 116 104 95 117 108 34 58 49 48 48 48 48 48 48 48 48 125 44 34 113 111 115 95 112 114 111 102 105 108 101 34 58 123 34 99 108 97 115 115 95 105 100 34 58 57 44 34 112 114 101 101 109 112 116 105 111 110 95 99 97 112 97 98 105 108 105 116 121 34 58 116 114 117 101 44 34 112 114 101 101 109 112 116 105 111 110 95 118 117 108 110 101 114 97 98 105 108 105 116 121 34 58 102 97 108 115 101 44 34 112 114 105 111 114 105 116 121 95 108 101 118 101 108 34 58 49 53 125 125]]
I0718 06:15:54.620424     461 main.go:230] [RUN] INSERT INTO cfg_entities (pk,network_id,type,"key",graph_id,config) VALUES ($1,$2,$3,$4,$5,$6) [878e6ab9-a5bd-47ab-860a-708ff84f19b7 mesh_surf_prod apn oai.ipv4 8a0bddae-0cef-4d11-9c62-5ca16c172a62 [123 34 97 109 98 114 34 58 123 34 109 97 120 95 98 97 110 100 119 105 100 116 104 95 100 108 34 58 50 48 48 48 48 48 48 48 48 44 34 109 97 120 95 98 97 110 100 119 105 100 116 104 95 117 108 34 58 49 48 48 48 48 48 48 48 48 125 44 34 113 111 115 95 112 114 111 102 105 108 101 34 58 123 34 99 108 97 115 115 95 105 100 34 58 57 44 34 112 114 101 101 109 112 116 105 111 110 95 99 97 112 97 98 105 108 105 116 121 34 58 116 114 117 101 44 34 112 114 101 101 109 112 116 105 111 110 95 118 117 108 110 101 114 97 98 105 108 105 116 121 34 58 102 97 108 115 101 44 34 112 114 105 111 114 105 116 121 95 108 101 118 101 108 34 58 49 53 125 125]]
I0718 06:15:54.629300     461 main.go:230] [RUN] INSERT INTO cfg_entities (pk,network_id,type,"key",graph_id,config) VALUES ($1,$2,$3,$4,$5,$6) [445d2cae-2a4c-40f6-953c-38209f64ddec loadstone_test1 apn oai.ipv4 9c4b5997-5220-4ea2-8efd-cadc1696e6ec [123 34 97 109 98 114 34 58 123 34 109 97 120 95 98 97 110 100 119 105 100 116 104 95 100 108 34 58 50 48 48 48 48 48 48 48 48 44 34 109 97 120 95 98 97 110 100 119 105 100 116 104 95 117 108 34 58 49 48 48 48 48 48 48 48 48 125 44 34 113 111 115 95 112 114 111 102 105 108 101 34 58 123 34 99 108 97 115 115 95 105 100 34 58 57 44 34 112 114 101 101 109 112 116 105 111 110 95 99 97 112 97 98 105 108 105 116 121 34 58 116 114 117 101 44 34 112 114 101 101 109 112 116 105 111 110 95 118 117 108 110 101 114 97 98 105 108 105 116 121 34 58 102 97 108 115 101 44 34 112 114 105 111 114 105 116 121 95 108 101 118 101 108 34 58 49 53 125 125]]
I0718 06:15:54.632217     461 main.go:383] [RUN] INSERT INTO cfg_assocs (from_pk,to_pk) VALUES ($1,$2) [eb521439-aeb4-4231-b383-72ae76dde545 445d2cae-2a4c-40f6-953c-38209f64ddec]
I0718 06:15:54.633141     461 main.go:416] [RUN] UPDATE cfg_entities SET graph_id = $1 WHERE (network_id = $2 AND graph_id = $3) [9c4b5997-5220-4ea2-8efd-cadc1696e6ec loadstone_test1 a0fbbb74-b523-4c28-9cd8-5e46ff275edc]
I0718 06:15:54.634629     461 main.go:383] [RUN] INSERT INTO cfg_assocs (from_pk,to_pk) VALUES ($1,$2) [53093f53-96c4-4299-9595-52a839ae33a8 445d2cae-2a4c-40f6-953c-38209f64ddec]
I0718 06:15:54.635399     461 main.go:416] [RUN] UPDATE cfg_entities SET graph_id = $1 WHERE (network_id = $2 AND graph_id = $3) [9c4b5997-5220-4ea2-8efd-cadc1696e6ec loadstone_test1 d3999d15-5133-4034-883e-7dcb0e91df0a]
I0718 06:15:54.636830     461 main.go:383] [RUN] INSERT INTO cfg_assocs (from_pk,to_pk) VALUES ($1,$2) [874bd376-bc44-4d6d-8f8d-e67ceb2899ee 445d2cae-2a4c-40f6-953c-38209f64ddec]
I0718 06:15:54.637626     461 main.go:416] [RUN] UPDATE cfg_entities SET graph_id = $1 WHERE (network_id = $2 AND graph_id = $3) [9c4b5997-5220-4ea2-8efd-cadc1696e6ec loadstone_test1 a7ff6f70-06e2-457c-8aaf-ae5a66427949]
I0718 06:15:54.638972     461 main.go:383] [RUN] INSERT INTO cfg_assocs (from_pk,to_pk) VALUES ($1,$2) [2e0779fa-171b-4c81-a806-1b1b9847f5bf 445d2cae-2a4c-40f6-953c-38209f64ddec]
I0718 06:15:54.639832     461 main.go:416] [RUN] UPDATE cfg_entities SET graph_id = $1 WHERE (network_id = $2 AND graph_id = $3) [3a483053-be64-476c-84f1-39060f6b7f1e loadstone_test1 9c4b5997-5220-4ea2-8efd-cadc1696e6ec]
I0718 06:15:54.641214     461 main.go:383] [RUN] INSERT INTO cfg_assocs (from_pk,to_pk) VALUES ($1,$2) [e964683e-ab33-4d95-9b37-77a55a5aa05d 445d2cae-2a4c-40f6-953c-38209f64ddec]
I0718 06:15:54.641965     461 main.go:416] [RUN] UPDATE cfg_entities SET graph_id = $1 WHERE (network_id = $2 AND graph_id = $3) [3a483053-be64-476c-84f1-39060f6b7f1e loadstone_test1 6a70b4a7-d592-4417-8710-17e12c63d5a6]
I0718 06:15:54.643234     461 main.go:383] [RUN] INSERT INTO cfg_assocs (from_pk,to_pk) VALUES ($1,$2) [9eec6d10-8f4b-4688-838b-a567ac56c0b5 445d2cae-2a4c-40f6-953c-38209f64ddec]
I0718 06:15:54.644127     461 main.go:416] [RUN] UPDATE cfg_entities SET graph_id = $1 WHERE (network_id = $2 AND graph_id = $3) [3a483053-be64-476c-84f1-39060f6b7f1e loadstone_test1 7d496c59-02a9-4da3-a166-1a97fe122826]
I0718 06:15:54.645266     461 main.go:230] [RUN] INSERT INTO cfg_entities (pk,network_id,type,"key",graph_id,config) VALUES ($1,$2,$3,$4,$5,$6) [24bd4c6e-8322-480a-b151-a66654b03bbc ens_test_import apn oai.ipv4 92dd51ee-04c4-4dea-ad7a-117dee0b0eb4 [123 34 97 109 98 114 34 58 123 34 109 97 120 95 98 97 110 100 119 105 100 116 104 95 100 108 34 58 50 48 48 48 48 48 48 48 48 44 34 109 97 120 95 98 97 110 100 119 105 100 116 104 95 117 108 34 58 49 48 48 48 48 48 48 48 48 125 44 34 113 111 115 95 112 114 111 102 105 108 101 34 58 123 34 99 108 97 115 115 95 105 100 34 58 57 44 34 112 114 101 101 109 112 116 105 111 110 95 99 97 112 97 98 105 108 105 116 121 34 58 116 114 117 101 44 34 112 114 101 101 109 112 116 105 111 110 95 118 117 108 110 101 114 97 98 105 108 105 116 121 34 58 102 97 108 115 101 44 34 112 114 105 111 114 105 116 121 95 108 101 118 101 108 34 58 49 53 125 125]]
I0718 06:15:54.648115     461 main.go:230] [RUN] INSERT INTO cfg_entities (pk,network_id,type,"key",graph_id,config) VALUES ($1,$2,$3,$4,$5,$6) [1ef3be05-3762-43c8-b23c-e228718193c2 xxxx apn oai.ipv4 a37d8fd5-e9ca-48fb-82f7-67bee190bd7b [123 34 97 109 98 114 34 58 123 34 109 97 120 95 98 97 110 100 119 105 100 116 104 95 100 108 34 58 50 48 48 48 48 48 48 48 48 44 34 109 97 120 95 98 97 110 100 119 105 100 116 104 95 117 108 34 58 49 48 48 48 48 48 48 48 48 125 44 34 113 111 115 95 112 114 111 102 105 108 101 34 58 123 34 99 108 97 115 115 95 105 100 34 58 57 44 34 112 114 101 101 109 112 116 105 111 110 95 99 97 112 97 98 105 108 105 116 121 34 58 116 114 117 101 44 34 112 114 101 101 109 112 116 105 111 110 95 118 117 108 110 101 114 97 98 105 108 105 116 121 34 58 102 97 108 115 101 44 34 112 114 105 111 114 105 116 121 95 108 101 118 101 108 34 5 [...]

2020-07-28 22:33 UTC, hcgatewood commented
Changes planned

2020-07-29 05:43 UTC, hcgatewood commented
@xjtian do we take regular checkpoints of our prod db? I feel like we should make sure we have a checkpoint before running this, just to make sure we don't totally bork something on accident

2020-07-29 17:18 UTC, xjtian requested changes
lgtm just some little things

2020-07-29 17:18 UTC, xjtian commented on orc8r/cloud/go/tools/migrations/m010_default_apns/types/apn.go
> +		glog.Fatalf("Error marshaling APN configuration: %v", err)
careful with fatal, I think you should add a recover() to ExecInTx to rollback the tx on panic

2020-07-29 17:18 UTC, xjtian commented on orc8r/cloud/go/tools/migrations/m010_default_apns/main.go
> +				squirrel.Eq{entNidCol: network},
this clause is unnecessary since graphs in different networks already all have different gids

2020-07-29 17:18 UTC, xjtian commented on orc8r/cloud/go/tools/migrations/m010_default_apns/main.go
> +	}
you should be able to do `squirrel.Eq{entGidCol: oldGIDs}` which will render to a `WHERE... IN` clause

2020-07-29 17:18 UTC, xjtian commented on orc8r/cloud/go/tools/migrations/m010_default_apns/main.go
> +}
I think it makes sense to sanity check the graphs for the default apns are correct. Load the default APN entity, then load its graph, and just verify that we get back exactly the set of subscribers that the APN has assocs to in the graph result

2020-07-29 19:50 UTC, hcgatewood commented on orc8r/cloud/go/tools/migrations/m010_default_apns/types/apn.go
> +		glog.Fatalf("Error marshaling APN configuration: %v", err)
- My understanding is that the commit will automatically roll back if it's not committed, i.e. fatal'ing will cause the commit to roll back even without recovering
- In any case, the `MustMarshalBinary` call occurs during the `init` function, not during the tx

2020-08-03 06:51 UTC, xjtian approved these changes

2020-08-03 06:51 UTC, merged