[magma][testcontroller] Updated testcontroller to enable dynamic start states
magma/magma pull request #2123
Opened 2020-07-29 22:26 UTC by gammaseeker

Signed-off-by: Joey Jiemjitpolchai <joeyjiem@fb.com>

## Summary
Updated testcontroller to take in a start state. Makes troubleshooting a failed state easier since we can now just jump to that failing state.

## Test Plan
All unit tests successfully run and pass

2020-07-29 22:37 UTC, mpgermano requested changes

2020-07-29 22:37 UTC, mpgermano commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +		checkForUpgradeState,
Let's reduce this to just states that modify some parameters (i.e check for upgrade, rebootEnodeb1State, reconfigEnodebSTate, restoreEnodebConfigState, subscriberInactive, subscriberActive). Don't include the retry states as well (e.g. trafficTest1State2, trafficTest1State3)

2020-07-30 17:10 UTC, xjtian requested changes

2020-07-30 17:10 UTC, xjtian commented on fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
> +	if !find(states, *config.StartState) {
this will nil-panic for existing test cases that don't have this specified. you should take this out of the required list of properties and regenerate the model.

2020-07-30 21:27 UTC, xjtian commented
@gammaseeker you have to regenerate the swagger model. don't forget to set MAGMA.MODULES_FILE env var locally before ./build.py -g. That's going turn the StartState field from a string pointer to a string scalar too.

2020-08-04 05:02 UTC, mpgermano approved these changes

2020-08-04 19:03 UTC, xjtian approved these changes

2020-08-04 19:03 UTC, merged