[orc8r][service_registry] Add GetAnnotationFields method to simplify retrieving strings annotations
magma/magma pull request #2127
Opened 2020-07-30 03:33 UTC by hcgatewood

## Summary

It's turned into a common service registry pattern to retrieve a (comma-separated) list of strings stored as an annotation.

This diff coalesces that functionality into a single method, with a stable and well-documented set of expectations.

Also updated go-funk for some reason, leaving the update in for simplicity.

## Test Plan

make test, and build everything and ensure an LTE swagger API call succeeds

## Additional Information

- [ ] This change is backwards-breaking

2020-07-30 21:25 UTC, xjtian requested changes

2020-07-30 21:25 UTC, xjtian commented on orc8r/lib/go/registry/registry.go
> +		Value().([]string)
eh at this point it's better to just write a for loop

2020-07-30 21:25 UTC, xjtian commented on orc8r/lib/go/registry/registry.go
> +func (r *ServiceRegistry) GetAnnotationFields(service, annotationName, fieldSeparator string) ([]string, error) {
`GetAnnotationListValue` or `GetListAnnotationValue` or something like that. This name makes me think you're grabbing all the annotation keys on a service. I think you can probably just use the const for the separator too

2020-07-30 21:25 UTC, xjtian commented on orc8r/lib/go/registry/global_registry.go
> +func GetAnnotationFields(service, annotationName, fieldSeparator string) ([]string, error) {
bubble up the name change

2020-08-03 03:59 UTC, xjtian approved these changes
Rebase and do a `make tidy` to sync up the go.mod/go.sum files before merging

2020-08-04 21:02 UTC, mpgermano approved these changes

2020-08-05 02:57 UTC, merged