[orc8r][agw] Updating metrics collection gRPC message size limit / making it configurable
magma/magma pull request #2296
Opened 2020-08-12 01:51 UTC by ardzoht

## Summary

- Adding max-send-message-size metrics_collector client gRPC channel parameter
- Adding grpc_max_size to magmad.yml configs to configure value
- Updating metricsd gRPC server to allow receiving messages up to 50MB

## Test Plan

- Tested on mcp02, with cwf02 and feg setup
- Tested locally with local orc8r and agw, setting configurable value 

## Additional Information

- [ ] This change is backwards-breaking

2020-08-12 09:04 UTC, xjtian requested changes
- Why set the client side payload limit to 4MB but the server side to 50?
- What is the behavior of the grpc client when the request is too large? Will we just drop that request on the client side? If the AGW is collecting a ton of metrics and every request is oversized, could we end up in a situation where we don't sync anything to metricsd?
- I think you need to combo this change with an update to the nginx container and Helm deployment yaml as well. http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size might be the right param to tweak here, @mpgermano might have some older nginx logs you could look at and see what the exact error is when we send a massive request.

2020-08-12 09:04 UTC, xjtian commented on cwf/gateway/configs/magmad.yml
> +  grpc_msg_size: 4 # Max message size for gRPC channel in MBs
be explicit: `max_grpc_msg_size_mb`

2020-08-12 09:04 UTC, xjtian commented on orc8r/gateway/python/magma/magmad/metrics_collector.py
> +                 queue_length, loop=None, post_processing_fn=None):
type annotate these params while you're touching this constructor

2020-08-12 09:04 UTC, xjtian commented on orc8r/gateway/python/magma/magmad/metrics_collector.py
> +def _get_metrics_chan_grpc_options(msg_size: int):
`msg_size_mb`

2020-08-12 09:04 UTC, xjtian commented on orc8r/gateway/python/magma/magmad/metrics_collector.py
> +                 queue_length, loop=None, post_processing_fn=None):
`grpc_max_msg_size_mb`

2020-08-12 20:07 UTC, ardzoht commented
@xjtian 

- I wanted to define a maximum receiving message size on the server side, and then having the AGW define a configurable maximum message size to send, previously they were on default values (4MB each)
- If the request is oversized, then the collected samples will not be synced to metricsd, we've encountered this issue on mcp setup where with scalability testing due to the gRPC message exceeding the maximum allowed size, ideally I'm thinking on implementing doing batching for sending the metrics but for now to unblock this we want to increase it as a short-term fix.
- That makes sense, will look for the changes to apply for nginx configuration.

2020-08-13 03:35 UTC, xjtian commented
Let's bump up the default send limit on the client side to something like 8MB in that case to give us some more headroom for the specific situations where we are experiencing oversized requests.

2020-08-13 20:11 UTC, ardzoht commented
@xjtian Added client_max_size to nginx config to resolve 413 error response code.

2020-08-14 07:51 UTC, xjtian approved these changes

2020-08-14 20:45 UTC, themarwhal approved these changes

2020-08-14 20:47 UTC, merged