[NMS] Cleanup subscriber component
magma/magma pull request #2317
Opened 2020-08-13 17:14 UTC by karthiksubraveti

Signed-off-by: Karthik Subraveti <karthikshyam@gmail.com>

## Summary

- Use subscriber context consistently across the subscriber components

- Add current usage and daily average metrics to the subscriber overview page

- Cleaned up subscriber usage metrics to use 'increase' over a week rather than
directly using the ue_traffic metric. This safeguards us against the counter resets.
This computes the increase in the value from over a week worth of period over 
different steps in the interval. This is not perfect, however it mostly gives us a monotonically 
increasing increments over this period of time. We should ideally compute the increase from
the start point at various points in the interval. 
For e.g. over a 60 min period, with step of 5 mins we should get
1st step - increase [5m]
2nd step - increase [10m]
3rd step - increase [15m]
There is no query which gets us this. Also there seems to be a similar proposal floated around.
https://github.com/prometheus/prometheus/issues/3806

## Test Plan
- yarn test succeeds

2020-08-13 18:15 UTC, Scott8440 requested changes
We need to figure out a new graph to display here because the current one is technically impossible using the data we have available. From what I understand, the graph should display: 

"The amount of data used by this subscriber from the beginning of time until this point (on the graph)"

Using `increase(ue_traffic[1w])` will not give us a monotonically increasing graph, but would rather just show us the amount of data used over the past week, which could decrease if a user uses 2MB one week, and then 1MB the next. Additionally this doesn't actually show us what the graph should.

The best we can do is: "The amount of data used by this subscriber since the time where we drop metrics (generally 30 days, but is configurable by the operator) until now"

With prometheus it will probably never be able to show us what the requested graph actually wants as that's not really something a TSDB should be doing. If we want this data we should store it in a DB (key=subscriber, value=amount of data used), but not a TSDB.

I suggest we change this graph to show the rate of data usage since that is a pretty useful metric and it's exactly what TSDBs were made for. Of course we can do something different and if we show week/week change that will work but we should make it clear in the graph title.

2020-08-13 18:15 UTC, Scott8440 commented
@xjtian Where did the specification of this graph come from and how flexible is it?

2020-08-14 07:47 UTC, xjtian commented
I'm OK with rate of usage, now that I think about it this does seem like a hard question to answer with prometheus.

If we do rate of usage on the graph, let's include some data usage aggregations in the KPI tray then? Total data usage over last 24 hours, 7 days, and 30 days? Thoughts @karthiksubraveti?

2020-08-14 12:31 UTC, karthiksubraveti commented
> I'm OK with rate of usage, now that I think about it this does seem like a hard question to answer with prometheus.
> 
> If we do rate of usage on the graph, let's include some data usage aggregations in the KPI tray then? Total data usage over last 24 hours, 7 days, and 30 days? Thoughts @karthiksubraveti?

Hey @xjtian @Scott8440 ,
Showing data usage aggregations in KPI tray. I can add a total data used over last 24 hours in the KPI tray in status tray .
![Screen Shot 2020-08-14 at 5 27 27 AM](https://user-images.githubusercontent.com/8224854/90249178-dabd1080-ddee-11ea-9044-7601669d0d50.png)
and then I wonder instead of showing a date time selector and showing rate, may be better to show a time range selector, which automatically gives user the information on the time range over which this data usage is computed over. 
That way for time ranges over last (3h, 6h, 12h, 24h, 7d, ...), We can either show the increase or the rate there. I am fine with both. 
..
Karthik

2020-08-14 17:07 UTC, Scott8440 commented
I like the idea of a rate in the graph, then add a few aggregations in the KPI table. My suggestion is 1hr, 1d, 1w, 30d. Maybe later on we can improve this and make it more configurable but this should be fine for now

2020-08-18 22:08 UTC, xjtian commented
Synced offline, we will change these graphs to stacked histograms

2020-08-19 16:26 UTC, xjtian commented
We should consistently make the download bar be the bottom one, in your screencap I see download at the bottom but it switches to the top after you change the time range

2020-08-19 16:29 UTC, Scott8440 commented
Nit: can we make the default colors not be red/blue? I'm personally just not a fan of that color combo and it really sticks out now that this is a histogram. Is there some palette the designers gave us that we can use? Like if purple is the primary color, we can use color 2 and 3 for the charts

2020-08-19 16:41 UTC, Scott8440 reviewed
mostly nits

2020-08-19 16:41 UTC, Scott8440 commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberChart.js
> +  if (val > 1000000) {
can you change these magic numbers to constants

2020-08-19 16:41 UTC, Scott8440 commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberChart.js
> +  let addLabels = true;
I'm kinda confused how this is used

2020-08-19 16:41 UTC, Scott8440 commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberChart.js
> +          networkId: networkId,
```suggestion
          networkId,
```
this works in JS I think?

2020-08-19 16:41 UTC, Scott8440 commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberChart.js
> +          query: `sum(increase(ue_traffic{IMSI="${subscriberId}",direction="down"}[1h]))`,
pull the query into a const and then add in the range for each request

2020-08-19 16:41 UTC, Scott8440 commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberChart.js
> +  const [usage1H, setUsage1H] = useState([0, 'bytes']);
Up to you: do you think it's cleaner to instead just have a single object with these fields instead of 4 separate state variables?

2020-08-19 16:41 UTC, Scott8440 commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberChart.js
> +  const [usage1H, setUsage1H] = useState([0, 'bytes']);
I'm also not a huge fan of using a mixed array to store [value, unit]. Maybe at least make this an object

2020-08-19 16:41 UTC, Scott8440 commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberOverview.js
> +      query: `sum by (IMSI) (ue_traffic)`,
super minor nit: I usually do `sum(<metric>) by (<label>)` since it looks a little more familiar.

2020-08-19 19:16 UTC, karthiksubraveti reviewed
@Scott8440 Thanks for reviewing the changes. I will make changes based on suggested feedback and submit.

2020-08-19 23:18 UTC, Scott8440 approved these changes

2020-08-19 23:18 UTC, Scott8440 commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberChart.js
> +      //addLabels = false;
whoops

2020-08-19 23:23 UTC, karthiksubraveti commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberChart.js
> +      //addLabels = false;
Missed that. Will clean it up.

2020-08-20 05:55 UTC, xjtian approved these changes

2020-08-20 06:10 UTC, merged