Add MME flows for connection tracker service
magma/magma pull request #2359
Opened 2020-08-16 06:04 UTC by koolzz

Signed-off-by: Nick Yurchenko <koolzz@fb.com>

## Summary

The connection tracker service send packets to an internal OVS port, as MME controls tbl 0 we need to allow this traffic to an table that will generate ipfix records

## Test Plan

make integ_test on lte test vm 

## Additional Information

- [ ] This change is backwards-breaking

2020-08-17 18:31 UTC, ardzoht requested changes

2020-08-17 18:31 UTC, ardzoht commented on lte/gateway/c/oai/lib/openflow/controller/GTPApplication.cpp
> +  OAILOG_DEBUG(LOG_GTPV1U, "Default table 0 flow added\n");
update log message to specify this is for internal packet forwarding

2020-08-17 18:31 UTC, ardzoht commented on lte/gateway/configs/spgw.yml
> +# Internal port for processing inetral sampling packets
inetral -> internal

2020-08-21 22:17 UTC, ssanadhya approved these changes
LGTM with minor comments

2020-08-21 22:17 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/GTPApplication.cpp
> +  // Set match on the internal pkt fen port
Typo "fen port"

2020-08-26 19:22 UTC, ardzoht approved these changes

2020-08-27 06:14 UTC, merged