[lte][agw] Pass created dedicated bearer context to sessiond
magma/magma pull request #2451
Opened 2020-08-22 20:47 UTC by ulaskozat

## Summary

- Added a new rpc call to Local Session Manager service to bind the created dedicated bearer to the policy rule for which the bearer is created.
- Implemented the methods for spgw task to make the rpc call to sessiond.

To Do:
- In another PR, sessiond part should call the methods to update the policy2bearer mapping.

## Test Plan
Integration testing.

Checked logs with dedicated bearer test cases to make sure that the rules are properly passed to local session manager, e.g.,
`Aug 22 20:28:13 magma-dev sessiond[20930]: I0822 20:28:13.815299 20977 LocalSessionManagerHandler.cpp:550] imsi: IMSI001010000000001 default bearer: 5 policy rule: rar_rule_1 created bearer: 6`

2020-08-22 21:29 UTC, hcgatewood approved these changes
Cloud change is gen'd files, lgtm

2020-08-24 10:27 UTC, themarwhal approved these changes

2020-08-24 16:38 UTC, emakeev approved these changes

2020-08-24 17:23 UTC, ssanadhya requested changes

2020-08-24 17:23 UTC, ssanadhya commented on lte/gateway/c/oai/lib/pcef/pcef_handlers.h
> + * pcef_end_session is an asynchronous call that binds policy rule id
```suggestion
 * pcef_send_policy2bearer_binding is an asynchronous call that binds policy rule id
```

2020-08-24 17:23 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/sgw/pgw_handlers.h
> +    gtpv2c_cause_value_t cause, imsi64_t imsi64, const char* imsi,
Passing both imsi64 and imsi seems overloaded. Can we use IMSI64_TO_STRING macro to convert "imsi64" parameter to "char* imsi"?

2020-08-24 17:57 UTC, ssanadhya approved these changes

2020-08-24 18:56 UTC, uri200 approved these changes

2020-08-24 19:42 UTC, merged