[orc8r][migrations] Update migration for QoS changes
magma/magma pull request #2479
Opened 2020-08-26 01:20 UTC by hcgatewood

## Summary

This is the migration for #2391.

## Test Plan

- [x] Manually validate against prod db copy
- [ ] Fully validate (deferring to #2391)

## Additional Information

- [ ] This change is backwards-breaking

2020-08-26 08:07 UTC, xjtian requested changes
Synced offline about upserts and deterministic pk generation

2020-08-26 08:07 UTC, xjtian commented on lte/cloud/go/tools/migrations/m012_policy_qos/main.go
> +			OnConflict(nil, entNidCol, entTypeCol, entKeyCol)
does this actually need to be an upsert? we shouldn't have any policy qos profile entities in the db already right?

2020-08-26 19:46 UTC, uri200 approved these changes

2020-08-27 00:14 UTC, xjtian approved these changes

2020-08-27 00:14 UTC, merged