[WIP][lte][agw] Add ovpn service wrapper to AGW
magma/magma pull request #2505
Opened 2020-08-27 19:58 UTC by ardzoht

## Summary

- Added openvpn service wrapper to AGW magma services
- Added openvpn dependency on ansible 
- Preburned new box with openvpn pkg installed
- WIP: Added retrieval of VPN certs to bootstrap_manager process on magmad from boostrapper

## Test Plan

- Spinning off a new VM to check openvpn is installed
- Activating ovpn service locally to check status

## Additional Information

- [ ] This change is backwards-breaking

2020-08-28 07:11 UTC, xjtian requested changes

2020-08-28 07:11 UTC, xjtian commented on lte/gateway/deploy/roles/magma/files/systemd/magma_ovpn.service
> +Description=Magma %i service
Can you use the placeholder in a service file that's fully-qualified? I think you should type it all out your self anyways

2020-08-28 07:11 UTC, xjtian commented on lte/gateway/deploy/roles/magma/files/systemd/magma_ovpn.service
> +SyslogIdentifier=%i
openvpn

2020-08-28 07:11 UTC, xjtian commented on orc8r/gateway/python/magma/magmad/bootstrap_manager.py
> +                client.RequestVPNCert.future(Void()),
Does this resolve to anything? I don't see the diff for the RPC method on this PR

2021-02-10 19:57 UTC, closed without merging

2021-02-10 19:57 UTC, karthiksubraveti commented
OLD PR will close this. @ardzoht will fix this once the dependencies are done.