[agw][new feature] Idle mode support for multiple pdns and multiple dedicated bearers
magma/magma pull request #2519
Opened 2020-08-28 11:24 UTC by pruthvihebbani

[agw][new feature] Idle mode support for multiple pdns and multiple dedicated bearers

## Summary

This PR has code to re-establish the PDN/s and dedicated bearer/s after UE come back from idle mode

## Test Plan
1. Verified S1 SIM sanity
2. Added a new TC test_attach_service_with_multi_pdns_and_bearers.py to verify the feature

## Additional Information

2020-08-31 00:41 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
> +          gtp_tunnel_ops->send_end_marker(enb, modify_bearer_pP->teid);
The end marker should be sent before the tunnel rule is deleted. Why did the ordering has changed here?

2020-08-31 00:49 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
> +static void populate_sgi_end_point_update(
Could you put a comment about the function? Also in the signature, it is better to put the arguments to be modified in the function call at the end for readability.

2020-08-31 00:50 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
> +    uint8_t sgi_rsp_idx, uint8_t* idx, imsi64_t imsi64) {
is there a reason why idx is passed as a pointer and not passed by value as uint8_t?

2020-08-31 01:16 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
> +  sgw_handle_sgi_endpoint_updated(&sgi_update_end_point_resp, imsi64);
move this to the end of the `if (bearer_ctxt_info_p) { ` to make it more readable as this is only supposed to be done when the if statement is true.

2020-08-31 01:22 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
>      OAILOG_FUNC_RETURN(LOG_SPGW_APP, rv);
can be handled by line 898 once line 897 is moved into the if clause....

2020-09-01 03:01 UTC, ulaskozat approved these changes
LGTM

2020-09-01 05:25 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
> +  OAILOG_FUNC_OUT(LOG_MME_APP);
Also add a corresponding OAILOG_FUNC_IN call at the beginning of the function

2020-09-01 05:25 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
> +  OAILOG_FUNC_OUT(LOG_MME_APP);
Add OAILOG_FUNC_IN too at the beginning of the function

2020-09-01 05:25 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
> +    itti_s11_modify_bearer_request_t* s11_modify_bearer_request, uint8_t pid,
Remove the "pid" argument as it is not used in this function.

2020-09-01 05:25 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
> +      GLOBAL_UNICAST_IPv4;                          // TODO
Add little more context on what is TODO here

2020-09-01 22:32 UTC, ulaskozat requested changes
When tested with real UE and eNB, the bearers that are re-established do not have the correct TFT rules and priorities installed.

2020-09-03 03:36 UTC, ulaskozat approved these changes

2020-09-03 03:39 UTC, merged