Add CPU usage to Gateway detail view
magma/magma pull request #2567
Opened 2020-09-01 20:43 UTC by HannaFar

Signed-off-by: HannaFar <hannafarag159@gmail.com>

## Summary
Add CPU usage to Gateway detail view

2020-09-01 21:29 UTC, karthiksubraveti commented on nms/app/packages/magmalte/app/views/equipment/GatewayDetailStatus.js
> +      query: `cpu_percent{gatewayID=~"${gwInfo.id}", service="magmad"}`,
Hey Hanna, Why do we have gatewayID=~"${gwInfo.id}" and why gatewayID="${gwInfo.id}" ?

2020-09-01 21:30 UTC, karthiksubraveti commented on nms/app/packages/magmalte/app/views/equipment/GatewayDetailStatus.js
> +      start: startTime.toString(),
this can be omitted I think

2020-09-01 22:56 UTC, karthiksubraveti approved these changes

2020-09-02 02:34 UTC, xjtian requested changes

2020-09-02 02:34 UTC, xjtian commented on nms/app/packages/magmalte/app/views/equipment/GatewayDetailStatus.js
> +        value: cpuPercent?.data?.result?.[0]?.values?.[0]?.[1] ?? '0',
Let's make the default value the string "Unknown"

2020-09-02 20:48 UTC, xjtian approved these changes

2020-09-02 20:48 UTC, merged