[orc8r][release] Add v1.2 orc8r upgrade docs
magma/magma pull request #2573
Opened 2020-09-01 22:53 UTC by hcgatewood

## Summary

Add docs to document the necessary steps to upgrade a v1.1 deployment to v1.2. The upgrade mainly focuses on upgrading Helm 2 to Helm 3, aside from the normal upgrade requirements.

Also included: fixed the "hidden proposals" issue by moving them to a canonical location and exposing them via the docusaurus sidebar

Internal notes

- The v1.2 branch doesn't exist yet, so you'll need to target master
- After moving the Helm 2 config to Helm 3, I had to `helm repo remove local` to successfully `terraform apply` -- not sure if that was a quirk or a general requirement

## Test Plan

- [x] Document upgrade steps
- [x] Hit an orc8r api endpoint on the "v1.2" deployment
- [ ] Dogfood the upgrade (deferring to datapath validation scheduled for ~Wed)

## Additional Information

- [ ] This change is backwards-breaking

2020-09-01 23:02 UTC, hcgatewood commented on docs/readmes/orc8r/upgrade_1_2.md
> +---
This file contains the v1.2 upgrade instructions

2020-09-02 04:47 UTC, xjtian requested changes

2020-09-02 04:47 UTC, xjtian commented on docs/readmes/orc8r/deploy_install.md
> +- `seed_certs_dir`: `"~/secrets/certs"` (local certs directory)
this is something that's configurable and we should continue to call it out as such

2020-09-02 04:47 UTC, xjtian commented on docs/readmes/orc8r/upgrade_1_1.md
> +$ terraform state mv -state-out=NEWTF/terraform.tfstate 'data.template_file.metrics_userdata' 'data.template_file.metrics_userdata'
The $ prompts are superfluous and left out on purpose so that some of these blocks can be copy-pasted as-is into a terminal, all lines at once. Obviously doesn't work for this specific block but for others it will. Bash blocks that also show sample output have the $ prompts in them to indicate what's a command and what's output

2020-09-02 04:47 UTC, xjtian commented on orc8r/cloud/go/tools/migrations/doc.go
> +	- Safe to downgrade
This actually isn't something we care to maintain in software when a DB snapshot will do you just fine

2020-09-02 04:47 UTC, xjtian commented on docs/readmes/orc8r/upgrade_1_2.md
> +there will be nonzero data loss until you upgrade to v1.2 or fall back to a DB
"data loss" is too scary, just call it a nonreversible schema change

2020-09-02 20:44 UTC, xjtian commented
Bump the helm chart versions too: https://github.com/magma/magma/pull/2589

2020-09-03 17:07 UTC, xjtian approved these changes

2020-09-03 17:07 UTC, merged