[lte][cwf][orc8r] Split relay_enabled flag to separate support for hss and gx_gy
magma/magma pull request #2574
Opened 2020-09-02 00:31 UTC by andreilee

Signed-off-by: Andrei Lee <andreilee@fb.com>

## Summary

- Split API endpoints for `relay_enabled` for `hss_relay_enabled` and `gx_gy_relay_enabled`
- Split support for `relay_enabled` in mconfigs
- Each gateway service is now changed for split relay support

## Test Plan

-

## Additional Information

- [x] This change is backwards-breaking

2020-09-08 21:49 UTC, ssanadhya approved these changes
Changes to MME (which are all from PR 2575) look good to me

2020-09-09 11:25 UTC, themarwhal approved these changes

2020-09-09 11:26 UTC, themarwhal commented
looks like orc8r test if failing though

2020-09-11 02:18 UTC, xjtian requested changes, later dismissed

2020-09-11 02:18 UTC, xjtian commented on lte/cloud/go/tools/migrations/m013_relay_split/types/new.go
> +	Ran *NetworkRanConfigs `json:"ran"`
For the fields that you're not migrating, you should just use `json.RawMessage`

2020-09-11 02:18 UTC, xjtian commented on lte/cloud/go/tools/migrations/m013_relay_split/main.go
> +		old := types.OldNetworkCellularConfigs{}
declare this closer to where it's used

2020-09-11 02:18 UTC, xjtian commented on lte/cloud/go/tools/migrations/m013_relay_split/main.go
> +		updateConf := updateConfByNid[nid]
use the 2-arg version of range

2020-09-11 02:18 UTC, xjtian commented on orc8r/cloud/go/tools/migrations/m013_relay_split/main.go
> +/*
delete this file

2020-09-15 02:14 UTC, xjtian submitted a review, later dismissed

2020-09-15 02:14 UTC, xjtian commented on orc8r/cloud/go/service/middleware/unary/identity_decorator.go
> +	//}
revert this

2020-09-22 07:06 UTC, xjtian approved these changes

2020-09-22 07:06 UTC, merged