[orc8r][lte][cwf] Split support of relay_enabled for hss and gx_gy on gateway
magma/magma pull request #2575
Opened 2020-09-02 01:06 UTC by andreilee

Signed-off-by: Andrei Lee <andreilee@fb.com>

## Summary

- proto messages modified to mark `relay_enabled` as `DEPRECATED`, but they are not disabled fields
- proto messages to add `hss_relay_enabled` and `gx_gy_relay_enabled`, but these fields are only read in the gateway
- cwf gateway integ tests modified for relay split
- `sessiond` internally renames `relay_enabled` to `gx_gy_relay_enabled`
- `mme` internally renames `relay_enabled` to `hss_relay_enabled`

## Test Plan

- new unit tests

## Additional Information

- [ ] This change is backwards-breaking

2020-09-03 15:58 UTC, themarwhal approved these changes
SessionD changes lgtm

2020-09-03 16:38 UTC, ssanadhya requested changes

2020-09-03 16:38 UTC, ssanadhya commented on lte/gateway/c/oai/include/pgw_config.h
> +  bool hss_relay_enabled;
Remove this as relay_enabled is not used in the SPGW task any more. All session messages are sent to SessionD.

2020-09-03 16:38 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/sgw/pgw_config.c
> +        config_pP->hss_relay_enabled = true;
Remove this config as it is not used anywhere.

2020-09-04 02:49 UTC, uri200 approved these changes

2020-09-07 06:48 UTC, xjtian approved these changes

2020-09-07 06:48 UTC, xjtian commented on lte/cloud/go/services/cellular/protos/cellular_service.proto
> +    // DEPRECATED
This entire package is deprecated actually (there are no usages of it and there shouldn't be). Looks like I just forgot to clean this up with the configurator migration a long time ago. You can revert this change, I'll rm this package myself

2020-09-08 21:46 UTC, ssanadhya approved these changes
Changes to MME service look good to me.

2020-09-09 22:02 UTC, merged