[5G: MVC] [SessionD] AMF Client Stub for SessionD Process
magma/magma pull request #2582
Opened 2020-09-02 08:56 UTC by rupa455

Signed-off-by: rupa455 <rupa.d@altencalsoftlabs.com>

## Summary

This file contains AMF Client Stub to send GRPC request to initiate SessionD process

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2020-09-02 09:28 UTC, sureshgorijavolu commented on lte/gateway/c/session_manager/test/test_stubs/amf_client.h
> +}
check indentation

2020-09-02 09:29 UTC, sureshgorijavolu commented on lte/gateway/c/session_manager/test/test_stubs/amf_client.h
> +};
check indentation

2020-09-02 09:30 UTC, sureshgorijavolu commented on lte/gateway/c/session_manager/test/test_stubs/amf_client.cpp
> +}
check indentation

2020-09-04 15:29 UTC, themarwhal commented
Have you looked into creating the client test script in Python? It can be done much shorter. `magma/lte/gateway/python/scripts` for other client scripts.

2020-09-08 20:15 UTC, themarwhal requested changes
Please provide some documentation on how to use this AMF client stuf, although I think it might be simpler to do this in Python as I wrote before.

2020-09-09 03:53 UTC, rupa455 commented
Hi Marie, 

Yes marie, i am following python test scripts for creating the client.sorry for the late response. 

Thanks & Regards, 
Rupa.D 


From: "Marie" <notifications@github.com> 
To: "magma/magma" <magma@noreply.github.com> 
Cc: "Rupa Dangudubiyyam" <rupa.d@altencalsoftlabs.com>, "Assign" <assign@noreply.github.com> 
Sent: Friday, September 4, 2020 9:00:10 PM 
Subject: Re: [magma/magma] [5G: MVC] [SessionD] AMF Client Stub for SessionD Process (#2582) 





Have you looked into creating the client test script in Python? It can be done much shorter. magma/lte/gateway/python/scripts for other client scripts. 

— 
You are receiving this because you were assigned. 
Reply to this email directly, [ https://github.com/magma/magma/pull/2582#issuecomment-687220974 | view it on GitHub ] , or [ https://github.com/notifications/unsubscribe-auth/AOHLAMNRVZZEDCBJ5HELMKDSEEBYFANCNFSM4QSYDKNA | unsubscribe ] .

2020-09-09 03:59 UTC, rupa455 commented
> 
> 
> Please provide some documentation on how to use this AMF client stuf, although I think it might be simpler to do this in Python as I wrote before.


> 
> 
> Have you looked into creating the client test script in Python? It can be done much shorter. `magma/lte/gateway/python/scripts` for other client scripts.

Yes marie, i am following python test scripts for creating the client

2020-09-09 04:02 UTC, rupa455 commented
> 
> 
> Have you looked into creating the client test script in Python? It can be done much shorter. `magma/lte/gateway/python/scripts` for other client scripts.

Yes marie, i am following python test scripts for creating the client

2020-09-09 04:04 UTC, rupa455 commented
> 
> 
> Please provide some documentation on how to use this AMF client stuf, although I think it might be simpler to do this in Python as I wrote before.

Sure we will provide the documentation.

2020-09-17 07:46 UTC, closed without merging