[orc8r][service_registry] Implement service registry service for orc8r service mesh
magma/magma pull request #2730
Opened 2020-09-13 00:05 UTC by mpgermano

Signed-off-by: mgermano <mgermano@fb.com>

## Summary

This PR implements the service registry service that will support service discovery
for the orc8r service mesh. This registry has two modes, set via env-var to back the registry
by either Docker or Kubernetes. This will allow us to continue to develop with docker-compose.

A stacked PR will add the necessary changes to the service registry client to flip this service to
in-use. This will also include the necessary helm chart changes that are needed.

## Test Plan

Added unit test.

For docker, add labels to `controller` container. Use a CLI to ensure
that each RPC call returns the expected values.

For K8s, deploy the code to minikube, create necessary service-reader role, serviceAccount, and roleBinding.
Use CLI to ensure each RPC call returns the expected values.

2020-09-14 23:51 UTC, uri200 commented on orc8r/cloud/go/services/service_registry/servicers/docker_servicer.go
> +	if req == nil {
Not sure if this is an implementation of GRPC service. But if so, is it possible req is ever nil, and we may not need this? Will not the GRPC client always create a default req?

If not GRPC implementation, then disregard the comment

2020-09-15 07:21 UTC, xjtian requested changes

2020-09-15 07:21 UTC, xjtian commented on orc8r/cloud/docker/docker-compose.yml
> +      SERVICE_REGISTRY_MODE: "0" # Docker backed service registry
let's use string values for this: `docker`, `k8s`, `yml`, etc

2020-09-15 07:21 UTC, xjtian commented on orc8r/cloud/go/services/service_registry/service_registry/main.go
> +	case "0":
let's make these strings and declare them as consts somewhere

2020-09-15 07:21 UTC, xjtian commented on orc8r/cloud/go/services/service_registry/servicers/docker_servicer.go
> +		services = append(services, serviceName)
some context here as to what the docker API returns and why you're doing the postprocessing would be useful

2020-09-15 07:21 UTC, xjtian commented on orc8r/cloud/go/services/service_registry/servicers/docker_servicer.go
> +		services = append(services, serviceName)
pull this code out into a helper, it's repeated from above

2020-09-15 07:21 UTC, xjtian commented on orc8r/cloud/go/services/service_registry/servicers/kubernetes_servicer.go
> +		ret.Services = append(ret.Services, splitSvcName[svcNameIndex])
same as for the other servicer, factor this out and add some context as to what you're doing here

2020-09-21 23:15 UTC, xjtian approved these changes

2020-09-21 23:15 UTC, merged