[orc8r] Moving DNS network configs to gateway cellular configs level
magma/magma pull request #2801
Opened 2020-09-17 00:22 UTC by ardzoht

## Summary

- This updates the network DNS configs, moving them from orc8r to lte module
- This also makes the configs part of LTE gateway cellular config, with same default values as before
- Updating orc8r/mconfigs dnsd entry and moving it to lte/mconfigs

## Test Plan

- make precommit
- Tested locally with orc8r and AGW
- Validated gateway.mconfig successfully builds on local AGW with cloud configs on Orchestrator

## Additional Information

- [ x] This change is backwards-breaking

- This updates cloud configurations that affect backwards compatibility, I manually checked prod networks and all of them contain the default values, we may include a data migration to fill all gateways with the values from network configs but these all contain defaults.

2020-09-18 06:52 UTC, xjtian requested changes

2020-09-18 06:52 UTC, xjtian commented on lte/cloud/go/services/lte/servicers/builder_servicer.go
> +			LocalTTL:          int32(swag.Uint32Value(gwDns.LocalTTL)),
let's make this a uint32 in the proto file to avoid the cast

2020-09-18 06:52 UTC, xjtian commented on lte/cloud/go/services/lte/servicers/builder_servicer.go
> +		protos.FillIn(record, recordProto)
How many fields are here? I'd prefer just instantiating the whole struct in-place for readability if it's <10 fields to fill. Gets rid of a tricky hidden coupling between the proto and swagger struct as well

2020-09-18 06:52 UTC, xjtian commented on lte/cloud/go/services/lte/obsidian/models/conversion.go
> +	*m = *cellularConfig.DNS
this can npe: https://play.golang.org/p/2jc3q1h10wU

2020-09-18 06:52 UTC, xjtian commented on lte/cloud/go/services/lte/obsidian/models/conversion.go
> +	*m = cellularConfig.DNS.Records
nilcheck here as well, cellularConfig.DNS can be nil since the field is optional

2020-09-18 06:53 UTC, xjtian commented
NVM not breaking. Just to double-check: the default mconfig value if this is not specified on the gw config is appropriate for vanilla AGW deployments?

2020-09-18 06:53 UTC, xjtian commented
Loop back with @karthiksubraveti on appropriate NMS changes please

2020-09-18 18:11 UTC, ardzoht commented
> NVM not breaking. Just to double-check: the default mconfig value if this is not specified on the gw config is appropriate for vanilla AGW deployments?

Yeah for GWs with unspecified DNS config the generated mconfig will contain the expected default values to have a working AGW.

2020-09-21 23:49 UTC, xjtian approved these changes

2020-09-21 23:50 UTC, merged