Fixed multi UE data test cases
magma/magma pull request #2864
Opened 2020-09-22 03:52 UTC by VinashakAnkitAman

## Title
[Data_Testing] Fixed multi UE data test cases

## Summary

The multi UE data test cases were failing and getting stuck for some random UE. This PR fixes one part of the issue where it was not handling EMM information message.

## Test Plan

Verified with Sanity and multiple runs of multi UE data test cases.

2020-10-16 18:36 UTC, ssanadhya approved these changes

2020-10-16 18:38 UTC, ssanadhya requested changes
@VinashakAnkitAman , I merged PR 2933 before merging this one so it is showing merge conflicts again. Could you please rebase and resolve the conflicts?

2020-10-18 08:25 UTC, VinashakAnkitAman commented
> @VinashakAnkitAman , I merged PR 2933 before merging this one so it is showing merge conflicts again. Could you please rebase and resolve the conflicts?

Hi @ssanadhya , I have rebased the code and resolved the merge conflicts. Now this PR can be pulled.

2020-10-18 21:20 UTC, ssanadhya approved these changes

2020-10-18 21:20 UTC, merged