Added testcase to validate Paging Response timer while mme restarts
magma/magma pull request #2928
Opened 2020-09-25 09:55 UTC by rsarwad

## Title [s1ap tester] Added test case to validate Paging Response timer while mme restarts

## Summary
The test case validates the handling of Paging Response timer while mme restarts. 
After mme restarts if timer has not expired, then mme shall start the timer with remaining duration.

Signed-off-by: rashmi <rashmi.sarwad@radisys.com>

2020-09-29 05:24 UTC, ssanadhya commented on lte/gateway/python/integ_tests/s1aptests/test_paging_with_mme_restart.py
> +        # column is a enb parameter,  row is a number of enbs
Lines 45-49 are not needed in this test case

2020-09-29 05:25 UTC, ssanadhya commented on lte/gateway/python/integ_tests/s1aptests/test_paging_with_mme_restart.py
> +            # Below commented lines needs to be uncommented in case if
Please include a reference to the configuration of paging response timer here.

2020-09-29 05:27 UTC, ssanadhya commented on lte/gateway/python/integ_tests/s1aptests/test_paging_with_mme_restart.py
> +            # Below commented lines needs to be uncommented in case if
Also add a comment that with current timer value, the timer expires by the time MME restarts and Paging indication is not re-transmitted.

2020-09-29 05:28 UTC, ssanadhya approved these changes

2020-09-29 05:28 UTC, ssanadhya commented on lte/gateway/python/integ_tests/s1aptests/test_paging_with_mme_restart.py
> +        # column is a enb parameter,  row is a number of enbs
Lines 45-49 are not needed in this test case

2020-09-29 05:29 UTC, ssanadhya requested changes

2020-09-29 05:29 UTC, ssanadhya commented on lte/gateway/python/integ_tests/s1aptests/test_paging_with_mme_restart.py
> +        # column is a enb parameter,  row is a number of enbs
Lines 45-49 are not needed in this test case

2020-09-29 22:16 UTC, ssanadhya requested changes

2020-09-29 22:16 UTC, ssanadhya commented on lte/gateway/python/integ_tests/s1aptests/test_paging_with_mme_restart.py
> +        Step5 : In response to Paging message, s1ap sends Service Request message
```suggestion
        Step5 : In response to Paging message, UE sends Service Request message
```

2020-09-29 22:16 UTC, ssanadhya commented on lte/gateway/python/integ_tests/s1aptests/test_paging_with_mme_restart.py
> +             macro, MME_APP_PAGING_RESPONSE_TIMER_VALUE. With current timer
```suggestion
             macro, MME_APP_PAGING_RESPONSE_TIMER_VALUE in mme.conf.template. With current timer
```

2020-09-29 22:16 UTC, ssanadhya commented on lte/gateway/python/integ_tests/s1aptests/test_paging_with_mme_restart.py
> +             Paging Response timer is configured more than mme restart time
```suggestion
             Paging Response timer is configured more than mme restart time (~40 seconds)
```

2020-09-30 04:28 UTC, rsarwad commented on lte/gateway/python/integ_tests/s1aptests/test_paging_with_mme_restart.py
> +            ser_req.rrcCause = s1ap_types.Rrc_Cause.TFW_MO_DATA.value
```suggestion
            ser_req.rrcCause = s1ap_types.Rrc_Cause.TFW_MT_DATA.value
```

2020-10-05 20:42 UTC, ssanadhya commented
@rsarwad Can you rebase this on latest master and confirm that `make run` succeeds. https://jenkins.magmacore.org/blue/organizations/jenkins/magma_integration_tests/detail/magma_integration_tests/448/pipeline shows that `make run` is failing.

2020-11-19 05:59 UTC, ssanadhya approved these changes

2020-11-19 06:00 UTC, merged