[s1 sim testcases] New test cases to test handling of activate default eps bearer…
magma/magma pull request #2942
Opened 2020-09-28 12:12 UTC by pruthvihebbani

… context reject sent by UE

Signed-off-by: Pruthvi Hebbani <pruthvi.hebbani@radisys.com>

[s1 sim testcases] New test cases to test handling of activate default eps bearer context reject sent by UE

## Summary

-	This PR contains new s1 sim test cases to test handling of Activate default EPS bearer context reject message

## Test Plan

Verified s1sim sanity

Note- This PR has dependency on magma PR #2941 and s1ap tester PR #36

2020-09-29 18:46 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej.py
> +class TestAttachStandaloneActvDfltBearCtxtRej(unittest.TestCase):
can you add description?

2020-09-29 18:52 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej.py
> +        )
Are we sending anything? What is the purpose of the second PDN connection request?

2020-09-29 18:53 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
> +    unittest.TestCase
add description for the test scenario.

2020-09-29 18:54 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
> +        act_def_bearer_req = response.cast(s1ap_types.uePdnConRsp_t)
what is the purpose of this second request?

2020-09-29 18:55 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
> +            % (req.ue_id, act_def_bearer_req.m.pdnInfo.epsBearerId)
I don't see any rejection being sent?

2020-09-29 18:56 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
> +        # Now detach the UE
how do you verify that dedicated bearer will not be established?

2020-09-29 18:56 UTC, ulaskozat requested changes
Added comments that require revision.

2020-10-07 05:57 UTC, pruthvihebbani commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej.py
> +class TestAttachStandaloneActvDfltBearCtxtRej(unittest.TestCase):
Description is there at line 30. For all the test cases description is usually added when we define the function

2020-10-07 05:57 UTC, pruthvihebbani commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej.py
> +        )
As mentioned in the description at line 30, this test case tests sending of activate default bearer reject for the secondary PDN. We already have a testcase to send activate default bearer reject along with attach complete during attach procedure "test_attach_act_dflt_ber_ctxt_rej.py"

2020-10-07 05:57 UTC, pruthvihebbani commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
> +    unittest.TestCase
Description is there at line 36. For all the test cases description is added when we define the function

2020-10-07 05:57 UTC, pruthvihebbani commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
> +            % (req.ue_id, act_def_bearer_req.m.pdnInfo.epsBearerId)
In line 174, UE_STANDALONE_ACTV_DEFAULT_EPS_BEARER_CNTXT_REJECT command is issued to the tfwApp which sets a flag is the ueCb. When ueApp receives activate default eps bearer req and if the flag is set in ueCb, ueApp sends activate default eps bearer reject message instead of accept

2020-10-07 05:57 UTC, pruthvihebbani commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
> +        act_def_bearer_req = response.cast(s1ap_types.uePdnConRsp_t)
As the name of the testcase indicates, the purpose of this test case is to test sending of activate default bearer reject for the secondary pdn. We already have a testcase to test activate default bearer reject sent along with attach complete i.e during attach

2020-10-07 05:57 UTC, pruthvihebbani commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
> +        # Now detach the UE
We have to verify in the pcap and mme logs

2020-10-08 00:12 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej.py
> +        )
Can you move this print statement before line 92?

2020-10-08 03:34 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
> +        # Now detach the UE
We can check the OVS rules here, can't we?

2020-10-08 03:37 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej.py
> +        )
disregard my previous comment. I got the answer in the other test case.

2020-10-08 03:39 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
> +
can we add a check for OVS rules?

2020-10-13 03:04 UTC, ulaskozat approved these changes
LGTM

2020-10-13 03:05 UTC, merged