AGW: SGW: Create separate tunnel for each eNodeB
magma/magma pull request #2954
Opened 2020-09-28 23:29 UTC by pshelar

## Summary

This patch create separate tunnel to each eNodeB on UE attach.
These tunnel are useful to track stats for each eNodeB.

This is feature is flag protected.

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>

## Test Plan
- [ ]  make test
- [ ] integ tests

## Additional Information

- [ ] This change is backwards-breaking

2020-09-29 23:23 UTC, ardzoht approved these changes
lgtm, please take a look at the merge conflict

2020-09-29 23:40 UTC, koolzz approved these changes
LGTM

2020-09-29 23:40 UTC, koolzz commented on lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
> + * generate GTP port name from eNodeB IP address
[nit] Generate

2020-09-30 04:37 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
> +      goto out;
why not simply use break?

2020-09-30 04:57 UTC, ulaskozat approved these changes
You can avoid the goto statement and section. Please check the test cases that are not added to the sanity yet to make sure that they are not broken.

2020-09-30 05:06 UTC, ulaskozat requested changes
There are test cases that are not part of sanity and uses GTP_PORT. Via grep on GTP_PORT, I can see the following tests dependent on this parameter.

```
s1aptests/test_attach_service_with_multi_pdns_and_bearers_failure.py:    GTP_PORT = 32768
s1aptests/test_attach_detach_rar_tcp_data.py:    GTP_PORT = 32768
s1aptests/test_attach_detach_rar_tcp_data.py:                        "match": {"in_port": self.GTP_PORT},
s1aptests/test_attach_service_with_multi_pdns_and_bearers_multi_ue.py:    GTP_PORT = 32768
s1aptests/test_attach_service_with_multi_pdns_and_bearers_mt_data.py:    GTP_PORT = 32768
s1aptests/test_attach_detach_with_ovs.py:    GTP_PORT = 32768
s1aptests/test_attach_detach_with_ovs.py:                                      "match": {"in_port": self.GTP_PORT}})
s1aptests/s1ap_utils.py:    GTP_PORT = 32768
s1aptests/s1ap_utils.py:                    "match": {"in_port": self.GTP_PORT},
s1aptests/test_attach_asr.py:    GTP_PORT = 32768
s1aptests/test_attach_detach_multiple_rar_tcp_data.py:    GTP_PORT = 32768
s1aptests/test_attach_detach_multiple_rar_tcp_data.py:                        "match": {"in_port": self.GTP_PORT},
s1aptests/test_dedicated_bearer_activation_idle_mode.py:    GTP_PORT = 32768

```

2020-09-30 05:22 UTC, pshelar commented
I am not able to find test_attach_service_with_multi_pdns_and_bearers_mt_data.py, test_attach_service_with_multi_pdns_and_bearers_multi_ue.py and other tests are already fixed in PR, can you clarify here.

2020-09-30 15:42 UTC, ulaskozat approved these changes
LGTM

2020-09-30 15:48 UTC, merged