[backport-v1.2] build: avoid git-cherry-pick ovs build script
magma/magma pull request #2998
Opened 2020-09-30 18:59 UTC by pshelar

## Summary

`git cherry-pick` needs git config on the build host. This patch
uses `git apply` to remove this requirement to fix AGW deployment.

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>

## Test Plan
ran ovs build script build-ovs.sh

## Additional Information

- [ ] This change is backwards-breaking

2020-09-30 23:28 UTC, ardzoht approved these changes

2020-10-06 07:42 UTC, xjtian commented
Rebase onto master and update the target branch here. We can pick it onto the release branch once it lands there.

2020-10-06 07:42 UTC, xjtian requested changes
see comment

2020-10-07 16:14 UTC, pshelar commented
@xjtian This patch is already merged to master. This patch is fox backport only.

2020-10-07 19:07 UTC, xjtian approved these changes

2020-10-07 19:07 UTC, merged