[smsd] Add API handlers for SMS management
magma/magma pull request #3032
Opened 2020-10-02 21:48 UTC by xjtian

Signed-off-by: Jacky Tian <xjtian@fb.com>

## Summary

- List, create, and delete handlers for SMS messages on the API
- This adds a new CRUD servicer that backs the API handlers, since the gateway-facing servicer interface doesn't cover the API user-cases

## Test Plan

- Clicked around the local API after building. No unit tests for this in the interest of time, plus these handlers are dead simple wrappers around storage.

## Additional Information

- [ ] This change is backwards-breaking

2020-10-02 21:58 UTC, mpgermano approved these changes

2020-10-02 21:58 UTC, mpgermano commented on lte/cloud/configs/service_registry.yml
> +    labels:
Reminder to add this service and labels to the lte-orc8r helm chart

2020-10-03 01:05 UTC, shaddi requested changes
Overall looks good to me, but we need to add an endpoint to get the status of a single message (by SMS id) as well.

2020-10-03 01:05 UTC, shaddi commented on lte/cloud/go/services/smsd/client_api.go
> +func ListMessages(networkID string) ([]*storage.SMS, error) {
Let's add an endpoint to get the status of a specific message by PK, rather than only having the option to return all messages.

2020-10-06 00:04 UTC, merged