SPGW: OAI: GTP: introduce IPv6 support
magma/magma pull request #3085
Opened 2020-10-06 15:47 UTC by pshelar

## Summary

This patch adds support for UE ipv6 flow generation. It uses
existing OpenFlow controller events to propagate IPv6 info from
SPGW to GTP APP.
IPV6 support for default brr and dedicated brr is added.

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>

## Test Plan
`make test_oai`

## Additional Information

- [ ] This change is backwards-breaking

2020-10-13 18:09 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/gtpv1-u/gtpv1u.h
> +  };
did you apply clang?

2020-10-13 18:22 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/gtpv1-u/gtpv1u.h
>  struct ipv4flow_dl {
if this is no longer specific to IPv4, we should change the name to ipflow_dl

2020-10-13 18:52 UTC, ulaskozat requested changes
Some nits need to be addressed.

2020-10-13 19:01 UTC, pshelar commented on lte/gateway/c/oai/tasks/gtpv1-u/gtpv1u.h
> +  };
nope, let me try it.

2020-10-15 18:23 UTC, ulaskozat approved these changes
LGTM

2020-10-15 19:12 UTC, merged