[orc8r][docs][helm] Minikube documentation
magma/magma pull request #3247
Opened 2020-10-15 17:55 UTC by Scott8440

Signed-off-by: Scott8440 <scott8440@gmail.com>

## Summary
* Document minikube development process in one place with all required steps
* Fix bug in secrets chart so this deployment actually works

## Test Plan
Docs generated:
![image](https://user-images.githubusercontent.com/13274915/96167782-b952d080-0ed4-11eb-9ebc-b0e338008d32.png)

Follow documented process exactly, orc8r deployed and API works:
![image](https://user-images.githubusercontent.com/13274915/96167881-dbe4e980-0ed4-11eb-8c6a-f015bd1ff3ef.png

2020-10-23 05:53 UTC, xjtian requested changes

2020-10-23 05:53 UTC, xjtian commented on docs/docusaurus/i18n/en.json
> +        "title": "Service Restriction Feature"
what's going on here

2020-10-23 05:53 UTC, xjtian commented on docs/docusaurus/sidebars.json
> +      "development/minikube_deployment"
make this a subsection under Orchestrator "Development"

2020-10-23 05:53 UTC, xjtian commented on docs/readmes/development/minikube_deployment.md
> +```
I think you can just link to the relevant section of the deploy docs for all this "Build Orchestrator". Then if we change this procedure we can just update it in one place

2020-10-23 05:53 UTC, xjtian commented on docs/readmes/development/minikube_deployment.md
> +```
you wanna put this somewhere in the repo so it's tracked as code? `orc8r/cloud/helm/orc8r/examples` maybe? Or just under `orc8r/cloud/helm`?

2020-10-23 05:53 UTC, xjtian commented on docs/readmes/development/minikube_deployment.md
> +```
x-ref the corresponding portion of the deployment docs for these sections as well, and just keep the nginx port-forwarding part in this document

2020-10-23 20:00 UTC, Scott8440 commented on docs/docusaurus/i18n/en.json
> +        "title": "Service Restriction Feature"
whoops

2020-10-23 20:40 UTC, Scott8440 commented on docs/docusaurus/i18n/en.json
> +        "title": "Service Restriction Feature"
Ok actually this gets generated every time I run `yarn build`. I think last time someone did this it just wasn't build so these generated changes weren't produced.

2020-10-23 20:41 UTC, Scott8440 commented
Address comments. Move values file to code, link to existing documents.

2020-11-11 19:51 UTC, xjtian approved these changes

2020-12-03 20:02 UTC, merged