[NMS] Add support to configure AGW management network GW IP
magma/magma pull request #3259
Opened 2020-10-15 23:14 UTC by HannaFar

Signed-off-by: HannaFar <hannafarag159@gmail.com>

## Summary

Add support to configure AGW management network GW IP
<img width="1034" alt="Capture d’écran 2020-10-16 à 01 13 42" src="https://user-images.githubusercontent.com/26038920/96195376-eb077e00-0f4c-11eb-8427-fa1959de4982.png">

## Additional Information

- [ ] This change is backwards-breaking

2020-10-15 23:17 UTC, andreilee approved these changes

2020-10-15 23:45 UTC, karthiksubraveti reviewed
#3256 just merged which adds sgi_management_iface_gw attribute to the gateway epc struct. Can you rebase your branch and add a attribute for configuring that as well here. Thanks.

2020-10-15 23:45 UTC, karthiksubraveti requested changes
#3256 just merged which adds sgi_management_iface_gw attribute to the gateway epc struct. Can you rebase your branch and add a attribute for configuring that as well here. Thanks.

2020-10-15 23:46 UTC, karthiksubraveti reviewed
Also as @andreilee  mentioned in slack, Can you change the DNS field placeholders to show dummy IP addresses instead labels.

2020-10-16 11:48 UTC, karthiksubraveti commented on nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
> +          <AltFormField label={'SGI VLAN ID'}>
Can we display this only when the network is configured under bridged mode
https://github.com/magma/magma/blob/master/docs/readmes/howtos/ue_ip_address_management.md#agw-management-traffic.

2020-10-16 14:10 UTC, HannaFar commented on nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
> +          <AltFormField label={'SGI VLAN ID'}>
it's disabled when NATed mode is enabled . Should I not display it instead ?

2020-10-16 18:09 UTC, pshelar requested changes
Lets rename label "Gateway SGi IP" to "SGi network Gateway IP address"
Also we need to make it required field when static IP is configured.

2020-10-16 18:11 UTC, pshelar requested changes

2020-10-16 18:11 UTC, pshelar commented on nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
> +          <AltFormField label={'SGI Static IP'}>
Lets rename "SGI Static IP" to "SGi management interface IP address"

2020-10-16 18:11 UTC, pshelar commented on nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
> +            <AltFormField label={'SGI VLAN ID'}>
Lets rename "SGI VLAN ID" to "SGi management network VLAN id"

2020-10-19 12:54 UTC, karthiksubraveti approved these changes
Changes. LGTM. Thanks for fixing this

2020-10-19 12:54 UTC, karthiksubraveti commented on nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
> +              required={
Nice. I didn't know OutlinedInput takes in a required parameter.

2020-10-19 16:03 UTC, pshelar approved these changes

2020-10-19 16:12 UTC, merged