Modified code to wait until controller connects to switch
magma/magma pull request #3273
Opened 2020-10-16 18:05 UTC by rsarwad

Modified code to wait until controller connects to switch

2020-11-03 21:59 UTC, pshelar requested changes

2020-11-03 21:59 UTC, pshelar commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
> +    if (cv.wait_for(lck, std::chrono::seconds(CONNECTION_EVENT_WAIT_TIME)) ==
Can you call is_controller_connected_to_switch() function here.

2020-11-03 21:59 UTC, pshelar commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
> +  std::unique_lock<std::mutex> lck(cv_mutex);
there shld be log msg to indicate the process is waiting connection.

2020-11-04 17:07 UTC, pshelar approved these changes
Thanks for exploring all options and finishing this issue.

2020-11-04 18:25 UTC, ssanadhya requested changes

2020-11-04 18:25 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
> +    return -1;
Use RETURNError or RETURNok here

2020-11-04 18:25 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
> +    if (!is_controller_connected_to_switch(CONNECTION_EVENT_WAIT_TIME)) {
This appears as if we are checking for the failure of `is_controller_connected_to_switch`, instead can we do
```suggestion
    if (is_controller_connected_to_switch(CONNECTION_EVENT_WAIT_TIME) == RETURNok) {
```

2020-11-04 18:25 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.h
> +  bool is_controller_connected_to_switch(int);
Add comment describing the function intent

2020-11-04 18:25 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
> +        "threads \n");
No need for new line here

2020-11-05 09:55 UTC, rdefosse commented
RestartIntegrationTests

2020-11-05 10:57 UTC, 119Vik commented
RestartLTETests

2020-11-05 11:00 UTC, 119Vik commented
RestartIntegrationTests

2020-11-05 11:17 UTC, 119Vik commented
RestartIntegrationTests

2020-11-05 11:17 UTC, 119Vik commented
RestartLTETests

2020-11-05 11:26 UTC, 119Vik commented
RestartIntegrationTests

2020-11-06 03:54 UTC, rsarwad commented
> Thanks for exploring all options and finishing this issue.

I should be grateful for suggestion from you, Ulas and Shruti

2020-11-06 03:55 UTC, rsarwad commented
> RestartIntegrationTests

Should we restart test c

2020-11-06 03:55 UTC, closed without merging