[5G: MVC][component: agw][type: enhancement] NGAP module development #2036 NGAP_Initialization changes
magma/magma pull request #3355
Opened 2020-10-21 05:43 UTC by ashish-pr

Signed-off-by: ashish-pr <ashish.p@altencalsoftlabs.com>

## Summary

Ngap module initialization code 

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2020-10-21 06:35 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/ngap/ngap_state.h
> +uint64_t ngap_get_comp_ngap_id(
here and also in some places function signature is broken into multiple lines. can you fix it?

2020-10-21 06:35 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/ngap/ngap_state.h
> +    __attribute__((unused)) hash_key_t keyP, void* elementP, void* parameterP,
why function signature has to be in multiple lines

2020-10-21 06:35 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/ngap/ngap_state_converter.h
> +      const ngap_imsi_map_t* ngap_imsi_map, oai::NgapImsiMap* ngap_imsi_proto);
why function signature in multiple lines?

2020-10-21 06:35 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/ngap/ngap_state_converter.h
> +      const oai::Ngap_UeDescription& proto, m5g_ue_description_t* ue);
fix the signature

2020-10-21 06:35 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/ngap/ngap_state_manager.cpp
> +
on all files run clang format command

2020-10-26 05:28 UTC, ssanadhya reviewed
Some nit comments on first parse. Will continue reviewing further.

2020-10-26 05:28 UTC, ssanadhya commented on lte/gateway/c/oai/common/amf_default_values.h
> +/*
Please use the Magma copyright for any new additions, as seen here https://github.com/magma/magma/blob/master/lte/gateway/c/session_manager/AAAClient.cpp

2020-10-26 05:28 UTC, ssanadhya commented on lte/gateway/c/oai/include/amf_app_messages_def.h
> +/*
Please use Magma copyright

2020-10-26 05:28 UTC, ssanadhya commented on lte/gateway/c/oai/common/amf_default_values.h
> +#ifndef FILE_AMF_DEFAULT_VALUES_SEEN
Replace lines 31,32 and 75 with `#pragma once`

2020-10-26 05:28 UTC, ssanadhya commented on lte/gateway/c/oai/include/amf_app_messages_def.h
> +  \author Sebastien ROUX, Lionel Gauthier
Include correct author information

2020-10-26 05:28 UTC, ssanadhya commented on lte/gateway/c/oai/include/amf_app_messages_types.h
> +/*! \fopyright 2020 The Magma Authors.
```suggestion
/*  Copyright 2020 The Magma Authors.
```

2021-01-13 12:27 UTC, 119Vik commented
RestartCWAGTests

2021-01-28 14:52 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-02-10 08:08 UTC, sureshgorijavolu commented on lte/gateway/c/oai/include/amf_app_ue_context.h
> +  sgs_fsm_state_t sgs_state;
do we need these in 5G context?

2021-02-10 08:08 UTC, sureshgorijavolu commented on lte/gateway/c/oai/include/amf_app_ue_context.h
> +  /* SGS EPS Detach indication timer */
are we using these timers in 5G?

2021-02-10 08:08 UTC, sureshgorijavolu commented on lte/gateway/c/oai/lib/3gpp/3gpp_38.413.h
> +  // Additional DL QoS Flow per TNL Information //optional TODO
let us also indicate when these will be implemented.

2021-02-10 08:08 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/ngap/ngap_amf.c
> +#include "config.h"
is this required?

2021-02-10 08:08 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/ngap/ngap_amf.c
> +#include "amf_default_values.h"
is this needed? or you want to delete in later PR?

2021-02-10 08:08 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/ngap/ngap_amf.c
> +  // put_n1ap_state(); //TODO : implement
ngap_state()?

2021-02-10 08:08 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/ngap/ngap_amf.c
> +    OAILOG_ERROR(LOG_NGAP, " sending SCTP_INIT_MSG to SCTP \n");
log level has to be INFO in this case.

2021-02-10 19:08 UTC, ashish-pr commented on lte/gateway/c/oai/tasks/ngap/ngap_amf.c
> +  // put_n1ap_state(); //TODO : implement
Yes, ngap_state()

2021-02-10 19:30 UTC, ashish-pr commented on lte/gateway/c/oai/tasks/ngap/ngap_amf.c
> +#include "amf_default_values.h"
Yes, these headers are required.

2021-02-10 19:31 UTC, ashish-pr commented on lte/gateway/c/oai/tasks/ngap/ngap_amf.c
> +#include "config.h"
NO, removed

2021-02-22 00:48 UTC, ulaskozat requested changes
What is the purpose of using c constructs for hash tables? You should use standard c++ data structures for hash tables rather than using the hast table constructs used in 4G C code.

Also please rebase so that sctp and sctpd stuff that are already landed do not show up in this PR.

2021-02-22 00:48 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/ngap/ngap_amf.c
> +  message_p->ittiMsg.sctpInit.ngap_ppid    = NGAP_SCTP_PPID;
supposed to reuse port and ppid, rather than new fields.

2021-02-22 00:48 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/ngap/ngap_amf.c
> +    OAILOG_ERROR(LOG_NGAP, " sending SCTP_INIT_MSG to SCTP \n");
use brackets for else

2021-02-22 00:48 UTC, ulaskozat commented on lte/gateway/c/oai/oai_mme/oai_mme.c
> +                    TASK_S6A, TASK_S1AP, TASK_NGAP, TASK_SCTP, TASK_SPGW_APP,
remove TASK_NGAP from this list and activate the task optionally based on a converged core config parameter in mme.yml and mme.conf.template files (check stateless or HA services as examples)

2021-02-22 00:48 UTC, ulaskozat commented on lte/gateway/c/oai/common/amf_default_values.h
> +#define RELATIVE_CAPACITY (15)
as discussed these will be read from config with a later PR.

2021-02-22 00:48 UTC, ulaskozat commented on lte/gateway/c/oai/oai_mme/oai_mme.c
> +  CHECK_INIT_RETURN(ngap_amf_init(&amf_config));
start this task conditioned on the ENABLE_CONVERGED_CORE being set to True.

2021-02-22 00:48 UTC, ulaskozat commented on lte/gateway/c/oai/oai_mme/oai_mme.c
> +  CHECK_INIT_RETURN(ngap_amf_init(&amf_config));
also pass mme_config so that common configs can be read from mme configuration.

2021-02-22 00:48 UTC, ulaskozat commented on lte/gateway/c/oai/lib/3gpp/3gpp_38.331.h
> +
include standard copyright.

2021-02-22 00:48 UTC, ulaskozat commented on lte/gateway/c/oai/lib/3gpp/3gpp_38.401.h
> +  Author      Sandeep Kumar Mall
remove author name

2021-02-22 00:51 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/ngap/ngap_amf.c
> +#endif
are these used anywhere?

2021-03-24 17:54 UTC, ulaskozat commented
can we close this PR if no more applicable?

2021-03-24 17:57 UTC, ulaskozat commented
Closing this, if needed can be reopened...

2021-03-24 17:57 UTC, closed without merging