Bring in FeG helmchart
magma/magma pull request #340
Opened 2019-06-14 00:13 UTC by reddydodda

1. This chart will help to deploy feg on top of K8S with help of virtlet

2. virtlet is to be installed on k8s-worker nodes

	https://docs.virtlet.cloud/user-guide/real-cluster/

	https://github.com/Mirantis/virtlet

2019-06-20 05:45 UTC, mpgermano requested changes
Looks generally good. Requested changes are mostly cleanup.

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/.helmignore
> +# Patterns to ignore when building packages.
Can we change this top level directory to feg/gateway/helm to follow the pattern used at magma/orc8r/cloud

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/Chart.yaml
> +description: Magma Federated Gateway
Let's add `appVersion: "1.0"`

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/templates/bin/_install_gateway.sh.tpl
> +if ! cmp "$INSTALL_DIR"/magma/orc8r/tools/docker/install_gateway.sh /opt/magma/bin/install_gateway.sh; then
Let's remove this `if statement` since these will always differ

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/templates/bin/_install_gateway.sh.tpl
> +#sudo usermod -aG docker "$SUDO_USER"
You can remove this line altogether

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/README.md
> +    url: https://github.com/reddydodda/magma/
```suggestion
    url: https://github.com/facebookincubator/magma/
```

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/README.md
> +$ helm upgrade --install feg --namespace magma orc8r --values=vals.yaml
Should this be `.` and not orc8r?

```suggestion
$ helm upgrade --install feg --namespace magma . --values=vals.yaml
```

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/templates/helpers/pod_anti_affinity.tpl
> +{{/*
What is the purpose of this template?

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/README.md
> +   gwcert.key:              1679 bytes
The gwcert.key and gwcert.crt are only generated after the gw has been registered

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/README.md
> +4. build images for feg
```suggestion
4. Build images for feg
```

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/README.md
> +2. register the gateway with orchestrator
```suggestion
2. Register the gateway with the Orchestrator
```

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/README.md
> +2. check if rootCA,gwcert.crt and gecert.key certs present under secrets named `orc8r-secrets-certs`
The secret that must exist is the rootCA. gwcert.crt and gwcert.key are both generated during the bootstrap/registration process and hence won't exist until after installation.
```suggestion
2. Check if rootCA.pem is present under secrets named `orc8r-secrets-certs`
```

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/README.md
> +1. we will first need the orc8r to be setup
```suggestion
1. We will first need the orc8r to be setup
```

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/templates/deployment.yaml
> +            - name: orc8r-secrets-certs
We shouldn't need this

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/templates/deployment.yaml
> +            - name: orc8r-secrets-certs
And this one as well

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/README.md
> +   b. ssh into VM
```suggestion
   b. SSH into VM
```

2019-06-20 05:45 UTC, mpgermano commented on feg/gateway/helmchart/feg/README.md
> +This chart installs the magma Federated Gateway.
```suggestion
This chart installs the Magma Federated Gateway.
```

2019-06-20 19:38 UTC, reddydodda commented on feg/gateway/helmchart/.helmignore
> +# Patterns to ignore when building packages.
fixed

2019-06-20 19:40 UTC, reddydodda commented on feg/gateway/helmchart/feg/templates/helpers/pod_anti_affinity.tpl
> +{{/*
removed this template as per the feedback from @xjtian

2019-06-21 18:21 UTC, mpgermano requested changes
Thanks for previous fixes. We'll need to update this PR due to some changes made recently (https://github.com/facebookincubator/magma/pull/369/files). The comments I've made should outline what needs updated.

2019-06-21 18:21 UTC, mpgermano commented on feg/gateway/helm/feg/templates/bin/_install_gateway.sh.tpl
> +
```suggestion
# Using RC as opposed to stable (1.24.0) due to
# SCTP port mapping support
DOCKER_COMPOSE_VERSION=1.25.0-rc1
```

2019-06-21 18:21 UTC, mpgermano commented on feg/gateway/helm/feg/templates/bin/_install_gateway.sh.tpl
> +sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```suggestion
sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

2019-06-21 18:21 UTC, mpgermano commented on feg/gateway/helm/feg/README.md
> +| `feg.image.docker_registry` | FeG docker registry host. | `docker.io` |
We'll need to add configuration for each port and network type added in `magma/feg/gateway/docker/.prod_env` https://github.com/facebookincubator/magma/pull/369/files

2019-06-21 18:21 UTC, mpgermano commented on feg/gateway/helm/feg/templates/bin/_env.tpl
> +CONFIGS_VOLUME=/var/opt/magma/configs
Update this with additions in .prod_env from https://github.com/facebookincubator/magma/pull/369/files

2019-06-21 18:21 UTC, mpgermano commented on feg/gateway/helm/feg/templates/bin/_install_gateway.sh.tpl
> +
```suggestion
# Load kernel module necessary for docker SCTP support
sudo modprobe nf_conntrack_proto_sctp
```

2019-06-21 18:21 UTC, mpgermano commented on feg/gateway/helm/feg/templates/bin/_install_gateway.sh.tpl
> +docker-compose pull
Duplicate line

2019-06-21 18:21 UTC, mpgermano commented on feg/gateway/helm/feg/README.md
> +2. check if rootCA.pem is present under secrets named `orc8r-secrets-certs`
```suggestion
2. Check if rootCA.pem is present under secrets named `orc8r-secrets-certs`
```

2019-06-24 21:37 UTC, mpgermano approved these changes
This looks good. Thanks for the updates!

2019-06-24 21:55 UTC, closed without merging