[xwf-m] xwf-m gateway with unique server id
magma/magma pull request #3524
Opened 2020-10-29 15:09 UTC by ymasmoudi

## Summary
Interrogates xwf-m orc8r and ensure a unique ID for each gateway.
Update hostname for the current host

## Test Plan
tested on xwfmqa1

2020-10-29 15:10 UTC, ymasmoudi commented
@AyliD with snowflake fix

2020-10-29 20:53 UTC, mpgermano requested changes
I don't support putting orc8r admin rest certs on the gateways. This would allow for a lot more damage if any gateway were to be compromised.

2020-11-02 10:36 UTC, ymasmoudi commented
@mpgermano we are deleting the certs after installation for now and we will figure another solution

2020-11-02 10:41 UTC, AyliD approved these changes

2020-11-05 07:23 UTC, mpgermano commented on xwf/gateway/deploy/roles/xwfm/tasks/main.yml
>  - name: delete ovs bridges incase they exist
We need to remove the cert here as well

2020-11-06 01:41 UTC, ymasmoudi commented on xwf/gateway/deploy/roles/xwfm/tasks/main.yml
>  - name: delete ovs bridges incase they exist
@mpgermano added.

2020-11-06 02:41 UTC, mpgermano approved these changes

2020-11-06 02:41 UTC, merged