[5G: MVC][component: agw][type: enhancement] sctp and sctpd modifications to support eNB and gNB sctp connections #2035
magma/magma pull request #3567
Opened 2020-11-02 11:31 UTC by sandeepkmall

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2020-11-02 11:44 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/sctp/sctp_primitives_server.c
> +//#include "amf_config.h"
you do not need a commented line in the headers. can you fix this?

2020-11-02 11:44 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/sctp/sctp_primitives_server.c
> +  /*
commented code without a reason. can you explain why you have commented code? what is your plan to test it?

2020-11-02 11:44 UTC, sureshgorijavolu commented on lte/protos/sctpd.proto
>      repeated string ipv6_addrs = 4; // ipv6 addresses to listen on
because you changed proto, do you need to create "go" files and commit those also? if not, does the jenkins job go well?

2020-11-18 18:16 UTC, ulaskozat commented on lte/protos/sctpd.proto
> +    uint32 ngap_ppid = 8; // ngap ppid used with new associations
why do you define separate fields for these? you should use port and ppid fields by passing the NGAP port and ppid.

2020-11-18 18:22 UTC, ulaskozat commented on lte/gateway/c/oai/include/sctp_messages_types.h
> +  uint32_t ngap_ppid;
you don't need separate fields for ngap. A sctp connection is either s1ap or ngap, not both. You should simply put the right port and ppid numbers.

2020-11-18 18:22 UTC, ulaskozat commented on lte/gateway/c/sctpd/sctpd_downlink_impl.cpp
> +  MLOG(MERROR) << "SctpdDownlinkImpl::req->ngap_port()=" << std::to_string(req->ngap_port());
no need for separate fields in the request for ngap.

2020-11-18 18:24 UTC, ulaskozat commented on lte/gateway/c/sctpd/sctpd_downlink_impl.cpp
> +  }else if (req->ngap_ppid() == NGAP) {
again you should use req->ppid(), no need for a separate field.

2020-11-18 18:27 UTC, ulaskozat commented on lte/gateway/c/sctpd/util.cpp
> +	}
why? you don't need a separate port field for ngap.

2020-11-18 18:31 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/sctp/sctp_primitives_server.c
> +      } else if (received_message_p->ittiMsg.sctpInit.ngap_ppid == NGAP) {
no need for separate field, reuse ppid

2020-11-19 16:55 UTC, ulaskozat requested changes
please remove separate fields added to proto file for ngap ppid and ngap port. existing fields for ppid and port should be reused instead for NGAP related set up.

2020-11-23 23:32 UTC, ulaskozat commented on lte/gateway/c/oai/common/amf_default_values.h
> +
Use the magma copyright statement

2021-01-10 00:47 UTC, closed without merging

2021-01-10 00:48 UTC, uri200 commented
Closed since it was abandoned