Rsarwad pthread condition variable
magma/magma pull request #3646
Opened 2020-11-07 11:03 UTC by rsarwad

[AGW] Modified code to wait until controller connects to switch

## Summary
On mme restart if Modify bearer Request arrives before controller connected to switch, it was making mme to crash. Because on reception of MBR message SPGW will invoke API to add OVS rules to Switch. Since connection is not established between controller and switch. It was resulting into crash.

2020-11-09 07:14 UTC, ssanadhya commented
RestartIntegrationTests

2020-11-09 07:14 UTC, ssanadhya commented
RestartLteTests

2020-11-09 07:15 UTC, ssanadhya commented
RestartLTETests

2020-11-09 09:18 UTC, rsarwad commented
> RestartLTETests

Hi @ssanadhya, How do I restartLteTests? I am not able to view the Jenkins report it generates only log files

2020-11-09 17:34 UTC, ssanadhya requested changes

2020-11-09 17:34 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/ControllerMain.cpp
> +#include <thread>
These headers are not being used here.

2020-11-09 17:34 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
> +#include <mutex>   // std::timed_mutex
Remove comments

2020-11-09 17:34 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
> +#include <chrono>  // std::chrono::seconds
Remove comments

2020-11-09 17:34 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
> +bool OpenflowController::is_controller_connected_to_switch(int duration) {
```suggestion
bool OpenflowController::is_controller_connected_to_switch(int conn_timeout) {
```

2020-11-09 17:34 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
> +  /* c++ provided conditional variable is added along with wait for seconds as
"Wait for conn_timeout seconds to make sure connection is established....."

2020-11-09 17:34 UTC, ssanadhya commented on lte/gateway/c/oai/lib/openflow/controller/OpenflowController.h
> +  bool is_controller_connected_to_switch(int);
Please add parameter name here

2020-11-10 17:59 UTC, ssanadhya approved these changes

2020-11-10 18:02 UTC, merged