[WIP][NMS] Add subscriber traffic policy config
magma/magma pull request #3658
Opened 2020-11-09 20:33 UTC by HannaFar

Signed-off-by: HannaFar <hannafarag159@gmail.com>

## Summary

Add subscriber traffic policy config tab

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2020-11-11 00:45 UTC, andreilee requested changes
Set the height of the content in the three dialog tabs to the same value, just as a minor usability improvement

2020-11-11 00:45 UTC, andreilee commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberDetailConfig.js
> +  );
I think that here it's better to increase code re-use by combining these three into a single component with an enum prop field to control which tab the dialog opens up with

2020-11-11 00:45 UTC, andreilee commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js
> +            placeholder="Enter Auth Key"
Have the placeholder show the input format

2020-11-11 00:45 UTC, andreilee commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js
> +            placeholder="Enter Auth OPC"
Have the placeholder show the input format

2020-11-11 00:45 UTC, andreilee commented on nms/app/packages/magmalte/app/views/subscriber/SubscriberApnStaticIpsEdit.js
> +                placeholder="Enter IP"
Show input format of IPv4 and example

2020-11-16 14:23 UTC, karthiksubraveti reviewed
Sorry for the late review here. Here instead of showing there is 1 active IP, i wonder if it might be better to show a table with a apn and the actual IP address which was configured. That might be better.

2020-11-18 22:03 UTC, andreilee approved these changes

2020-11-18 23:08 UTC, merged