Updated Orcr8r install with terraform pre-requisites
magma/magma pull request #3763
Opened 2020-11-18 18:33 UTC by jaredmullane

>>>>>> Updated orc8r install pre-reqs to include having terraform in the working directory

Signed-off-by: Jared Mullane <jmullane@fb.com>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2020-11-18 20:05 UTC, hcgatewood requested changes
Need to add this notice to a couple additional places
- The upgrade_intro page: docs/readmes/orc8r/upgrade_intro.md
- The non-versioned versions of these docs: docs/readmes/orc8r/upgrade_1_2.md and docs/readmes/orc8r/upgrade_1_3.md

2020-11-18 20:05 UTC, hcgatewood commented on docs/docusaurus/versioned_docs/version-1.2.0/orc8r/upgrade_1_2.md
> +Ensure that all Terraform state files (I.e. terraform.tfstate) are located
Make these changes to each copy of this block of text

- ~~that~~
- within -> in
- I.e. -> i.e.
- terraform.tfstate -> `terraform.tfstate`
- Link this page for the "Terraform state files": https://www.terraform.io/docs/state/index.html (e.g. [Terraform state files](https://www.terraform.io/docs/state/index.html))
- Append this sentence: "This means `terraform show` should list existing state (rather than outputting `No state`)."

2020-11-18 23:45 UTC, hcgatewood commented on docs/docusaurus/versioned_docs/version-1.2.0/orc8r/upgrade_1_2.md
> +Ensure that all Terraform state files (I.e. terraform.tfstate) are located
Also prepend: "If you are using local Terraform state (the default), ensure all..."

Because they can also use non-local state

2020-12-01 20:20 UTC, mpgermano approved these changes

2020-12-16 18:09 UTC, merged