[docs] Adding enodeb_config migration to orc8r migration steps docs
magma/magma pull request #3782
Opened 2020-11-19 07:08 UTC by ardzoht

Signed-off-by: Alejandro Rodriguez <alexrod@fb.com>

## Summary

- Adds `m014_enodeb_config` to migrations steps for 1.3 upgrade orc8r section

## Test Plan

- Verified locally using `./create_docusaurus_website.sh`

## Additional Information

- [ ] This change is backwards-breaking

2020-11-19 11:35 UTC, hcgatewood requested changes
See my comment on your Workplace post: also include a "NOTE: ..." that, if the upgrade is targeting the v1.3.0 tag specifically, they won't need the m014 migration

Also can you summarize my comment in the summary of this PR for future reference 🙂

2020-11-20 17:57 UTC, mpgermano approved these changes

2020-11-23 02:05 UTC, hcgatewood approved these changes
Lgtm can you just handle the one additional commend I added

2020-11-23 02:05 UTC, hcgatewood commented on docs/docusaurus/versioned_docs/version-1.3.0/orc8r/upgrade_1_3.md
> +> **_NOTE:_** If you're upgrading to release v1.3.0 specifically, `m014_enodeb_config` is not required.
Can you make it "... upgrading to release tag v1.3.0 specifically" -- just to clarify this only applies to the tag (not the v1.3 patch branch or subsequent tags)

2020-11-30 17:32 UTC, merged