[AGW Pooling][Proto] Define draft agw pooling proto
magma/magma pull request #3860
Opened 2020-12-01 22:47 UTC by mpgermano

Signed-off-by: Michael Germano <mgermano@fb.com>

## Summary

Define a draft proto for the AGW pooling service. This PR is intended for discussion purposes only.

The idea with this proto is that backup instances in an AGW pool (i.e. cloud based AGWs) will call this 
defined RPC endpoint to fetch all relevant ENB states in order to determine which ENBs to offload back 
to the primary.

I am thinking the logic for this RPC method should work something like this (open for discussion):

1. AWS backup AGW calls `GetEnodebOffloadState`
2. Orc8r fetches gatewayID of caller
3. Using gatewayID, fetch all gateway pool IDs that this gateway belongs to
4. For each pool, fetch all gateways in the pool:
   a. Skip any gateways whose rel capacity is lower than the calling gateway
   b. For each ENB connected to a gateway in the pool, query how many users are connected to the ENB
      i. If connected users > 0, set ENB state to PRIMARY_CONNECTED_AND_SERVING_UES
      ii. Otherwise, connected users == 0, set ENB state to PRIMARY_CONNECTED.
5. Return map of all ENB states. If an ENB is missing, it is considered to be a no-op. This will be the case for ENBs connected to the secondary whose primary is still offline.

2020-12-01 23:09 UTC, ulaskozat commented
This summary looks good to me. So the implicit assumption is that an  AGW X is a backup to another AGW Y if and only if:
1. X is included in the pool that Y belongs to.
2. X has a relative MME capacity that is strictly less than that of Y.

2020-12-05 01:17 UTC, ulaskozat commented on lte/protos/had_orc8r.proto
> +    map<string, EnodebOffloadState> enodeb_offload_states = 1;
can you instead make this mapping from uint32_t (from eNB ID to offloadstate)?

2020-12-05 01:22 UTC, ulaskozat requested changes
see the comment regarding the eNB serial number vs. ID.

2020-12-08 20:57 UTC, mpgermano commented
Addressed comment

2020-12-08 21:11 UTC, ulaskozat approved these changes
LGTM

2020-12-08 22:42 UTC, merged