[AGW Documentations] AGW Static IP set up
magma/magma pull request #3888
Opened 2020-12-03 22:08 UTC by jaredmullane

## Summary

Adding instructions for partners who were looking to do non-DHCP AGW installs. Related to T79129909. 

## Test Plan

docs/docusaurus/create_docusaurus_website.sh

2021-01-06 06:25 UTC, pshelar requested changes

2021-01-06 06:25 UTC, pshelar commented on docs/docusaurus/versioned_docs/version-1.0.1/lte/setup_deb.md
@jaredmullane there is orc8r API and NMS option to set static IP for SGi interface, can you document that

2021-03-31 02:11 UTC, ekowtaylor commented
@jaredmullane are you moving forward with this?

2021-04-06 16:14 UTC, ulaskozat commented
What is the status here?

2021-04-06 21:02 UTC, jaredmullane commented
Going to close this as we have updated the steps in the FAQ.

2021-04-06 21:02 UTC, closed without merging