[show-tech] installing ansible community and updating README.md
magma/magma pull request #3969
Opened 2020-12-09 12:12 UTC by AyliD

Signed-off-by: Ayelet Regev Dabah <ayelet.regev@gmail.com>

## Summary

Resolving chicken and egg issue identified on vagrant that playbook that installs this community cannot parse the playbook till community is installed.
Adding installation to physical installations script and updating README.md for vagrant.

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2020-12-09 14:08 UTC, karthiksubraveti approved these changes

2020-12-09 15:39 UTC, tmdzk requested changes

2020-12-09 15:39 UTC, tmdzk commented on lte/gateway/deploy/agw_install.sh
> +  ansible-galaxy collection install community.general
Let's wrap ansivle-galaxy collection install in the base role of agw installation.

2020-12-09 15:39 UTC, tmdzk commented on show-tech/README.md
> +$ sudo ansible-galaxy collection install community.general
There is an ansible role that provision the Vagrant box, let's add it there.

2020-12-15 21:30 UTC, karthiksubraveti reviewed
We should also make changes in show-tech playbooks to remove the installation of ansible community right?

2020-12-20 10:27 UTC, AyliD reviewed
Moved instructions to playbooks @tmdzk

2020-12-21 12:10 UTC, tmdzk approved these changes

2020-12-21 20:55 UTC, pshelar approved these changes
LGTM

2020-12-22 08:40 UTC, merged