Added testcase to validate 3495 timer for both default and dedicated bearer while mme restarts
magma/magma pull request #4016
Opened 2020-12-11 09:44 UTC by rsarwad

[AGW]: Added testcase to validate 3495 timer for both default and dedicated bearer while mme restarts
## Summary
Added testcase to validate 3495 timer for both default and dedicated bearer while mme restarts

## Test Plan
Executed s1ap sanity test suite

## Additional Information
Dependent PRs are,

2021-01-19 17:26 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_dedicated_bearer_with_mme_restart.py
> +        Step6: TFW shall receive re-transmitted Actiavte Dedicated EPS
Typo Actiavte->Activate

2021-01-19 17:26 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_dedicated_bearer_with_mme_restart.py
> +               Bearer Context Request and send Actiavte Dedicated EPS Bearer
Same typo as above.

2021-01-19 17:27 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_dedicated_bearer_with_mme_restart.py
> +        Step7: TFW shall initaite de-activation of deidicated bearer and then
typos initaite->initiate and deidicated -> dedicated

2021-01-19 17:28 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_default_bearer_with_mme_restart.py
> +        Step3: Initaite activation of secondary PDN
typo Initaite -> Initiate

2021-01-19 17:29 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_default_bearer_with_mme_restart.py
> +            "*** Sending indication to disbale dropping of Erab Setup Req",
typo disbale -> disable

2021-01-19 17:31 UTC, ulaskozat requested changes
Fix the typos.

2021-03-25 19:38 UTC, ulaskozat commented
@rsarwad could you take care of codacy warnings?

2021-03-25 19:38 UTC, ulaskozat approved these changes
LGTM with nits to be completed from codacy warnings.

2021-03-31 16:35 UTC, ssanadhya commented
@rsarwad , could you please remove the T3485 test cases from this PR as they need changes on MME? The T3495 tests are good to merge once the T3485 tests are removed.

2021-04-01 05:54 UTC, ssanadhya approved these changes

2021-04-02 14:44 UTC, merged