[orc8r] Remove MemoryBlobStorage
magma/magma pull request #4384
Opened 2021-01-15 04:57 UTC by AndyLKhuu

## Summary

MemoryBlobStorage and its usage has long been obsolete in favor of SqlMemoryBlobStorage which grants us the same benefits of having a local in-memory blobstorage to test from. MemoryBlobStorage itself is filled with bugs and for the sake of clarity and simpler repo, we have decided to remove it.

## Test Plan
- [x] cd $MAGMA_ROOT/orc8r/cloud/docker && ./build.py -t ; noti

## Additional Information

- [ ] This change is backwards-breaking

2021-01-15 21:50 UTC, hcgatewood commented
FYI: feg-build job is flaky (download issues), is a known issue and @tmdzk is working on it

2021-01-15 22:41 UTC, hcgatewood requested changes
Looks good, couple small things -- mainly I gave you the names I want for each blobstore mem table name

2021-01-15 22:41 UTC, hcgatewood commented on cwf/gateway/integ_tests/hssless_test.go
> +	store := test_utils.NewSQLBlobstore(t, "blobstore_hss_table")
"hssless_test_blobstore"

2021-01-15 22:41 UTC, hcgatewood commented on cwf/gateway/services/uesim/servicers/eap_aka_test.go
> +		server, ue, err := setupTest(t)
Run go fmt on every save https://www.jetbrains.com/help/idea/integration-with-go-tools.html

2021-01-15 22:41 UTC, hcgatewood commented on cwf/gateway/services/uesim/servicers/eap_test.go
> +	"magma/orc8r/cloud/go/test_utils"
Organize imports (for now) as (stdlib, magma, third-party). You can have this done mostly-automatically https://www.jetbrains.com/help/idea/integration-with-go-tools.html

2021-01-15 22:41 UTC, hcgatewood commented on cwf/gateway/services/uesim/servicers/eap_test.go
> +	store := test_utils.NewSQLBlobstore(t, "blobstore_uesim_table")
"uesim_eap_test_blobstore"

2021-01-15 22:41 UTC, hcgatewood commented on cwf/gateway/services/uesim/servicers/uesim_test.go
> +	store := test_utils.NewSQLBlobstore(t, "blobstore_uesim_test_table")
"uesim_uesim_test_blobstore"

2021-01-15 22:41 UTC, hcgatewood commented on cwf/gateway/services/uesim/test_init/test_service_init.go
> +	factory := test_utils.NewSQLBlobstore(t, "blobstore_cwf_table")
"uesim_test_service_blobstore"

2021-01-15 22:41 UTC, hcgatewood commented on cwf/gateway/services/uesim/uesim/main.go
> +	"magma/orc8r/cloud/go/test_utils"
Imports order, see other comment

2021-01-15 22:41 UTC, hcgatewood commented on cwf/gateway/services/uesim/uesim/main.go
> +	store, err := test_utils.NewSQLBlobstoreForServices("uesim_table_main")
"uesim_main_blobstore"

2021-01-15 22:41 UTC, hcgatewood commented on cwf/gateway/services/uesim/uesim/main.go
> +		glog.Fatalf("Error creating in-memory blobstore: %s", err)
Use `%+v` when logging errors -- to get the full stack trace

2021-01-15 22:41 UTC, hcgatewood commented on feg/cloud/go/services/health/client_api_test.go
> +	assert.Equal(t, test_utils.TestFegNetwork, active)
@mpgermano @emakeev please give input here -- my reading of the health service is that this change in the test is fine, but please advise

2021-01-15 22:41 UTC, hcgatewood commented on orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers_test.go
> +	fact := test_utils.NewSQLBlobstore(t, "blobstore_ctrace_table")
"ctraced_handlers_test_blobstore"

2021-01-15 22:41 UTC, hcgatewood commented on orc8r/cloud/go/services/device/test_init/test_service_init.go
> +	factory := test_utils.NewSQLBlobstore(t, "blobstore_orc8r_table")
"device_test_service_blobstore"

2021-01-15 22:41 UTC, hcgatewood commented on orc8r/cloud/go/services/tenants/servicers/servicer_test.go
> +	factory := test_utils.NewSQLBlobstore(t, "blobstore_tenant_servicer_table")
"tentants_servicer_test_blobstore"

2021-01-15 22:41 UTC, hcgatewood commented on orc8r/cloud/go/test_utils/test_db.go
> +// Table name is an optional parameter. Defaults to "blobstore_table_name".
This doc line is no longer accurate

2021-01-15 23:34 UTC, hcgatewood commented on feg/cloud/go/services/health/client_api_test.go
> +	assert.Equal(t, test_utils.TestFegNetwork, active)
From offline: Michael confirmed this is a safe change

2021-01-15 23:34 UTC, hcgatewood approved these changes

2021-01-19 14:10 UTC, themarwhal approved these changes
![image](https://user-images.githubusercontent.com/37634144/105045591-b3b5db00-5a2d-11eb-8b0d-1f82cdbb4c46.png)

2021-01-19 19:56 UTC, merged