{WIP}[agw][lte] PLMN restriction
magma/magma pull request #4448
Opened 2021-01-20 13:26 UTC by pruthvihebbani

{WIP}[agw][lte] PLMN restriction

## Summary

Added support to configure a list of restricted PLMNs in mme.conf.template file and a function to check if the PLMN in IMSI/GUTI received in attach request message matches with the configured restricted PLMN list. If it matches attach reject is sent. 

## Test Plan

Configured 001 010 PLMN in mme.conf.template file and verified that attach reject is sent with emm cause "PLMN not allowed" upon execution of test_attach_detach.py TC

2021-01-22 08:40 UTC, rdefosse commented
Can one of the admins verify this patch?

2021-01-28 14:57 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-02-03 16:11 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-02-08 02:38 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/mme_app/mme_config.c
> +            char c[2]                                     = {mcc[0], 0};
can you instead use `{mcc[0], '\0'}` and comment that this is a null terminated string?

2021-02-08 02:39 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/mme_app/mme_config.c
> +            char c[2]                                     = {mnc[0], 0};
same comment as in line 859.

2021-02-08 02:41 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
> +
is this function used anywhere in this PR? might be better to move to the relevant PR.

2021-02-08 02:41 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
> +        self.IMSI_LEN = 15
will you be adding a test case in this PR? maybe move to the PR that has the actual test cases?

2021-02-08 02:47 UTC, ulaskozat commented on lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
> +    def gen_imsi(self, prefix=None):
maybe throw an exception if the overall length of  idx + prefix is longer than IMSI_LEN.

2021-02-08 06:35 UTC, ardzoht requested changes

2021-02-08 06:35 UTC, ardzoht commented on lte/gateway/configs/templates/mme.conf.template
> +    # List of restricted PLMNs
We should add a comment here that the maximum length for the restricted PLMN is 10

2021-02-08 06:35 UTC, ardzoht commented on lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
> +    def gen_imsi(self, prefix=None):
```suggestion
    def generate_imsi(self, prefix=None):
```

2021-02-08 06:35 UTC, ardzoht commented on lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
> +        padding = self.IMSI_LEN - len(idx) - len(prefix[4:])
this will throw `TypeError` exception if prefix is `None`

2021-02-08 11:11 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-02-08 14:49 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-02-10 05:01 UTC, ulaskozat approved these changes
LGTM

2021-02-10 05:05 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/mme_app/mme_config.c
> +            config_pP->restricted_plmn.plmn[i].mnc_digit1 = (uint8_t) atoi(c);
instead of this, you can use:
```
AssertFatal(mnc[0]>='0' && mnc[0]<='9');
config_pP->restricted_plmn.plmn[i].mnc_digit1 = mnc[0] - '0';
```

2021-02-10 05:05 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/mme_app/mme_config.c
> +            config_pP->restricted_plmn.plmn[i].mnc_digit1 = (uint8_t) atoi(c);
and do the similar thing in other parts codacy has warnings.

2021-02-10 17:43 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-02-16 16:51 UTC, ardzoht approved these changes
Lgtm

2021-02-16 17:20 UTC, ulaskozat commented
Bypassing ci/circleci: feg-build check as this PR is self contained on the mme side with no impact on FEG or vice versa.

2021-02-16 17:21 UTC, merged