[feg] add template for s8 feg relay
magma/magma pull request #4490
Opened 2021-01-21 22:54 UTC by uri200

Signed-off-by: Oriol Batalla <obatalla@fb.com>

## Summary

Add feg-relay template for s8

## Test Plan

make precommit orc8r

## Additional Information

- [ ] This change is backwards-breaking

2021-01-21 23:01 UTC, emakeev approved these changes

2021-01-21 23:11 UTC, themarwhal approved these changes

2021-01-22 02:31 UTC, mpgermano requested changes
Looks good. One thing is missing:
In `magma/feg/cloud/helm/feg-orc8r/values.yaml` there needs to be a s8_proxy service
defined. We can leave the labels and annotations blank:
```
s8_proxy:
  service:
    labels: {}
    annotations: {}
```

2021-01-22 02:58 UTC, uri200 commented
added s8_proxy: on `values.yaml`

2021-01-22 03:03 UTC, mpgermano approved these changes
lgtm

2021-01-22 03:18 UTC, merged