[5G: MVC][component: agw][type: enhancement] AMF Base Timer Changes
magma/magma pull request #4687
Opened 2021-02-02 11:36 UTC by hkshiv1

Signed-off-by: hkshiv1 <shivakumar.hk@acldigital.com>

## Summary

AMF Timers T3560, T3570, T3550 code changes

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-02-17 11:56 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
> +  Version     0.1
take out version, subsystem, author & product

2021-02-17 11:56 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
> +    OAILOG_ERROR(
this should be an info level log statement.

2021-02-17 11:56 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
> +    OAILOG_ERROR(LOG_AMF_APP, "Timer: After stopping SMC MODE timer \n");
is this a DEBUG level log statement?

2021-02-17 11:56 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
> +    /* Nothing to do in
can you modify the comment? it is not conveying clear message.

2021-02-17 11:56 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
> +    // amf_registration_success_security_cb(amf_ctx);
if you no longer need this dead code, take it out.

2021-02-17 11:56 UTC, sureshgorijavolu commented on lte/gateway/c/oai/tasks/amf/amf_identity.cpp
> +#if 0
we do not need code that does not compile.

2021-03-22 16:39 UTC, ulaskozat commented
Can you please indicate on which other PR(s) this PR is dependent?

2021-03-23 19:56 UTC, ulaskozat commented
remove all the commented code out if they are not used. clearly list to do and have place holder functions instead.

2021-03-24 19:19 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
> +#if 0
This is effectively dead code, please remove!

2021-03-24 19:19 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
> +#if 0
This is effectively dead code, please remove!

2021-03-24 19:20 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
> +//#if 1
Remove

2021-03-24 19:54 UTC, ssanadhya commented on lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
> +#if 0
Remove dead code

2021-03-24 19:54 UTC, ssanadhya requested changes
Please remove all code inside `#if 0` blocks.

2021-04-15 11:49 UTC, closed without merging