[Converged-MME]ts9_timer edit
magma/magma pull request #4787
Opened 2021-02-05 15:45 UTC by Vyas20

[lte][converged-mme][agw]

## Summary
Part of replacing the existing timers with zmq timers, this branch is forked from the branch in PR #4786  and contains ts9_timer edits.

## Test Plan
Testing with S1-AP Tester and dsTester.

2021-02-05 15:45 UTC, Vyas20 commented
MAGMA-OAI-TESTS

2021-03-03 15:01 UTC, Vyas20 commented
MAGMA-OAI-TESTS

2021-03-03 17:33 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-03-06 01:55 UTC, ulaskozat requested changes
Still have the file MmeUeContext.cpp

2021-03-07 22:49 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
>          "SGS EPS Detach Timer expired but no assoicated SGS context for UE "
fix the typo `assoicated`

2021-03-08 11:30 UTC, Vyas20 commented
MAGMA-OAI-TESTS

2021-03-08 11:36 UTC, Vyas20 commented on lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
>          "SGS EPS Detach Timer expired but no assoicated SGS context for UE "
Resolved

2021-03-09 17:37 UTC, ulaskozat approved these changes
LGTM

2021-03-10 18:21 UTC, merged