[lte] Minor CMakeLists.txt cleanups
magma/magma pull request #4978
Opened 2021-02-16 18:34 UTC by mcallahan

Make sure all of the CMakeLists.txt files in lte contain
the magma copyright, contain a reasonable minimum cmake version
(arbitrarily picked at 3.7.2 for the C++ extensions),
and set C++14 as the language to use.

## Summary

Make sure all of the CMakeLists.txt files in lte contain
the magma copyright, contain a reasonable minimum cmake version
(arbitrarily picked at 3.7.2 for the C++ extensions),
and set C++14 as the language to use.

## Test Plan

grep, jenkins

## Additional Information

- [ ] This change is backwards-breaking

2021-02-17 10:44 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-02-18 17:56 UTC, uri200 commented
just curious, is there any specific reason why 3.7.2?

2021-02-22 19:59 UTC, uri200 commented
Can you rebase so the feg test can pass please?

2021-03-19 21:33 UTC, themarwhal approved these changes
looks cleaner! Thanks :)

2021-03-19 22:01 UTC, themarwhal commented
Hey @mcallahan ! I assigned the PR to you so that you can rebase and re-trigger.

2021-03-24 16:03 UTC, themarwhal requested changes
@mcallahan Sorry :( I think I made some changes that collided with yours. Do you mind rebasing?

2021-03-24 16:28 UTC, ssanadhya commented
RestartIntegrationTests

2021-03-31 16:43 UTC, ssanadhya commented
@mcallahan , it will be great if you can run S1ap integration tests after making these changes! Alternatively, you can test with the Jenkins CI check, which runs the `magma_integration_tests` pipeline.

2021-04-02 14:09 UTC, themarwhal requested changes
Please resolve the merge conflicts.

2021-04-13 16:04 UTC, ulaskozat commented
This PR looks stale. Please close if no longer necessary.

2021-04-21 15:19 UTC, ulaskozat commented
@mcallahan will you be rebasing and resolve merge conflicts for this PR?

2021-04-22 15:47 UTC, closed without merging