[doc][orc8r] Add documentation on AWS resources deployed for Orchestrator
magma/magma pull request #5019
Opened 2021-02-18 13:39 UTC by joary

## Summary

- Added documentation on Orc8r resources deployed on AWS
- Included documentation in docusaurus sidebar

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-02-18 17:45 UTC, hcgatewood requested changes
Hey Joary thanks for adding this. Couple requests

High level
- Include a screen cap of the page running locally. At minimum so we can see the included image
- Let's make a new "Architecture" subsection under "Orchestrator", i.e. `Orchestrator > Architecture`
- Then we can move your AWS info as well as this page https://magma.github.io/magma/docs/next/orc8r/intro into that section, which feels like a better home

Particular: some small nits for the documentation style
- Capitalization: make a pass to ensure consistency for the following capitalizations
    - K8s, Kubernetes
    - Orc8r, Orchestrator
    - NMS
    - Magma
    - Helm
- Don't use "here" as hyperlink text. The [chosen hyperlink text should be self-descriptive](https://www.nngroup.com/articles/writing-links/)

2021-04-01 07:29 UTC, hcgatewood requested changes
Hey @joary, the Docusaurus layout was updated recently, so you'll need to rebase

Aside from that, content looks good. Consider taking a look at Magma Markdown conventions as part of your last-pass over the PR https://magma.github.io/magma/docs/next/contributing/contribute_conventions#markdown

Looking forward to merging this in!

2021-04-21 17:26 UTC, hcgatewood commented
Ping @joary

2021-05-07 18:25 UTC, hcgatewood approved these changes
Great thanks Joary. Accepted with a couple comments, please incorporate before merging 🙂

2021-05-07 18:25 UTC, hcgatewood commented on docs/docusaurus/i18n/en.json
> +        "title": "Orchestrator AWS Stack"
```suggestion
        "title": "AWS Stack"
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +title: Orchestrator AWS Stack
```suggestion
title: AWS Stack
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +# Orchestrator Stack on AWS
```suggestion
# AWS Stack
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +
```suggestion
This document describes the Orchestrator stack when it's deployed to AWS.

```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +## What does terraform deploy in my AWS account?
```suggestion
## What does Terraform deploy in my AWS account?
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +The following resources are the basic infrastructure necessary to deploy Magma services:
```suggestion
The following resources are the basic infrastructure necessary to deploy Magma services
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +* **Kubernetes cluster:** Orc8r runs over a Kubernetes (K8s) cluster, Magma uses Elastic Kubernetes Service (EKS) to deploy the cluster. Other resources are created to support this cluster.
```suggestion
* **Kubernetes cluster (EKS).** Orc8r runs over a Kubernetes (K8s) cluster, Magma uses Elastic Kubernetes Service to deploy the cluster. Other resources are created to support this cluster.
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +* **Elastic File System (EFS):** File system to hold persistent data for Kubernetes cluster.
Change all these colons to periods

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +Some configurations do not have default values and are mandatory to be present in your main.tf.
```suggestion
Some configurations do not have default values and are mandatory to be present in your `main.tf`.
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +The values for these configurations can be defined/overwritten in your main.tf `orc8r` module.
```suggestion
The values for these configurations can be defined/overwritten in your `main.tf` `orc8r` module.
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +The values of these configurations can be defined/overwritten in your main.tf `orc8r-app` module.
```suggestion
The values of these configurations can be defined or overwritten in your `main.tf` file's `orc8r-app` module.
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +    1. Prometheus/Thanos for metric storage.
```suggestion
    1. Prometheus for metric storage.
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +## Which certificates Magma use?
```suggestion
## Which certificates does Magma use?
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +Orc8r needs certificates to assure messages traveling over the internet are encrypted and secure. Certificates are created in pairs with a public certificate (.crt or .pem) and a private key (.key).
```suggestion
Orc8r needs certificates to assure messages traveling over the internet are encrypted and secure. Certificates are created in pairs with a public certificate (`.crt` or `.pem`) and a private key (`.key`). The former needs to be safely stored and kept secret, while the latter can be distributed to clients. Please read the [certificates section on Orchestrator architecture](https://magma.github.io/magma/docs/next/orc8r/dev_security#certificates).
```

2021-05-07 18:25 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +</span>
```suggestion
> ***NOTE:*** All certificates are created with validity time period, so make sure you know when your certificates expire and schedule a maintenance to update them.
```

2021-05-10 20:14 UTC, joary commented
@hcgatewood I included all your comments, though I'm not authorized to merge.

2021-05-11 02:21 UTC, hcgatewood approved these changes
One last nit (formatting error) then I'll merge for you!

2021-05-11 02:21 UTC, hcgatewood commented on docs/readmes/orc8r/dev_aws_stack.md
> +* **Kubernetes cluster (EKS).* Orc8r runs over a Kubernetes (K8s) cluster, Magma uses Elastic Kubernetes Service to deploy the cluster. Other resources are created to support this cluster.
```suggestion
* **Kubernetes cluster (EKS).** Orc8r runs over a Kubernetes (K8s) cluster, Magma uses Elastic Kubernetes Service to deploy the cluster. Other resources are created to support this cluster.
```

2021-05-11 17:41 UTC, joary commented
Thanks @hcgatewood, I solved it.

2021-05-11 21:38 UTC, joary commented
@hcgatewood , I had to rebase last two commits to include sign, DCO was failing for those.

2021-05-11 22:05 UTC, merged