Feature issue 4981
magma/magma pull request #5101
Opened 2021-02-23 18:54 UTC by ranj8work

## Summary

## Test Plan

## Additional Information

- [ NO] This change is backwards-breaking

2021-02-23 19:20 UTC, tmdzk requested changes
Please fill the 
```
Summary
Test Plan
Additional Information
[ NO] This change is backwards-breaking
```

and give a more explicit names

2021-02-23 19:20 UTC, tmdzk commented on orc8r/tools/ansible/roles/pkgrepo/tasks/debian.yml
> +  block:
As discuss, I think we can do it one shot with apt_key and specifying the url. [ansible module for apt](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html) 

```bash
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
    state: present
```

2021-02-23 19:20 UTC, tmdzk commented on orc8r/tools/ansible/roles/pkgrepo/tasks/debian.yml
> +    - get_url:
Pretty sure you didn't have to store it in a variable and you could have just used `file:` in the apt_key command

2021-02-24 00:37 UTC, tmdzk approved these changes

2021-02-24 23:13 UTC, hcgatewood approved these changes
Don't have context for this workflow, deferring to Tim's stamp

2021-02-24 23:16 UTC, merged