[orc8r] Shift eventd handler attachment from orc8r to eventd
magma/magma pull request #5219
Opened 2021-03-01 06:21 UTC by AndyLKhuu

Signed-off-by: Andy Lee Khuu <andykhuu@stanford.edu>

## Summary

## Test Plan
- [x] cd $MAGMA_ROOT/orc8r/cloud/docker && ./build.py -t ; noti
- [x] Manually Spinning up Swagger UI and testing that eventd handler endpoints still work

## Additional Information

- [ ] This change is backwards-breaking

2021-03-01 12:36 UTC, karthiksubraveti reviewed
Most changes LGTM. Left a few comments.

2021-03-01 12:36 UTC, karthiksubraveti commented on orc8r/cloud/go/services/eventd/obsidian/handlers/handlers.go
> +		ret = append(ret, obsidian.Handler{Path: EventsPath, Methods: obsidian.GET, HandlerFunc: getInitErrorHandler(err)})
minor nit: we can do an early return in this if block and unindent the else block

2021-03-01 12:36 UTC, karthiksubraveti commented on orc8r/cloud/go/services/eventd/obsidian/handlers/handlers.go
> +			ret = append(ret, obsidian.Handler{Path: LogSearchQueryPath, Methods: obsidian.GET, HandlerFunc: getInitErrorHandler(err)})
minor nit: setting the error handling can be done in a loop, might be cleaner that way.

2021-03-01 12:36 UTC, karthiksubraveti commented on orc8r/cloud/go/services/eventd/obsidian/handlers/handlers.go
> +		ret = append(ret, obsidian.Handler{Path: LogSearchQueryPath, Methods: obsidian.GET, HandlerFunc: getInitErrorHandler(err)})
Also we should probably be setting error handlers for all the paths, I understand this is old code, but I guess this might not have been updated.

2021-03-01 12:36 UTC, karthiksubraveti commented on orc8r/cloud/go/services/eventd/obsidian/handlers/handlers.go
> +		return obsidian.HttpError(fmt.Errorf("initialization Error: %v", err), 500)
minor nit: we should probably move our error codes to a constants file and use that instead of using 500 here.

2021-03-02 01:49 UTC, hcgatewood requested changes
You'll also need to update the annotations in relevant service_registry.yml and values.yml files

Give it a sanity check on Minikube as well -- it's fine if it returns an error (depending on whether elastic is up in the cluster), but if it 404s that means the service mesh labels/annotations weren't correct

2021-03-02 01:49 UTC, hcgatewood commented on orc8r/cloud/go/services/eventd/obsidian/handlers/handlers.go
> +		ret = append(ret, setInitErrorHandlers(err)...)
Make this an early return instead of an if-else

2021-03-03 21:35 UTC, hcgatewood approved these changes
👍

2021-03-03 21:38 UTC, hcgatewood requested changes
Oops realized we also need to update chart version @AndyLKhuu

2021-03-04 21:31 UTC, hcgatewood approved these changes

2021-03-04 21:32 UTC, merged