[MME] Fix nas_state_converter calloc sizes
magma/magma pull request #5332
Opened 2021-03-05 12:19 UTC by electronjoe

## Summary

Both Calloc which utilized the wrong struct for sizeof - were shielded
from the worst outcomes because the correct structure was (today)
smaller than the mistakenly used struct.  So this had perf implications
but not safety implications.

## Testing Plan

Confirmed Clang-Tidy findings were resolved and then:

```
cd lte/gateway
make build_oai
```

Signed-off-by: Scott Harrison Moeller <smoeller@fb.com>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-03-05 12:20 UTC, electronjoe commented
MAGMA-OAI-TESTS

2021-03-05 17:50 UTC, ssanadhya requested changes
Same comment as #5330

2021-03-05 18:35 UTC, electronjoe commented
Thanks @ssanadhya!

Working as intended - this is how we are doing c inheritance. I will work at add Clang-Tidy annotations so this is ignored moving forward.

Niggling concern that these types may not technically be 100% `compatible types` due to differing tags - so just to drop that breadcrumb (don't think this is biting us):

```
6.2.7 Compatible type and composite type
1 Two types have compatible type if their types are the same. Additional rules for
determining whether two types are compatible are described in 6.7.2 for type specifiers,
in 6.7.3 for type qualifiers, and in 6.7.6 for declarators.55) Moreover, two structure,
union, or enumerated types declared in separate translation units are compatible if their
tags and members satisfy the following requirements: If one is declared with a tag, the
other shall be declared with the same tag...
```

Of C11 draft spec (all I can get for free online).

2021-03-07 11:06 UTC, electronjoe commented
This PR seemed like a reasonable place to move to a NOLINT annotation.

Please take a look @ssanadhya! This will prevent this warning in the future.

2021-03-08 09:19 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-03-29 18:18 UTC, ssanadhya approved these changes

2021-03-29 18:19 UTC, merged