[fix] the build-magam.sh script fixes related to multi-architecture b…
magma/magma pull request #5341
Opened 2021-03-05 18:42 UTC by jordanvrtanoski

[lte][agw] Fixing the build script to support multi-platform build in docker 

## Summary

1) Fixing the defaulted architecture in the build script. The fix will make a check if the variable is already set in the environment and will add the default values only if the variables are missing. Following variables are affected:

   `ARCH` - CPU Architecture for which the build is executed
   `PKGFMT` - Package Format, allowing to introduce packages for non Debian distributions
   `PKGNAME` - Name of the magma package

1) Added new variable called `DOCKER_BUILD`. If set, the build is executed in a docker environment and the OVS build will be skipped since its independent build chain.

1) Fixing the links toward config files that are vagrant dependent. The files now point toward files in the repository, not to files that are already present on the vagrant build box.

## Test Plan

* test the build with unset environment. The build should produce debian package with name `magma`  for `amd64` architecture
* build the ARM architecture

## Additional Information

- [ ] This change is backwards-breaking
- [X] Mandatory for multi-platform build

2021-04-15 17:04 UTC, tmdzk requested changes
Thanks a lot for your changes, let's resolve the few comments, resolve the conflictr and get that merged

2021-04-15 17:04 UTC, tmdzk commented on lte/gateway/release/build-magma.sh
> +$(glob_files "${SERVICE_DIR}/magma_dnsd.service" /etc/systemd/system/magma@dnsd.service) \
We need to keep the `@` otherwise it will break a lot of things in our codebase and documentation.

2021-04-15 17:04 UTC, tmdzk commented on lte/gateway/release/build-magma.sh
> +if [[ x"${DOCKER_BUILD}" == "x" ]]; then
This is to force rebuild the ovs packages, why is it wrapped around this if?

2021-09-01 15:15 UTC, ekowtaylor commented
Will need to rebase to move this forward

2021-09-01 15:15 UTC, closed without merging