[lte][agw] Scptd modifications to avoid burst after mme recovery
magma/magma pull request #5355
Opened 2021-03-07 06:04 UTC by ulaskozat

## Summary

In stateless mode, when mme crashes, sctpd was queuing up duplicate events from the same UE towards MME due to UE timers. This PR makes the following improvements:
- Place an explicit short time out for uplink rpc calls for s1ap requests to prevent bursts of S1AP requests towards UE that were queued up during the MME recovery.
- When a new association event comes in and it cannot be delivered to MME, close the association.

## Test Plan

Spirent tests and S1 AP tests with forced MME restarts.

## Additional Information

- [ ] This change is backwards-breaking

2021-03-07 06:05 UTC, ulaskozat commented
MAGMA-OAI_TESTS

2021-03-08 09:00 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-03-08 09:07 UTC, rdefosse commented
@ulaskozat 

Build failure on our variant

```bash
7/14] Building CXX object CMakeFiles/SCTPD_LIB.dir/sctp_connection.cpp.o
FAILED: CMakeFiles/SCTPD_LIB.dir/sctp_connection.cpp.o
/usr/bin/c++ -DLOG_WITH_GLOG -I/usr/local/include/prometheus -I/magma/lte/gateway/c/sctpd -I. -I/magma/orc8r/gateway/c/common/logging -g -std=gnu++14 -MD -MT CMakeFiles/SCTPD_LIB.dir/sctp_connection.cpp.o -MF CMakeFiles/SCTPD_LIB.dir/sctp_connection.cpp.o.d -o CMakeFiles/SCTPD_LIB.dir/sctp_connection.cpp.o -c /magma/lte/gateway/c/sctpd/sctp_connection.cpp
/magma/lte/gateway/c/sctpd/sctp_connection.cpp: In member function 'magma::sctpd::SctpStatus magma::sctpd::SctpConnection::HandleComUp(int, sctp_assoc_change*)':
/magma/lte/gateway/c/sctpd/sctp_connection.cpp:271:54: error: no matching function for call to 'magma::sctpd::SctpEventHandler::HandleNewAssoc(sctp_assoc_t&, __u16&, __u16&, std::__cxx11::string&)'
           change->sac_outbound_streams, ran_cp_ipaddr) < 0) {
                                                      ^
In file included from /magma/lte/gateway/c/sctpd/sctp_connection.cpp:14:0:
/magma/lte/gateway/c/sctpd/sctp_connection.h:42:15: note: candidate: virtual int magma::sctpd::SctpEventHandler::HandleNewAssoc(uint32_t, uint32_t, uint32_t, uint32_t, std::__cxx11::string&)
   virtual int HandleNewAssoc(
               ^~~~~~~~~~~~~~
/magma/lte/gateway/c/sctpd/sctp_connection.h:42:15: note:   candidate expects 5 arguments, 4 provided
```

2021-03-08 09:08 UTC, rdefosse requested changes
Build failure on our variant

2021-03-08 10:00 UTC, rdefosse approved these changes
@ulaskozat 

sorry. It passes now on your last commit.

Cheers
Raphael

2021-03-08 19:05 UTC, ssanadhya approved these changes

2021-03-08 22:52 UTC, merged