[lte][agw] Updating ipv6 and ipv4v6 handlers on MobilityClient through ITTI msgs
magma/magma pull request #5485
Opened 2021-03-15 00:04 UTC by ardzoht

Signed-off-by: Alex Rodriguez <ardzoht@gmail.com>

## Summary

- This PR completes the movement of processing of SPGW-mobilityd IP allocation through ITTI messaging, similarly as was done on https://github.com/magma/magma/pull/5416/ 

## Test Plan

- Tested sanity with make integ_test
- Running `test_ipv6_secondary_pdn_rs_retransmit.py` and `test_ipv4v6_secondary_pdn.py` as well as other ipv6 related s1ap integ tests, however tests are failing due to an unrelated issue 

## Additional Information

- [ ] This change is backwards-breaking

2021-03-15 00:04 UTC, ardzoht commented
MAGMA-OAI-TESTS

2021-03-16 22:12 UTC, ssanadhya requested changes

2021-03-16 22:12 UTC, ssanadhya commented on lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp
> +            status, ip6_addr, vlan, subscriber_id, apn, pdn_type, context_teid,
As with Ipv4 changes, please pass a String object instead of pointer for subscriber_id, apn and pdn_type

2021-03-16 22:12 UTC, ssanadhya commented on lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp
> +            status, ip4_addr, ip6_addr, vlan, subscriber_id, apn, pdn_type,
Same comment as above

2021-03-16 22:13 UTC, ssanadhya commented on lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp
> +  return 0;
```suggestion
  return RETURNok;
```

2021-03-22 21:43 UTC, closed without merging