[lte][agw] Improve writes to redis for ue hash tables and s1ap states
magma/magma pull request #5486
Opened 2021-03-15 00:26 UTC by ulaskozat

## Summary
This PR adds couple of speed improvements to MME particularly for stateless.
- In stateless mode, every message leads to writes regardless of whether there were any state changes or not. PR adds generation numbers to hash tables. For state_ue_ht (used across S1AP, MME and SPGW) and s1ap state hashtables, it only writes if there were changes to these hash tables by keeping track of generation numbers for the hash tables. Upon first start up and restarts, all generation numbers start from zero.
- Increased the small hash table sizes to improve the look up speeds as the defaults were too low for handling 100s of UEs.

## Test Plan

Spirent tests and s1ap integ tests.

## Additional Information

- [ ] This change is backwards-breaking

2021-03-15 00:29 UTC, ulaskozat commented
MAGMA-OAI-TESTS

2021-03-15 07:23 UTC, ulaskozat commented
PR has a bug. Don't merge it.

2021-03-15 12:20 UTC, rdefosse commented
MAGMA-OAI-TESTS

2021-03-15 16:35 UTC, ssanadhya requested changes
@ulaskozat, the PR is tracking state change with hash table insert/remove events, but what would happen in scenarios where the entry in hashtable is only modified without insertion/removal? For example, the UE context in MME app is updated with new security keys after Auth Info Answer is processed by MME app.

2021-03-16 16:09 UTC, ulaskozat commented
closing this as we are taking a different direction for speed ups.

2021-03-16 16:09 UTC, closed without merging

2021-03-16 16:21 UTC, themarwhal commented
Removing the tag as this PR never merged.