[doc] proposal 011: Add S1 intra-AGW mobility
magma/magma pull request #5501
Opened 2021-03-15 16:47 UTC by shaddi

## Summary

Add proposal for S1 Intra-AGW mobility.

2021-03-15 18:03 UTC, amarpad commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +- Support for a ``large number'' of eNodeBs attached to a single AGW: The distributed nature of Magma means that any given AGW is responsible for a relatively small number of eNodeBs. This proposal d
I would add a testing section to say the test cases that will be run as well as how it is run (s1aptester, tm-500 whatever)

2021-03-17 16:46 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +Currently, mobility in Magma is limited to RAN a single AGW where RAN elements support the X2 interface. This isn't always feasible; S1 mobility is the "fallback" method for mobility in LTE networks
fix the sentence

2021-03-17 16:47 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +Currently, mobility in Magma is limited to RAN a single AGW where RAN elements support the X2 interface. This isn't always feasible; S1 mobility is the "fallback" method for mobility in LTE networks
Fix the first sentence of the paragraph.

2021-03-17 16:47 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +Currently, mobility in Magma is limited to RAN a single AGW where RAN elements support the X2 interface. This isn't always feasible; S1 mobility is the "fallback" method for mobility in LTE networks
typo `avaialble`

2021-03-17 16:50 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +The intended use case for this proposal is single cell tower (or small cluster of cell sites) connected to a single AGW, potentially using a mix of eNB equipment, where the network operator wishes to
The last sentence is incomplete. The first sentence can be rephrased as `The intended use case for this proposal is to support UE mobility across multiple eNBs with no X2 connections in between and anchored at the same AGW instance.

2021-03-17 16:51 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +The traditional S1 mobility call flow is our guide. A good overview of this particular flow is available [here](https://www.eventhelix.com/lte/handover/s1/).
better to provide a spec as the authoritative reference on this one.

2021-03-17 16:51 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +The following new proceedures will be added to the SGW:
typo `proceedures`.

2021-03-17 16:52 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +S1 handover is used when there is no direct forwarding path between the two eNodeBs. So, we need to create an indirect forwarding path on the S11 interface and then modify bearers to the UE after han
S11 interface? Do you mean S1?

2021-03-17 16:56 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +Ideally, we'd have `s1aptester` tests for this feature; however, `s1aptester` does not currently support S1 handover. In the meantime, we'll be testing with the following setups:
in formal proposal documents let's use "is not" rather than "isn't", "we would" rather than "we'd", etc.

2021-03-17 16:57 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +  - Scale Test S1-Handover with 10 subscribers
can you be more descriptive on this one? will you handover all 10 subscribers at the same time?

2021-03-17 16:58 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +  - Scale Test S1-Handover with 10 subscribers
can you add a test case for ping pong handovers between two eNBs?

2021-03-17 16:58 UTC, ulaskozat requested changes
Comments added.

2021-04-13 17:18 UTC, ulaskozat commented on docs/readmes/proposals/p011_intra_agw_mobility.md
> +Ideally, we would have `s1aptester` tests for this feature; however, `s1aptester` does not currently support S1 handover. In the meantime, w will be testing with the following setups:
w will -> we will

2021-04-13 17:18 UTC, ulaskozat approved these changes
LGTM with a nit typo fix.

2021-04-15 01:08 UTC, merged