[lte][agw] Datapath Actions Script
magma/magma pull request #5554
Opened 2021-03-17 07:50 UTC by saurabhm3hra

Signed-off-by: Saurabh Mehra <saurabhmehra@fb.com>

## Summary

CLI wrapper around ovs-appctl ofproto/trace to display the Datapath actions of the supplied IMSI.
This will help to easily trace the packets coming in to the UE.

If the packets are dropped, Datapath Actions will print drop
If successful, Datapath Actions will print the tunnel id.

- I mistakenly closed the old PR https://github.com/magma/magma/pull/5551
- Incorporating the changes which were requested

## Test Plan
![image](https://user-images.githubusercontent.com/26427970/111432762-635eaf00-8738-11eb-9729-3c4395d29fca.png)

2021-03-17 08:39 UTC, pshelar commented on lte/gateway/python/scripts/dp_actions_cli.py
> +#!/usr/bin/env python3
lets rename it to dp-probe cli, or something else that is not very specific, since we will continue to add more features to this cli.

2021-03-17 13:41 UTC, karthiksubraveti reviewed
@saurabhm3hra Can you add a document providing more information on the CLI and adding it to "Debugging Tools" under docs. Thanks. 
https://github.com/magma/magma/tree/master/docs/readmes/debugging_tools
and link this to 
https://github.com/magma/magma/blob/master/docs/docusaurus/sidebars.json

![Screen Shot 2021-03-17 at 6 40 45 AM](https://user-images.githubusercontent.com/8224854/111476782-b52d1800-86eb-11eb-9e1e-0e7d4d98027a.png)

2021-03-17 13:42 UTC, karthiksubraveti requested changes
@saurabhm3hra Can you add a document providing more information on the CLI and adding it to "Debugging Tools" under docs. Thanks. 
https://github.com/magma/magma/tree/master/docs/readmes/debugging_tools
and link this to 
https://github.com/magma/magma/blob/master/docs/docusaurus/sidebars.json

![Screen Shot 2021-03-17 at 6 40 45 AM](https://user-images.githubusercontent.com/8224854/111476782-b52d1800-86eb-11eb-9e1e-0e7d4d98027a.png)

2021-03-22 10:50 UTC, saurabhm3hra reviewed
Addressing comments

2021-03-23 04:01 UTC, pshelar approved these changes
LGTM

2021-03-23 12:26 UTC, karthiksubraveti approved these changes
Looks good. Thanks for adding the doc

2021-03-23 12:27 UTC, karthiksubraveti commented
@saurabhm3hra You might have to sign your commit and push. `git commit --amend -s`

2021-03-23 17:31 UTC, ardzoht approved these changes
lgtm

2021-03-24 05:35 UTC, merged