Bump OVS to 2.14.3 on Ubuntu and libfluid to 0.1.0.6
magma/magma pull request #5644
Opened 2021-03-22 02:58 UTC by tmdzk

Signed-off-by: Timothée Dzik <timdzik@fb.com>

Bump OVS to 2.14.3 on Ubuntu and libfluid to 0.1.0.6

## Summary

cd lte/gateway && bash agw_install.sh on Ubuntu 20

## Test Plan

![](https://media3.giphy.com/media/3ornjSL2sBcPflIDiU/giphy.gif)

2021-03-22 02:59 UTC, tmdzk commented
Note: packages are already on the public registry and being built by CI (triggered some test.)

cc @pshelar

2021-03-22 15:00 UTC, 119Vik approved these changes

2021-03-22 15:01 UTC, 119Vik requested changes

2021-03-22 15:01 UTC, 119Vik commented on lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
> +  packages_debian:
Should it be packages_ubuntu ?

2021-03-22 18:48 UTC, tmdzk commented on lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
> +  packages_debian:
Sure is!

2021-03-23 11:38 UTC, pshelar approved these changes

2021-03-23 11:38 UTC, pshelar commented on lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
> +    - "oai-gtp_4.9-9_amd64.deb"
OAI package is not required on ubuntu.

2021-03-23 11:38 UTC, pshelar commented on lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
> +    - "openvswitch-datapath-source_2.14.3_all.deb"
No need to install sources package.

2021-03-23 13:58 UTC, pshelar commented on lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
> +
I do not see OVS packages getting installed in magma_focal VM with this patch applied.

2021-03-25 19:20 UTC, 119Vik approved these changes

2021-04-20 16:16 UTC, ardzoht commented
@tmdzk clearing my queue, what is the plan for this PR?

2021-04-22 14:34 UTC, closed without merging