AGW: deploy OVS 2.14 on magma-dev VM
magma/magma pull request #5744
Opened 2021-03-25 17:09 UTC by pshelar

Use prebuilt OVS packages for ubuntu.

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-03-26 17:12 UTC, ardzoht approved these changes
lgtm

2021-03-26 17:12 UTC, ardzoht commented on lte/gateway/deploy/roles/magma/tasks/main.yml
> +      - libopenvswitch
It would be good to verify this with building local package, to confirm there's no dependency issue?

2021-03-28 23:41 UTC, tmdzk requested changes
This role is for local VM. It's pointing to an internal registry that don't have any OVS packages.. Which means It will take the community one and as we didn't fix the versions It will install the 2.15 one. 

2 Solutions: 
- host ovs packages in that internal registry
- Fix version of OVS

2021-03-29 11:52 UTC, pshelar commented
facebookconnectivity has OVS 2.14 packages. I have already verified these patches.

2021-03-29 17:08 UTC, tmdzk approved these changes

2021-03-29 17:20 UTC, merged