[Orc8r] Add upgrade prechecks to deployer tool
magma/magma pull request #5790
Opened 2021-03-29 18:33 UTC by karthiksubraveti

## Summary

Following PR adds upgrade prechecks to the deployer tool.
    Upgrade prechecks includes
    - Checking if terraform state exists
    - Checking if deployed EKS version <= EKS version specified in values
    - Checking if deployed RDS version <= DB instance version specified in values

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-03-31 19:10 UTC, andreilee commented on orc8r/cloud/deploy/orc8r_deployer/docker/run_deployer
> +}
I believe you could avoid the repeated `echo` calls:

https://stackoverflow.com/questions/10969953/how-to-output-a-multiline-string-in-bash

```suggestion
__help="
./run_deployer runs the orc8r deployer container
orc8r deployer contains scripts which enable user to configure, run prechecks
install, upgrade, verify and cleanup an orc8r deployment

Syntax: run_deployer [-d|-r|-b|-h]
options:
-h     Print this Help
-d  deployment dir containing configs and secrets
-r  magma root directory
-b  build the deployer container
note: -deploy_root is mandatory
example: ./run_deployer -deploy_root /tmp/orc8r_14_deployment
"

Print_Help()
{
   echo "$__help"
}
```

2021-03-31 19:10 UTC, andreilee commented on orc8r/cloud/deploy/orc8r_deployer/docker/run_deployer
> +docker build --pull -t ksubraveti/orc8r_deployer:latest .
```suggestion
    docker build --pull -t ksubraveti/orc8r_deployer:latest .
```

2021-03-31 19:10 UTC, andreilee commented on orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/configlib.py
> +# limitations under the License.
```suggestion
"""
Copyright 2021 The Magma Authors.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
```

2021-03-31 19:10 UTC, andreilee commented on orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/configlib.py
> +
This seems a little redundant to me

2021-03-31 19:10 UTC, andreilee commented on orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/orcl.py
> +# initiialize CLI
typo

2021-03-31 19:10 UTC, andreilee commented on orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/configlib.py
> +        ''' check if all mandatory options of a specific component is set '''
nit
```suggestion
        """ check if all mandatory options of a specific component is set """
```

2021-04-01 01:12 UTC, karthiksubraveti commented on orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/configlib.py
> +
This is for mocking the get_input in tests.

2021-04-01 06:53 UTC, hcgatewood requested changes
Clearing queue. Please make this a draft PR until the "depended" PR is merged.

2021-04-05 04:28 UTC, closed without merging