[1.5] Update NMS DB Migration script download reference
magma/magma pull request #5862
Opened 2021-03-31 22:42 UTC by andreilee

Signed-off-by: Andrei Lee <andreilee@fb.com>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-03-31 22:50 UTC, andreilee commented
Maybe I should have put this into its own package originally instead of the scripts directory

2021-04-01 00:10 UTC, karthiksubraveti requested changes, later dismissed

2021-04-01 00:10 UTC, karthiksubraveti commented on docs/readmes/orc8r/upgrade_1_5.md
> +`wget https://raw.githubusercontent.com/magma/magma/3c61a6388406fe4c6bc6dc90665889cc575a24fc/nms/app/packages/magmalte/scripts/fuji-upgrade/pre-upgrade-migration.sh && chmod +x pre-upgrade-migration.
use this rather https://raw.githubusercontent.com/magma/magma/master/nms/app/packages/magmalte/scripts/fuji-upgrade/pre-upgrade-migration.sh

2021-04-01 21:25 UTC, karthiksubraveti approved these changes

2021-04-02 04:57 UTC, merged