[feg][cwf][orc8r]Promote script to promote docker images from test repo to prod repo
magma/magma pull request #5974
Opened 2021-04-06 22:25 UTC by ranj8work

Signed-off-by: Ranjini Iyer <ranj8work@gmail.com>

## Summary
**First version of Promote script to promote docker images of feg, cwf, orc8r or docker from -test repo to -prod repo**

## Test Plan
Testing is done by running this script on httpd docker image. Promoted its version 1.0 from feg-test to feg-prod. Screenshots are attached below: 

![image](https://user-images.githubusercontent.com/77810379/113785094-772c7e00-9704-11eb-8130-89ed7b4889b7.png)
![image](https://user-images.githubusercontent.com/77810379/113785472-32551700-9705-11eb-9b83-d7104fb0b8c4.png)

## Additional Information

2021-04-08 16:58 UTC, ranj8work commented
Updated changes to push helm charts to new jfrog as well:

Testing screenshot is pasted below:

![image](https://user-images.githubusercontent.com/77810379/114066782-174fe780-986a-11eb-9c44-56d069dbb374.png)

2021-04-09 16:08 UTC, tmdzk requested changes
I think most of the code is there. 
But there are a few issues. 

Main feedback related to the promotion script:
1 -  let's use fabric in order to be able to split the differents function and keep using what magma devs and contributors are used to. 
2 - we should be able to promote all the images of a module 
3 - we should be able to promote all images of all modules at once

Please split the upload helm logic into a new script that we will integrate to CI

2021-04-09 16:08 UTC, tmdzk commented on orc8r/tools/helm/package.sh
>  # limitations under the License.
Let's separate the Helm changes from the more general promotion changes.

2021-04-09 16:08 UTC, tmdzk commented on orc8r/tools/helm/package.sh
> +# Updated to publish the helm charts to new jfrog artifactory repository as well
This script is meant to be use if you want to publish in your own helm registry. 
The logic should remain the same and we should still let people upload to their own registry (github repo)

The upload of the chart should be in a different script and in my opinion within CI, we have to stop to manual push packages/images/binaries

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +#!/usr/bin/python3
Let's use fabric like we do in the current release process, to make it cleaner and fits our current tool suite

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +    modules = [ 'docker', 'feg', 'cwf', 'orc8r', 'all' ]
From what I read If I pass `all` as modules it doesn't do what expected but just try to get all-test

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +    imgName = sys.argv[2]
I don't think specifying the image name is needed. We need to promote all images that have the `imgVersion` available. 

like 
`promote.py feg 1a4b2b30`

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +    status = callJFROGAPI(method='GET')
I think this function should be redesign. 
Calling callJfrogApi with a get shouldn't hardcode get packages. `callJfrogApi` should only be a function that call the api with 0 logic in it just the request.

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +def promote(module):
promote  with only the module argument should be able to promote all images of a module.

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +    status = callJFROGAPI(method='POST', payload={ "targetRepo": targetRepo, "dockerRepository": imgName, "tag": imgVersion, "copy": "true" })
Same here callJfrogApi should only be doing the call, 0 logic there. 
payload could have been defined before for readability

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +JFROG_URL = 'https://artifactory.magmacore.org/artifactory/api/docker'
As we will implement other promotions here the jfrog url shouldn't be tied to docker

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +def callJFROGAPI(method='GET',
This function needs to be reworked to be more simple with 0 promotion logic. 
It should only be a function that calls the Jfrog Api

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +              print(f"Response Body={response.content}")
you don't need to print that much information, just the first print is enough

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +              print(f"HTTPError Occurred. Error=")
combine the 2 prints

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +              print("HTTPError Occurred. Error=")
combine the 2 prints

2021-04-09 16:08 UTC, tmdzk commented on lte/gateway/release/promote.py
> +    status = promote(module)
There is some logic missing. 
what if I want to promote all images? 
what if I only want the agw one? 

Let's do fab function:
1 for docker 
1 for agw 
1 for helm

2021-04-13 07:02 UTC, hcgatewood approved these changes
Approving to unblock need for orc8r-approvers stamp. @tmdzk can handle full review of this PR

As an aside: agree with let's use fab

2021-07-30 19:52 UTC, hcgatewood commented
Closing due to inactivity. Please reopen if desired @ranj8work

2021-07-30 19:52 UTC, closed without merging