Amf core dependent files
magma/magma pull request #5989
Opened 2021-04-07 07:28 UTC by chandra-77

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-04-07 18:27 UTC, ulaskozat requested changes
you need to generate go files for proto.

2021-04-09 04:07 UTC, ulaskozat reviewed
Please fix the redeclaration of LOG_NGAP

2021-04-09 04:23 UTC, chandra-77 commented
> 
> 
> Please fix the redeclaration of LOG_NGAP

Fixed

2021-04-09 16:23 UTC, ulaskozat commented on lte/gateway/c/oai/lib/3gpp/3gpp_38.413.h
> +  Ngap_PagingPriority_ty RAN_Paging_Priority; /*optional*/
should not this be `Ngap_PagingPriority_t`?

2021-04-09 20:49 UTC, ulaskozat approved these changes
LGTM

2021-04-09 20:54 UTC, merged