Addressed comments on s8 task observed during testing
magma/magma pull request #6133
Opened 2021-04-14 14:56 UTC by rsarwad

"[lte][agw]: Addressed comments on s8 task observed during testing

## Summary
1. Added ULI and serving network in deletion session request
2. Added pco in create session request and processing pco which is received in create session response
3. Removed explicit length and num_protocol_container_id field in pco
4. Fixed the memory leak found during testing
## Test Plan
Executed s1ap sanity test suite

2021-04-14 17:24 UTC, uri200 requested changes

2021-04-14 17:24 UTC, uri200 commented on lte/gateway/c/oai/lib/s8_proxy/s8_client_api.cpp
> +  }
i can comment the line 499, but shoudnt we be checking `if (response.has_gtp_error())` as the very beginning of this function? 

If we have gtp_error, the other field are going to be bad. Only gtp_error is good. So no need to go through the whole function.

2021-04-14 17:24 UTC, uri200 commented on lte/gateway/c/oai/tasks/mme_app/mme_app_itti_messaging.c
> +      (session_request_p->serving_network), (ue_mm_context->e_utran_cgi.plmn));
👍

2021-04-15 02:10 UTC, ulaskozat commented on lte/gateway/c/oai/lib/s8_proxy/s8_client_api.cpp
> +    mnc[2]  = '\0';
looks already initialized to null (ascii 0) on line 202.

2021-04-15 02:12 UTC, ulaskozat approved these changes
LGTM

2021-04-15 04:51 UTC, uri200 approved these changes

2021-04-15 20:24 UTC, merged