[docs] Add orcl to docusaurus
magma/magma pull request #6175
Opened 2021-04-16 11:10 UTC by karthiksubraveti

Signed-off-by: Karthik Subraveti <ksubraveti@fb.com>

## Summary
Add orcl to orc8r deployment documentation

## Test Plan
<img width="1677" alt="Screen Shot 2021-04-16 at 4 05 52 AM" src="https://user-images.githubusercontent.com/8224854/115016197-9e541f80-9e69-11eb-9146-95164c0fc469.png">

## Additional Information

- [ ] This change is backwards-breaking

2021-04-20 21:01 UTC, andreilee requested changes

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +```
Some more whitespace can be helpful here. It's a little difficult to parse at a glance

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +```
Not a comment about the docs, specifically, but options that are longer than a single letter typically have two hyphens.

```
--help
-h
--deploy-dir
-d
--root-dir
-r
--build
-b
```

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +orc8r deployer contains scripts which enable user to configure, run prechecks
Missing a comma at the end of this line
```suggestion
orc8r deployer contains scripts which enable user to configure, run prechecks,
```

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +Deployment directory will be used to maintain the configs, secrets and also contain the deployment related files such as main.tf etc. It is important to use the same deployment directory during the u
Should `orcl` be used with specifying a `/tmp` directory for a more permanent deployment? The earlier section is a little bit misleading with that.

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +In the following section, we will discuss each of the orcl commands in detail.
```suggestion
In the following sections, we will discuss each of the orcl commands in detail.
```

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +## Configure
I think these headers should explicitly state these are subcommands - just a little bit easier when skimming
```suggestion
## Configure Command
```

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +Every orc8r deployment relies on several configuration attributes. For e.g cluster_name attribute is used to identify the orc8r  kubernetes cluster, orc8r_tag provides the image tag to be used during
```suggestion
Every orc8r deployment relies on several configuration attributes. For example cluster_name attribute is used to identify the orc8r kubernetes cluster, orc8r_tag provides the image tag to be used during the deployment. Configure command enables user to easily configure the mandatory configs necessary for the deployment. It additionally provides the ability to also configure optional attributes through the ***set*** subcommand. Configure command also has subcommands like ***info*** to show all the possible configuration attributes and ***show*** to display the current configuration. Finally configure also contains a subcommand ***check*** which provides the ability to check if all mandatory configs needed by the deployment have been successfully configured.
```

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +
I liked how the other sections begin with a clear statement of what the command is for. Copying and pasting from the paragraph in the next line:
```suggestion
Configure command enables user to easily configure the mandatory configs necessary for the deployment.
```

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +For e.g.
Preferentially use the English word over the latin abbreviation except under narrow circumstances

```suggestion
For example
```

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +Certs is a orcl command for managing certificates. Currently it has only one subcommand ***add*** which can be used to add application certs and self signed root certificates(optional).
For quick referencing, subsections can be added for each command to list and explain the subcommands.

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +Verify command provides the ability to post deployment checks on orc8r.
```suggestion
Verify command provides the ability to run post-deployment checks on orc8r.
```

2021-04-20 21:01 UTC, andreilee commented on docs/readmes/orc8r/deploy_orcl.md
> +  Run post deployment checks on orc8r
```suggestion
  Run post-deployment checks on orc8r
```

2021-04-21 13:11 UTC, karthiksubraveti commented on docs/readmes/orc8r/deploy_orcl.md
> +```
I think both styles are used. For e.g. in terraform there is only single dashed option. That being said, The orcl cli internally uses click which uses double hyphen for multiple letters. I will change this and keep it consistent.

2021-04-21 14:05 UTC, karthiksubraveti commented on docs/readmes/orc8r/deploy_orcl.md
> +Deployment directory will be used to maintain the configs, secrets and also contain the deployment related files such as main.tf etc. It is important to use the same deployment directory during the u
It is an example. I can set some other location if you thought this was misleading.

2021-04-21 23:24 UTC, karthiksubraveti commented on docs/readmes/orc8r/deploy_orcl.md
> +Certs is a orcl command for managing certificates. Currently it has only one subcommand ***add*** which can be used to add application certs and self signed root certificates(optional).
I have added that already below. 
```

Commands:
  add  Add creates application and self signed(optional) certs
```

2021-04-21 23:25 UTC, karthiksubraveti commented on docs/readmes/orc8r/deploy_orcl.md
> +
This is the entire description  of the command.
"Every orc8r deployment relies on several configuration attributes. For example, cluster_name attribute is used to identify the orc8r  kubernetes cluster, orc8r_tag provides the image tag to be used during the deployment. Configure command enables user to easily configure the mandatory configs necessary for the deployment. It additionally provides the ability to also configure optional attributes through the ***set*** subcommand. Configure command also has subcommands like ***info*** to show all the possible configuration attributes and ***show*** to display the current configuration. Finally configure also contains a subcommand ***check*** which provides the ability to check if all mandatory configs needed by the deployment have been successfully configured."
The configure command has subcommands set, show, info etc. So I had explained everything in there.

2021-04-22 18:18 UTC, andreilee approved these changes

2021-04-22 18:18 UTC, merged