CreateSessionUtil imports issue for pipelined_cli #6130
magma/magma pull request #6191
Opened 2021-04-16 20:42 UTC by prabinakpattnaik

Signed-off-by: prabina pattnaik <prabinak@wavelabs.ai>

## Summary

ng_set_session_msg.py script is changed the place from tests/app to python/scripts.
Bare metal build is not included the tests directory.

## Test Plan
Executed the use-case using python/scripts/pipelined_cli.py.

2021-04-19 22:24 UTC, ardzoht requested changes

2021-04-19 22:24 UTC, ardzoht commented on lte/gateway/python/scripts/pipelined_cli.py
> +from ng_set_session_msg import CreateSessionUtil
Not sure if `lte/gateway/python/scripts` would be the best place to have these on here, this looks pretty specific to pipelined since it was on pipelined/tests? If there's no clear path to move this one here, something we could try is maybe define a `scripts/helpers` to put util related files on here? cc @koolzz

2021-04-20 00:37 UTC, koolzz commented on lte/gateway/python/scripts/pipelined_cli.py
> +from ng_set_session_msg import CreateSessionUtil
Yeah I agree, I don't think we currently have a good dir for this. scripts/helpers sounds fine to me

2021-04-21 17:43 UTC, prabinakpattnaik commented on lte/gateway/python/scripts/pipelined_cli.py
> +from ng_set_session_msg import CreateSessionUtil
The "ng_set_session_msg" python file is used in pipeleind_cli.py and tests/test_ng_servicer_session.py. But for bare metal build "pipeliend/tests" directory is not included. Previously ng_set_session_msg file was kept on pipelined/tests. So CreateSessionUtil imports issue getting when executed pipelined_cli.py.

Now we moved to "pipeliend/tests" to "python/scripts" for "ng_set_session_msg" python file.

Yes I agree, it should be defined in meaningful path. I will do create a new directory "scripts/helpers" for same.

2021-04-22 14:47 UTC, koolzz approved these changes

2021-04-22 15:49 UTC, ardzoht approved these changes

2021-04-22 15:50 UTC, merged