New FDD LTE bands
magma/magma pull request #6603
Opened 2021-04-30 19:18 UTC by lfarizav

New FDD LTE bands
Signed-off-by: Luis Felipe Ariza Vesga <lfarizav@unal.edu.co>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-04-30 19:19 UTC, hcgatewood reviewed
Adding @andreilee and @ulaskozat as they're likely most familiar

2021-04-30 19:27 UTC, ulaskozat commented
Please fill up the summary (why this PR is needed, what is its impact) and test plan (how it is tested/used).

2021-04-30 20:29 UTC, lfarizav commented
> Please fill up the summary (why this PR is needed, what is its impact) and test plan (how it is tested/used).

Dear ulaskozat. I have already complete the summary and test plan.

2021-04-30 21:26 UTC, andreilee commented
@lfarizav Has this been replaced with another PR? Why did you close this PR?

2021-05-04 17:46 UTC, lfarizav commented
> @lfarizav Has this been replaced with another PR? Why did you close this PR?

@andreilee I am not sure what happened. I do not know if new FDD bands for LTE will be merged into the master branch using another PR. By the way, we can do the changes by ourselves and enable the bands we need.

2021-05-04 21:03 UTC, andreilee commented
Reopening this PR

2021-05-07 06:06 UTC, ulaskozat commented on lte/cloud/go/lte/lte_bands.go
> +	{ID: 28, Mode: FDDMode, StartEarfcnDl: 9210, StartEarfcnUl: 27210, CountEarfcn: 59376},
Why is `CountEarfcn` is changed to 59376 from 450 for ID 28?

2021-05-07 06:08 UTC, ulaskozat commented on lte/cloud/go/lte/lte_bands.go
> +	{ID: 71, Mode: FDDMode, StartEarfcnDl: 68586, StartEarfcnUl: 133122, CountEarfcn: 59426},
For ID: 71, `CountEarfcn` should be 350.

2021-05-07 06:10 UTC, ulaskozat requested changes
Please check the additional comments on earfcn counts.

2021-05-11 17:49 UTC, lfarizav commented on lte/cloud/go/lte/lte_bands.go
> +	{ID: 28, Mode: FDDMode, StartEarfcnDl: 9210, StartEarfcnUl: 27210, CountEarfcn: 59376},
Dear @ulaskozat the correct CountEartfcn values were changed.

2021-05-11 17:55 UTC, ulaskozat approved these changes
LGTM

2021-05-11 17:59 UTC, lfarizav reviewed
I correct the mistake of the CountEarfcn for bands 28 and 71. I apologize because of the mistake. The changes are the following: 
	{ID: 28, Mode: FDDMode, StartEarfcnDl: 9210, StartEarfcnUl: 27210, CountEarfcn: 450},
	{ID: 71, Mode: FDDMode, StartEarfcnDl: 68586, StartEarfcnUl: 133122, CountEarfcn: 350},

2021-05-11 17:59 UTC, lfarizav commented on lte/cloud/go/lte/lte_bands.go
> +	{ID: 28, Mode: FDDMode, StartEarfcnDl: 9210, StartEarfcnUl: 27210, CountEarfcn: 59376},
> Why is `CountEarfcn` is changed to 59376 from 450 for ID 28?

Sorry, it was a mistake, values were updated.

2021-05-12 02:07 UTC, lfarizav commented
> @lfarizav Has this been replaced with another PR? Why did you close this PR?

Sorry @andreilee, I did not close the PR. It was done automatically.

2021-07-30 19:52 UTC, hcgatewood commented
Closing due to inactivity. Please reopen if desired @lfarizav

2021-07-30 19:52 UTC, closed without merging

2021-07-30 20:12 UTC, ulaskozat commented
@hcgatewood why is this closed. The inactivity looks on the side of code owners and not the PR owner.

2021-07-30 21:28 UTC, hcgatewood commented
> @hcgatewood why is this closed. The inactivity looks on the side of code owners and not the PR owner.

My impression was "last update May 11", and some CI checks were failing. I'm fine with reopening if desired 🙂

2021-07-30 21:35 UTC, ulaskozat commented
> > @hcgatewood why is this closed. The inactivity looks on the side of code owners and not the PR owner.
> 
> My impression was "last update May 11", and some CI checks were failing. I'm fine with reopening if desired 🙂

which checks were failing? @lfarizav let us know if you want this to be reopened and merged. Could you also post your test results?