Modified script to get default interface device for sgw_s8_user_plane
magma/magma pull request #6712
Opened 2021-05-04 16:25 UTC by rsarwad

Signed-off-by: rashmi <rashmi.sarwad@radisys.com>
## Summary
Modified script to get default interface device for sgw_s8_user_plane
## Test Plan
Executed s1ap sanity test suite

## Additional Information
After replacing oai_generate_oai_config.py, spgw.yml and misc_utils.py in Tera VM; test case is failing

2021-05-04 17:51 UTC, uri200 commented on orc8r/gateway/python/magma/common/misc_utils.py
> +    return gws['default'][netifaces.AF_INET][1]
maybe you need to use get function in case `default` and `netifaces.AF_INET` and `1` doesn't exist

2021-05-04 17:51 UTC, uri200 commented on orc8r/gateway/python/magma/common/misc_utils.py
> +def get_default_interface():
you need to state the return type 
`get_default_interface(): -> str:`

2021-05-05 15:27 UTC, pshelar requested changes

2021-05-05 15:27 UTC, pshelar commented on lte/gateway/configs/mme.yml
> +enable_nat: true
this is already there in mconfig, no need to add it here.

2021-05-05 15:27 UTC, pshelar commented on lte/gateway/python/scripts/generate_oai_config.py
> +       iface_name= get_service_config_value("spgw", "sgw_s5s8_up_non_nat_iface_name", "")
can you also fix linter issues, some of these looks legit.

2021-05-06 01:40 UTC, uri200 commented on lte/gateway/configs/spgw.yml
> +sgw_s5s8_up_non_nat_iface_name: "uplink_br0"  # 'sgw_s5s8_up_ip' will be filled automatically
```
sgw_s5s8_up_iface_name
sgw_s5s8_up_iface_name_non_nat
```

What about using same name but with a suffix to highlight the idea they are the same interface (s5s8) but on different configurations

2021-05-06 05:52 UTC, pshelar approved these changes
please fix as per the minor comment.

2021-05-06 05:52 UTC, pshelar commented on lte/gateway/python/scripts/generate_oai_config.py
> +            'spgw', 'sgw_s5s8_up_iface_name', '',
you could use single variable for the iface name?

2021-05-06 05:52 UTC, pshelar commented on lte/gateway/python/scripts/generate_oai_config.py
> +        iface_name = get_service_config_value(
same here.

2021-05-06 16:20 UTC, uri200 approved these changes

2021-05-06 18:39 UTC, rsarwad commented
> please fix as per the minor comment.

Done

2021-05-07 03:54 UTC, emakeev approved these changes

2021-05-11 19:39 UTC, merged