save OVS Flow TEID to register in pipelined #6596
magma/magma pull request #6771
Opened 2021-05-05 19:29 UTC by prabinakpattnaik

Signed-off-by: prabina pattnaik <prabinak@wavelabs.ai>

## Summary

Add reg9 for store TEID value in ovs table 0 

## Test Plan
Output of table 0 entries:
vagrant@magma-dev:~/magma/lte/gateway$ sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=0
 cookie=0x0, duration=1.903s, table=0, n_packets=0, n_bytes=0, priority=10,tun_id=0x5,in_port=gtp0 actions=set_field:02:00:00:00:00:01->eth_src,set_field:ff:ff:ff:ff:ff:ff->eth_dst,set_field:0x5->reg9,set_field:0x1388->metadata,resubmit(,1)
 cookie=0x0, duration=1.891s, table=0, n_packets=0, n_bytes=0, priority=10,ip,in_port=LOCAL,nw_dst=192.168.128.30 actions=set_field:0x3e8->tun_id,set_field:192.168.60.141->tun_dst,set_field:0x8000->reg8,set_field:oam->tun_flags,set_field:0x5->reg9,set_field:0x1388->metadata,resubmit(,1)
 cookie=0x0, duration=1.891s, table=0, n_packets=0, n_bytes=0, priority=10,ip,in_port=mtr0,nw_dst=192.168.128.30 actions=set_field:0x3e8->tun_id,set_field:192.168.60.141->tun_dst,set_field:0x8000->reg8,set_field:oam->tun_flags,set_field:0x5->reg9,set_field:0x1388->metadata,resubmit(,1)
 cookie=0x0, duration=1.891s, table=0, n_packets=0, n_bytes=0, priority=10,arp,in_port=LOCAL,arp_tpa=192.168.128.30 actions=set_field:0x1388->metadata,resubmit(,1)
 cookie=0x0, duration=1.891s, table=0, n_packets=0, n_bytes=0, priority=10,arp,in_port=mtr0,arp_tpa=192.168.128.30 actions=set_field:0x1388->metadata,resubmit(,1)
 cookie=0x0, duration=1.903s, table=0, n_packets=69, n_bytes=5006, priority=0 actions=resubmit(,1)
 cookie=0x0, duration=1.903s, table=0, n_packets=0, n_bytes=0, priority=0,in_port=ipfix0 actions=resubmit(,201)
 cookie=0x0, duration=1.903s, table=0, n_packets=0, n_bytes=0, priority=0,in_port="li_port" actions=resubmit(,202)

2021-05-06 04:23 UTC, pshelar requested changes

2021-05-06 04:23 UTC, pshelar commented on lte/gateway/python/magma/pipelined/app/classifier.py
> +from magma.pipelined.openflow.registers import TUN_PORT_REG, TUN_ID_REG, Direction
Can you rename this that tells its ingress tunnel id.

2021-05-06 13:14 UTC, prabinakpattnaik commented on lte/gateway/python/magma/pipelined/app/classifier.py
> +from magma.pipelined.openflow.registers import TUN_PORT_REG, TUN_ID_REG, Direction
changed the name as "INGRESS_TUN_ID_REG".

2021-05-07 04:54 UTC, pshelar requested changes

2021-05-07 04:54 UTC, pshelar commented on lte/gateway/python/magma/pipelined/app/classifier.py
can you also fix the lint issues posted on this review.

2021-05-07 18:54 UTC, prabinakpattnaik commented on lte/gateway/python/magma/pipelined/app/classifier.py
Sorry, I forgot to remove the commented code for UT purpose. I have removed it.

2021-05-11 13:29 UTC, koolzz approved these changes
cc @pshelar

2021-05-11 15:31 UTC, pshelar approved these changes

2021-05-13 02:41 UTC, merged