[component: agw] Session Release & UE Deregister
magma/magma pull request #7029
Opened 2021-05-20 18:27 UTC by panyogesh

Fixes included :
  1. PDU Session Release
  2. UE Deregistration

Testcases :
  1. Unit Testcases of ngap
  2. Testing of PDU Session Release on UERANSIM
  3. Testing of UE Deregistration on UERANSIM

Signed-off-by: YOGESH PANDEY <yogesh@wavelabs.ai>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-05-24 18:57 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
> +  //        pdu_res_set_change
can you remove commented out code?

2021-05-24 18:58 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
> +    //    amf_app_handle_nas_dl_req(ue_id, buffer, rc);
remove commented out code pieces.

2021-05-24 18:58 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
> +    //    buffer->slen = bytes;
remove commented out code pieces.

2021-05-24 18:58 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
> +    // return rc;
remove

2021-05-24 19:06 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
> +    bdestroy(buffer);
if there will be no return in this clause `bdestroy` on lines 302 and 304 can be moved out to if/else clause. However, if NAS encode has failed, do we still want to send msg and return RETURNok?

2021-05-24 19:08 UTC, ulaskozat commented on lte/gateway/c/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
> +    bdestroy(buffer);
if returning in else clause, we need to free the allocated message.

2021-05-26 04:06 UTC, ulaskozat approved these changes

2021-05-26 04:07 UTC, ulaskozat requested changes
update session_manager.pb.go

2021-05-26 18:07 UTC, panyogesh commented
<img width="1416" alt="Test-Logs-May-26" src="https://user-images.githubusercontent.com/69527565/119709903-5cac9080-be7b-11eb-82fd-6ca72588c66f.png">

2021-05-26 18:16 UTC, merged

2021-05-27 06:03 UTC, sureshgorijavolu commented
code is merged through #7092