Clean up dead code from service mesh changes
magma/magma pull request #7048
Opened 2021-05-21 21:55 UTC by wangyyt1013

Signed-off-by: Yuanyuting Wang <yuanyutingwang@fb.com>

## Summary

- Remove `Indexer.GetIndexerInfo` rpc and related objects / function implementations
- Remove `reporter_hwid` message field from `IndexRequest` proto
- Remove `StreamProvider.GetStreamName` function definition and related implementations, and adjust related test cases to bypass this change

## Test Plan

Run all existing test cases; all tests should pass

## Additional Information

2021-05-24 04:53 UTC, hcgatewood requested changes
Looks great, thanks Elaine. Just one small cleanup then we can get it merged

2021-05-24 04:53 UTC, hcgatewood commented on feg/gateway/policydb/policydb_test.go
> +	streamer_test_init.StartNewTestProvider(t, &mockStreamProvider{Name: "policydb"}, "policydb")
`mockStreamProvider` doesn't need to know what its stream name is, so can remove it altogether from the object defn

2021-05-24 04:53 UTC, hcgatewood commented on feg/gateway/policydb/policydb_test.go
> +	streamer_test_init.StartNewTestProvider(t, &mockStreamProvider{Name: "policydb"}, "policydb")
`mockStreamProvider` doesn't need to know what its stream name is, so can remove it altogether from the object defn

2021-05-24 04:53 UTC, hcgatewood commented on orc8r/cloud/go/services/streamer/integ_test.go
> +	streamer_test_init.StartNewTestProvider(t, mockProvider, mockProvider.name)
Related to my above comment: this should just be `t, mockProvider, testStreamName`

2021-05-24 04:53 UTC, hcgatewood commented on orc8r/cloud/go/services/streamer/integ_test.go
> +	streamer_test_init.StartNewTestProvider(t, mockProvider, mockProvider.name)
Related to my above comment: this should just be `t, mockProvider, testStreamName`

2021-05-24 04:53 UTC, hcgatewood commented on orc8r/cloud/go/services/streamer/test_init/test_provider_servicer.go
> +func StartNewTestProvider(t *testing.T, provider providers.StreamProvider, name string) {
```suggestion
func StartNewTestProvider(t *testing.T, provider providers.StreamProvider, streamName string) {
```

2021-05-24 04:53 UTC, hcgatewood commented on orc8r/cloud/go/services/streamer/test_init/test_provider_servicer.go
> +func StartNewTestProvider(t *testing.T, provider providers.StreamProvider, name string) {
```suggestion
func StartNewTestProvider(t *testing.T, provider providers.StreamProvider, streamName string) {
```

2021-05-24 17:02 UTC, themarwhal approved these changes
The FeG changes lgtm! :)

2021-05-25 19:25 UTC, wangyyt1013 commented
Creating [new PR](https://github.com/magma/magma/pull/7146) for merging based on changed made

2021-05-25 19:25 UTC, closed without merging