[nms] NMS startup creates a default master user and organization if none exist
magma/magma pull request #7153
Opened 2021-05-26 01:24 UTC by andreilee

Signed-off-by: Andrei Lee <andreilee@fb.com>
## Summary

Currently when the NMS is started for the first time, there are no organizations and users. There is no way to resolve this by creating an organization through the UI because you need to be logged in to create one.

This is currently resolved with the script `dev_setup.sh`, or with the `yarn` command `setAdminPassword` which can help you create a user and organization.

Rather than require a script to be run, this pull request adds in a check on NMS startup which creates a default user and organization with the following credentials:

**Email:** `admin@magma.test`
**Password**: `password1234`

If somebody has a suggestion on making this default user configurable, that would be great

## Test Plan

Tested manually by clearing my local development NMS DB of users, and restarting the NMS pod:

**Before NMS pod restart**
```
nms=# select * from "Users";
 id |      email       |                           password                           | role |         createdAt          |         updatedAt          | networkIDs | verificationType | organization | readOnly |  tabs
----+------------------+--------------------------------------------------------------+------+----------------------------+----------------------------+------------+------------------+--------------+----------+---------
  1 | admin@magma.test | $2a$10$ix5uz3Lt85oRu9DDUmGxQONyse7OCm2gPI4nLoDd/hCUdRWJc1v8i |    3 | 2021-04-28 00:22:52.541+00 | 2021-04-28 00:22:52.541+00 | []         |                0 | magma-test   | f        | ["nms"]
  2 | admin@magma.test | $2a$10$ddQlzG03I5FTebskqO8WA.IY1XR.gyacdpZQKIrfZfe082wJmgp4m |    3 | 2021-04-28 00:22:55.142+00 | 2021-04-28 00:22:55.142+00 | []         |                0 | master       | f        | ["nms"]
  3 | test@magma.test  | $2a$10$g18t5kCZVlh/k8eMTfatGOdmkdNed5yz9hTOiw9/8NnxMIeNXzbbS |    0 | 2021-04-28 00:23:31.527+00 | 2021-04-28 00:23:31.527+00 | []         |                0 | magma-test   | f        | []
(3 rows)

nms=# DELETE from "Users";
DELETE 3
nms=# select * from "Users";
 id | email | password | role | createdAt | updatedAt | networkIDs | verificationType | organization | readOnly | tabs
----+-------+----------+------+-----------+-----------+------------+------------------+--------------+----------+------
(0 rows)
```

**After NMS pod restart**
```
nms=# select * from "Users";
 id |      email       |                           password                           | role |         createdAt         |         updatedAt         | networkIDs | verificationType | organization | readOnly |  tabs
----+------------------+--------------------------------------------------------------+------+---------------------------+---------------------------+------------+------------------+--------------+----------+---------
  4 | admin@magma.test | $2a$10$t7LjdKd0jS1e7RRwpAI93OzjTbiJNQBzJDPrIkyQ8KvF7Q9BJaqj. |    3 | 2021-05-26 00:57:43.67+00 | 2021-05-26 00:57:43.67+00 | []         |                0 | master       | f        | ["nms"]
(1 row)
```

## Additional Information

- [ ] This change is backwards-breaking

2021-05-26 03:14 UTC, karthiksubraveti reviewed
This might not be safe from security perspective. It is better not to create any default users. However your point is right on the painpoint of creating a user with a script. We should be able to automate this if we install it as a post-install hook for the NMS helm chart.

2021-05-27 16:54 UTC, electronjoe approved these changes
LGTM for documentation change

2021-07-30 05:06 UTC, hcgatewood requested changes
I'm excited about this feature, but this is not how I'd accomplish it

Operators should be able to delete all their users/orgs and not have a globally-accessible user be silently created

Instead of doing this "on startup if zero users exist", store a flag on whether the default user has ever been created for this deployment

If the flag's not set, create the default user on startup + set the flag. If it is set, skip

P.S. looks like this PR is pretty stale, was there a roadblock?

2021-09-01 15:50 UTC, ekowtaylor commented
@andreilee what are the plans to move forward with this?

2021-09-09 15:44 UTC, ekowtaylor commented
@andreilee checking in again on this PR

2021-09-27 23:34 UTC, andreilee commented
Based on @karthiksubraveti's feedback, I won't move forward with this as a solution. Closing this pull request, and a different solution will be put up for review at a later time.

2021-09-27 23:34 UTC, closed without merging