[lte][agw] Congestion control
magma/magma pull request #7212
Opened 2021-06-01 04:22 UTC by ulaskozat

## Summary

- Adds zmq delay logging for S1AP and MME APP tasks.
- Adds a basic congestion control mechanism based on absolute latency thresholds to eliminate MME and AGW instability. The packets are dropped at points where UE based retries can be done and attach requests are rejected explicitly in the case of congestion.
- Adds configuration parameters for the threshold values to be used by S1AP and MME APP tasks. 

## Test Plan

- Spirent tests where the system is loaded above, at and under its capacity. 
- Integ tests.

## Additional Information

- [ ] This change is backwards-breaking

2021-06-01 12:58 UTC, themarwhal commented on lte/gateway/configs/mme.yml
> +s1ap_zmq_th: 2000000 # microseconds (delay threshold used for dropping initial UE message)
nit: might be good to append all the configs with `_us` to have the unit in the name itself?

2021-06-01 16:15 UTC, ardzoht requested changes
few comments to address

2021-06-01 16:15 UTC, ardzoht commented on lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
> +  OAILOG_INFO(
should this be DEBUG level?

2021-06-01 16:15 UTC, ardzoht commented on lte/gateway/c/oai/tasks/nas/emm/Authentication.c
> +#include "mme_app_state.h"
is this include being actually used?

2021-06-01 16:15 UTC, ardzoht commented on lte/gateway/configs/mme.yml
> +mme_app_zmq_auth_th: 200000 # microseconds (delay threshold used for dropping Authentication Complete)
legit linting warnings

2021-06-02 05:18 UTC, ardzoht approved these changes
Lgtm

2021-06-02 06:01 UTC, ulaskozat commented
@rdefosse could you check why OAI pipeline is failing?

2021-06-02 08:00 UTC, rdefosse commented
> 
> 
> @rdefosse could you check why OAI pipeline is failing?

@ulaskozat 

We had an issue with DsTester yesterday. I think your pull request is OK but you can resynch and re-trigger for safety

Raphael

2021-06-02 15:19 UTC, merged