[mme][refactor] Remove AssertFatal from mme_api_get_emm_config
magma/magma pull request #7377
Opened 2021-06-07 22:00 UTC by andreilee

Signed-off-by: Andrei Lee <andreilee@fb.com>

## Summary

This PR is among a series of changes to rework how the `AssertFatal` macro is used in MME. As part of this, API methods should not use `AssertFatal`, instead allowing callers higher up to decide whether or not to stop MME.

In this PR, function `mme_api_get_emm_config(..)` is modified to remove all calls to the `AssertFatal` macro, instead returning `RETURNerror`. The only caller of this function is `emm_main_initialize(..)`, which has been modified to call `Fatal`.

## Test Plan

Only built MME service:

```
vagrant@magma-dev:~/magma/lte/gateway$ make build_oai
.
.
.
[1971/1971] Linking CXX executable oai_mme/mme
vagrant@magma-dev:~/magma/lte/gateway$ 
```

## Additional Information

- [ ] This change is backwards-breaking

2021-06-08 16:32 UTC, ulaskozat requested changes
We lose granularity on what config was the culprit for initialization failure.

2021-06-10 00:44 UTC, andreilee commented
@ulaskozat MME should still throw, no? And it looks like there's only one config that gets processed by that function as well.

2021-06-10 00:47 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/nas/emm/emm_main.c
> +    Fatal("EMM-MAIN  - Failed to get MME configuration data");
Maybe add more context to message, e.g., "EMM-MAIN - Failed to get all required MME config data, check the error logs for missing configs"

2021-06-10 00:48 UTC, ulaskozat approved these changes
Okay I guess we are printing the Error logs so one can figure out the offending configs. I added a nit comment so that message provides hint to look for the missing config.

2021-06-11 22:23 UTC, merged