Poll Stats GRPC Endpoint(DRAFT)
magma/magma pull request #7397
Opened 2021-06-08 17:33 UTC by veshkemburu

Signed-off-by: Vesh Kemburu <veshkemburu@fb.com>

## Summary

Creating a functional pipelined grpc endpoint that replies with stats for a certain subset of rules(matched by cookie mask).
Still in progress.

## Test Plan

1. Add GRPC Endpoint to pipelined.proto, which takes in a GetStatsRequest and returns a RuleRecordTable
2. Define GetStatsRequest message in pipelined.proto to have two attributes: cookie and cookie mask
3. Add argument fields to enforcement_parser in pipelined_cli.py, including a new pull stats command, and two arguments cookie and cookie mask, linking to an rpc wrapper function
4. Define the grpc wrapper function that takes in a client and a set of arguments and returns a response. In this function define a GetStatsRequest using the args, and call GetStats on the client to retrieve a response(then return this response) 
5. In rpc_servicer.py, define GetStats grpc handler. Have this handler invoke the api in flows.py by calling an intermediate function we define in enforcement_stats.py. The intermediate function will return a rule record table which is returned from this function
6. Have the handler in enforcement_stats.py invoke the API? I’m guessing no futures are needed(everything is built into the API), and then use _get_usage_from_flow_stat to convert the result into a RuleRecordTable.
7. From sessiond’s perspective, we need to update PipelinedClient.h to include the new endpoint
8. Add unit test to verify function 

## Additional Information

- [ ] This change is backwards-breaking

2021-06-08 17:36 UTC, themarwhal commented
Hey vesh! Is it possible to split this up into two PRs? one for pipelined changes and one for sessiond?

2021-06-09 20:47 UTC, koolzz commented on lte/gateway/python/scripts/pipelined_cli.py
> +from magma.pipelined.
rm

2021-06-10 17:08 UTC, themarwhal commented on lte/gateway/python/magma/enodebd/rpc_servicer.py
> +    def GetStats(self, request):
?

2021-06-11 18:30 UTC, koolzz requested changes

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/scripts/pipelined_cli.py
> +    print("=============")
rm print

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/scripts/pipelined_cli.py
> +    return response
instead of return just ```pprint(response)```

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/scripts/pipelined_cli.py
> +    print(type(request))
rm print

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/scripts/pipelined_cli.py
> +    subcmd = subparsers.add_parser('pull_stats_grpc', help = 'Enables or disables pull model for stats collection')
change help explanation

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/scripts/pipelined_cli.py
> +
rm whitespace

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/scripts/pipelined_cli.py
> -
add back the newline

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/magma/pipelined/tests/test_pull_stats.py
> +    def test_poll(self):
missing space between funcs

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/magma/pipelined/tests/test_pull_stats.py
> +    convert_ipv6_bytes_to_ip_proto,
Clean up unused imports

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> +def GetStats(self, request):
Move this up so its part of the
```

    # --------------------------
    # Enforcement App
    # --------------------------
```
section

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> +    #call intermediate enforcement stats function defined in enforcement_stats.py
rm comment

2021-06-11 18:30 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> +#grpc handler
rm comment

2021-06-11 19:53 UTC, koolzz requested changes

2021-06-11 19:53 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +        #invoke RYU API
Rm

2021-06-11 19:53 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +        message = parser.OFPFlowStatsRequest(datapath=self._datapath, cookie = cookie, cookie_mask = cookie_mask)
If you don't need ofproto don't save it

2021-06-11 19:53 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +        '''
Rm comment/comment block

2021-06-11 19:53 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +        RRTable = self._get_usage_from_flow_stat(response[0].body)
I think you're missing proto conversion? Also don't use upper case when naming

2021-06-11 19:53 UTC, koolzz commented on lte/gateway/python/magma/pipelined/tests/test_pull_stats.py
> +            TODO: Call your new  enforcement_stats function from here and verify output
Rm todo

2021-06-11 19:53 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +        response = ofctl_api.send_msg(self, message, reply_cls=parser.OFPFlowStatsReply,
I think this can throw exceptions (check the api) surround with try/catch and let's handle thosr

2021-06-11 21:09 UTC, koolzz requested changes

2021-06-11 21:09 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +        _, parser = self._datapath.ofproto, self._datapath.ofproto_parser
If you don't need ofproto don't save it

2021-06-11 21:09 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +                    reply_multi=True)
Lets do
`reply_multi=False`

2021-06-11 21:09 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +            RRTable = self._get_usage_from_flow_stat(response[0].body)
change name to confirm to style standards, smth like `flows = self._get_usage_from_flow_stat(response[0].body)`

2021-06-11 21:09 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +            RRTable = self._get_usage_from_flow_stat(response[0].body)
check that response is not None

2021-06-11 21:09 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> -
undo whitespace removal

2021-06-11 21:09 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> +    def getStatsHelper(self, request, fut):
following other naming convenctions lets do `get_stats`

2021-06-11 21:09 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> +            return RuleRecordTable()
add space after

2021-06-11 21:09 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> +        #linked to pipelined_cli and returns result of command line invocation on pull stats
this is already implied by it being a grpc function so rm

2021-06-11 21:09 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> +        #linked to pipelined_cli and returns result of command line invocation on pull stats
you can add a docstring explanation of what its doing though

2021-06-11 21:09 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> +            logging.error("Get Stats timed out")
`GetStats request processing timed out`

2021-06-14 17:00 UTC, koolzz requested changes

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> -
undo whitespace changes

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> -
undo whitespace changes

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> -
undo whitespace changes

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/magma/pipelined/tests/test_pull_stats.py
> +            theStats = self.enforcement_stats_controller.get_stats()
don't use camelcase for variable naming in python, also theStats is not a very descriptive name, try:
```
rule_map = self.enforcement_stats_controller.get_stats()
if rule_map.records[0].rule_id ==  DEFAULT_DROP_FLOW_NAME:
    rule_record = rule_map.records[0]
else:
    rule_record = rule_map.records[1]
```
Then use this kind of comparison for all
self.assertEqual(rule_record.sid, imsi)

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> +<<<<<<< HEAD
resolve

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/magma/pipelined/rpc_servicer.py
> +            return None
```
            context.set_code(grpc.StatusCode.UNAVAILABLE)
            context.set_details('Service not enabled!')
            return None
            ```

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
> +
undo whitespace changes

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/scripts/pipelined_cli.py
> -
undo whitespace changes

2021-06-14 17:00 UTC, koolzz commented on lte/protos/pipelined.proto
> +  rpc GetStats(GetStatsRequest) returns (RuleRecordTable);
This isn't debugging method so move it up to the `Enforcement App:` section

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +            return RuleRecordTable()
log error here

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +            if response:
prefer
```
if response == None:
    return RuleRecordTable()
```
Also log error as reply didn't return anything

2021-06-14 17:00 UTC, koolzz commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> -
undo whitespace changes in this file

2021-06-14 19:22 UTC, koolzz commented on lte/gateway/python/magma/pipelined/tests/test_pull_stats.py
> +            DEFAULT_DROP_FLOW_NAME = "(ノಠ益ಠ)ノ彡┻━┻"
no need to redefine this, its in self. DEFAULT_DROP_FLOW_NAME

2021-06-14 23:07 UTC, koolzz approved these changes

2021-06-16 16:51 UTC, pshelar commented on lte/gateway/python/magma/pipelined/app/enforcement_stats.py
> +            return RuleRecordTable()
can you also add context, like the cookie and mask.

2021-06-16 16:51 UTC, pshelar commented on lte/gateway/python/magma/pipelined/tests/test_pull_stats.py
> +            rule_map = self.enforcement_stats_controller.get_stats()
can you also add test case that request stats with cookie and mask?

2021-06-16 18:19 UTC, pshelar approved these changes
LGTM

2021-06-16 19:07 UTC, merged