Common AGW builds
magma/magma pull request #7713
Opened 2021-06-22 22:40 UTC by arunuke

Signed-off-by: Arun Thulasi <arunt@fb.com>

Building version independent AGWs

## Summary

Changed version-specific AGW build scripts to a version based on tunables.

## Test Plan

Run devops tool chain to generate AGW versions starting v 1.5

## Additional Information

- [ ] This change is backwards-breaking

2021-06-23 15:59 UTC, quentinDERORY requested changes
It might be good to override the default version of the magma-deploy role from lte/gateway/deploy/roles/magma-deploy with this new buildAgwVersion variable.
It means specifying in experimental/cloudstrapper/playbooks/roles/magma-agw/tasks/agw-setup.yaml this variable:
 - magma_pkgrepo_dist: focal-1.6.0
 Otherwise it will always grab the latest packages version.

2021-06-23 19:23 UTC, arunuke commented
> It might be good to override the default version of the magma-deploy role from lte/gateway/deploy/roles/magma-deploy with this new buildAgwVersion variable.
> It means specifying in experimental/cloudstrapper/playbooks/roles/magma-agw/tasks/agw-setup.yaml this variable:
> 
> * magma_pkgrepo_dist: focal-1.6.0
>   Otherwise it will always grab the latest packages version.

Added a new variable defined in build (and used for devops purposes) to reflect package of choice.

2021-06-23 20:05 UTC, quentinDERORY reviewed
The magma_pkgrepo_dist: "focal-{{ buildAgwPackage }}" will not be picked by the magma-deploy role, you need to put this variable inside this file: experimental/cloudstrapper/playbooks/roles/magma-agw/files/ansible-env.yaml .

2021-06-24 16:57 UTC, quentinDERORY approved these changes

2021-06-24 18:08 UTC, merged