[show-tech] Add commands and logs in playbook
magma/magma pull request #7841
Opened 2021-06-29 20:36 UTC by wallyrb

Signed-off-by: Wally Rodriguez B <wallyrb@fb.com>

## Summary

- "command" in ansible doesn't take pipes. Changing to "dpkg -l magma*" in order to get sctpd and other magma package related versions
- Add "sudo" in the documentation
- Add ovs commands to be collected
- Scheck service status from ovs and scptd
- Collect all /var/log folder from AGW
- Since we are collecting syslogs, remove the journalctl -u magma@* command

## Test Plan

Tested in 1.5 Ubuntu AGW

2021-06-29 22:30 UTC, pshelar commented on show-tech/constants.yml
> +  - "/var/log/*"
can you also include '/var/log/openvswitch/'

2021-06-29 22:57 UTC, karthiksubraveti requested changes
We should be able to set privilege escalation to individual tasks instead of running ansible-playbook in sudo mode. Can you add sudo to tasks which require this alone. https://docs.ansible.com/ansible/2.3/become.html

2021-07-01 02:16 UTC, pshelar commented on show-tech/constants.yml
> +  - "dpkg -l magma*"
lets also get ovs version: `dpkg -l openvswitch*`

2021-07-01 09:29 UTC, wallyrb commented
> We should be able to set privilege escalation to individual tasks instead of running ansible-playbook in sudo mode. Can you add sudo to tasks which require this alone. https://docs.ansible.com/ansible/2.3/become.html

@karthiksubraveti I tried using become in the tasks that required it. However, for the module "copy" and any other module with "src", become will apply only for writing the file not for reading. Therefore, if the local user doesn't have permissions to read "src"  it will fail with "an error occurred while trying to read the file Permission denied"

https://superuser.com/questions/1522927/ansible-copy-module-become-permission-denied

We could either use "sudo' when run the playbook or try with another module that is not copy. (maybe command)

2021-07-06 14:34 UTC, themarwhal approved these changes
doc changes lgtm

2021-07-06 14:49 UTC, electronjoe commented
I was waiting for clear-up of the questions posted by @pshelar and @karthiksubraveti  - before giving docs LGTM from owner-side. I'll give stamp now but not clear to me if all parties are yet satisfied above?

2021-07-06 14:49 UTC, electronjoe approved these changes
Thank you for updating docs Wally!

2021-07-06 15:31 UTC, pshelar approved these changes

2021-07-06 15:40 UTC, karthiksubraveti commented
> become

Sounds good. Let's go with this and change it when we have a better approach

2021-07-06 15:40 UTC, karthiksubraveti approved these changes

2021-07-14 02:02 UTC, wallyrb commented
hey @electronjoe ! could you help me check if something is pending to merge this? Will appreciate any suggestions to complete this. Thanks!

2021-07-14 02:04 UTC, merged