[new testcases] New s1ap tester testcases to test concurrent pdn sessions
magma/magma pull request #7880
Opened 2021-07-01 12:27 UTC by pruthvihebbani

[new testcases] New s1ap tester testcases to test concurrent PDN session creation

## Summary

Added two TCs to test standalone concurrent PDN sessions.

## Test Plan

- Verified PDN sessions are successfully created by executing the new TCs
- Verified s1sim sanity suite

2021-07-01 15:42 UTC, ulaskozat requested changes
change category of the tests for now.

2021-07-01 15:42 UTC, ulaskozat commented on lte/gateway/python/integ_tests/defs.mk
> +s1aptests/test_concurrent_secondary_pdn_reject.py \
let's add these to NON_SANITY_TEST as sessiond has issues with concurrent standalone PDN requests for the same UE (not always but will make these tests flaky). After @themarwhal lands the fix, we can add them back to EXTENDED_TESTS.

2021-07-01 20:36 UTC, themarwhal commented on lte/gateway/python/integ_tests/s1aptests/test_concurrent_secondary_pdns.py
> +            ue_id, s1ap_types.ueDetachType_t.UE_SWITCHOFF_DETACH.value, False,
`ue_id, s1ap_types.ueDetachType_t.UE_SWITCHOFF_DETACH.value, wait_for_s1_ctxt_release=False,`

2021-07-06 17:08 UTC, themarwhal commented
dw about the format check, as it is unrelated to your PR. Thanks for addressing all python annotations!

2021-07-13 06:12 UTC, ulaskozat approved these changes
LGTM

2021-07-13 06:15 UTC, ulaskozat commented
For Semantic Pull Request to pass, you need to follow the convention here https://docs.magmacore.org/docs/next/contributing/contribute_workflow#guidelines 

"Required: PR title must follow conventional commits format. For example, fix(agw): Fix pyroute2 dependency. See semantic.yml for the set of supported scopes."

2021-07-13 16:11 UTC, merged