fix(agw): Process subscriber data before digest data
magma/magma pull request #7983
Opened 2021-07-10 19:57 UTC by wangyyt1013

## Summary

1. Switched ordering of processing subscriber data (now first) and digest data (now second) in case there's a gw failure between the two calls

## Test Plan

1. Ran all existing tests; all passed

## Additional Information

- This fix is meant to be back-ported to v1.6

2021-07-15 01:13 UTC, hcgatewood requested changes
As discussed offline: open this PR against master and add the `apply-v1.6` label

2021-07-16 04:50 UTC, hcgatewood reviewed
As discussed offline: need to fix the base branch

2021-07-16 16:14 UTC, hcgatewood approved these changes

2021-07-16 19:30 UTC, ardzoht approved these changes
lgtm

2021-07-16 20:04 UTC, merged