docs(agw): [proposal] UE Requested PDU Session Modification with magma
magma/magma pull request #7988
Opened 2021-07-12 13:04 UTC by GANESH-WAVELABS

[proposal] UE Requested PDU Session Modification with magma

## Summary
Handling of UE Requested PDU Session Modification in magma

## Test Plan
UE requested session modification should be tested with DSTester and TeraVM.

## Additional Information
Signed-off-by: GANESH-WAVELABS <ganesh.irrinki@wavelabs.ai>

2021-07-12 13:26 UTC, electronjoe requested changes

2021-07-12 13:26 UTC, electronjoe commented on docs/readmes/proposals/p018_ue_requested_pdu_session_modification.md
> +can fulfil such a request from the UE by modifying a PDU session or releasing
Minor misspelling of `fulfill`

2021-07-12 13:27 UTC, electronjoe commented
Is there an associated Github Issue for this proposal? The process calls for one, it's nice to link it in the PR description so they are tied.

2021-07-12 16:08 UTC, GANESH-WAVELABS commented on docs/readmes/proposals/p018_ue_requested_pdu_session_modification.md
> +can fulfil such a request from the UE by modifying a PDU session or releasing
Corrected the misspelling. Thank you

2021-07-12 16:09 UTC, GANESH-WAVELABS commented
> Is there an associated Github Issue for this proposal? The process calls for one, it's nice to link it in the PR description so they are tied.

Added Corresponding Github issue : #7971 in Summary.

2021-07-16 15:40 UTC, uri200 commented
Please, plan on adding unit test to those systems that allow it currently. For example sessiond.

Also what is the plan to test it with TereaVm?  What is DSTest?

2021-07-16 17:17 UTC, uri200 commented on docs/readmes/proposals/p018_ue_requested_pdu_session_modification.md
> +
When SMF receives the request to modify Qos, how does SMF decides if this change is valid or not? 
Does SMF stores any kind of profile information ? Does SMF do a query to any other system to check if the Qos change is allowed?

2021-07-19 19:23 UTC, ulaskozat commented
@sureshgorijavolu can you link the zenhub issue for PCF extensions to this proposal?

2021-07-30 19:45 UTC, hcgatewood commented
@uri200 @ulaskozat where are we at with this PR

2021-07-30 20:09 UTC, ulaskozat commented
@hcgatewood it is still under progress and discussion.

2021-08-24 10:38 UTC, GANESH-WAVELABS commented
As per Phil's suggestion "this feature to be suspended as there is no demand from the customers for years on this features" Hence take it off the radar closing the issue.

2021-08-24 10:38 UTC, closed without merging