fix(pipelined): avoid cleaning up uplink-br0 in stateless mode.
magma/magma pull request #7997
Opened 2021-07-12 18:04 UTC by pshelar

Cleaning up uplink-br0 can disrupt traffic during service restart.

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>

## Summary

## Test Plan
TODO: Test it in lab setup.
 

## Additional Information

- [ ] This change is backwards-breaking

2021-07-12 18:10 UTC, amarpad requested changes
Don't you still have to check the flow table is inline with what it needs to be, what happens if the config changes?

2021-07-12 18:26 UTC, amarpad reviewed
Also can you explain def initialize_on_connect(self, datapath) and if it wouldn't clear the flows as well? It has a delete_all_flows

2021-07-12 18:50 UTC, pshelar commented
> Don't you still have to check the flow table is inline with what it needs to be, what happens if the config changes?

initialize_on_connect() delete flows takes care of cleanup.

2021-07-12 18:53 UTC, pshelar commented
> Also can you explain def initialize_on_connect(self, datapath) and if it wouldn't clear the flows as well? It has a delete_all_flows

yes, but the uplink-controller adding flows right after that, so OVS would be missing flows for few milliseconds.
we can improve it by generation flows based on flow diff.

2021-07-13 02:15 UTC, pshelar commented
I validated it on bare metal AGW, it works fine.
even without this patch I dont see loosing flows in uplink_br0, so we dont needs to backport this PR.

2021-07-13 02:17 UTC, amarpad commented
But on 1.5 I saw the flows getting nuked because at a later point pipelined crashed. I still think we should be conservative and diff against forwarding state and not nuke flows as the downside of bricking a box is really big

2021-07-13 02:42 UTC, amarpad approved these changes
This is a different issue than the one we saw, approving this.

2021-07-13 17:14 UTC, merged