[orc8r][ci] Add git status output to slack failing notification
magma/magma pull request #8192
Opened 2021-07-20 18:48 UTC by quentinDERORY

Signed-off-by: Quentin, Derory <15911421+quentinDERORY@users.noreply.github.com>

## Summary

Add git status output to insync-checkin slack failure notification

## Test Plan

Tested in my local repo

## Additional Information

- [ ] This change is backwards-breaking

2021-07-20 18:49 UTC, mattymo approved these changes

2021-07-21 07:50 UTC, hcgatewood requested changes
Thanks for this @quentinDERORY! One small request, then will be ready

2021-07-21 07:50 UTC, hcgatewood commented on .github/workflows/cloud-workflow.yml
> +            echo GIT_STATUS=`git status` >> $GITHUB_ENV
Can you both save it and print it here (that way we can view it both from the Slack notification and in the job

2021-07-21 07:50 UTC, hcgatewood commented on .github/workflows/cloud-workflow.yml
> +            echo GIT_STATUS=`git status` >> $GITHUB_ENV
Also, nit for uniformity:
```suggestion
            echo GIT_STATUS=$(git status) >> $GITHUB_ENV
```

2021-07-21 19:35 UTC, hcgatewood approved these changes
💯

2021-07-21 19:35 UTC, hcgatewood commented on .github/workflows/cloud-workflow.yml
> +            echo $GIT_STATUS
Does this work? Nice

2021-07-21 23:04 UTC, quentinDERORY commented on .github/workflows/cloud-workflow.yml
> +            echo $GIT_STATUS
Now yes !

2021-07-22 15:05 UTC, merged