Added config flag for max shard size
magma/magma pull request #8303
Opened 2021-07-27 17:42 UTC by veshkemburu

Signed-off-by: veshkemburu <veshkemburu@fb.com>

## Summary

Shard size should be changeable dynamically rather than be set to a constant value. Let's add the field to sessiond.yml

## Test Plan

Checked that proper value was loaded in, and when config was omitted. 

## Additional Information

- [ ] This change is backwards-breaking

2021-07-27 17:48 UTC, pshelar requested changes
Please post perf numbers with different shard size, so rationalize the default shard size.

2021-07-27 17:55 UTC, koolzz commented on lte/gateway/c/session_manager/ShardTracker.cpp
> +  // read max shard size config value from sessiond.yml
I think its eaasier to just parse config in sessiond_main (and pass the value)

2021-07-27 21:22 UTC, themarwhal commented on cwf/gateway/configs/sessiond.yml
> +# set to the maximum amount of UEs that can be assigned a particular shard id
```suggestion
maximum number of UEs that can be assigned a particular shard id
```
for all the config files

2021-07-27 21:26 UTC, themarwhal requested changes
looks good, minor nits.

2021-07-27 21:26 UTC, themarwhal commented on lte/gateway/c/session_manager/ShardTracker.cpp
> +ShardTracker::ShardTracker(uint32_t max_shard_size) {
```suggestion
ShardTracker::ShardTracker(uint32_t max_shard_size): max_shard_size_(max_shard_size) {
```

2021-07-27 21:26 UTC, themarwhal commented on lte/gateway/c/session_manager/sessiond_main.cpp
> +    max_shard_size = 100;
Let's define the default value in a variable above like others

2021-07-27 21:26 UTC, themarwhal commented on lte/gateway/c/session_manager/sessiond_main.cpp
> +    max_shard_size = 100;
If we're using the default value, we should log that

2021-07-27 21:26 UTC, themarwhal commented on lte/gateway/c/session_manager/test/test_local_enforcer.cpp
> +    auto shard_tracker   = std::make_shared<ShardTracker>(100);
maybe define the default value in Consts.h?

2021-08-04 16:52 UTC, themarwhal approved these changes

2021-08-09 16:09 UTC, pshelar approved these changes
LGTM

2021-10-04 19:01 UTC, ekowtaylor commented
@veshkemburu , @pshelar this PR has now gone stale. To maintain a healthy codebase, it will automatically closed unless there are plans to rebase and merge by close of week

2021-10-04 19:34 UTC, pshelar commented
@koolzz can we get this in, I dont see any downside of this.

2021-10-04 19:44 UTC, koolzz commented
> @koolzz can we get this in, I dont see any downside of this.

sure, tests seem stuck let me restart

2021-11-11 18:14 UTC, ekowtaylor commented
@koolzz, what are the next steps? This has gone stale again

2022-02-16 18:51 UTC, ekowtaylor commented
@pshelar , @koolzz this PR has definitely gone stale. Wondering if it makes sense to close and start over if the intent results is still required?

2022-02-16 22:05 UTC, closed without merging