5G Idle mode and service request procedure
magma/magma pull request #8418
Opened 2021-08-02 13:00 UTC by VinayKumar1591

feat(mme): 5G Idle mode and service request procedure

       1. Tested on NGAP Tester
       2. Tested on DS Tester

Signed-off-by: vinay <vinay.tokala@radisys.com>

## Summary

Added changes to support Idle mode and service request procedure

## Test Plan

Tested on NGAP and DS Tester

2021-08-02 18:45 UTC, ulaskozat requested changes
Please add unit test coverage.

2021-08-03 17:37 UTC, VinayKumar1591 commented
> Please add unit test coverage.

Added UT cases

2021-08-04 04:58 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GPDUSessionReActivationResult.cpp
> +int M5GPDUSessionReActivationResult::EncodePDUSessionReActivationResult(
can you add unit test?

2021-08-04 04:58 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GPDUSessionReActivationResult.cpp
> +int M5GPDUSessionReActivationResult::DecodePDUSessionReActivationResult(
add unit test

2021-08-04 04:59 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/nas5g/src/M5GServiceAccept.cpp
> +  if ((encoded_result = svc_acpt->pdu_session_status.EncodePDUSessionStatus(
add unit test

2021-08-04 05:00 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
> +static int amf_service_acceptmsg(
add unit test

2021-08-05 17:46 UTC, ulaskozat approved these changes
Additional unit tests will be added in a separate PR after build paths are resolved properly.

2021-08-06 17:33 UTC, merged