Update apn configuration docs
magma/magma pull request #8520
Opened 2021-08-06 08:07 UTC by avast1268

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-08-06 22:47 UTC, hcgatewood requested changes
Hey Ava, thanks for adding this PR!

One note on the content: looks like you're adding some png files that aren't being referenced in the actual documentation. Let's go ahead and remove the ones that are unused

And for passing CI: the DCO check and semantic pr check should provide comments on how to fix them. You'll also want to follow our [Docs Precommit](https://magma.github.io/magma/docs/next/docs/docs_overview#precommit) howto for linting your doc changes

2021-08-06 22:47 UTC, hcgatewood commented on docs/readmes/lte/deploy_config_apn.md
> +
No need for these extra newlines

2021-08-06 22:47 UTC, hcgatewood commented on docs/readmes/lte/deploy_config_apn.md
> +
Nit: no need for these newlines between list points

2021-08-06 22:47 UTC, hcgatewood commented on docs/readmes/lte/deploy_config_apn.md
> +choose the Sunscriber tab.
Typo (?)

2021-09-09 21:02 UTC, ekowtaylor commented
@avast1268 what support is needed to merge these changes?

2022-02-16 22:07 UTC, ekowtaylor commented
@avast1268 any interests in moving forward with this PR?

2022-02-17 17:07 UTC, ekowtaylor commented
Lets reopen and rebase if you plan to move forward with this.

2022-02-17 17:07 UTC, closed without merging