[tracing] Context propagation for all network-related functions in configurator client API
magma/magma pull request #8535
Opened 2021-08-08 02:24 UTC by xjtian

## Summary

- Propagate contexts in all network functions in configurator client_api.go

## Test Plan

- make test

## Additional Information

- [ ] This change is backwards-breaking

Signed-off-by: Jacky Tian <jacky@xjtian.com>

2021-08-10 04:40 UTC, hcgatewood requested changes
Looking good! Got about halfway through, main thing I notice is we're passing context.Background() as args in a fair number of places where we actually wanna forward a context from the scope's params

Take a skim through when you have a chance, then msg me when you're ready and I'll give it another look over 🙂

2021-08-10 04:40 UTC, hcgatewood commented on cwf/cloud/go/services/cwf/obsidian/handlers/handlers.go
> +	if err := haPair.ValidateModel(context.Background()); err != nil {
Why context.Background here? Assuming we can grab the reqCtx from the echo.Context and pass it in

2021-08-10 04:40 UTC, hcgatewood commented on lte/cloud/go/services/lte/analytics/calculations/state.go
> +	networks, err := configurator.ListNetworkIDs(context.Background())
All calculations can take a ctx from https://github.com/magma/magma/blob/4676cc0b7897a219473f41f6b6e02d64da3d141a/orc8r/cloud/go/services/analytics/collector_servicer.go#L49-L50

2021-08-10 04:40 UTC, hcgatewood commented on lte/cloud/go/services/lte/obsidian/handlers/handlers.go
> +	if err := payload.ValidateModel(context.Background()); err != nil {
Same here and below: seems like most of these can take a reqCtx

2021-08-10 04:40 UTC, hcgatewood commented on lte/cloud/go/services/lte/obsidian/models/validate.go
> +	if err := m.Cellular.ValidateModel(context.Background()); err != nil {
These can be the passed context param

2021-08-10 09:58 UTC, xjtian commented
> Looking good! Got about halfway through, main thing I notice is we're passing context.Background() as args in a fair number of places where we actually wanna forward a context from the scope's params
> 
> Take a skim through when you have a chance, then msg me when you're ready and I'll give it another look over 🙂

My plan at the moment is to tackle the top-level callsites of `ValidateModel` along the way as I refactor the entity-related functions - that diff will hit all of those. Then I can follow that up with a cleanup diff that addresses the recursive `ValidateModel` calls in the model definitions.

Thoughts?

2021-08-10 20:47 UTC, hcgatewood commented
> > Looking good! Got about halfway through, main thing I notice is we're passing context.Background() as args in a fair number of places where we actually wanna forward a context from the scope's params
> > Take a skim through when you have a chance, then msg me when you're ready and I'll give it another look over 🙂
> 
> My plan at the moment is to tackle the top-level callsites of `ValidateModel` along the way as I refactor the entity-related functions - that diff will hit all of those. Then I can follow that up with a cleanup diff that addresses the recursive `ValidateModel` calls in the model definitions.
> 
> Thoughts?

Yeah I think what we can do then is I'll just go ahead and stamp all your PRs going forward, then at the end we can have ~2 cleanup PRs

1. Remove all the `x/.../context` in favor of the stdlib `context`
2. Comb through all non-test `context.Background()` declarations and determine whether they should be removed in favor of passing a received context

2021-08-10 20:48 UTC, hcgatewood approved these changes

2021-08-11 12:04 UTC, themarwhal approved these changes

2021-08-12 16:01 UTC, uri200 approved these changes

2021-08-25 08:49 UTC, merged