Changed Host-IP-Address in CER to be local address configured in diameter client.
magma/magma pull request #8753
Opened 2021-08-25 02:52 UTC by sourabh-nanoti

https://github.com/magma/magma/issues/8752 

## Summary

## Test Plan

Verified the changes by establishing connections with the PCRF as mentioned in the PR description,.

## Additional Information

- [ ] This change is backwards-breaking -- No
<img width="1666" alt="Screen Shot 2021-08-25 at 10 27 00 AM" src="https://user-images.githubusercontent.com/48265190/130718490-640fc131-3c6c-4062-b244-6536e5718a04.png">

2021-08-25 22:44 UTC, emakeev requested changes
please see the inline comment.

2021-08-25 22:44 UTC, emakeev commented on feg/gateway/diameter/diameter_client.go
> +		HostIPAddress:    datatype.Address(net.ParseIP(clientCfg.Host)),
It's only going to work in case of clientCfg.Host being an IP. Host is DiamIdent, HostIPAddress is Address.
How would it work when you need to set Origin-Host to 'feg.magma.com' and Host-IP-Address to '10.16.2.204'?

How was it tested?

You may need a new config parameter added to DiameterClientConfig to set Host-IP-Address independently from Origin-Host.

2021-08-26 03:52 UTC, sourabh-nanoti commented on feg/gateway/diameter/diameter_client.go
> +		HostIPAddress:    datatype.Address(net.ParseIP(clientCfg.Host)),
"How would it work when you need to set Origin-Host to 'feg.magma.com' and Host-IP-Address to '10.16.2.204'?"
@emakeev - Thanks for pointing this out. It worked because due to the error introduced by the above change, the HostIPAddress was set  to a nil string. 
Upon examination of the  code in Fiorix, (https://github.com/fiorix/go-diameter/blob/master/diam/sm/client.go) Line#196, if the HostIPAddress is nil, the module calls getLocalAddresses() API which sets it to the correct IP address. Hence the test was successful as you see in the Github issue https://github.com/magma/magma/issues/8752
Do you think we should leave the HostIPAddress as nil for Fiorix to pick up the correct IP address?

2021-08-26 04:09 UTC, sourabh-nanoti commented on feg/gateway/diameter/diameter_client.go
> +		HostIPAddress:    datatype.Address(net.ParseIP(clientCfg.Host)),
@emakeev Although when SCTP multihoming  is supported we would need a configuration to specify multiple ip addresses here as the Requests can  go via different ip addresses for SCTP. We can attempt that in the future.

2021-08-26 17:44 UTC, emakeev commented on feg/gateway/diameter/diameter_client.go
> +		HostIPAddress:    datatype.Address(net.ParseIP(clientCfg.Host)),
I would just add a single optional parameter (multihoming support can be done later if needed) to allow setting the IP & make default nil to let diameter to pick local addr if the parameter is not provided.

2022-02-16 22:15 UTC, ekowtaylor commented
@sourabh-nanoti please advise if you'd like to proceed with this.

2022-02-17 16:19 UTC, closed without merging