fix(agw) Update WaitEmptyMessageState logic
magma/magma pull request #8857
Opened 2021-08-28 23:36 UTC by amarpad

## Summary
Add a get_message implementation to WaitEmptyMessageState that returns
and empty Dummy message. This allows for the ACS state to transition to
it even in response to any initial message like bootstrap.

Also fix the if logic in the read_message to return unknow_param_transition
only if the method is set.

Signed-off-by: Amar Padmanabhan <amar@freedomfi.com>

## Test Plan

- unit test
- Sercomm radio configuration

## Additional Information

- [ ] This change is backwards-breaking

2021-08-30 17:11 UTC, ardzoht requested changes
nits about formatting and keyword arguments

2021-08-30 17:11 UTC, ardzoht commented on lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
> +        if (self.unknown_param_transition):
```suggestion
        if self.unknown_param_transition:
```

2021-08-30 17:11 UTC, ardzoht commented on lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
> +            if (get_optional_param_to_check((self.acs.data_model))):
```suggestion
            if get_optional_param_to_check((self.acs.data_model)):
```

2021-08-30 17:11 UTC, ardzoht commented on lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
> +                return AcsReadMsgResult(True, self.unknown_param_transition)
```suggestion
                return AcsReadMsgResult(msg_handled=True, next_state=self.unknown_param_transition)
```

2021-08-30 17:11 UTC, ardzoht commented on lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
> +        return AcsReadMsgResult(True, self.done_transition)
```suggestion
        return AcsReadMsgResult(msg_handled=True, next_state=self.done_transition)
```

2021-08-30 21:50 UTC, amarpad commented
Updating with the corresponding style changes, thanks!

2021-08-31 20:54 UTC, ardzoht approved these changes
lgtm

2021-08-31 21:00 UTC, merged