fix(orc8r): Simplify CountEntities
magma/magma pull request #8897
Opened 2021-08-30 20:58 UTC by mstre123

fix(orc8r): Simplify CountEntities

## Summary

Remove unused fields from CountEntities call

## Test Plan

Ran docker tests locally

2021-08-30 20:59 UTC, mstre123 commented
Converting to draft until prs that this is stacked on merge

2021-08-31 23:16 UTC, hcgatewood requested changes
Pull this even further into the servicer -- don't need to pass a load criteria at all

2021-09-01 20:51 UTC, hcgatewood approved these changes

2021-09-01 20:51 UTC, hcgatewood commented on orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers.go
>  	)
Nit: move this to single line now that it fits

2021-09-02 08:15 UTC, merged