feat(amf): Selection of algorithms based on preference
magma/magma pull request #8998
Opened 2021-09-08 16:24 UTC by Chandhu-Wavelabs

Signed-off-by: chandhu-wavelabs <chandhu.naga@wavelabs.ai>

## Summary

Support added for algorithm selection based on preference, also added IA1 mac calculation support.

## Test Plan

Tested with UERANSIM, need to test in TVM setup.

## Additional Information

- [ ] This change is backwards-breaking

2021-09-15 23:12 UTC, ulaskozat commented
merge conflict

2021-09-15 23:16 UTC, ulaskozat requested changes
We keep adding settings available as part of MME config to AMF with verbatim copying from mme code. I will block this PR until all such redundancy is removed. cc @sureshgorijavolu @panyogesh

2021-11-03 01:41 UTC, ulaskozat approved these changes
LGTM

2021-11-03 01:42 UTC, ulaskozat commented
Can you add pcaps for successful registration with the newly added integrity protection?

2021-11-03 05:48 UTC, Chandhu-Wavelabs commented
> Can you add pcaps for successful registration with the newly added integrity protection?
@ulaskozat , Please find the attachment for pcap.
 IA1 as selected integrity protection:
![image](https://user-images.githubusercontent.com/84959602/140014463-678e4404-a1ad-466d-9320-800ceeeef3b5.png)
Security mode procedure successful and registration procedure completed:
![image](https://user-images.githubusercontent.com/84959602/140014526-619ef18a-0be6-4c63-bfaa-e1ff69c5c495.png)
[SA_TC1_2_3_4_Hyper_Suci_211028_054006-1_scn2.zip](https://github.com/magma/magma/files/7465556/SA_TC1_2_3_4_Hyper_Suci_211028_054006-1_scn2.zip)

2021-11-03 17:10 UTC, merged