fix(ci): lint-clang-format always runs
magma/magma pull request #9033
Opened 2021-09-09 18:13 UTC by electronjoe

Any Github check that we want to make Required for PR merge, unfortunately, must execute for every PR. Github is not presently smart enough to realize that un-executed workflows are not required, even if annotated required.  This was discovered by @themarwal when working on Python linting infrastructure.

Signed-off-by: Scott Harrison Moeller <smoeller@fb.com>

2021-09-09 18:19 UTC, quentinDERORY requested changes
Let's use this module fkirc/skip-duplicate-actions@master instead to avoid noisy lint issues not coming from the PR itself.
we need to put a pre job that will skip the linter if files did not change in the specified path.
@themarwhal did it there #9032

2021-09-09 19:17 UTC, themarwhal approved these changes

2021-09-10 09:12 UTC, electronjoe commented
@quentinDERORY thanks for the pointer! I agree this is much better - given GH's limitations on path triggers and required flows. Please take a look at the revised PR!

2021-09-10 15:46 UTC, quentinDERORY approved these changes
Perfect :)

2021-09-10 15:46 UTC, merged