feat(amf): Handling SCTP close association
magma/magma pull request #9105
Opened 2021-09-15 13:40 UTC by Chandhu-Wavelabs

Signed-off-by: chandhu-wavelabs <chandhu.naga@wavelabs.ai>

## Summary

Support added for handling sctp close association.

## Test Plan

Tested with UERANSIM.

## Additional Information

- [ ] This change is backwards-breaking

2021-09-15 22:20 UTC, ulaskozat requested changes
I do not see how this is releasing UE contexts and putting them in idle mode.

2021-09-15 22:22 UTC, ulaskozat commented
@Chandhu-Wavelabs can you attach test results?

2021-09-16 17:51 UTC, Chandhu-Wavelabs commented
> @Chandhu-Wavelabs can you attach test results where multiple UEs were actually registered via this eNB?

Hi @ulaskozat, I have attached the UERANSIM test results.

2021-09-16 17:56 UTC, ulaskozat commented
> > @Chandhu-Wavelabs can you attach test results where multiple UEs were actually registered via this eNB?
> 
> Hi @ulaskozat, I have attached the UERANSIM test results.

@Chandhu-Wavelabs I was not asking for logs etc. For instance how did you verify (with multiple UEs), their contexts were actually released and they transitioned into idle mode?

2021-09-16 18:02 UTC, ulaskozat commented
I am checking pcap and I see bunch of service rejects, unanswered session establishment requests, etc. How is this the expected behavior?

2021-09-16 18:17 UTC, Chandhu-Wavelabs commented
> I am checking pcap and I see bunch of service rejects, unanswered session establishment requests, etc. How is this the expected behavior?

@ulaskozat, I have tested 1 gNB with 5 UEs. After restarting(stop and start) the gNB, previously connected UEs are connecting again and sending service requests, because they are in IDLE mode due to IDLE-UPLINK-SIGNAL-PENDING.

For unanswered pdu session establishments, I tested without restarting the services, it might be the reason for retransmitting the pdu sessions. I will check and fix this.

2021-09-16 18:18 UTC, ulaskozat commented
Can you test the following scenario:
Precondition:
1. Have 5 UEs to be registered and established session (they are in connected state)
2. Have 5 UEs to be registered, established session and moved to idle mode.

Action: Trigger sctp shutdown

Post conditions: 
1. Observe that all UEs transition into idle mode in the logs, NGAP receives the context releases
2. Table-0 rules have the correct rules installed

Action: Bring up gNB and have UEs send service request
Post condition:
1. Observe that all UEs are switched from idle to connected state in the logs
2. Observe that Table 0 has the right rules installed.

2021-09-16 18:19 UTC, ulaskozat commented
> > I am checking pcap and I see bunch of service rejects, unanswered session establishment requests, etc. How is this the expected behavior?
> 
> @ulaskozat, I have tested 1 gNB with 5 UEs. After restarting(stop and start) the gNB, previously connected UEs are connecting again and sending service requests, because they are in IDLE mode due to IDLE-UPLINK-SIGNAL-PENDING.
> 
> For unanswered pdu session establishments, I tested without restarting the services, it might be the reason for retransmitting the pdu sessions. I will check and fix this.

why do you need to restart the services during the test?

2021-09-16 18:25 UTC, Chandhu-Wavelabs commented
> > > I am checking pcap and I see bunch of service rejects, unanswered session establishment requests, etc. How is this the expected behavior?
> > 
> > 
> > @ulaskozat, I have tested 1 gNB with 5 UEs. After restarting(stop and start) the gNB, previously connected UEs are connecting again and sending service requests, because they are in IDLE mode due to IDLE-UPLINK-SIGNAL-PENDING.
> > For unanswered pdu session establishments, I tested without restarting the services, it might be the reason for retransmitting the pdu sessions. I will check and fix this.
> 
> why do you need to restart the services during the test?

I mean not during this test, i did some other tests with multiple UEs before the sctp shutdown test, in the previous tests those already have established the sessions.

2021-09-16 18:26 UTC, Chandhu-Wavelabs commented
> Can you test the following scenario:
> Precondition:
> 
> 1. Have 5 UEs to be registered and established session (they are in connected state)
> 2. Have 5 UEs to be registered, established session and moved to idle mode.
> 
> Action: Trigger sctp shutdown
> 
> Post conditions:
> 
> 1. Observe that all UEs transition into idle mode in the logs, NGAP receives the context releases
> 2. Table-0 rules have the correct rules installed
> 
> Action: Bring up gNB and have UEs send service request
> Post condition:
> 
> 1. Observe that all UEs are switched from idle to connected state in the logs
> 2. Observe that Table 0 has the right rules installed.

Sure @ulaskozat, I will test and share the results.

2021-09-22 20:16 UTC, ulaskozat commented
Can you add a unit test (e.g., see the example in `test_s1ap_handle_new_association.cpp`) for this PR? cc @markjen @panyogesh.  You can mock `ngap_send_gnb_deregistered_ind` and modify the signature for `ngap_handle_sctp_disconnection` by passing callback function to be applied (e.g., in actual code you pass `ngap_send_gnb_deregistered_ind` but in test code you pass `mock_ngap_send_gnb_deregistered_ind`).

2021-10-20 12:49 UTC, Chandhu-Wavelabs commented
> Can you add a unit test (e.g., see the example in `test_s1ap_handle_new_association.cpp`) for this PR? cc @markjen @panyogesh. You can mock `ngap_send_gnb_deregistered_ind` and modify the signature for `ngap_handle_sctp_disconnection` by passing callback function to be applied (e.g., in actual code you pass `ngap_send_gnb_deregistered_ind` but in test code you pass `mock_ngap_send_gnb_deregistered_ind`).

@ulaskozat , UT is added, we are facing issue in testing with UERANSIM i.e UERANSIM is not sending **5G-S-TMSI** IE in service request, so that AMF is rejecting the service request.

We have asked arun help for testing the scenario that which you have suggested, Arun is working on the script to simulate the scenario.

2021-10-27 23:25 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
> +          SCTP_CLOSE_ASSOCIATION(received_message_p).reset);
I don't think that this function is implemented correctly. cc @panyogesh

2021-10-27 23:28 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_handle_close_association.cpp
> +TEST(test_ngap_handle_close_association, shutdown) {
you need to add test cases to cover the situations where there are actual UEs associated.

2021-10-27 23:31 UTC, ulaskozat requested changes
`ngap_handle_sctp_disconnection` does not look correctly implemented. TC test case might be passing from expected signaling point of view on RAN side, but I want to see the evidence that the state on ngap and amf were also what is expected.

2021-10-27 23:32 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_handle_close_association.cpp
> +TEST(test_ngap_handle_close_association, shutdown) {
also need coverage for reset cases.

2022-02-25 20:37 UTC, ekowtaylor commented
@Chandhu-Wavelabs any plans to implement the required changes and move this forward?

2022-02-26 04:16 UTC, panyogesh commented
> @Chandhu-Wavelabs any plans to implement the required changes and move this forward?

The functionality is planned but changes have some pre-requisites. Need to commit them before landing this PR. I will update more information here once the related PRs are raised or merged.

2022-04-19 09:20 UTC, closed without merging