ci: turns up Bazel GH Action validating all build and test tarets
magma/magma pull request #9110
Opened 2021-09-15 15:24 UTC by electronjoe

Signed-off-by: Scott Moeller <electronjoe@gmail.com>

2021-09-15 17:00 UTC, themarwhal commented on .github/workflows/bazel.yml
> +         paths: '[".github/workflows/bazel.yml", "lte/gateway/c/**", "orc8r/gateway/c/**"]'
and protos too

2021-09-16 17:30 UTC, tmdzk approved these changes

2021-09-16 18:44 UTC, quentinDERORY requested changes
Can you rebase your PR?
I just merged a fix for reviewdog that was avoiding the linters to run correctly on the PR.
I realized it while wondering why the linter was saying everything is fine on your PR ^^'

2021-09-16 20:09 UTC, electronjoe commented
While we experiment with Bazel Build, it would be nice to have CI support validating our tests and builds.

This PR is an initial pass at that.  The build times are not yet accelerated by caching - though the docker builds are cached (we may want to migrate them to a container repository).

For accelerating Bazel Build using remote caching - see examples from [TensorFlow on Github](https://github.com/tensorflow/io/issues/1236).

Signed-off-by: Scott Moeller <electronjoe@gmail.com>

2021-09-16 20:27 UTC, quentinDERORY approved these changes
LGTM except some minor lint issues

2021-09-17 10:47 UTC, merged