fix(mme): AMF module warning cleanup#8985
magma/magma pull request #9155
Opened 2021-09-17 07:28 UTC by sreedharkumartn

Signed-off-by: sreedharkumartn <sreedhar.kumar@wavelabs.ai>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-09-20 13:16 UTC, lionelgo requested changes

2021-09-20 13:16 UTC, lionelgo commented on lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GMMCause.cpp
> +                 << int(*(buffer + encoded)) << std::endl;
We should harmonize hex or dec to trace iei

2021-09-20 13:16 UTC, lionelgo commented on lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GAuthenticationParameterAUTN.cpp
> +    MLOG(MDEBUG) << "In EncodeAuthenticationParameterAUTNMsg: iei" << std::hex
IEI here in hex

2021-09-20 13:16 UTC, lionelgo commented on lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GAuthenticationFailureIE.cpp
> +    MLOG(MDEBUG) << "In DecodeM5GAuthenticationFailureIE: iei = " << std::dec
IEI here in dec

2021-09-20 13:16 UTC, lionelgo commented on lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp
> +  MLOG(MDEBUG) << "   Odd/Even Indecation = " << std::dec << int(guti->odd_even)
typo indication

2021-09-20 13:16 UTC, lionelgo commented on lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
> +    OAILOG_ERROR(LOG_AMF_APP, "Smf context is not exist UE ID: %lu", ue_id);
we could use AMF_UE_NGAP_ID_FMT.

2021-09-21 11:15 UTC, sreedharkumartn commented on lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
> +    OAILOG_ERROR(LOG_AMF_APP, "Smf context is not exist UE ID: %lu", ue_id);
Addressed the review comment

2021-09-21 11:17 UTC, sreedharkumartn commented on lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp
> +  MLOG(MDEBUG) << "   Odd/Even Indecation = " << std::dec << int(guti->odd_even)
Addressed the review comment

2021-09-21 11:24 UTC, sreedharkumartn commented on lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GMMCause.cpp
> +                 << int(*(buffer + encoded)) << std::endl;
hex format is a better format to trace IEI, so we can compare pcap buffer with trace directly.

2021-09-21 11:26 UTC, sreedharkumartn commented on lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GAuthenticationParameterAUTN.cpp
> +    MLOG(MDEBUG) << "In EncodeAuthenticationParameterAUTNMsg: iei" << std::hex
hex format is a better format to trace IEI, so we can compare pcap buffer with trace directly.

2021-09-21 11:27 UTC, sreedharkumartn commented on lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GAuthenticationFailureIE.cpp
> +    MLOG(MDEBUG) << "In DecodeM5GAuthenticationFailureIE: iei = " << std::dec
We have changed IEI format to hex.

2021-09-21 15:28 UTC, sreedharkumartn commented
verified UERANSIM.
please find logs and pcap attached.
[mme_warning_cleanup.log](https://github.com/magma/magma/files/7204364/mme_warning_cleanup.log)
![image](https://user-images.githubusercontent.com/89978170/134200328-044df080-185d-40b3-89f0-2996d6c34542.png)

2021-09-22 07:13 UTC, rdefosse commented
@sreedharkumartn 

OAI CI build failed --> `https://jenkins-oai.eurecom.fr/job/MAGMA-MME-production/6696/artifact/build_results_magma_oai_mme.html`

```
`lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GPDUSessionIdentity.cpp`  line 32 | Error | fatal | 'endl' was not declared in this scope
```

2021-09-22 10:07 UTC, sreedharkumartn commented
I did some mistake and messed this review. I raised separate PR https://github.com/magma/magma/pull/9238.
I addressed all the review comments from @lionelgo and @rdefosse. I updated the PR #9238 . 
So, I am discarding this PR.

2021-09-22 10:07 UTC, closed without merging