feat(agw) add management server and sync 1588 parameters
magma/magma pull request #9156
Opened 2021-09-17 09:49 UTC by sxkmg

Signed-off-by: root <369888042@qq.com>

 feat(agw): add management server and sync 1588 parameters
   

## Summary

add None 243  management server and sync 1588 parameters

## Test Plan

1.Start the magma service
2.Configure the base station none-243 to connect to the gateway
3.Test and issue parameters through the magma swagger API(https://magma-test.localhost:9443/swagger/v1/ui/lte#/EnodeBs/get_lte__network_id__enodebs__enodeb_serial_)
![image](https://user-images.githubusercontent.com/87301024/133762970-16046f04-15ad-48e9-bfb6-ab1ae844b3e7.png)

4.View the configuration file and verify whether the parameters are distributed to the gateway
（ sudo tail -1000f /var/opt/magma/configs/gateway.mconfig ）
![image](https://user-images.githubusercontent.com/87301024/133763065-c1f5f0df-fa8b-4873-84ee-9ea4adfa0601.png)

5.Check whether the parameters are successfully distributed to the base station
sudo tail -1000f /var/log/enodebd.log
![image](https://user-images.githubusercontent.com/87301024/133763163-e5bad52b-d77b-4162-9fb0-017205f91342.png)

![image](https://user-images.githubusercontent.com/87301024/133763195-1b1110ab-0372-4c6e-ae92-0b88a920dfe8.png)

## Additional Information

2021-09-17 19:57 UTC, uri200 requested changes

2021-09-17 19:57 UTC, uri200 commented on orc8r/cloud/docker/.env
> +COMPOSE_FILE=docker-compose.yml:docker-compose.metrics.yml:docker-compose.override.yml
i think you need to remove this

2021-09-17 19:57 UTC, uri200 commented on orc8r/cloud/docker/run.py
> +DO_NOT_COMMIT = ''
remove these

2021-09-22 03:36 UTC, sxkmg commented on orc8r/cloud/docker/.env
> +COMPOSE_FILE=docker-compose.yml:docker-compose.metrics.yml:docker-compose.override.yml
OK, it has been deleted, thank you!

2021-09-22 03:36 UTC, sxkmg commented on orc8r/cloud/docker/run.py
> +DO_NOT_COMMIT = ''
OK, it has been deleted, thank you!

2021-09-28 19:36 UTC, uri200 commented
you may need to review the check that faile. For example you will need to change the name of your PR and ad `:`
```
feat(agw):
```
to pass the semantic check

You may need to rebase to make the other test pass

@andreilee @hcgatewood  please take a look at this PR

2021-09-29 04:56 UTC, hcgatewood approved these changes
Deferring to @ulaskozat / @uri200 for domain-specific Orc8r functionality

2021-10-04 20:39 UTC, andreilee requested changes

2021-10-04 20:39 UTC, andreilee commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +  managementServer:
Mind the naming conventions
```suggestion
  management_erver:
```

2021-10-04 20:39 UTC, andreilee commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +    description: ManagementServer Configuration for  eNodeb devices.
```suggestion
    description: Management server configuration for eNodeb devices.
```

2021-10-04 20:39 UTC, andreilee commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +    description: sync_1588 Configuration for  eNodeb devices.
```suggestion
    description: sync_1588 Configuration for eNodeb devices.
```

2021-10-04 20:39 UTC, andreilee commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +    description: sync_1588 Configuration for  eNodeb devices.
Looks like there's a few versions - is there a reference that can be included to a specification number?

2021-10-04 20:39 UTC, andreilee commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +      sync_1588_msg_interval:
include the units, definition (as well as info to look up with a spec), and limits

2021-10-04 20:39 UTC, andreilee commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +      sync_1588_unicast_serverIp:
Please mind the naming conventions
```suggestion
      sync_1588_unicast_server_ip:
```

2021-10-04 20:39 UTC, andreilee commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +      sync_1588_msg_interval:
Please also extend this to the other properties in the swagger definitions.

2021-10-04 20:39 UTC, andreilee commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +    description: ManagementServer Configuration for  eNodeb devices.
Also include information about this being for a TR-069 auto configuration server

2021-10-04 20:39 UTC, andreilee commented on nms/packages/magmalte/app/views/equipment/EnodebDetailConfigEdit.js
> +  }
There's a lot of repetitive code added here. Can this be done in a way to adhere to the "DRY" principle?

2021-10-04 20:41 UTC, andreilee commented
I see that there are 72 commits included in this pull request. Please rebase your branch, and merge commits. Use git amend to update your commits.

2021-10-07 10:01 UTC, talkhasib requested changes
We should not be changing the management server as this might break TR69 management of the eNB using Magma AGW.
Magma AGW uses DNS to configure itself as the management server.

2022-02-18 09:49 UTC, sxkmg commented
ee

2022-02-18 09:56 UTC, closed without merging