feat(orc8r): SubscriberDB Extensions - Updation to Swagger API doc, callback functions, subscriberDB service.
magma/magma pull request #9161
Opened 2021-09-17 12:58 UTC by Abhishek-R15

## Summary

Addition of "core_network_type_restriction" to the swagger API 

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-09-21 17:30 UTC, Abhishek-R15 commented
/subscriber_cli.py
![image](https://user-images.githubusercontent.com/89023967/134218952-e1241ddd-863d-4a28-9c75-8ddfd996abcb.png)

2021-09-28 22:04 UTC, andreilee reviewed
How will subscribers without existing values of 'Allowed Network Types' be handled?

2021-09-28 22:04 UTC, andreilee commented on orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
> +      - NT_EPC
What's the purpose of the `'NT'` prefix here? Why not just `'EPC', '5GC'`

2021-09-29 05:00 UTC, hcgatewood approved these changes
Deferring to @ulaskozat / @uri200 for domain-specific functionality

2021-09-29 05:26 UTC, anusha-konda commented
> How will subscribers without existing values of 'Allowed Network Types' be handled?

Existing Subscribers without any value for "Allowed Network Types" will be by default assumed to have access to both "EPC" and "5GC" networks.

2021-09-29 07:16 UTC, anusha-konda commented on orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
> +      - NT_EPC
@andreilee , Will remove "NT_" and do the changes in Orc8r and NMS accordingly. This is somehow mistook with the constraint on the variables starting with number. Will correct it. Thanks.

2021-09-29 07:47 UTC, andreilee requested changes
@anusha-konda Could you update the swagger.v1.yml file so that it's clear just from reading it?

@hcgatewood @electronjoe Not sure if a migration to update the subscribers with the `core network restriction` is necessary. But as this PR is stands, there's a bit of an oddity here where a subscriber can access `5GC` and `EPC` either if it has a `core network restriction` with both those types, or no `core network restriction`, which is a strange way to structure our API.

2021-10-05 12:17 UTC, Abhishek-R15 commented on orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
> +      - NT_EPC
@andreilee We have removed "NT_" from the swagger file, now its just 'EPC', '5GC'.

2021-10-05 16:12 UTC, anusha-konda commented
> @anusha-konda Could you update the swagger.v1.yml file so that it's clear just from reading it?
> 
> @hcgatewood @electronjoe Not sure if a migration to update the subscribers with the `core network restriction` is necessary. But as this PR is stands, there's a bit of an oddity here where a subscriber can access `5GC` and `EPC` either if it has a `core network restriction` with both those types, or no `core network restriction`, which is a strange way to structure our API.

@hcgatewood @electronjoe @ulaskozat , could you please provide your comments here.

2021-10-05 16:19 UTC, ulaskozat commented
> > @anusha-konda Could you update the swagger.v1.yml file so that it's clear just from reading it?
> > @hcgatewood @electronjoe Not sure if a migration to update the subscribers with the `core network restriction` is necessary. But as this PR is stands, there's a bit of an oddity here where a subscriber can access `5GC` and `EPC` either if it has a `core network restriction` with both those types, or no `core network restriction`, which is a strange way to structure our API.
> 
> @hcgatewood @electronjoe @ulaskozat , could you please provide your comments here.

I tend to agree with @andreilee here. It would be better to invert the logic and instead of specifying "allowed core networks" we should have "forbidden core networks"

2021-10-05 16:48 UTC, anusha-konda commented
> > > @anusha-konda Could you update the swagger.v1.yml file so that it's clear just from reading it?
> > > @hcgatewood @electronjoe Not sure if a migration to update the subscribers with the `core network restriction` is necessary. But as this PR is stands, there's a bit of an oddity here where a subscriber can access `5GC` and `EPC` either if it has a `core network restriction` with both those types, or no `core network restriction`, which is a strange way to structure our API.
> > 
> > 
> > @hcgatewood @electronjoe @ulaskozat , could you please provide your comments here.
> 
> I tend to agree with @andreilee here. It would be better to invert the logic and instead of specifying "allowed core networks" we should have "forbidden core networks". Otherwise (i.e., if we continue to use allowed core networks) we should not let a subscriber to attach when this information is empty. This then would require a db migration for existing subscribers. @anusha-konda

@ulaskozat , thank you for the reply. Agree on what you said. Initially, allowed network types is chosen from TS 23-501 
![image](https://user-images.githubusercontent.com/88875090/136065795-60038281-bc60-4caa-a0f3-ecdbeb662e9d.png)
So forbidden core networks can accept list of network types to be restricted and will not enable any default value from NMS for this option, so it will be assumed that subscriber has access to all Network Types.

2021-10-05 23:22 UTC, hcgatewood commented
Supporting the input from @ulaskozat and @andreilee: let's go ahead and use "forbidden core networks" as the new field, so that its zero-value is backwards-compatible cc @anusha-konda

2021-10-05 23:22 UTC, hcgatewood requested changes
As noted: let's swap to using the "forbidden core networks" pattern

2021-10-06 19:07 UTC, Abhishek-R15 commented
output of subscriber_cli.py
![image](https://user-images.githubusercontent.com/89023967/136267257-e1dcd46e-5fa6-49ce-ad2f-f96a063ff9d7.png)

2021-10-06 19:37 UTC, anusha-konda commented
@ulaskozat , @andreilee , @hcgatewood , Could you please review the changes

1. Swapped allowed_nw_types with forbidden_nw_types.
2. If forbidden network types is not configured, subscriber will have access to all Network Types by default.
3. From NMS UI, no default value will be populated for Forbidden Network per Subscriber.
4. Verified Add/Edit/Get/Delete subscriber from NMS UI

Please find corresponding NMS code changes, verified UI screenshots in PR #9165 .

2021-10-07 02:38 UTC, hcgatewood requested changes
Cool, shape looks good for Orc8r. Handle the couple nits then am ready to approve!

2021-10-07 02:38 UTC, hcgatewood commented on lte/cloud/go/services/subscriberdb/load_test.go
> +	sub_nt := models.CoreNetworkType{"5GC", "EPC"}
Nit: use camelCase in golang

2021-10-07 02:38 UTC, hcgatewood commented on lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
> +  core_network_type:
Semantically, this is actually `core_network_types` (plural) since it's an array

2021-10-07 02:38 UTC, hcgatewood commented on lte/protos/subscriberdb.proto
> +  repeated CoreNetworkTypes forbidden_nw_types = 1;
Here and throughout: I'm not a fan of abbreviating when it's not an abundantly clear abbreviation, especially for IDLs such as protos or swagger. So e.g. "nw" isn't 90%+ clear that it means "network", so let's go ahead and spell it out as "network"

2021-10-07 02:38 UTC, hcgatewood commented on lte/cloud/go/services/subscriberdb/load.go
> +		subNetwork.ForbiddenNwTypes[i] = lte_protos.CoreNetworkType_CoreNetworkTypes(lte_protos.CoreNetworkType_CoreNetworkTypes_value[coreNwTypePrefix+nwType])
Nit: prefer sprintf over concatenation (for clarity)

2021-10-07 15:35 UTC, Abhishek-R15 commented on lte/cloud/go/services/subscriberdb/load_test.go
> +	sub_nt := models.CoreNetworkType{"5GC", "EPC"}
Updated _sub_nt_ to _subNt_ .

2021-10-07 15:36 UTC, Abhishek-R15 commented on lte/protos/subscriberdb.proto
> +  repeated CoreNetworkTypes forbidden_nw_types = 1;
Updated _forbidden_nw_types_ to _forbidden_network_types_ .

2021-10-07 15:37 UTC, Abhishek-R15 commented on lte/cloud/go/services/subscriberdb/load.go
> +		subNetwork.ForbiddenNwTypes[i] = lte_protos.CoreNetworkType_CoreNetworkTypes(lte_protos.CoreNetworkType_CoreNetworkTypes_value[coreNwTypePrefix+nwType])
Used sprintf instead of concatenation.

2021-10-13 04:59 UTC, hcgatewood approved these changes
Orc8r changes look reasonable to me 👍

2021-10-13 14:21 UTC, Abhishek-R15 commented on orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
> +      - NT_EPC
@andreilee We've made the necessary changes, please review this PR.

2021-10-13 18:35 UTC, andreilee reviewed
Looks good. I just have two nits.

2021-10-13 18:35 UTC, andreilee commented on lte/protos/subscriberdb.proto
> +  repeated CoreNetworkTypes forbidden_network_types = 1;
In general, I think that our `.proto` files can have more documentation. Please add some detailed info to our RPC/API definitions when possible, otherwise people reading these need to poke around into a lot of code to figure it out.
```suggestion
  // Network Types to be restricted per subscriber. If not configured, subscriber will have access to all Network Types by default.
  repeated CoreNetworkTypes forbidden_network_types = 1;
```

2021-10-13 18:35 UTC, andreilee commented on lte/cloud/go/services/subscriberdb/load.go
> +	const coreNwTypePrefix = "NT_"
Is there any particular reason we need this prefix? The values are set inside the field `ForbiddenNetworkTypes`, so even without the prefix, it seems clear to me that the values are network types.

2021-10-14 15:39 UTC, Abhishek-R15 commented on lte/protos/subscriberdb.proto
> +  repeated CoreNetworkTypes forbidden_network_types = 1;
@andreilee Added description to the proto file

2021-10-14 15:47 UTC, Abhishek-R15 commented on lte/cloud/go/services/subscriberdb/load.go
> +	const coreNwTypePrefix = "NT_"
This prefix is used to map swagger and proto enum values for Core Network Type. In swagger enum values are _5GC,EPC_, but in proto enum values are _NT_5GC,NT_EPC_. Hence the prefix is added here.

2021-10-22 15:57 UTC, Abhishek-R15 commented on orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
> +      - NT_EPC
@andreilee Can you please review the changes.

2021-10-26 03:57 UTC, ulaskozat commented on lte/cloud/go/services/subscriberdb/load.go
> +	const coreNwTypePrefix = "NT_"
why not then use `NT_` prefix also in swagger enums?

2021-10-26 04:00 UTC, ulaskozat approved these changes
LGTM

2021-10-26 04:06 UTC, anusha-konda commented on lte/cloud/go/services/subscriberdb/load.go
> +	const coreNwTypePrefix = "NT_"
Hi @ulaskozat , @andreilee suggested to remove NT_ prefix in swagger, same has been reflected in UI as well, as options in UI is referred from swagger. As it is not possible to remove NT_ in proto, we continued with.

2021-10-26 04:08 UTC, ulaskozat commented on lte/cloud/go/services/subscriberdb/load.go
> +	const coreNwTypePrefix = "NT_"
okay, I leave it up to @andreilee then.

2021-10-27 18:12 UTC, andreilee approved these changes

2021-10-30 00:18 UTC, merged