ci: adds scheduled gh action to populate Bazel cache
magma/magma pull request #9259
Opened 2021-09-23 09:44 UTC by electronjoe

Signed-off-by: Scott Moeller <electronjoe@gmail.com>

2021-09-23 15:31 UTC, quentinDERORY requested changes
Why not use the original workflow, add the trigger there and just not trigger the last test step of the other workflow when the `github.event_name` is schedule?

2021-09-27 13:18 UTC, electronjoe commented
Blocked by #9292

2021-09-27 14:33 UTC, electronjoe commented
> Why not use the original workflow, add the trigger there and just not trigger the last test step of the other workflow when the `github.event_name` is schedule?

Good point! Revisions made, please take a look @quentinDERORY

2021-09-27 14:35 UTC, quentinDERORY commented on .github/workflows/bazel.yml
> +    # or a push_request that skip-duplicate-action wants to run again.
typo: pull_request

2021-09-27 14:36 UTC, quentinDERORY approved these changes

2021-09-27 15:04 UTC, merged

2021-09-27 16:59 UTC, electronjoe commented on .github/workflows/bazel.yml
> +    # or a push_request that skip-duplicate-action wants to run again.
Shoot I had auto-merge on =P Fix PR incoming