[orc8r]: Add ReferenceSignalPower,PowerClass,Pa,Pb,X2,FactoryReset to managed eNB configs
magma/magma pull request #9315
Opened 2021-09-28 06:13 UTC by hakeen0618

Signed-off-by: hakeen <hanhufeng@baicells.com>

## Summary

- Add new parameters to eNB, including the following paramters:
- Reference_Signal_power,PA,PB,PowerClass
- X2 Enable/Disable
- Factory Reset
- We can set the eNB detail config from NMS eNB config, if the eNB support the params.

-  On NMS , we can config the eNB details use the PA,PB,Reference_Signal_power, as following test pic.
## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

This add enb parameters as optional for managed configs. We already test it on NMS , AGW , it should be good.
![swagger](https://user-images.githubusercontent.com/86106068/133031243-2dc0a679-6fe2-4057-b43e-d8ecb2c0876b.JPG)
![agw_data](https://user-images.githubusercontent.com/86106068/133031299-865c389a-726e-46a4-a63a-f9cd06cea231.JPG)
![log_enodeb](https://user-images.githubusercontent.com/86106068/133031313-401fb949-5617-4a02-880e-5f4c6f7891c5.JPG)
![magma_pb](https://user-images.githubusercontent.com/86106068/133031334-fbea6169-4a11-4ce1-a06c-65afae7b151c.JPG)

2021-09-29 04:57 UTC, hcgatewood approved these changes
Deferring to @ulaskozat / @uri200 for domain-specific functionality

2021-09-29 17:08 UTC, uri200 commented
This needs reviews from NMS And Python mantainers @andreilee @pshelar @koolzz

2021-09-29 20:06 UTC, andreilee requested changes
Thanks for putting up this pull request!

Something to consider from a usability perspective - `factory_reset_asap` should log an error for eNodeB handlers if unimplemented. Otherwise, somebody may try and trigger a factory reset and be confused when nothing happens. This sort of visibility should also be propagated to the NMS side - users should be prevented to attempting to factory reset an eNodeB if that capability is unavailable.

And from a code review perspective - to make code review easier, splitting up pull requests by units of functionality or topic can be helpful. Perhaps, one pull request to add 'ReferenceSignalPower, PowerClass, Pa, Pb, X2', and another pull request to add 'FactoryReset' functionality.

2021-09-29 20:06 UTC, andreilee commented on lte/gateway/python/scripts/enodebd_cli.py
> +    parser_facetory_reset_enodeb = subparsers.add_parser(
Typo
```suggestion
    parser_factory_reset_enodeb = subparsers.add_parser(
```

2021-09-29 20:06 UTC, andreilee commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +      reference_signal_power:
Could you add some description about the units, and min/max values?

2021-09-29 20:06 UTC, andreilee commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +      pa:
What's the definition of this parameter? A link to a spec can be very helpful here

2021-09-29 20:06 UTC, andreilee commented on lte/gateway/configs/magmad.yml
> +    - name: factory_reset_enodeb
This will be really helpful. Thanks for adding this.

2021-09-29 20:06 UTC, andreilee commented on lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
> +        """
While the docstrings are well appreciated, this one (as well as some others in this file that have been added) is unnecessary, as it doesn't add any context beyond the abstract definitions.

2021-09-29 20:06 UTC, andreilee commented on lte/gateway/python/magma/enodebd/tr069/models.py
> +    """
nit - put this in a single line
```suggestion
    """ no input parameters """
```

2021-09-29 20:06 UTC, andreilee commented on lte/gateway/python/magma/enodebd/tr069/models.py
> +    """
nit - The first content in the docstring should describe what the class is

2021-09-29 20:06 UTC, andreilee commented on lte/gateway/python/scripts/enodebd_cli.py
> +    """ impl the command line method """
nit - Replace docstring content with a bit more context about what the method is for

2021-09-29 20:06 UTC, andreilee commented on lte/protos/mconfig/mconfigs.proto
> +        PowerControl power_control = 11;
Since proto definition files and the swagger files are sources of truth for the definitions of our APIs and RPCs, I would suggest adding some references to the specs and definitions of `reference_signal_power`, `pa`, `pb`, etc, as well as their valid value ranges, and units, and also include the same content in the swagger files.

2021-09-29 20:06 UTC, andreilee commented on lte/gateway/python/magma/enodebd/state_machines/enb_acs.py
> +        pass
Add implementations to the eNodeB handler classes other than `baicells_rts.py`, even if just to error log that there isn't a valid implementation. Without that, it can be confusing for somebody trying to trigger a factory reset of an eNodeB, and seeing that nothing occurred.

2021-09-30 08:48 UTC, hakeen0618 commented on lte/gateway/python/scripts/enodebd_cli.py
> +    parser_facetory_reset_enodeb = subparsers.add_parser(
I modify them at current PR.

2021-09-30 08:51 UTC, hakeen0618 commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +      reference_signal_power:
I already add min/max values if the parameter have the range values ,https://cwmp-data-models.broadband-forum.org/tr-196-2-1-1-cwmp.html

2021-09-30 08:53 UTC, hakeen0618 commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +      pa:
https://cwmp-data-models.broadband-forum.org/tr-196-2-1-1-cwmp.html.

2021-09-30 08:54 UTC, hakeen0618 commented on lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
> +        """
Delete them , otherwise the ci will report the issue, "no have commits"

2021-09-30 08:54 UTC, hakeen0618 commented on lte/gateway/python/magma/enodebd/tr069/models.py
> +    """
Modify.

2021-09-30 08:56 UTC, hakeen0618 commented on lte/gateway/python/scripts/enodebd_cli.py
> +    """ impl the command line method """
Modify the commits to tell others who need to develop the same func.

2021-09-30 08:57 UTC, hakeen0618 commented on lte/gateway/python/magma/enodebd/state_machines/enb_acs.py
> +        pass
I add the impl func for all eNBs ,i.e baciells,baicells-old,qafb,qafa.

2021-09-30 10:13 UTC, closed without merging