feat(mme): NGAP Unit Testing Setup Changes
magma/magma pull request #9414
Opened 2021-10-02 19:08 UTC by panyogesh

Changes:
  1. Updated the Cmake fir test/ngap
  2. Renamed the test_ngap file to reflect the
     intent of functionality

Test:
  1. Unit Testing (test_oai)

Signed-off-by: Yogesh Pandey <yogesh@wavelabs.ai>

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-10-06 16:27 UTC, ulaskozat requested changes
This adds a third pattern in unit testing. Currently we use gmock and `#if !MME_UNIT_TEST` patterns. I think we should not have a runtime logic to check whether this is unit testing or not. cc @ardzoht @markjen

2021-10-06 18:36 UTC, panyogesh commented
> This adds a third pattern in unit testing. Currently we use gmock and `#if !MME_UNIT_TEST` patterns. I think we should not have a runtime logic to check whether this is unit testing or not. cc @ardzoht @markjen

Sure.. I will change it to compile time.

2021-10-12 16:33 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +      NULL);
is this still needed if there are no actual itti messages being passed among the threads?

2021-10-12 16:48 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
> +  return send_message_to_amf(task_zmq_ctx_p, destination_task_id, message);
why not instead move `ngap_send_msg_to_task` to c++ file and have the content of `send_message_to_amf` in there?

2021-10-12 16:48 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/ngap/ngap_client_enforcer.cpp
> +}
why can't this be merged with `ngap_client_servicer.cpp`?

2021-10-12 16:52 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/ngap/include/ngap_client_enforcer.h
> +#endif
why can't this be merged with `ngap_client_servicer.h`?

2021-10-13 07:50 UTC, panyogesh commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +      NULL);
itti_init() is needed as it fills the MessageDef struct. For instance in func _ngap_amf_itti_ngap_initial_ue_message()_ a new message is allocated (NGAP_INITIAL_UE_MESSAGE). Without itti_init indexing can't be done for _NGAP_INITIAL_UE_MESSAGE_ and hence will result in crash.

2021-10-13 07:51 UTC, panyogesh commented on lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
> +  return send_message_to_amf(task_zmq_ctx_p, destination_task_id, message);
Comments addressed.  Removed the client_enforcer layer along with send_message_to_amf() funciton.

2021-10-13 07:52 UTC, panyogesh commented on lte/gateway/c/core/oai/tasks/ngap/ngap_client_enforcer.cpp
> +}
Comments addressed.  Removed the client_enforcer layer.

2021-10-13 07:52 UTC, panyogesh commented on lte/gateway/c/core/oai/tasks/ngap/include/ngap_client_enforcer.h
> +#endif
Comments addressed.  Removed the client_enforcer layer.

2021-10-13 15:30 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  unsigned short length =
legit github action comment

2021-10-13 15:50 UTC, ulaskozat approved these changes
LGTM

2021-10-13 15:51 UTC, ulaskozat commented
@panyogesh there is one minor nit. please address it and then mark this as ready to merge.

2021-10-13 18:04 UTC, panyogesh commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  unsigned short length =
Comments addressed.

2021-10-13 18:36 UTC, ulaskozat approved these changes
LGTM

2021-10-15 00:06 UTC, merged