refactor: change all other TypeAndKey declarations to TK
magma/magma pull request #9432
Opened 2021-10-04 17:00 UTC by reginawang3495

## Summary

## Test Plan

## Additional Information

- [ ] This change is backwards-breaking

2021-10-04 20:27 UTC, andreilee requested changes
Looks good to me, excepting some nits. I would suggest being more descriptive about what these IntelliJ tests include, since only those with the same setup as yourself would know what that's about.

Found something for guidance on capitalization of acronyms in golang:
https://github.com/golang/go/wiki/CodeReviewComments#initialisms

2021-10-04 20:27 UTC, andreilee commented on fbinternal/cloud/go/services/testcontroller/store/testcontroller_store.go
> +	TK := storage.TK{
Should be lower case since it's local
```suggestion
	tk := storage.TK{
```

2021-10-04 20:27 UTC, andreilee commented on orc8r/cloud/go/services/configurator/storage/sql_test.go
> +	TKFilters := &testCase{
camelcase?
```suggestion
	tkFilters := &testCase{
```

2021-10-05 00:08 UTC, reginawang3495 commented
@andreilee I think I've added some description about the IntelliJ tests--hope that's what you meant!

2021-10-05 18:07 UTC, hcgatewood approved these changes
Lgtm, thanks for adding! What are the intellij tests @andreilee mentioned?

Other than that, msg me when ready to merge!

2021-10-05 19:10 UTC, themarwhal approved these changes

2021-10-05 20:04 UTC, andreilee approved these changes

2021-10-05 20:04 UTC, merged