feat(orc8r): remove old northbound listSubscribers handler
magma/magma pull request #9473
Opened 2021-10-05 22:12 UTC by christinewang5

## Summary
* Remove old northbound listSubscribers handler
* Updated tests to reflect change

## Test Plan
* ran tests 
![image](https://user-images.githubusercontent.com/25142344/136109862-285ed51c-ec36-4be3-a62a-bce63de719d4.png)

2021-10-05 22:28 UTC, hcgatewood reviewed
Looks great, thanks for adding!

I think to finish it out let's go ahead and just use the original endpoint name (so use the new endpoint, but no "v2" in the name). So make the change in the Go code (and validate at the rest api as you have so far), then for the NMS:

1. Search for `v2\b` (or just `v2`) in `nms/packages/magmalte/`, and you'll want to replace the subscribersv2 names with subscribers
2. [Run NMS precommit tests](https://magma.github.io/magma/docs/next/nms/dev_testing#pre-commit-tests)
3. [Spin up your local NMS](https://magma.github.io/magma/docs/next/basics/quick_start_guide#using-the-nms-ui) and sanity check (create a subscriber then delete it) the [subscribers page](https://magma.github.io/magma/docs/next/nms/subscriber)

cc @andreilee

2021-10-05 22:28 UTC, hcgatewood commented on lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go
> +	expected = subscriberModels.PaginatedSubscribers{TotalCount: 1, NextPageToken: "", Subscribers: map[string]*subscriberModels.Subscriber{
Nit: move the fields of the PaginatedSubscribers each to their own line

2021-10-06 21:07 UTC, hcgatewood requested changes
Okay! As discussed offline, I pulled down your PR and validated the NMS changes. Everything lgtm!

Let's make that 1 swagger.v1.yml change (you'll have to build.py --generate again), then I'm ready to stamp and ship 🙂 

<img width="1792" alt="Screen Shot 2021-10-06 at 2 05 21 PM" src="https://user-images.githubusercontent.com/8029544/136283153-214b4eed-d21a-42bf-8800-3b27bb281b99.png">

2021-10-06 21:07 UTC, hcgatewood commented on lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
>    /lte/{network_id}/subscribers_v2:
Need to remove the `_v2` from this for the swagger ui

<img width="1792" alt="Screen Shot 2021-10-06 at 2 05 36 PM" src="https://user-images.githubusercontent.com/8029544/136283260-59845729-a490-44c3-9943-dd4b69e38fa4.png">

2021-10-06 21:08 UTC, hcgatewood commented
Side notes:

1. To pass the semantic pr check, prepend `refactor: ` to your PR title
2. You'll have to pull and rebase onto latest master to reconcile the merge conflict in lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go

2021-10-06 22:21 UTC, christinewang5 commented on lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
>    /lte/{network_id}/subscribers_v2:
removed!

![image](https://user-images.githubusercontent.com/25142344/136291624-c9773840-af71-44cd-892e-6904ed452730.png)

2021-10-07 19:46 UTC, christinewang5 commented
closing because there is a new pr with the correct rebasing: 
https://github.com/magma/magma/pull/9567

2021-10-07 19:46 UTC, closed without merging