test(orc8r): add tests for checking entBlobStore -> sqlBlobStore migration
magma/magma pull request #9541
Opened 2021-10-07 09:29 UTC by reginawang3495

## Summary
Tests that SQL→ent application change won’t require a data migration

## Test Plan
Ran stated test in IntelliJ

2021-10-14 20:41 UTC, hcgatewood requested changes
I think we're moving in the right direction. Here's what I had in mind for the top-level

- TestEntToToSQLMigration, TestSQLToEntMigration
- writeBlobs, readExistingBlobs

Where each migration test does the following
- writeBlobs with impl A
- readExistingBlobs with impl A
- readExistingBlobs with impl B

And writeBlobs tests all the write-based interface methods, while readExistingBlobs tests all the read-based interface methods

I think this way of structuring the tests, plus the comments I added below, will make for a more concise migration test

Also down to talk through any of the individual points, either in Slack or in vc, just lmk!

2021-10-14 20:41 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +func testMigrationsToDifferentBlobstores(t *testing.T, fact1 blobstore.BlobStorageFactory, fact2 blobstore.BlobStorageFactory) {
This is short enough, let's just inline it

2021-10-14 20:41 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +func TestSQLToEntMigration(t *testing.T) {
General input: structure your file such that the "most important" or "top-level" functions are at the top -- this will generally mean putting the public functions first. Then, organize the remaining functions (often private) in roughly the order in which they're called

Another way of thinking about this is, you have some rough approximation of a call tree -- the order of your functions should correlate with that call tree, meaning layer 0 functions at the top, layer 1 functions in the middle, layer 2 functions near the bottom, etc

There's no way to be perfect about this, but approximating this flow will make reading your code feel more natural, like reading a book

2021-10-14 20:41 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +	// Spin up DB
These types of "topic sentence" comments are a bad code smell. Instead, either omit them, or move the block into a function and use the comment as the function name. In this particular case, you can just omit the comment

Caveat 1: it is helpful to use these comments *during* development. But the final, checked-in code should generally be free of them

Caveat 2: in test code, providing a description of "what you're testing" can be a useful application of these topic sentences. So e.g. `// Ensure GetMany works` is fine, since it summarizes the intent of the block, but `// Spin up DB` is unnecessary since it's clear from skimming the next two lines

2021-10-14 20:41 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +/**
Style preference is single-line comments (`//`) rather than java-style multiline

2021-10-14 20:41 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +var blobPair1 = Pair{
Personally I don't like declaring package-level variables in your test files. This causes issues with variable name clashes when you add other test files in the same pkg. Instead, declare these directly in the function where they're needed

2021-10-14 20:42 UTC, hcgatewood requested changes
Edit: github being buggy. Ignore this requested change in favor of the above^

2021-10-14 20:46 UTC, hcgatewood commented
P.S. looks like the cloud linter job is failing. To fix this, you'll want to add gofmt as an on-save job to intellij https://stackoverflow.com/questions/33774950/execute-gofmt-on-file-save-in-intellij

The easy solution here is copy the watcher file from .intellij.shared to .intellij https://github.com/magma/magma/tree/ce40d2585f9de0a7a7b66a4c88aa9d4b2815a2ed/.idea.shared

2021-10-15 22:03 UTC, hcgatewood requested changes
Okay this is looking great 👍 Couple nits and one q on the checkBlobInStore seems like it should fail (?), other than that I think we're gtg

2021-10-15 22:03 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +func TestSQLToEntMigration(t *testing.T) {
I think we can actually just have 1 `TestBlobstoreImplMigrations`, then run `checkBlobstoreMigrations` twice in that func (or use a sub-test with `t.Run`)

2021-10-15 22:03 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +// Assumes that expectedBlobs length is at least 2.
Docstrings should be prefixed with the identifier -- so e.g.
```suggestion
// checkReadBlobs does xyz.
// Assumes that expectedBlobs length is at least 2.
```

2021-10-15 22:03 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +	assert.ElementsMatch(t, blobs, blobSlice)
Throughout: use `want`/`got` style, either as want/got or as e.g. `expectedBlobs`/`actualBlobs`

2021-10-15 22:03 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +	checkBlobInStore(t, store, networkID, blobNotInFact)
Feels like this should fail ?

2021-10-15 22:03 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +	require.NoError(t, err)
I know this file already used require, but an opportunity to improve the file is to use assert rather than require. Difference is require fails immediately. Assert is preferred cause it's easier to understand what happened in CI

2021-10-15 22:03 UTC, hcgatewood commented on orc8r/cloud/go/blobstore/ent_test.go
> +func getTKsFromBlobs(blobs blobstore.Blobs) storage.TKs {
I think these 2 helper funcs already exist in the codebase

2021-10-15 23:14 UTC, reginawang3495 commented on orc8r/cloud/go/blobstore/ent_test.go
> +	checkBlobInStore(t, store, networkID, blobNotInFact)
Not really, can see L152-155. This function checks that writing works, so we first check that `CreateOrUpdate` wrote `blobNotInFact` properly

2021-10-18 20:31 UTC, hcgatewood requested changes
Edit: disregard, misread the test 🙂 

---

Okay, I see where I was confused for checkBlobInStore

1. checkWriteBlobs *does* have a side effect -- namely, it adds blobNotInFact into the fact. So let's fix that doc comment
2. Add a comment above where blobNotInFact gets added in, to draw a bit of extra attention to the fact that we are, in fact, mutating the store to make sure writes still succeed

Other than that lgtm, msg when ready and I'll accept + merge

2021-10-18 20:41 UTC, hcgatewood approved these changes

2021-10-18 20:42 UTC, hcgatewood commented
Force-merging to override borked unrelated test

2021-10-18 20:42 UTC, merged