fix(agw): Fixed memory leak found on network initiated detach procedure
magma/magma pull request #9661
Opened 2021-10-13 17:04 UTC by rsarwad

fix(agw): Fixed memory leak found on network initiated detach procedure

## Summary
For network initiated detach procedure, mme starts 3422 timer and allocates memory to store the required information. As part of handling detach, mme needs to clear the in-memory contexts, As part of clearing in-memory contexts, memory allocated for 3422 timer was not freed.
Now added fix to clear memory allocated for 3422 timer while clearing in-memory contexts.
## Test Plan
Executed s1ap sanity test suite

With fixes, there are no memory leaks found.
Without fix, memory leaks were found

2021-10-13 17:10 UTC, ulaskozat approved these changes
LGTM. Can you also backport this to v1.6?

2021-10-13 18:52 UTC, ulaskozat commented
@rsarwad this looks like failing a unit test.

2021-10-14 13:11 UTC, rsarwad commented
> LGTM. Can you also backport this to v1.6?

This leak observed after porting timers to zmq. v1.6 doesn't include zmq timer. Backporting this PR is not required.

2021-10-14 17:30 UTC, ulaskozat commented
> > LGTM. Can you also backport this to v1.6?
> 
> This leak observed after porting timers to zmq. v1.6 doesn't include zmq timer. Backporting this PR is not required.

How does migration to zmq affect this?

2021-10-22 00:51 UTC, ulaskozat commented
@rsarwad any plans to revisit this?

2021-10-22 02:13 UTC, rsarwad commented
> @rsarwad any plans to revisit this?

Hi @ulaskozat, I was working on adding unit test cases for dedicated bearer creation and deletion. Planning spare some time today.

2021-10-25 16:42 UTC, rsarwad commented
> > > LGTM. Can you also backport this to v1.6?
> > 
> > 
> > This leak observed after porting timers to zmq. v1.6 doesn't include zmq timer. Backporting this PR is not required.
> 
> How does migration to zmq affect this?

Yes @ulaskozat, my analysis is wrong. But let me find the cause why the leak is not shown on branch v1.6

2021-10-26 04:17 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/nas/emm/EmmCommon.c
> +      (emm_attach_request_ies_t*) calloc(1, sizeof(emm_attach_request_ies_t));
`ies` is a stolen reference. you do not need to calloc.

2021-10-26 04:18 UTC, ulaskozat requested changes
I recently fixed a memory leak. please double check with that.

2021-10-26 04:23 UTC, ulaskozat commented
which test are you using for memory leak?

2021-10-26 04:27 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
> +  free_wrapper((void**) &ue_context_p->emm_context.new_attach_info->ies);
I don't think this is needed...

2021-10-26 05:46 UTC, rsarwad commented on lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
> +  free_wrapper((void**) &ue_context_p->emm_context.new_attach_info->ies);
As per the discussion, in this PR retaining fixes only network initiated detach procedure

2021-10-26 05:47 UTC, ulaskozat approved these changes
LGTM

2021-10-26 05:47 UTC, rsarwad commented
> which test are you using for memory leak?

The leak was observed for TC,  test_attach_nw_initiated_detach_with_mme_restart.py

2021-10-26 05:54 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/nas/emm/emm_data_ctx.c
> +  }
isn't this handled as part of `nas_delete_all_emm_procedures`?

2021-10-26 07:39 UTC, rsarwad commented on lte/gateway/c/core/oai/tasks/nas/emm/emm_data_ctx.c
> +  }
There is no emm procedure created for detach procedure, so condition, https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/tasks/nas/nas_procedures.c#L563 fails

2021-10-26 16:55 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/nas/emm/emm_data_ctx.c
> +  }
the question then is "should it be created". If we do not have a "detach procedure", let's clean it up.

2021-10-26 16:58 UTC, merged