fix(agw): AGW containerization fixes
magma/magma pull request #9669
Opened 2021-10-14 01:31 UTC by rmeleromira

Signed-off-by: Ramon Melero <ramonmelero@fb.com>

## Summary

These are fixes needed for containerized AGW

- [ ] This change is backwards-breaking

2021-10-14 12:03 UTC, electronjoe commented on lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
> +    only_upgrade: yes
Here and elsewhere below - per yamllint, could you use `true` instead of `yes`?

2021-10-14 17:37 UTC, arunuke commented on lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
> +    name: systemd-resolved
Why do we need to stop using systemd-resolved and hardcode the dns value?

2021-10-14 18:32 UTC, ymasmoudi commented on lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
> +    only_upgrade: yes
be careful here, ansible expect yes I think

2021-10-14 19:17 UTC, ymasmoudi requested changes

2021-10-14 19:17 UTC, ymasmoudi commented on lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
> +    name: systemd-resolved
@rmeleromira adding a tag agwc will not prevent these tasks from running when installing normal agw.
in addition, all these changes to systemd-resolved are needed for aws only. We might want to not impact the default installation.

2021-10-19 03:08 UTC, rmeleromira commented on lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
> +    name: systemd-resolved
I thought at one point Youssef said that we needed to replace systemd-reolved, so I tried this method. Rather than selectively do these steps based on being on aws, I did a little more digging. It seems that it's the ipfix0 interface that is causing issues. Repo instructions here

https://gist.github.com/rmeleromira/ecac9790cf8fc7c59c07ebd4e983c351#file-test-md

There's a vagrantfile that reproduces the issue. 

```
# start vm using Vagrantfile
vagrant up
vagrant ssh

# test broken dns
ping google.com

# bring down ipfix0 and restart dns
ifdown ipfix0
systemctl restart systemd-resolved

# test and it works
ping google.com
```
Issue with this is I'm not sure how to fix this, so I'll remove the DNS changes I made and leave the rest.

Here's a run through of the whole repro

https://gist.github.com/rmeleromira/163b4ff6ecb31b16685b9b4c39ee8713#file-gistfile1-txt-L755-L768

2021-10-19 03:11 UTC, rmeleromira commented on lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
> +    only_upgrade: yes
Fixed. Seems on with true

```
ok: [127.0.0.1] => {
    "cache_update_time": 1634612673,
    "cache_updated": false,
    "changed": false,
    "invocation": {
        "module_args": {
            "name": [
                "ca-certificates"
            ],
            "only_upgrade": true,
```

2021-10-21 07:05 UTC, ymasmoudi approved these changes
please rebase and fix the conflicts

2021-10-21 20:07 UTC, arunuke approved these changes
LGTM. Let's track the DNS issue as a separate one since there is a manual workaround to it if the problem occurs.

2021-10-21 20:09 UTC, pshelar requested changes

2021-10-21 20:09 UTC, pshelar commented on lte/gateway/docker/readme.md
> +cat /etc/netplan/50-cloud-init.yaml
we don't support netplan, it would confict with OVS bridge interface definitions. Can you use interface file for physical inerfaces/

2021-10-21 20:30 UTC, rmeleromira commented on lte/gateway/docker/readme.md
> +cat /etc/netplan/50-cloud-init.yaml
The current deploy tasks for containerized AGW leaves netplan in place if it's there and netpan comes with ubuntu 20. Should we add some tasks to disable netplan? Or I can just change this part of the documentation to udev rules which will accomplish the renaming without using netplan. Or leave out the example all together. I just put it in there cause I figured almost everyone will need to change their interface names and would be nice to supply an example.

2021-10-21 20:39 UTC, pshelar commented on lte/gateway/docker/readme.md
> +cat /etc/netplan/50-cloud-init.yaml
its done during agw deployment:
https://github.com/magma/magma/blob/2635f924633f0245b47420294257f80bc8007c4f/lte/gateway/deploy/agw_install_ubuntu.sh#L118

2021-10-21 21:27 UTC, rmeleromira commented on lte/gateway/docker/readme.md
> +cat /etc/netplan/50-cloud-init.yaml
I see. Package agw script enables networking service and purges netplan, but not containerized atm. I'll bring this up to Youssef to see how we can handle it.

why is the eth1 hard coded in [agw_install_ubuntu.sh](https://github.com/magma/magma/blob/master/lte/gateway/deploy/agw_install_ubuntu.sh#L113-L116)? 

It figures out the ip info for eth0 but not eth1, not sure why

2021-10-22 12:33 UTC, arunuke commented on lte/gateway/docker/readme.md
> +cat /etc/netplan/50-cloud-init.yaml
A key point to remember that the containerized AGW is different from the packaged AGW because of it's expected independence of the host. The packaged AGW is built to run on Ubuntu while the objective of the containerized AGW is to run across hosts which is why the configuration of the host itself is separated from the starting up of the containers.

2021-10-22 12:51 UTC, electronjoe approved these changes

2021-10-22 12:51 UTC, electronjoe commented on lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
> +  become: yes
Can we use the yamlint recommendation of `become: true`?

2021-10-22 12:51 UTC, electronjoe commented on lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
> +    only_upgrade: yes
Can we use the yamlint advice of `only_upgrade: true`?

2021-10-22 12:51 UTC, electronjoe commented on lte/gateway/docker/publish.sh
> +  docker tag agw_gateway_$1:latest "${REGISTRY}"agw_gateway_$1:"${VERSION}"
Is it possible to address the Shellcheck findings here and below?

2021-10-22 15:33 UTC, pshelar commented on lte/gateway/docker/readme.md
> +cat /etc/netplan/50-cloud-init.yaml
> I see. Package agw script enables networking service and purges netplan, but not containerized atm. I'll bring this up to Youssef to see how we can handle it.
> 
> why is the eth1 hard coded in [agw_install_ubuntu.sh](https://github.com/magma/magma/blob/master/lte/gateway/deploy/agw_install_ubuntu.sh#L113-L116)?
> 
> It figures out the ip info for eth0 but not eth1, not sure why

eth1 (S1) is typically private network, so we recommend this specific network.

2021-10-22 15:53 UTC, pshelar commented on lte/gateway/docker/readme.md
> +cat /etc/netplan/50-cloud-init.yaml
> A key point to remember that the containerized AGW is different from the packaged AGW because of it's expected independence of the host. The packaged AGW is built to run on Ubuntu while the objective of the containerized AGW is to run across hosts which is why the configuration of the host itself is separated from the starting up of the containers.

I agree with this in medium term, but today we do make use of host networking for containers, that creates dependency on the host network configuration.
For now we need to move our OVS bridge configuration to netplan based config to have single/consistent configuration across all host devices.

2021-10-22 17:16 UTC, arunuke commented on lte/gateway/docker/readme.md
> +cat /etc/netplan/50-cloud-init.yaml
Agree. Although the ideal goal is full independence, since we have some tight dependencies today (as you highlight above) the hope is to keep them as minimal as possible to essential elements (like OVS running on the base host). If it works, we can experimentally pilot the addition of netplan support for OVS in the container AGW effort since this is still in alpha without impacting the package based version which is the currently prod supported version.

2021-10-22 21:50 UTC, pshelar approved these changes
as Arun mentioned we will continue to make progress to netplan based config for containerized agw.

2021-10-22 22:45 UTC, rmeleromira commented on lte/gateway/docker/readme.md
> +cat /etc/netplan/50-cloud-init.yaml
I've removed the section mentioning netplan, this should resolve this for this PR.

2021-10-25 19:32 UTC, merged