feat(orc8r): add indexRemove to indexers interface
magma/magma pull request #9671
Opened 2021-10-14 01:43 UTC by uri200

Signed-off-by: Oriol Batalla <obatalla@fb.com>

## Summary

This PR modifies protos to include `IndexRemove` and includes end points on all the required implementation of Indexer interface. 

It also modify the function that handles Index to include IndexRemove by the Indexer.

## Test Plan

```
./build.py -g
./build.py -c
```

## Additional Information

- [ ] This change is backwards-breaking

2021-10-14 05:21 UTC, hcgatewood requested changes
Lgtm, couple nits then good to go

As an optional aside: I actually like `DeIndex` better than `IndexRemove`, to me it's more self-descriptive. But up to you 🙂

2021-10-14 05:21 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/indexer.go
> +//go:generate bash -c "mockery --name=Indexer --note='Run ./build -g at Orc8r to re-generate'"
Nit
```suggestion
//go:generate bash -c "mockery --name=Indexer --note='Run ./build --generate at Orc8r to re-generate'"
```

2021-10-14 05:21 UTC, hcgatewood commented on orc8r/cloud/go/services/state/protos/indexer.proto
> +  rpc IndexRemove(IndexRequest) returns (IndexResponse) {}
Preferred pattern is to have a unique Request, Response per rpc -- so `IndexRemove(IndexRemoveRequest) ...`

2021-10-14 05:21 UTC, hcgatewood commented on orc8r/cloud/go/services/state/test_init/test_indexer_servicer.go
> +an
Typo?

2021-10-14 05:21 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/index/index.go
> +func indexerSingleAction(networkID string, idx indexer.Indexer, states state_types.SerializedStatesByID, actionType int) error {
Nit: function names should start with a verb. In this case, I'm fine with leaving it as `indexOne` and having the action type in the fn signature make it clear that this could be either index or deindex

2021-10-14 20:41 UTC, uri200 commented on orc8r/cloud/go/services/state/protos/indexer.proto
> +  rpc IndexRemove(IndexRequest) returns (IndexResponse) {}
yep forgot that

2021-10-14 20:42 UTC, uri200 commented on orc8r/cloud/go/services/state/test_init/test_indexer_servicer.go
> +an
vim command 😅

2021-10-15 18:11 UTC, uri200 commented on lte/gateway/python/integ_tests/federated_tests/configs/service_registry.yml
> +    port: 9094
changed port on feg_hello service to avoid collision with metrics service on orc8r when running feg and or8cr on the same machine

2021-10-15 18:26 UTC, ardzoht approved these changes
agw changes lgtm

2021-10-15 22:52 UTC, hcgatewood approved these changes
Lgtm!

2021-10-15 22:52 UTC, hcgatewood commented on docs/readmes/orc8r/dev_security.md
> +commands)
Comment?

2021-10-15 22:52 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/indexer.go
> +//go:generate bash -c "mockery --name=Indexer --note='Run ./build --generate at Orc8r to re-generate'"
Nit 
```suggestion
//go:generate bash -c "mockery --name=Indexer --note='Run build --generate at Orc8r to re-generate'"
```

2021-10-18 18:19 UTC, electronjoe commented on orc8r/cloud/go/services/state/indexer/index/index_test.go
> +
Drive-by nit: this unit test is getting pretty large - a failure may increasingly become harder to differentiate the cause (which part of happy path is broken).  At some point we probably want to break the happy path up into step-focused happy path sub-tests?

2021-10-18 18:20 UTC, electronjoe commented
Thanks for implementing this functionality, @uri200

2021-10-18 20:56 UTC, merged