feat(ci): new ci for pre and post merge
magma/magma pull request #9682
Opened 2021-10-14 17:01 UTC by quentinDERORY

Signed-off-by: quentinDERORY <15911421+quentinDERORY@users.noreply.github.com>

## Summary

Pre merge pipeline:
- deploy build to test registries when there is a change (currently pointing to CI, will change when test registries are created) 
- Test executes in parallel of build
- Integ test (CWF & LTE) on demand

Post merge pipeline:
- Always deploy build to ci registries  (no path filtering as makes it harder to deploy latest of master to an environment if only one part of magma is on ci-registries)
- Test executes in parallel of build
- Integ test (CWF & LTE) always run

Build of agw has been migrated to github actions.
CWF integ tests run on two runners due to poor performance of docker-compose on MacOS.

Will later improve tests result display when building the full post build heavy testing pipeline with firebase.

## Test Plan

Tested on Forked repo

## Additional Information

Will later improve the way the workflows file hierarchy, but we will no be able to achieve one file per pre/post merge due to permissions in forked repo.
And current reusability of workflow is showing limitations.

2021-10-26 21:26 UTC, tmdzk requested changes
overall looks good just 2 tiny comments

2021-10-26 21:26 UTC, tmdzk commented on .github/workflows/agw-workflow.yml
> +      - v1.*
at some point this won't work anymore, we'll need to come up with a solution, lat time I tried `v*.*` it didnt' work

2021-10-26 21:26 UTC, tmdzk commented on .github/workflows/agw-workflow.yml
> +          echo ${{ github.event.number }} > ./pr/NR
let's store them in /tmp 
on top of that let's just do one file with all env var, so that we can just source the file and have it 

echo "PR_NUMBER=${{ github.event.number }}" >> /tmp/ci_vars

something like that 

then when needed we do `source /tmp/ci_vars`

2021-10-27 16:08 UTC, quentinDERORY commented on .github/workflows/agw-workflow.yml
> +          echo ${{ github.event.number }} > ./pr/NR
I understand the intent but, the way artifacts are retrieved today is with javascript code being executed on the triggered workflow.
Changing it to a source file will make the workflow needing the information longer(still need js code to fetch artifacts and download it) and exporting variable in gha is a litlle bit trickier than regular export of variable.
All in all, it's possible but will imply a not tiny refactor for a not so better code.

2021-10-27 16:09 UTC, quentinDERORY commented on .github/workflows/agw-workflow.yml
> +      - v1.*
we can always add v2.* when needed and figure out a solution by then.

2021-10-27 16:15 UTC, tmdzk approved these changes

2021-10-27 18:24 UTC, merged