fix(mobilityd): ipv6 block size
magma/magma pull request #9712
Opened 2021-10-15 23:30 UTC by pshelar

mobilityD expect operator to allocate '/48' or
bigger range. That is not practical or required for
many deployments. Following PR relaxes it to
'/60' and makes it configurable.

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>

## Summary

## Test Plan
`make test`

## Additional Information

- [ ] This change is backwards-breaking

2021-10-15 23:33 UTC, ardzoht approved these changes
lgtm

2021-10-15 23:58 UTC, ulaskozat commented
@pshelar, @ardzoht currently prefix allocation to a session happens randomly. To prevent too many collisions, I believe Alex have left originally at least 16 bits.  Can you guys add a non-random strategy for prefix assignment to the sessions if we are shrinking this to as small as 4 bits?

2021-10-15 23:59 UTC, ulaskozat requested changes
add a non-random assignment strategy first as each session must have a unique IPv6 prefix.

2021-10-18 17:27 UTC, pshelar commented
> @pshelar, @ardzoht currently prefix allocation to a session happens randomly. To prevent too many collisions, I believe Alex have left originally at least 16 bits. Can you guys add a non-random strategy for prefix assignment to the sessions if we are shrinking this to as small as 4 bits?

@ulaskozat I have increased number of tries for now. we can discuss improvement in separate ticket: #9735

2021-10-18 17:56 UTC, ulaskozat approved these changes
LGTM. Let's not have the follow up issue to fall through the cracks.

2021-10-18 19:20 UTC, merged