feat(orc8r): Changes to accept AMF configs from orc8r
magma/magma pull request #9756
Opened 2021-10-19 14:35 UTC by shivesh-wavelabs

## Summary

This PR deals with the changes as mentioned in the [document ](https://docs.google.com/document/d/1yywmytLNr8p704m7rFcAfHGanG90ZeIo/edit#)

Added updates to swagger.v1.yml to accept AMF configs.
Modified Mconfig builder to fill the mconfig message with New attributes
Added/Modified obsidian handlers to accept AMF configs.

AGW and proto changes are in [#10392](https://github.com/magma/magma/pull/10392).

### Test Plan

Added UT cases in obsidian handlers to verify the new endpoints and new attributes for added AMF attributes.

2021-10-21 21:19 UTC, hcgatewood requested changes
Overall lgtm. 2 small things then I'll be content

2021-10-21 21:19 UTC, hcgatewood commented on lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
> +					Ngc: &lteModels.GatewayNgcConfigs{AmfDefaultSd: "AFAFAF", AmfDefaultSst: swag.Uint32(25), AmfName: "amf.example.org", AmfPointer: "1F", AmfRegionID: "C1", AmfSetID: "2A1"},
Nit: here and elsewhere: let's break these long-line struct literals into multiple lines -- one field per line

2021-10-21 21:19 UTC, hcgatewood commented on lte/cloud/go/services/lte/servicers/builder_servicer.go
> +			DefaultSliceServiceType:    *gwNgc.AmfDefaultSst,
This feels dangerous. Either make the field non-nil (in swagger), or guard against the field potentially being nil

2021-10-22 07:20 UTC, shivesh-wavelabs commented on lte/cloud/go/services/lte/servicers/builder_servicer.go
> +			DefaultSliceServiceType:    *gwNgc.AmfDefaultSst,
Sure, I'll make `x-nullable:false` for these in swagger.

2021-10-22 07:21 UTC, shivesh-wavelabs commented on lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
> +					Ngc: &lteModels.GatewayNgcConfigs{AmfDefaultSd: "AFAFAF", AmfDefaultSst: swag.Uint32(25), AmfName: "amf.example.org", AmfPointer: "1F", AmfRegionID: "C1", AmfSetID: "2A1"},
Sure.

2021-10-22 18:12 UTC, hcgatewood reviewed
2 comments, not sure on the latter one so feel free to DM me if I'm misunderstanding. Otherwise lgtm -- lmk and I'll approve!

2021-10-22 18:12 UTC, hcgatewood commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +
Fix yamllint errors

2021-10-22 18:12 UTC, hcgatewood commented on lte/cloud/go/services/lte/servicers/builder_servicer.go
> +			DefaultSliceServiceType:    *gwNgc.AmfDefaultSst,
Looks like this is still a ptr that we're not nil-guarding (?)

2021-10-22 18:14 UTC, shivesh-wavelabs commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +
okay.

2021-10-22 18:17 UTC, hcgatewood commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +        description: AMF Default Slice Service Type. Values 0 to 127 correspond to the standardized SST range. Values 128 to 255 correspond to the Operator-specific range. See clause 28.4.2 of 3GPP T
@shivesh-wavelabs this is the particular object I believe you need to mark as x-nullable false

2021-10-22 18:21 UTC, hcgatewood commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +        type: integer
```suggestion
      amf_default_sst:
        type: integer
        x-nullable: false
```

2021-10-22 21:25 UTC, shivesh-wavelabs commented on lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
> +        description: AMF Default Slice Service Type. Values 0 to 127 correspond to the standardized SST range. Values 128 to 255 correspond to the Operator-specific range. See clause 28.4.2 of 3GPP T
got it.

2021-10-22 22:24 UTC, hcgatewood approved these changes
Lgtm 👍

2021-10-26 06:36 UTC, anusha-konda commented
Looks like each section in gateway.mconfig represents a service ( like mme, pipelined) in AGW, whereas AMF is launched as thread.
Introducing a separate section for amf is not inline with the current framework to read configs from gateway.mconfig by a service.
So will add all the new attributes in mme section itself and make it configurable from swagger.
cc @panyogesh, @ulaskozat

2021-11-01 17:55 UTC, shivesh-wavelabs commented
Hi @hcgatewood, can you re-review this PR ?

2021-11-02 21:34 UTC, hcgatewood approved these changes
Lgtm! 💯💯

2021-11-11 01:43 UTC, ulaskozat approved these changes
LGTM

2021-11-11 01:51 UTC, ulaskozat commented
proto and pb files are in #10222, right? Please update the summary about the dependence.

2021-11-23 12:09 UTC, shivesh-wavelabs commented
@hcgatewood could you merge this PR, its dependent PR #10392 is already merged.

2021-11-23 19:22 UTC, hcgatewood commented
@shivesh-wavelabs looks like the insync job is hanging. Can you rebase onto latest master and retry, should fix

2021-11-24 18:51 UTC, shivesh-wavelabs commented
> @shivesh-wavelabs looks like the insync job is hanging. Can you rebase onto latest master and retry, should fix

done.

2021-11-29 21:15 UTC, merged