refactor(orc8r): Add obsidian middleware to properly log and report non-2xx responses
magma/magma pull request #9767
Opened 2021-10-19 20:54 UTC by christinewang5

## Summary
* Created Makefile in orc8r for better dev experience
* Added obsidian middleware to each service to properly log and report non-2xx responses 
* Removed old `obsidian.HttpError` pattern 

## Test Plan
1. Ran unit tests that evoke the middleware function `Logger` with various verbosity levels
<img width="655" alt="newLogs" src="https://user-images.githubusercontent.com/25142344/138355310-89e1e004-5425-41de-99c8-eafa69eec64b.png">

2. Checked `docker-compose logs -f controller` and sent erroneous requests from swagger ui 
<img width="1792" alt="service" src="https://user-images.githubusercontent.com/25142344/138215817-63113e57-160d-4ded-a684-73475d1c5cc3.png">

2021-10-21 17:21 UTC, hcgatewood requested changes
Looks great! Couple small things then we'll be ready to merge 💯🌟

2021-10-21 17:21 UTC, hcgatewood commented on orc8r/cloud/go/obsidian/server/metrics_test.go
> +func TestLogger(t *testing.T) {
Hm so, this doesn't *programmatically* test anything (i.e. there aren't any asserts)

As an aside, this is why dependency injection is so useful -- you can assert that the logger actually did log what you want, programmatically

But anyways, I don't think there's a good way to make this test programmatically useful, so for now I think we should omit it. Lmk if you feel strongly though

2021-10-21 17:21 UTC, hcgatewood commented on orc8r/cloud/go/obsidian/server/metrics_test.go
> +// Run `go test -v ./... --args --logtostderr -v=<verbosity>` to see logs
Side note: you can achieve this programmatically e.g. https://github.com/magma/magma/blob/13b485a9b6da5874761919c840e4c0a8be81641d/orc8r/cloud/go/services/state/indexer/reindex/queue_sql_test.go#L39-L41

2021-10-21 17:21 UTC, hcgatewood commented on orc8r/cloud/go/obsidian/server/metrics_test.go
> +	deviceTestInit "magma/orc8r/cloud/go/services/device/test_init"
Nit: I feel mixed, but at the end of the day we've settled on doing `device_test_init` rather than `deviceTestInit` -- thought there are plenty of places in the codebase where that's not the case yet

2021-10-21 17:21 UTC, hcgatewood commented on orc8r/cloud/go/obsidian/server/server.go
> +				// tls.TLS_RSA_WITH_AES_256_CBC_SHA,
Let's just go ahead and delete these, they've been commented-out for over 2 years

2021-10-21 17:21 UTC, hcgatewood commented on orc8r/cloud/go/service/service.go
> +			he, _ := err.(*echo.HTTPError)
I don't think this is guaranteed -- i.e. you *can* return any type of error, we just happen to always return an echo.HTTPError

I would just pass the error directly to the logger -- and the `%s` directive should coerce it into its stringified form by calling `Error`

If that doesn't work, you can conditionally convert the err directly -- `errMsg := err.Error()`

2021-10-21 17:21 UTC, hcgatewood commented on orc8r/cloud/go/service/service.go
> +				glog.Infof("REST HTTP Error: %s, Status: %d", he.Message, he.Code)
Put the code first, then the msg -- will be easier to grep for and visually skim

2021-10-21 17:21 UTC, hcgatewood commented on orc8r/cloud/go/service/service_test.go
> +func TestLogger(t *testing.T) {
Same idea for this test -- we don't have great DI right now, so this doesn't actually test anything programmatically, so let's default to leaving it out for now

2021-10-21 20:32 UTC, christinewang5 commented on orc8r/cloud/go/obsidian/server/metrics_test.go
> +func TestLogger(t *testing.T) {
Yup I agree, deleting it in the next commit....

2021-10-21 20:56 UTC, christinewang5 commented on orc8r/cloud/go/service/service.go
> +			he, _ := err.(*echo.HTTPError)
Sounds good, here are the new error logs:
<img width="655" alt="newLogs" src="https://user-images.githubusercontent.com/25142344/138355401-17f6e97c-bafc-428c-b1d8-8089c6a537fe.png">

2021-10-21 21:00 UTC, christinewang5 commented
Ok also I decided to just delete the logging from `obsidian.HttpError` rather than replace it completely, because it did some error formatting for certain errors and a bunch of tests were failing without them...

2021-10-26 00:13 UTC, hcgatewood requested changes
Looking good, couple nits, main thing is obsidian.MakeHTTPError should just be a one-liner

2021-10-26 00:13 UTC, hcgatewood commented on orc8r/cloud/docker/Makefile
> +build:
Nit: let's make this a separate PR. For that PR: can you change these build.py calls to be build.py --all --parallel

2021-10-26 00:13 UTC, hcgatewood commented on orc8r/cloud/go/obsidian/handler.go
> +func HTTPError(err error, code ...int) *echo.HTTPError {
Couple nits

- From offline discussion: let's make this `MakeHTTPError` or `NewHTTPError`
- "...wraps the passed error as an echo HTTP error..." (add "echo")
- Add a not in the doc comment that echo.NewHTTPError should be preferred where possible

2021-10-26 00:13 UTC, hcgatewood commented on orc8r/cloud/go/service/service.go
> +				glog.Infof("Error: %s", err)
```suggestion
				glog.Infof("HTTP server error: %s", err)
```

2021-10-26 00:13 UTC, hcgatewood commented on orc8r/cloud/go/service/service.go
> +				glog.V(1).Infof("Error: %s", err)
```suggestion
				glog.V(1).Infof("HTTP error: %s", err)
```

2021-10-26 00:13 UTC, hcgatewood commented on orc8r/cloud/go/service/service.go
> +// Logger is the middleware function
```suggestion
// Logger is a middleware function that intelligently logs HTTP errors.
```

2021-10-26 00:13 UTC, hcgatewood commented on orc8r/cloud/go/obsidian/handler.go
>  	}
From offline: we don't want to do any logging from this func at all -- just coerce the error to echo.HTTPError (the final line of the fn)

2021-10-27 16:35 UTC, hcgatewood approved these changes
Awesome! Excited for this, thanks for the fix @christinewang5 💯

2021-10-27 16:45 UTC, hcgatewood commented
Looks like cloud lint may be failing

Also, looks like CWF operator is failing... not super certain how that's happening. Try rebasing onto latest master first. If that doesn't work, try running those tests locally on your branch and see if they fail. If yes, try to debug / lmk what you find. If no, lmk and we can look into it together

2021-10-30 10:36 UTC, themarwhal approved these changes

2021-11-02 05:50 UTC, merged