feat(mme): SubscriberDB-Ext, Handling of Subscriber validation based on forbidden network type
magma/magma pull request #9775
Opened 2021-10-20 05:28 UTC by rupa455wavelabs

### **SUMMARY**

Code changes for subscriber DB extension
Updated processor.py file to verify forbidden network types for subscriber.

### **Order of Merge**
Please merge the current PR as per the below specified order
PR #9161 - PR #9165 - PR #9775 

### **Test Plan**
Added Unit test cases for all the modified functions.
Verified end-to-end by configuring forbidden network type as NT_EPC, NT_5GC and tested it using SrsRan and UERANSIM.

**Additional Information**
Signed-off-by: rupa455wavelabs <rupa.seshaveni@wavelabs.ai>

2021-10-20 12:27 UTC, rupa455wavelabs commented
```
**4G Testing** 
 Forbidden network type                    Result
 NT_EPC                                              Attach Rejected due to network failure
 NT_5GC                                             Attach,PDN connectivity is successful
 NT_EPC, NT_5GC                               Attach Rejected due to network failure
 No_Forbidden_NetworkType            Attach, PDN connectivity is successful


**5G Testing logs**
(python) vagrant@magma-dev-focal:~/magma/lte/gateway/python/scripts$ subscriber_cli.py get IMSI901700000000011
sid {
id: "901700000000011"
}
gsm {
}
lte {
state: ACTIVE
auth_key: "F[\\\350\261\231\264\237\252_\n.\3428\246\274"
auth_opc: "\350\355(\235\353\251R\344(;T\350\216a\203\312"
}
state {
}
sub_network {
forbidden_network_types: NT_5GC
}
**UERANSIM:**
[nas] [error] Initial Registration failed [ILLEGAL_UE]

(python) vagrant@magma-dev-focal:~/magma/lte/gateway/python/scripts$ subscriber_cli.py get IMSI901700000000012
sid {
id: "901700000000012"
}
gsm {
}
lte {
state: ACTIVE
auth_key: "F[\\\350\261\231\264\237\252_\n.\3428\246\274"
auth_opc: "\350\355(\235\353\251R\344(;T\350\216a\203\312"
}
state {
lte_auth_next_seq: 2
}
sub_network {
forbidden_network_types: NT_EPC
}

**UERANSIM behaviour:**
Timer expired two times but then PDU session established.
vagrant@ue-ran-sim:~/UERANSIM$ sudo build/nr-ue -c config/open5gs-ue.yaml
UERANSIM v3.2.4
[2021-10-19 16:56:05.798] [nas] [info] UE switches to state [MM-DEREGISTERED/PLMN-SEARCH]
[2021-10-19 16:56:05.799] [rrc] [debug] New signal detected for cell[1], total [1] cells in coverage
[2021-10-19 16:56:05.799] [nas] [info] Selected plmn[901/70]
[2021-10-19 16:56:05.799] [rrc] [info] Selected cell plmn[901/70] tac[1] category[SUITABLE]
[2021-10-19 16:56:05.799] [nas] [info] UE switches to state [MM-DEREGISTERED/PS]
[2021-10-19 16:56:05.799] [nas] [info] UE switches to state [MM-DEREGISTERED/NORMAL-SERVICE]
[2021-10-19 16:56:05.799] [nas] [debug] Initial registration required due to [MM-DEREG-NORMAL-SERVICE]
[2021-10-19 16:56:05.800] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2021-10-19 16:56:05.800] [nas] [debug] Sending Initial Registration
[2021-10-19 16:56:05.800] [nas] [info] UE switches to state [MM-REGISTER-INITIATED]
[2021-10-19 16:56:05.800] [rrc] [debug] Sending RRC Setup Request
[2021-10-19 16:56:05.801] [rrc] [info] RRC connection established
[2021-10-19 16:56:05.801] [rrc] [info] UE switches to state [RRC-CONNECTED]
[2021-10-19 16:56:05.801] [nas] [info] UE switches to state [CM-CONNECTED]
[2021-10-19 16:56:20.951] [nas] [debug] NAS timer[3510] expired [1]
[2021-10-19 16:56:20.951] [nas] [info] UE switches to state [MM-DEREGISTERED/PS]
[2021-10-19 16:56:20.951] [nas] [info] UE switches to state [5U2-NOT-UPDATED]
[2021-10-19 16:56:20.951] [nas] [info] Performing local release of NAS connection
[2021-10-19 16:56:20.951] [nas] [info] UE switches to state [MM-DEREGISTERED/ATTEMPTING-REGISTRATION]
[2021-10-19 16:56:20.951] [rrc] [info] UE switches to state [RRC-IDLE]
[2021-10-19 16:56:20.952] [nas] [info] UE switches to state [CM-IDLE]
[2021-10-19 16:56:31.036] [nas] [debug] NAS timer[3511] expired [1]
[2021-10-19 16:56:31.036] [nas] [debug] Initial registration required due to [T3511-EXPIRY-IN-ATT-REG]
[2021-10-19 16:56:31.036] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2021-10-19 16:56:31.036] [nas] [debug] Sending Initial Registration
[2021-10-19 16:56:31.036] [nas] [info] UE switches to state [MM-REGISTER-INITIATED]
[2021-10-19 16:56:31.037] [rrc] [debug] Sending RRC Setup Request
[2021-10-19 16:56:31.040] [rrc] [info] RRC connection established
[2021-10-19 16:56:31.040] [rrc] [info] UE switches to state [RRC-CONNECTED]
[2021-10-19 16:56:31.040] [nas] [info] UE switches to state [CM-CONNECTED]
[2021-10-19 16:56:31.077] [nas] [debug] Authentication Request received
[2021-10-19 16:56:31.077] [nas] [debug] Sending Authentication Failure due to SQN out of range
[2021-10-19 16:56:31.088] [nas] [debug] Authentication Request received
[2021-10-19 16:56:31.091] [nas] [debug] Security Mode Command received
[2021-10-19 16:56:31.092] [nas] [debug] Selected integrity[2] ciphering[0]
[2021-10-19 16:56:31.097] [nas] [debug] Registration accept received
[2021-10-19 16:56:31.097] [nas] [info] UE switches to state [MM-REGISTERED/NORMAL-SERVICE]
[2021-10-19 16:56:31.097] [nas] [info] UE switches to state [5U1-UPDATED]
[2021-10-19 16:56:31.097] [nas] [debug] Sending Registration Complete
[2021-10-19 16:56:31.097] [nas] [info] Initial Registration is successful
[2021-10-19 16:56:31.097] [nas] [debug] Sending PDU Session Establishment Request
[2021-10-19 16:56:31.100] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2021-10-19 16:56:33.165] [nas] [debug] PDU Session Establishment Accept received
[2021-10-19 16:56:33.165] [nas] [info] PDU Session establishment is successful PSI[1]
[2021-10-19 16:56:33.185] [app] [info] Connection setup for PDU session[1] is successful, TUN interface[uesimtun0, 192.168.128.254] is up.
  
 ```


![No_fordidden_network_types](https://user-images.githubusercontent.com/84853370/138092339-650fec27-43ee-4607-b86e-d0658e961ac5.PNG)

![NT_5GC](https://user-images.githubusercontent.com/84853370/138092350-2f6ced4a-3da1-46b1-a0a9-7c39ede64249.PNG)
![NT_5GC_NT_EPC](https://user-images.githubusercontent.com/84853370/138092353-633b6619-2eae-44bf-8b2f-0ce6e6ff5cb6.PNG)
![NT_EPC](https://user-images.githubusercontent.com/84853370/138092356-caa0e14f-188f-41ff-966c-0d5b56e091d6.PNG)

2021-10-21 00:08 UTC, ulaskozat commented
@tmdzk do we not run insync checks? This PR does not have the go protobuf files generated and added, yet there is no warning? (cc @themarwhal, @hcgatewood).

2021-10-21 00:15 UTC, ulaskozat requested changes
please generate and add .pb files for the cloud.

Run docker on host machine and run `build.py -g` under directory `/magma/orc8r/cloud/docker` to auto-generate files.

Other useful commands:
```
orc8r/cloud/docker/build.py -m
make precommit
make gen 
```

2021-10-21 00:22 UTC, ulaskozat commented on lte/gateway/python/magma/subscriberdb/processor.py
> +            raise CryptoError("5G services not allowed for %s" % sid)
this is not really a crypto error. can you define a new exception class about subscription? you can define an error such as ServiceNotActive (utilize it for lte.state as well in this case).

2021-10-21 00:23 UTC, ulaskozat commented on lte/gateway/python/magma/subscriberdb/processor.py
>              raise CryptoError("LTE service not active for %s" % sid)
since we are overloading this for 5G, we should change the error type and message should say `5G service not active ...` rather than `LTE service not active ...`.

2021-10-21 00:58 UTC, themarwhal commented
> @tmdzk do we not run insync checks? This PR does not have the go protobuf files generated and added, yet there is no warning? (cc @themarwhal, @hcgatewood).

It looks like the insync check falls under the cloud-workflow which only gets run for the paths outlined here: https://github.com/magma/magma/blob/master/.github/workflows/cloud-workflow.yml#L27

We should trigger these on proto changes as well.

2021-10-21 01:56 UTC, ardzoht requested changes

2021-10-21 01:56 UTC, ardzoht commented on lte/gateway/python/magma/subscriberdb/processor.py
> +        sub_network=CoreNetworkType(),
we should avoid initializing class members with default arguments
```suggestion
        sub_network=None,
```

and on line 132 do:
`self._sub_network = sub_network or CoreNetworkType()`

2021-10-21 02:35 UTC, anusha-konda commented
> please generate and add .pb files for the cloud.
> 
> Run docker on host machine and run `build.py -g` under directory `/magma/orc8r/cloud/docker` to auto-generate files.
> 
> Other useful commands:
> 
> ```
> orc8r/cloud/docker/build.py -m
> make precommit
> make gen 
> ```

@ulaskozat , This PR is dependent on #9161 (Orc8r changes) and #9165 (NMS Changes)  which are not merged. pb.go files are added as part of PR #9161 . Will make sure to add it as part of this PR as well.

2021-10-21 06:10 UTC, tmdzk commented
> > @tmdzk do we not run insync checks? This PR does not have the go protobuf files generated and added, yet there is no warning? (cc @themarwhal, @hcgatewood).
> 
> It looks like the insync check falls under the cloud-workflow which only gets run for the paths outlined here: https://github.com/magma/magma/blob/master/.github/workflows/cloud-workflow.yml#L27
> 
> We should trigger these on proto changes as well.

Sure will create an issue and assign it to the devops team thanks for the catch @themarwhal

2021-10-21 07:00 UTC, ulaskozat commented
> > please generate and add .pb files for the cloud.
> > Run docker on host machine and run `build.py -g` under directory `/magma/orc8r/cloud/docker` to auto-generate files.
> > Other useful commands:
> > ```
> > orc8r/cloud/docker/build.py -m
> > make precommit
> > make gen 
> > ```
> 
> @ulaskozat , This PR is dependent on #9161 (Orc8r changes) and #9165 (NMS Changes) which are not merged. pb.go files are added as part of PR #9161 . Will make sure to add it as part of this PR as well.

always include pb.go files in the PR that modifies the proto. For dependent PRs, please explicitly specify in the summary in what order they are supposed to be merged.

2021-10-22 06:51 UTC, anusha-konda commented
> > > please generate and add .pb files for the cloud.
> > > Run docker on host machine and run `build.py -g` under directory `/magma/orc8r/cloud/docker` to auto-generate files.
> > > Other useful commands:
> > > ```
> > > orc8r/cloud/docker/build.py -m
> > > make precommit
> > > make gen 
> > > ```
> > 
> > 
> > @ulaskozat , This PR is dependent on #9161 (Orc8r changes) and #9165 (NMS Changes) which are not merged. pb.go files are added as part of PR #9161 . Will make sure to add it as part of this PR as well.
> 
> always include pb.go files in the PR that modifies the proto. For dependent PRs, please explicitly specify in the summary in what order they are supposed to be merged.

@ulaskozat , we have included in the PR pb.go file. As suggested, updated Order of Merge in all PRs summary (#9161 , #9165 , #9775 )

2021-10-22 06:56 UTC, rupa455wavelabs commented on lte/gateway/python/magma/subscriberdb/processor.py
> +            raise CryptoError("5G services not allowed for %s" % sid)
Hi @ulaskozat , updated with new exception ServiceNotActive, also added the result code DIAMETER_ERROR_UNAUTHORIZED_SERVICE (5511) , Handled the exception in dependent files and verified the changes.

2021-10-22 06:57 UTC, rupa455wavelabs commented on lte/gateway/python/magma/subscriberdb/processor.py
>              raise CryptoError("LTE service not active for %s" % sid)
Modified as suggested.

2021-10-22 06:57 UTC, rupa455wavelabs commented on lte/gateway/python/magma/subscriberdb/processor.py
> +        sub_network=CoreNetworkType(),
Modified as suggested.

2021-10-26 03:53 UTC, ulaskozat approved these changes
LGTM

2021-11-01 15:42 UTC, ulaskozat commented
@ardzoht I think this needs your approval as you asked for revisions?

2021-11-01 16:44 UTC, ardzoht approved these changes
lgtm

2021-11-02 02:38 UTC, merged

2022-05-10 20:16 UTC, uri200 commented on lte/gateway/python/magma/subscriberdb/processor.py
> +        sub_network=None,
you need to add doc string so we can know what those parameters mean