feat(mme): Add ipv6 msg updates
magma/magma pull request #9781
Opened 2021-10-20 07:12 UTC by koolzz

Signed-off-by: Nick Yurchenko <koolzz@fb.com>

## Summary

- Adds the last remaining conversions to enable IPV6 underlay layer support on agw.
- Mostly just tracking the eth1 ipv6 addr and using that whenever pdn type is ipv6

## Test Plan

- Validated on spirient

## Additional Information

- [ ] This change is backwards-breaking

2021-10-20 18:12 UTC, ardzoht commented on lte/protos/oai/spgw_state.proto
> +    bytes sgw_ipv6_address_s1u_s12_s4_up = 28;
we need to add state conversion and deconversion for this one, check `lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp` for reference

2021-10-21 05:38 UTC, pruthvihebbani commented on lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
> +  bearer_ctxt_p                        = sgw_cm_get_eps_bearer_entry(
Add NULL check for bearer_ctxt_p

2021-10-24 21:23 UTC, koolzz commented on lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
> +  bearer_ctxt_p                        = sgw_cm_get_eps_bearer_entry(
If its null should I call Fatal()?

2021-10-24 21:45 UTC, koolzz commented on lte/protos/oai/spgw_state.proto
> +    bytes sgw_ipv6_address_s1u_s12_s4_up = 28;
added

2021-10-25 05:17 UTC, pruthvihebbani commented on lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
> +  bearer_ctxt_p                        = sgw_cm_get_eps_bearer_entry(
Throw an error message and return

2021-10-25 11:40 UTC, koolzz commented on lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
> +  bearer_ctxt_p                        = sgw_cm_get_eps_bearer_entry(
done

2021-11-01 17:10 UTC, ardzoht requested changes
minor changes to be applied

2021-11-01 17:10 UTC, ardzoht commented on lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
> +  if ((uint32_t) enb_addr.s_addr == 0 && enb_addr_ipv6 == NULL) {
should this be `||`?

2021-11-01 17:10 UTC, ardzoht commented on lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
> +        LOG_SPGW_APP, imsi64, "Failed to retrieve bearer ctxt: \n ");
```suggestion
        LOG_SPGW_APP, imsi64, "Failed to retrieve bearer ctxt: %u\n", bearer_req_p->lbi);
```

2021-11-01 17:10 UTC, ardzoht commented on lte/gateway/python/scripts/generate_oai_config.py
> +    get_if_ip_with_netmask,
Run https://docs.magmacore.org/docs/next/lte/dev_unit_testing#format-agw for formatting

2021-11-01 17:12 UTC, koolzz commented on lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
> +  if ((uint32_t) enb_addr.s_addr == 0 && enb_addr_ipv6 == NULL) {
nope, either one is fine. the error is only when provided ips are both null

2021-11-01 17:47 UTC, ardzoht approved these changes
lgtm

2021-11-01 19:44 UTC, themarwhal approved these changes

2021-11-01 21:46 UTC, merged