ci(nms): Publish Testim reports to Slack
magma/magma pull request #9782
Opened 2021-10-20 07:18 UTC by andreilee

Signed-off-by: Andrei Lee <andreilee@fb.com>

## Summary

Publishes reports to Magma's Slack whenever the daily Testim test plan finishes running.

**Test example**:
![Screen Shot 2021-10-20 at 12 13 42 AM](https://user-images.githubusercontent.com/804385/138045427-d58a49ae-edc0-41c3-b969-72fcf7bcc034.png)

First, a header is posted to channel `testim-reports` showing whether the daily tests passed or failed, and shows a count of how many passed. Then, a breakdown of the failed tests is shown. Finally, and not shown in the screenshot, a generated `.html` test report of the results is posted for more detailed viewing if desired.

## Test Plan

Used [`nektos/act`](https://github.com/nektos/act) to test the modified `testim-workflow.yml` locally:
```
➜  magma git:(1-10-testim-ci2) ✗ act -j testim_check_job --secret-file .secrets --insecure-secrets
...
[Testim Check/Testim Check]   ✅  Success - Run Daily NMS Tests
[Testim Check/Testim Check] ⭐  Run Post Test Report
...
[Testim Check/Testim Check]   ✅  Success - Post Test Report
[Testim Check/Testim Check] ⭐  Run Generate HTML Report
[Testim Check/Testim Check]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/andreilee/magma/workflow/8] user=
[Testim Check/Testim Check]   ✅  Success - Generate HTML Report
[Testim Check/Testim Check] ⭐  Run Post HTML Report File
...
```
- Secrets were copied to a local file, `.secrets`, to be able to run with `nektos/act`
- A simplified test plan from the one that will be used in production was chosen for local testing

## Additional Information

- [ ] This change is backwards-breaking

2021-10-20 08:22 UTC, quentinDERORY commented on .github/workflows/testim-workflow.yml
> +      - name: Post Test Report
add` if: always()` on all steps after running the test so that it always post results if the test step fails

2021-10-20 08:28 UTC, quentinDERORY requested changes
Instead of writing our own html generator, would it not be enough to construct a message in the worflow with the module `uses: actions/github-script@v3` (javascript code) and use the existing slack module to publish this message: `rtCamp/action-slack-notify@v2`.
It's currently how all others workflow are set up.

2021-10-20 22:01 UTC, andreilee commented
@quentinDERORY The html generator is just a separate downloaded dependency, which just processes the JUnit XML file output from Testim. The message shown in Slack in the PR description is also too rich in detail for `rtCamp/action-slack-notify@v2`. In hindsight, writing that script in `js` instead of `python` would have made this simpler as whole, but I don't think it's worth it to rewrite it now.

edit: I think it's important to include specifically which tests failed, and what the error messages are, as not everybody will have a Testim account to view detailed test results. Having all Magma contributors able to see at a glance what tests are failing can give good signal if you accidentally broke something from a recent PR.

2021-10-20 22:16 UTC, andreilee commented on .github/workflows/testim-workflow.yml
> +      - name: Post Test Report
I tried this and maybe I just couldn't get it working with `nektos/act`, because whenever any tests failed, the steps annotated with `always()` wouldn't run. So, I made it so that the `Run Daily NMS Tests` step always passes. There's that ` || true` at the end of the command that the step runs.

2021-10-21 07:50 UTC, quentinDERORY commented on .github/workflows/testim-workflow.yml
> +      - name: Post Test Report
We kind of loose the information at a glance that the test failed... If everything else is working, I can ensure using always will work.

2021-10-25 20:53 UTC, andreilee commented
Added `if: always()` to steps running after triggering Testim 'test plan'.

2021-10-25 20:57 UTC, quentinDERORY approved these changes

2021-10-26 02:32 UTC, merged