refactor: move out indexVersioner from jobQueue
magma/magma pull request #9800
Opened 2021-10-20 23:51 UTC by reginawang3495

## Summary
Move out `indexVersioner` from `jobQueue`.
## Test Plan
Run all orch8r tests in intelliJ

## Additional Information

- [ ] This change is backwards-breaking

2021-10-21 20:57 UTC, reginawang3495 commented
We can either move tests for `indexVersioner` out from the `jobQueue` now, or do it later when we completely remove `jobQueue` and leave `indexVersioner` behind. 

I prefer the second, but am not opposed to the first.

2021-10-21 21:09 UTC, hcgatewood requested changes
Looks great. Couple nits, main thing is: let's add some `Versioner`-specific tests. Feel free to use the existing tests as a starting point

2021-10-21 21:09 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/index_versioner.go
> +type indexVersionerImpl struct {
I would just call this `versioner` -- and the interface `Versioner`, for conciseness. The "Index" is implicit from the pkg context, and also add a doc/description to the interface

2021-10-21 21:09 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/index_versioner.go
> +		return getIndexerVersionsImpl(i.builder, tx)
Here and elsewhere: just call this `getIndexerVersions`, since it being private is sufficient / no need to add "Impl"

2021-10-21 21:09 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/index_versioner.go
> +	TestHookGet()
Do we still need these hooks here? I recall adding them mostly to deal with the complexities of testing the queue

2021-10-21 21:09 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/queue_sql.go
> +	IndexVersioner
Move this to the top of the struct -- is clearer

2021-10-21 21:09 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/queue_sql.go
> +	i := NewIndexVersioner(db, builder)
`i` is a risky variable to use, cause people usually expect it to contain an integer. Instead, just skip the var entirely and create the object directly in the struct literal

2021-10-22 19:26 UTC, reginawang3495 commented on orc8r/cloud/go/services/state/indexer/reindex/index_versioner.go
> +	TestHookGet()
I believe so, unless we mock out `Versioner` in `queue_sql_integ_test.go`, or move it to something in `queue_sql.go`. <`TestSQLReindexJobQueue_Integration_PopulateJobs` fails otherwise. I can diagnose the issue if you want me to though>

Since it's an integration test, I think it makes sufficient sense to leave as is?

2021-10-22 19:44 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/index_versioner.go
> +	TestHookGet()
Ah right, so basically: if we're going to re-use the existing tests, then we need to keep this for now, with the idea that we can remove it once we remove the reindexer_queue impl

Anyways, re-request review / DM when ready for next round of review

2021-10-22 20:04 UTC, hcgatewood requested changes
Looks great, couple small things then I think we're there!

2021-10-22 20:04 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/queue.go
> +	// Tracks version info for all tracked indexers
General nit: prepend with identifier name
```suggestion
	// Versioner tracks version info for all tracked indexers
```

2021-10-22 20:04 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/queue.go
> +	InitializeVersioner() error
I'm like 60% sure there's a way you can have this be named just `Initialize` (remove the `Initialize` from the `JobQueue` interface, then call `versioner.Initialize` from `queue.Initialize`)

If not, add a todo for yourself to this method to rename it back to `Initialize` once we remove jobqueue

2021-10-22 20:04 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/versioner_test.go
> +	versioner := initVersioner(t, dbName)
Since the versioner doesn't rely on postgres-specific syntax (just the job queue), we can just use an in-memory sqlite db, same as how you did for milestone 1

2021-10-22 20:05 UTC, reginawang3495 commented on orc8r/cloud/go/services/state/indexer/reindex/queue.go
> +	InitializeVersioner() error
I couldn't find one easily from stack overflow (I tried prior to you mentioning it), so I'll just add a TODO

2021-10-22 20:08 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/queue.go
> +	InitializeVersioner() error
I think let's at least give it a shot. We can trial together during 1-1 if needed

2021-10-22 20:09 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/queue.go
> +	InitializeVersioner() error
Did you try the solution I outlined?

2021-10-22 20:15 UTC, reginawang3495 commented on orc8r/cloud/go/services/state/indexer/reindex/queue.go
> +	InitializeVersioner() error
Now I did, and it looks like it should work if interfaces aren't used as per https://stackoverflow.com/questions/20861786/golang-struct-calling-embedded-type-methods-when-method-has-been-overloaded

In this case, it says `Duplicate method 'Initialize'` probably because interface method overloading

![image](https://user-images.githubusercontent.com/29292203/138517495-dc38d982-ea48-4484-8d2d-eee849eed74b.png)

2021-10-22 20:30 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/queue.go
> +	InitializeVersioner() error
Right, so remove the `Initialize` method from JobQueue, because it's included implicitly as part of the `Versioner` embedded iface

2021-10-22 20:31 UTC, reginawang3495 commented on orc8r/cloud/go/services/state/indexer/reindex/queue.go
> +	InitializeVersioner() error
`Initialize` is needed in JobQueue also though

2021-10-25 18:35 UTC, hcgatewood approved these changes
Awesome!

2021-10-25 18:35 UTC, hcgatewood commented on orc8r/cloud/go/services/state/indexer/reindex/queue.go
> +	// Tracks version info for all tracked indexers
Nit: we would want this to be `// Versioner tracks version info...`

2021-10-25 18:35 UTC, merged