feat(amf): UT cases for the NGAP UE specific Messages
magma/magma pull request #9816
Opened 2021-10-21 13:26 UTC by VinayKumar1591

UT cases for the NGAP UE specific Messages

## Summary

1. Added changes to support UT for the NGAP messages

## Test Plan

1. Added UT using Gtest
2. Verified sanity on NGAT Tester

## Additional Information

2021-10-21 16:09 UTC, ulaskozat reviewed
can you add more comments on individual tests? e.g., why an error expected or okay result expected?

2021-10-23 04:47 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // veirfy Ngap_ProtocolIE_ID_id_PDUSessionResourceSetupListSURes ie is present
verify

2021-10-23 04:48 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // is invalid in ue_ref than ie present in pdu_session_resource_setup message
sentence does not read correct

2021-10-23 04:51 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // is invalid in ue_ref than ie present in ue_context_release_request
comment does not looks grammatically correct after "... is invalid in ue_ref"

2021-10-23 04:53 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // is invalid in ue_ref than ie present in initial_context_setup_response
check the grammar of the comment after "... is invalid in ue_ref"

2021-10-23 04:54 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // in ue_ref than ie present in uplink_nas_transport
check the grammar

2021-10-23 04:54 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // in ue_ref than ie present in uplink_nas_transport
check the grammar

2021-10-23 04:54 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // is invalid in ue_ref than ie present in itti ue_context_release_command
check the grammar

2021-10-23 04:55 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // is invalid in ue_ref than ie present in pdu_session_resource_setup message
second part of the comment does not make sense here as ie is not checked until the next comment.

2021-10-23 04:56 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
veriy -> verify
are -> is

2021-10-23 04:56 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // veriy number of connected GNB's are 1
same comment

2021-10-23 04:56 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // veriy number of connected GNB's are 1
same comment

2021-10-23 04:57 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same comment

2021-10-23 04:57 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same comment

2021-10-23 04:57 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:57 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:58 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:58 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:58 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:58 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:58 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:58 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:59 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:59 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:59 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:59 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:59 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-23 04:59 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Veriy number of connected GNB's are 1
same

2021-10-25 00:11 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> + * Unless required by applicable law or agreed to in writing, softwis
revert this change.

2021-10-25 00:12 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  sctp_new_peer_t p;
give a more meaningful name to the variable

2021-10-25 00:13 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Check for UE associated with GNB
gNB

2021-10-25 00:14 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Check if GNB exists
check all GNBs in the comments and change them to gNB

2021-10-25 00:17 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  bdestroy(NGAP_NAS_DL_DATA_REQ(message_p).nas_msg);
`itti_free_msg_content` should have handled this, why do we need to bdestroy again?

2021-10-25 00:34 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/ngap/ngap_client_servicer.cpp
>    }
these are supposed to be handled with `itti_free_msg_content` and should be moved there. Also I noticed that `handle_message` in `ngap_amf.c` and `amf_app_main.cpp` do not follow the same pattern as other handlers in the mme service. We should use `MessageDef* received_message_p = receive_msg(reader);`,   `itti_free_msg_content(received_message_p);` and 
 `free(received_message_p);`. cc @panyogesh

2021-10-25 00:34 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/ngap/ngap_client_servicer.cpp
>    }
can you fix those in this PR as well?

2021-10-25 00:37 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  bdestroy(NGAP_NAS_DL_DATA_REQ(message_p).nas_msg);
this should have been addressed by `itti_free_msg_content`.

2021-10-25 00:38 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  free(message_p);
move `free(message_p)` to below `itti_free_msg_content`.

2021-10-25 00:42 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +      initial_context_setup_response_message_hexbuf, length);
why do we need this after using blk2bstr in the line above?

2021-10-25 00:43 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +      length);
why is this needed given the above line?

2021-10-25 00:44 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  memcpy(
please check everywhere you use blk2bstr as it is supposed to copy the content.

2021-10-25 00:45 UTC, ulaskozat requested changes
see my additional comments

2021-10-25 00:50 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  // Verify initial_context_Setup_rsp is encoded correctly
s/Setup/setup

2021-10-25 00:52 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
> +  bdestroy(NGAP_PDUSESSIONRESOURCE_REL_REQ(message_p).nas_msg);
should have been handled by `itti_free_msg_content`, please fix these patterns everywhere. also call `free(message_p)` immediately after `itti_free_msg_content` everywhere it is used.

2021-10-25 13:25 UTC, VinayKumar1591 commented on lte/gateway/c/core/oai/tasks/ngap/ngap_client_servicer.cpp
>    }
these are handled in itti_free_msg_content  and here also these are required incase of UT because AMF and SCTP are mocked in this case, so message is dropped here only

2021-10-25 18:25 UTC, ulaskozat commented on lte/gateway/c/core/oai/tasks/ngap/ngap_client_servicer.cpp
>    }
use `bdestroy_wrapper(&(...))` so that the pointer is not dangling.

2021-10-26 04:31 UTC, ulaskozat approved these changes
LGTM

2021-10-26 05:01 UTC, merged