fix(pipelined): Adding support for read enable5g_features flag from available config file
magma/magma pull request #9843
Opened 2021-10-22 17:53 UTC by GANESH-WAVELABS

fix(pipelined): Adding support for read enable5g_features flag from available config file

## Summary

Existing Problem : In teravm setup always TC2 & TC9 are getting failed in daily jenkins. The reason was in teravm setup `enable5g_features` flag is reading from /var/opt/magma/configs/pipelined.yml file, but current pipelined code is reading from /etc/magma/pipelined.yml file. Also `periodic_stats_reporting` flag was set to `true` by default due to this traffic was failing.

Solution :
1) Added support for reading `enable5g_features` flag based on the available config file /var/opt/magma/configs/pipelined.yml or /etc/magma/pipelined.yml and set the default value of `enable5g_features` flag to `true` in /etc/magma/pipelined.yml
2) Also `periodic_stats_reporting` flag set to `false` by default in /etc/magma/pipelined.yml
3) In sessiond `enable5g_features` flag set to `true` by default in /etc/magma/sessiond.yml

## Test Plan
Tested the PDU session establishment & release with stubbed CLI magma/lte/gateway/python/scripts/smf_upf_integration_cli.py
For test logs and screen shots please refer below comment.

## Additional Information
Corresponding git hub issue IDs are #9638 #9012

2021-10-22 17:55 UTC, uri200 requested changes

2021-10-22 17:55 UTC, uri200 commented on lte/gateway/configs/pipelined.yml
> +  periodic_stats_reporting: false
why this change?

2021-10-22 17:55 UTC, uri200 commented on lte/gateway/configs/pipelined.yml
> +enable5g_features: true
same here

2021-10-22 18:07 UTC, GANESH-WAVELABS commented
When magma/lte/gateway/configs/gateway.mconfig changes the `enable5g_features` flag value will reflect here as shown in the below screen shot.
![image](https://user-images.githubusercontent.com/70899516/138502035-102950be-beaa-4b96-81bb-50b136f4d40a.png)

Below are the `/var/log/syslog` during PDU session establishment:
```vagrant@magma-dev-focal:~/magma/lte/gateway$ sudo tail -f /var/log/syslog
Oct 22 16:49:41 magma-dev-focal magmad[335300]: E1022 16:49:41.559319236  335322 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
Oct 22 16:49:41 magma-dev-focal magmad[335300]: E1022 16:49:41.866251211  335322 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
Oct 22 16:49:43 magma-dev-focal magmad[335300]: E1022 16:49:43.701633749  335322 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
Oct 22 16:49:45 magma-dev-focal magmad[335300]: E1022 16:49:45.232548449  335322 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
Oct 22 16:49:45 magma-dev-focal magmad[335300]: E1022 16:49:45.621125498  335322 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
Oct 22 16:49:45 magma-dev-focal smsd[335422]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 22 16:49:50 magma-dev-focal magmad[335300]: E1022 16:49:50.887004350  335322 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
Oct 22 16:49:50 magma-dev-focal smsd[335422]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 22 16:49:51 magma-dev-focal magmad[335300]: E1022 16:49:51.224281410  335322 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
Oct 22 16:49:52 magma-dev-focal magmad[335300]: E1022 16:49:52.233131897  335322 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
Oct 22 16:49:56 magma-dev-focal smsd[335422]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.623716 335508 GrpcMagmaUtils.cpp:58]
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:   magma.lte.SetSMSessionContext {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:       common_context {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         sid {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           id: "IMSI12345"
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         apn: "BLR"
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         rat_type: TGPP_NR
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:       }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:       rat_specific_context {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         m5gsm_session_context {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           pdu_session_id: 1
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           pdu_address {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:             redirect_server_address: "192.168.128.11"
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           ssc_mode: SSC_MODE_3
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           gnode_endpoint {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:             teid: 10000
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:             end_ipv4_addr: "192.168.60.141"
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:       }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:   }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.627454 335358 SetMessageManagerHandler.cpp:120] Requested session from UE with IMSI: IMSI12345 PDU ID 1
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.627873 335358 SetMessageManagerHandler.cpp:261] First Requested session from UE with IMSI: IMSI12345 Generated session IMSI12345-781354 PDU id 1
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.628005 335358 SessionStateEnforcer.cpp:102]  New SessionState object created with IMSI: IMSI12345 session context id : IMSI12345-781354
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.628186 335358 SessionStateEnforcer.cpp:844] Acquried Teid: 2147483647
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.628376 335358 SessionState.cpp:233]  Current version is 1
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.628463 335358 SessionStateEnforcer.cpp:120] Added a session (1) for IMSI IMSI12345 with session context ID
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.633601 335358 SetMessageManagerHandler.cpp:276] Successfully initialized 5G session for subscriber IMSI12345 with PDU session ID 1
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.633664 335358 GrpcMagmaUtils.cpp:58]
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:   magma.lte.CreateSessionRequest {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:       session_id: "IMSI12345-781354"
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:       common_context {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         sid {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           id: "IMSI12345"
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         apn: "BLR"
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         rat_type: TGPP_NR
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:       }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:       rat_specific_context {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         m5gsm_session_context {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           pdu_session_id: 1
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           pdu_address {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:             redirect_server_address: "192.168.128.11"
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           ssc_mode: SSC_MODE_3
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           gnode_endpoint {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:             teid: 10000
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:             end_ipv4_addr: "192.168.60.141"
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:       }
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:   }
Oct 22 16:49:57 magma-dev-focal policydb[335384]: INFO:root:Creating a session for subscriber ID: IMSI12345
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.638090 335358 SetMessageManagerHandler.cpp:296] Processing a CreateSessionResponse for IMSI12345-781354
Oct 22 16:49:57 magma-dev-focal sessiond[335358]: I1022 16:49:57.638110 335358 GrpcMagmaUtils.cpp:58]
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:   magma.lte.CreateSessionResponse {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:       dynamic_rules {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:         policy_rule {
Oct 22 16:49:57 magma-dev-focal sessiond[335358]:           id: "allowlist_sid-IMSI12345-BLR"
Oct 22 16:49:57 magma-dev-focal sessi [...]

2021-10-22 20:54 UTC, ulaskozat commented on lte/gateway/configs/sessiond.yml
> +enable5g_features: true
why?

2021-10-22 20:57 UTC, ulaskozat commented
@GANESH-WAVELABS is there a confusion here? by default 5G features should be disabled. `/var/opt/magma/configs/pipelined.yml` is for overwriting configs. If you do not want to overwrite orc8r setting, then you should remove the entries from there. cc @panyogesh

2021-10-22 20:59 UTC, ardzoht requested changes
Requested a change related to OAI config generation, I would also recommend including the verification that the configs are updated when restarting MME and add it to the Test Plan. Thanks!

2021-10-22 20:59 UTC, ardzoht commented on lte/gateway/configs/templates/spgw.conf.template
> +    UPF_NODE_IDENTIFIER                       = "{{ upf_node_identifier }}";
I think we're missing the config retrieval and generation for this parameter on `generate_oai_config.py`, in this case please add it, you can validate the change by running `/usr/local/bin/generate_oai_config.py` manually.

2021-10-25 18:11 UTC, GANESH-WAVELABS commented
When enable5g_features flag set to `false` in `gateway.mconfig` reflected in `/var/log/mme.log` and `/var/opt/magma/tmp/spgw.conf`
below is the corresponding screenshot :
![image](https://user-images.githubusercontent.com/70899516/138747750-bfa7b23b-57f8-4298-8efa-359e859d909e.png)

When enable5g_features flag set to `true` in `gateway.mconfig` reflected in `/var/log/mme.log` and `/var/opt/magma/tmp/spgw.conf`
below is the corresponding screenshot :
![image](https://user-images.githubusercontent.com/70899516/138747919-54ed77e7-e7f6-4809-9507-2967c71afbe2.png)

2021-10-25 18:12 UTC, ardzoht commented
@GANESH-WAVELABS Is this PR ready to be reviewed? If so please mark it as ready for review, also thanks for your config validation 👍

2021-11-01 17:45 UTC, panyogesh commented
@GANESH-WAVELABS : As discussed and verified on TerraVM regression setup, periodic_stats flags was not set as expected. Can you mark it for closure if its correct.

2021-11-02 01:38 UTC, uri200 commented
> @GANESH-WAVELABS : As discussed and verified on TerraVM regression setup, periodic_stats flags was not set as expected. Can you mark it for closure if its correct.

It means it can be closed, right?

2021-11-02 04:35 UTC, GANESH-WAVELABS commented
> > @GANESH-WAVELABS : As discussed and verified on TerraVM regression setup, periodic_stats flags was not set as expected. Can you mark it for closure if its correct.
> 
> It means this PR can be closed, right?

Yes, It can be closed @uri200 , I am closing it now.

2021-11-02 04:35 UTC, closed without merging