feat(agw): Add service level memory and cpu metrics
magma/magma pull request #9872
Opened 2021-10-26 05:50 UTC by wallyrb

## Summary

1. Add memory usage of magma@*,  stcpd and ovs services. Memory will be taken from systemctl property MemoryCurrent, only for services that have MemoryAccounting enabled.
2. Add memory percent usage for magma@*,  stcpd and ovs services. Calculation is based using MemoryCurrent(from 1) divided my MemoryLimit obtained from systemctl properties.
3.  Add cpu_percent using psutil using the MainPID for each of the service. MainPID is obtained from systemctl property.

## Test Plan

- Tested in master

![image](https://user-images.githubusercontent.com/37117037/138827262-cbe0f2bb-25bd-49cd-8c59-91d3300cf93a.png)

![image](https://user-images.githubusercontent.com/37117037/138816242-e89ce942-8cf1-462d-a6e9-bb3fac905644.png)
![image](https://user-images.githubusercontent.com/37117037/138816449-e09304b9-bdd4-49b9-b172-78eb0b313c63.png)

- service303_cli.py metrics magmad https://www.internalfb.com/phabricator/paste/view/P464745922

## Additional Information

- [ ] This change is backwards-breaking

2021-10-26 20:57 UTC, ardzoht requested changes

2021-10-26 20:57 UTC, ardzoht commented on orc8r/gateway/python/magma/magmad/metrics.py
> +    output = subprocess.check_output(cmd)
rather than using subprocess, you can use 
```
process = psutil.Process(os.getpid())
print(process.memory_info().rss)  # bytes
```
to get the current mem usage of each process

2021-10-26 21:08 UTC, wallyrb commented on orc8r/gateway/python/magma/magmad/metrics.py
> +    output = subprocess.check_output(cmd)
thanks @ardzoht , actually I tried using memory_info().rss and memory_info().vms but the values didn't match in what systemctl was showing. For example below, memory_info is showing 403 MB, but systemctl has accounted 342M


```
vagrant@magma-dev-focal:~$ sudo service magma@mme status
● magma@mme.service - Magma OAI MME service
     Loaded: loaded (/etc/systemd/system/magma@mme.service; disabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-10-26 07:17:58 UTC; 13h ago
    Process: 146425 ExecStartPre=/usr/bin/env python3 /usr/local/bin/generate_oai_config.py (code=exited, status=0/SUCCESS)
    Process: 146439 ExecStartPre=/usr/bin/env python3 /usr/local/bin/config_stateless_agw.py reset_sctpd_for_stateful (code=exited, status=0/SUCCESS)
   Main PID: 146443 (mme)
      Tasks: 28 (limit: 9511)
     Memory: 342.5M (min: 512.0M limit: 1.0G)
     CGroup: /system.slice/system-magma.slice/magma@mme.service
             └─146443 /usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.conf


>>> process = psutil.Process(pid=146443)
>>> process.memory_info()
pmem(rss=423452672, vms=21990709542912, shared=68476928, text=48164864, lib=0, data=15393784320000, dirty=0)
>>> 423452672/1024/1024
403.8359375
>>> 21990709542912/1024/1024
20971974.890625

```

2021-10-26 21:12 UTC, wallyrb commented on orc8r/gateway/python/magma/magmad/metrics.py
> +    output = subprocess.check_output(cmd)
I wanted to match what systemctl was showing, since the memory limits are set there.

2021-10-26 22:11 UTC, ardzoht commented on orc8r/gateway/python/magma/magmad/metrics.py
> +    output = subprocess.check_output(cmd)
Ok sounds good, for the purposes of unblocking this I think we can start with calling subprocess, however I think we can use `pystemd` (which is already installed) to talk directly to systemd instead of using commands, could you please add a TODO to mark that we plan to migrate this using pystemd library?

2021-10-26 22:11 UTC, ardzoht approved these changes
lgtm, let's mark migration to pystemd as a TODO as a follow-up

2021-10-26 22:27 UTC, wallyrb commented on orc8r/gateway/python/magma/magmad/metrics.py
> +    output = subprocess.check_output(cmd)
noted, I added the TODO mark and will look into the psystemd library. Thanks @ardzoht !

2021-10-26 22:47 UTC, ardzoht commented on orc8r/gateway/python/magma/magmad/metrics.py
> +    magma_services = str(output, "utf-8").strip().replace("Names=", "").split("\n\n")
magma_services can be retrieved from `service.config['magma_services'` and then attaching `magma@<service>` prefix, check line 124 on this file

2021-10-27 00:18 UTC, ardzoht commented on orc8r/gateway/python/magma/magmad/metrics.py
> +SERVICE_METRICS = Gauge(
one more nit: I think we should separate these into `SERVICE_CPU_USAGE`, `SERVICE_MEMORY_USAGE`, `SERVICE_MEMORY_PERCENTAGE` from prometheus view is better to keep separate metrics with values rather than separating the metrics using labels

2021-10-27 00:19 UTC, ardzoht requested changes
we should separate `SERVICE_METRICS` labels into separate metrics themselves

2021-10-27 04:52 UTC, wallyrb commented on orc8r/gateway/python/magma/magmad/metrics.py
> +SERVICE_METRICS = Gauge(
Thanks @ardzoht for the suggestion. I have updated the PR

2021-10-27 05:12 UTC, ardzoht approved these changes
lgtm, thanks for this!

2021-11-02 19:12 UTC, hcgatewood approved these changes
Thanks for the addition Wally!

@wallyrb @ardzoht any interest in a ready-made solution for the next iteration of this? https://github.com/povilasv/systemd_exporter

2021-11-03 05:19 UTC, ardzoht commented
> Thanks for the addition Wally!
> 
> @wallyrb @ardzoht any interest in a ready-made solution for the next iteration of this? https://github.com/povilasv/systemd_exporter

@hcgatewood Yeah that should be the definitive option to migrate in the future, thanks for bringing that up!

2021-11-03 17:19 UTC, merged