docs: edited pyenv set up
magma/magma pull request #9882
Opened 2021-10-26 14:56 UTC by christinewang5

## Summary
Edited pyenv set up to match the [pyenv docs](https://github.com/pyenv/pyenv#basic-github-checkout)

2021-10-26 14:57 UTC, electronjoe commented
Thanks for the docs fixup @christinewang5!

2021-10-26 14:57 UTC, electronjoe approved these changes

2021-10-27 16:53 UTC, hcgatewood approved these changes
Thanks @christinewang5! Msg me when ready and I'll merge 💯

2021-10-27 16:53 UTC, hcgatewood commented on docs/docusaurus/versioned_docs/version-1.0.1/basics/prerequisites.md
>  # IMPORTANT: Use .bash_profile, not .bashrc for bash
```suggestion
# NOTE: this assumes you're using zsh.
# See the above pyenv install instructions if using alternative shells.
```

2021-10-27 16:53 UTC, hcgatewood commented on docs/docusaurus/versioned_docs/version-1.0.1/basics/prerequisites.md
> +# Restart your terminal
```suggestion
# IMPORTANT: close your terminal tab and open a new one before continuing
```

2021-10-29 16:44 UTC, themarwhal commented on docs/docusaurus/versioned_docs/version-1.0.1/basics/prerequisites.md
> +# NOTE: this assumes you're using zsh.
do we want to update this to the non-versioned doc as well? Or do we only want to update it for v1.0.1

2021-10-29 17:10 UTC, christinewang5 commented on docs/docusaurus/versioned_docs/version-1.0.1/basics/prerequisites.md
> +# NOTE: this assumes you're using zsh.
you are so right, I didn't notice there were versions, but will edit this right now... 🤦🏻‍♀️

2021-10-30 08:45 UTC, hcgatewood requested changes

2021-10-30 08:45 UTC, hcgatewood commented on docs/readmes/basics/prerequisites.md
> +pyenv global 3.7.3
This should still be 3.8.10 if I'm not mistaken

2021-11-02 05:51 UTC, hcgatewood approved these changes
💯🔥

2021-11-02 05:51 UTC, merged