feat(orc8r): add bootstrap metrics to determine which networks are active
magma/magma pull request #9892
Opened 2021-10-26 18:42 UTC by christinewang5

## Summary
* We want to know, on a per-network basis, the rate at which gateways are checking in — that way, we can determine whether a network is dead vs. actively used.
* Gateways have to re-bootstrap every ~4 days to receive new session certificates, so we can just increment a per-network counter every time a gateway successfully bootstraps ([bootstrap overview](https://magma.github.io/magma/docs/next/orc8r/dev_security#gateway-bootstrap))([code ref](https://github.com/magma/magma/blob/72b1f20e85dcf83fe2d16ca38408bb52d56ce5c3/orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go#L141-L145))

## Test Plan
* manually triggering bootstrapping by deleting session certs
  1. `vagrant ssh magma`
  2. `cd lte/gateway`
  3. `sudo rm /var/opt/magma/certs/gateway.{crt,key}`
  4. `make restart`

* checked prometheus to see if logged successfully (deleted twice)
![image](https://user-images.githubusercontent.com/25142344/139131393-13ec0d98-5f0c-4dd6-b21a-b11428d2008e.png)

2021-10-27 17:00 UTC, hcgatewood requested changes
Looks great! 2 small things, and then: for testing, can you delete the session certs twice, so we see the counter get incremented twice -- just to double check 🙂 

Thanks Christine!

2021-10-27 17:00 UTC, hcgatewood commented on orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go
> +			Help: "Number of bootstrap attempts for each network",
Currently this is number of *successful* attempts

2021-10-27 17:00 UTC, hcgatewood commented on orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go
> +	bootstrapAttempts.WithLabelValues(entity.NetworkID, hwId).Inc()
- We can use the hwid from the `resp` variable, so no need for a configurator call
- Since successful bootstrap happens per-gateway once every ~3 days, let's also add a .Info log

2021-10-27 17:00 UTC, hcgatewood commented
cc @talkhasib

2021-10-27 18:41 UTC, christinewang5 commented on orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go
> +	bootstrapAttempts.WithLabelValues(entity.NetworkID, hwId).Inc()
I'm already using the `hwid` from the `resp` variable, the configurator call is for network ID and am not sure if there are alternatives to this but was just looking at examples. 


Also I wasn't sure whether to use `glog` or `log`, and bc `errorLogger` in this file seems to use the latter I used it here too...

2021-10-30 08:48 UTC, hcgatewood requested changes

2021-10-30 08:48 UTC, hcgatewood commented on orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go
> +	bootstrapAttempts.WithLabelValues(entity.NetworkID, hwId).Inc()
- Ah I see, sorry I misread -- this is indeed the correct way to do this 🙂 
- As for log -- `log` is legacy for our codebase, prefer `glog`
- Finally, handle the err case for loading the entity -- probably just glog the error

2021-11-02 05:54 UTC, hcgatewood requested changes

2021-11-02 05:54 UTC, hcgatewood commented on orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go
> +		return nil, errorLogger(status.Errorf(codes.NotFound, "Gateway with hwid %s is not registered: %s", hwId, err))
Nit
```suggestion
		return nil, errorLogger(status.Errorf(codes.NotFound, "Gateway with HWID %s is not registered: %+v", hwId, err))
```

2021-11-02 05:54 UTC, hcgatewood commented on orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go
> +	"github.com/gogf/gf/os/glog"
Wrong glog 🙂 

```suggestion
	"github.com/golang/glog"
```

2021-11-02 14:06 UTC, christinewang5 commented on orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go
> +	"github.com/gogf/gf/os/glog"
oops thanks

2021-11-03 05:43 UTC, hcgatewood approved these changes
💯 🔥

2021-11-03 21:04 UTC, hcgatewood commented
@christinewang5 looks like merge conflict

2021-11-04 17:46 UTC, merged