chore(mme): new unit tests for mme procedure procedure failures, idle mode, etc.
magma/magma pull request #9916
Opened 2021-10-27 05:46 UTC by ulaskozat

## Summary

- Added new unit tests for authentication request and SMC message transmission failures.
- Added unit test for attach-idle mode transition-detach sequence.
- Added modify bearer request stages where it is needed.
- Expanded expect call macro with additional fields and added new message types as boundary conditions that wakes up the main thread waiting on the conditional variable.
## Test Plan

Run `make test_oai`.
## Additional Information

- [ ] This change is backwards-breaking

2021-10-27 16:41 UTC, ardzoht requested changes
minor changes on send_modify_bearer_resp utility function

2021-10-27 16:41 UTC, ardzoht commented on lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
> +    std::vector<int>& bearer_to_modify, std::vector<int>& bearer_to_remove) {
```suggestion
    const std::vector<int>& bearer_to_modify, const std::vector<int>& bearer_to_remove) {
```

2021-10-27 16:41 UTC, ardzoht commented on lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
> +        .eps_bearer_id = bearer_to_modify[i];
this should be `bearer_to_remove[i]`

2021-10-27 16:41 UTC, ardzoht commented on lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
> +    std::vector<int>& bearer_to_modify, std::vector<int>& bearer_to_remove);
```suggestion
    const std::vector<int>& bearer_to_modify, const std::vector<int>& bearer_to_remove);
```

2021-10-28 20:16 UTC, ulaskozat commented on lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
> +        .eps_bearer_id = bearer_to_modify[i];
good catch!

2021-10-28 21:19 UTC, ardzoht approved these changes
lgtm

2021-10-29 03:00 UTC, merged