feat(ci): PR push to CI registry
magma/magma pull request #9965
Opened 2021-10-28 20:51 UTC by tmdzk

Signed-off-by: Timothée Dzik <timdzik@fb.com>

feat(ci): PR push to CI registry

## Summary

Created:
orc8r-ci (docker)
feg-ci (docker)
cwag-ci (docker)
ci (debian)
helm-ci (helm charts)

Virtual: docker-ci composed of orc8r-ci (docker), feg-ci (docker), cwag-ci (docker)

## Test Plan

Let it run and populate the registry

## Additional Information

- [ ] This change is backwards-breaking
![](https://media3.giphy.com/media/Hw8vYF4DNRCKY/giphy.gif)

2021-10-29 17:40 UTC, koolzz approved these changes

2021-10-29 18:02 UTC, themarwhal approved these changes

2021-11-01 08:35 UTC, quentinDERORY commented on .github/workflows/deploy-build-from-pr.yml
>            DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
DOCKER_REGISTRY was pointing to the old fb artifactory... So you need to update the USERNAME AND PASSWORD too to:
`       DOCKER_USERNAME: "${{ secrets.JFROG_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.JFROG_PASSWORD }}"`

2021-11-01 08:37 UTC, quentinDERORY requested changes
LGTM but change credentials for xwfm images push

2021-11-09 14:44 UTC, merged